### ISSUE TITLE
Add appropriate Wasteland Blockers to new provinces

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#1001]
Add appropriate wasteland blockers to all new wasteland provinces. Ideally, also do it for the ones present in earlier start dates as it will save us time in the long run and wouldnt be that much more work.

**Comment by JukeJukestar** [comment]
All done for the Subterranean counties. Now only Eriador/Lindon needs some care

**Comment by jj248** [comment]
These are added but we need new blocker clearance events to compliment them PLUS more appropriate or reflavoured ongoing random colonisation events.

@RedArkady and @VectorMaximus - might be one for you two to strategise over in the first instance?

**Comment by Jaco-Daan** [comment]
This has been done, closing
