### ISSUE TITLE
Consolidate "Restore Historical Province" Decisions

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#1002]
Since the Persia update, we now have the option to give several selectable options inside of a major decision. Me and Jaco talked about using this to solve the UI bloat on all of the gondorian province reclamation decisions - Have them all within one larger "Restore Historical Province" decision (Patent pending).

**Comment by JukeJukestar** [comment]
Done. Please test if you find anything strange!
Available to Stewards of Gondor, Kings of Gondor, Castamiri Gondor, Reunited Kingdom, Numenor-In-Exile. Includes territorial annexaction options for
- Harondor
- Harnendor (Formable Harnen kingdom)
- Andrast
- Umbar
- Calenardhon/ Rohan
- South Rhovanion/ Dor Rhunen
- Eriador (RK+NiE Only)
- Eregion (RK + NiE Only)

**Comment by savagesach** [comment]
As stated in discord, the 500 gold cost unreasonably adds more expenses to Gondor when they are already dealing with attacks from Mordor. Also the 1000 prestige per kingdom means you'd have to spend 5000 prestige on top of the 2500 gold to integrate everything, when all you get is de jure drifting. If you are really set on making the decisions cost gold/prestige, the cost needs to be decreased and the decisions should grant some sort of additional reward.

**Comment by JukeJukestar** [comment]
Nerfed the cost to 250 gold/ 500 Prestige for players, and 0 for AI.
Made some tweaks so the decision will not show up if you integrated all the possible provinces.

**Comment by jj248** [comment]
Assume this is ready to test again?

**Comment by Jaco-Daan** [comment]
This has been done + no issues reported, closing
