### ISSUE TITLE
Pipeweed Implementation

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#1003]
Chose to reflavor vanilla hashish stuff instead of setting up an entirely unique trait.
Can receive through stress break and rare vanilla events.
Different flavor ("Westman's Weed") depending on culture and region.

Set up in a way where it can appear before it was actually invented around TA 2700

Lookin for feedback on implementation and feel especially in regards to modifiers and frequency

**Comment by Cairo-Fischer** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/110961821/29292fc3-30f9-426f-9dba-2f86574b9fa5)

**Comment by Cairo-Fischer** [comment]
seems to work
