### ISSUE TITLE
"Commander of the Faithful" vanilla war event triggers for Sauron

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#1009]
Holy Caliph Sauron is getting some very unfitting events. Report from public version

![Image](https://github.com/jj248/RealmsInExile/assets/76008882/dee4367d-7c01-4341-ac65-30df016fbc89)

**Comment by BriceLeduc** [comment]
Bug report from outdated version, already corrected in v3.3 and v4
