### ISSUE TITLE
Sauron can utilize the Minas Anor Stone

### ISSUE THREAD

**Issue by VectorMaximus** [jj248/RealmsInExile#101]
As listed in #bugreports
![Minas Anor Stone](https://user-images.githubusercontent.com/79318177/120641904-d45d5b00-c439-11eb-846e-3bfbf618d332.png)

I am unsure how to tackle it, but I think it would be a simple fix restricting only certain cultures to utilizing the Anor-stone.

**Comment by jj248** [comment]
Fix applied.  Decision should no longer be available for Maiar, Nazgul, Istari, Forces of Evil characters and Dark-Aligned Men of Darkness characters who hold Minas Tirith.
