### ISSUE TITLE
Adapt FP3 Persian Flavor Events

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#1010]
A lot of them are very unfitting and mention islamic concepts from the real world, We need to look over all of em

**Comment by JukeJukestar** [comment]
![Image](https://github.com/jj248/RealmsInExile/assets/76008882/dfd2ea8b-b228-4dc9-be15-77c416e0c07e)

Report from public ver

**Comment by BriceLeduc** [comment]
Those events have already been disabled

**Comment by BriceLeduc** [comment]
I have already done a full review and adaptation of events
