### ISSUE TITLE
Character wearing Orc Armor

### ISSUE THREAD

**Issue by Hendrix1337x** [jj248/RealmsInExile#1018]
![Crusader Kings III Screenshot 2024 01 02 - 05 29 53 18](https://github.com/jj248/RealmsInExile/assets/154389264/f0dcf7db-f1d5-47f8-93c9-325130070fdb)

**Comment by jj248** [comment]
I'll look at it.

**Comment by Hendrix1337x** [comment]
Kingdom tier Hobbit wearing Orc Armour
![15](https://github.com/jj248/RealmsInExile/assets/154389264/bf3cfda3-b50a-40b7-8b6f-fd5b680f6d22)

**Comment by Hendrix1337x** [comment]
Duchy tier Marshal wearing orc armour
![17](https://github.com/jj248/RealmsInExile/assets/154389264/a7c918ec-6ac9-416a-81cb-7263fc930fdc)

**Comment by Hendrix1337x** [comment]
the problem persists still :(
![image](https://github.com/jj248/RealmsInExile/assets/154389264/ca8f7709-aa09-4c53-a3d9-df20ae9e5d7a)

**Comment by Jaco-Daan** [comment]
Issue seems to have been solved. Tested with:

- Duchy tier vassal hobbit being marshal
- County tier vassal hobbit being marshal
- Courtier hobbit being marshal
- All of above WHILE being a vassal
- A hobbit being a marshal on a different race's court
- Marshal/Ruler being commander of an army

![20240418231617_1](https://github.com/jj248/RealmsInExile/assets/62937916/a68eaeef-62e3-42ed-96fd-0c005b2fbbbe)

![20240418231620_1](https://github.com/jj248/RealmsInExile/assets/62937916/d1e1203b-5fec-4f68-82d2-331a81d1c45e)
 
![20240418231624_1](https://github.com/jj248/RealmsInExile/assets/62937916/3daf58aa-fb84-481e-be3b-5a7858784c41)

![20240418231646_1](https://github.com/jj248/RealmsInExile/assets/62937916/dd6d2428-4417-43f7-89be-9c4936abe21c)

Seems the issue has been fixed, closing for now
