### ISSUE TITLE
Localisation error in travel event

### ISSUE THREAD

**Issue by Hendrix1337x** [jj248/RealmsInExile#1019]
![Crusader Kings III Screenshot 2024 01 02 - 09 21 04 10](https://github.com/jj248/RealmsInExile/assets/154389264/2c439e27-9b77-401b-8db0-9b963cf0ebe7)
![Crusader Kings III Screenshot 2024 01 02 - 09 25 35 68](https://github.com/jj248/RealmsInExile/assets/154389264/0639b1a6-6c92-4f10-ae8b-fc513a7c4c58)

**Comment by JukeJukestar** [comment]
This seems to be a vanilla error, funnily enough. Closing.

**Comment by Hendrix1337x** [comment]
another bugged travel event
![image](https://github.com/jj248/RealmsInExile/assets/154389264/1b7758a0-2d55-4cd2-90f2-f770fd53d496)

**Comment by Jaco-Daan** [comment]
Seems like another vanilla issue (i.e., it's a vanilla event). We haven't touched anything do with this events code, closing for now
