### ISSUE TITLE
"Move the Seat of Kings" minor decision

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#1021]
Added a new decision to move your capital+dejure capital to a new location as a numenorean realm.
Different options depending on your title.
Available to Arnor, Arthedain, Cardolan, Gondor, Ithilien, Stewards of Gondor, Reunited Kingdom, Numenor-in-Exile, Pharazain etc etc.

**Comment by jj248** [comment]
@savagesach - Juke finished this very recently, please can you test?

**Comment by Jaco-Daan** [comment]
Since this is working, closing
