### ISSUE TITLE
Remove old draft terrain types

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#1022]
Here are the existing LotR terrain types and my suggested actions on them:

- Mangrove - this feels like madness to me.  It's not used anywhere yet, and it feels like we could represent with some combination of wetlands / jungle.
- Littoral - this feels even more mad.  I see no need to represent coastal zones in this way.
- Dune Sea - fine, makes sense to model this.  Gives local MaA a good boost and allows us to represent slow terrain movement.
- Desert Hills - we use this a lot but it's borderline for me.  Vanilla distinguishes between mountains and desert mountains, but often the effects are very similar.  Suggest we keep, but retrospectively I wouldn't have made the distinction.
- Saltflats - bonkers.  This exists solely in Abrakhan in like... one province.  I can barely think of where else we'd put it.  Suggest we cull.
- Savanna - we have this a little around Ray and other areas in the south.  It's okay, but I really don't know how it's really much different from Drylands functionally...
- Mallorn Forest - fine, probably a bit superfluous.  Not many provinces but allows us to give elves a nice defensive boost.  Suggest we keep.
- Deep Forest - used widely, makes total sense.  Keep.
- Myrtle Forest - again, madness.  We don't need any more forests.  Hard suggest we cull.
- Volcanic plains - needed for Mordor, makes total sense.  Keep.
- Arctic - if we go far enough North, I think we'll need this.  We should revisit stats, modifiers and even the name though.
- Caverns - dead.  We're consolidating into a single underground type.
- Halls - dead.  We need to change the label across the whole code to be something more like subterranean or underground.
- Paths of the Dead - true madness.  Cull.

And here is what I think we might be missing:

- Tundra - this would be the natural transition between plains and arctic.  We already have taiga for cold forests, so this feels natural.

**Comment by Jaco-Daan** [comment]
Has been done, closing
