### ISSUE TITLE
The shards of Narsil do not get destroyed after Anduril is made

### ISSUE THREAD

**Issue by Hendrix1337x** [jj248/RealmsInExile#1025]
After Aragorn becomes King and wields Anduril the court artifact of the Shards of Narsil still exists.
![narsil](https://github.com/jj248/RealmsInExile/assets/154389264/ca79e71f-2555-4546-8d30-0b17911433f1)

**Comment by BriceLeduc** [comment]
Yes, that's because I haven't coded the events yet

**Comment by Hendrix1337x** [comment]
Post King Strife the shards of narsil do not get destroyed
![image](https://github.com/jj248/RealmsInExile/assets/154389264/dd173340-7022-40d3-bf46-c353bee003cc)

**Comment by Hendrix1337x** [comment]
This might be due to the grand wedding not taking place, but i didn't get the Anduril event
![image](https://github.com/jj248/RealmsInExile/assets/154389264/f7ca695c-5dca-4a6c-aba3-a11fcda389a7)

**Comment by savagesach** [comment]
I pushed a fix, this still needs to be tested to close.

**Comment by Hendrix1337x** [comment]
I haven't come across this in all of my games ever since the fix so I'm closing this issue.
