### ISSUE TITLE
Unable to assign new loremaster

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#1026]
![Image](https://github.com/jj248/RealmsInExile/assets/76008882/48a84d56-28f0-46fa-8838-8d96c949058a)

Playing with lay clergy; temporal revocable (Turthalis Dunlending faith) I reassigned my loremaster (Who was also a landed ruler) to be my chancellor. This made me permanently unable to assign a new loremaster. This can only be fixed by converting to a different faith with theocratic clergy.
Please investigate and fix

**Comment by BriceLeduc** [comment]
I have encountered this bug too as an Erulaitale. It's very annoying

**Comment by BriceLeduc** [comment]
I believe it's a generic issue in the mod

**Comment by Jaco-Daan** [comment]
This bug has been fixed, closing
