### ISSUE TITLE
Grey Mountains pathing

### ISSUE THREAD

**Issue by blackbird5598** [jj248/RealmsInExile#1028]
The county directly east of Nordinbad isn't registering as being next to it, instead the county west of Nordinbad is counted as the one next to it. So the player both has to colonize west & move their armies west to go east. 
![image](https://github.com/jj248/RealmsInExile/assets/125709421/9fd7257f-e6d3-4e4a-a0f1-1dfa61f56dd9)

**Comment by Cairo-Fischer** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/110961821/1e67b830-7c5b-4d87-a098-f108ecb6e8d0)
Seems to be working now
