### ISSUE TITLE
Dwarves fulfill the requirements for the Overseer of the mines post but yet, can't be appointed

### ISSUE THREAD

**Issue by Hendrix1337x** [jj248/RealmsInExile#1029]
Don't know what's causing this :((. It doesn't matter if they are councillors or courtiers with no jobs they still can't be assigned.
![image](https://github.com/jj248/RealmsInExile/assets/154389264/5e19a283-4aef-4e2d-b0bb-2f8074c98643)
![image](https://github.com/jj248/RealmsInExile/assets/154389264/4468d4ed-9beb-4929-b5a7-28b689bfa647)

**Comment by BriceLeduc** [comment]
That's because Dwarves can't use this job. Instead they can become Stonesingers

**Comment by Jaco-Daan** [comment]
This was caused due to merging errors with the old artifact_crafting branch, has been solved + tested. Closing
