### ISSUE TITLE
Adventure inspirations seem to be bugged

### ISSUE THREAD

**Issue by Hendrix1337x** [jj248/RealmsInExile#1031]
Sent my son to the Grey Mountains. The adventure completes but the character returns with nothing (this is after i told him to bring back something unique)
![image](https://github.com/jj248/RealmsInExile/assets/154389264/350c5bcc-b2cd-40ad-a056-d189cf587dc3)

**Comment by BriceLeduc** [comment]
That's because I haven't coded any unique items for 4.0 yet. It's not a bug, it's just WIP

**Comment by BriceLeduc** [comment]
This is merged with  #1058
