### ISSUE TITLE
Stale air removed building does not clear

### ISSUE THREAD

**Issue by savagesach** [jj248/RealmsInExile#1032]
I noticed that there is a chance that when the stale air building is cleared, the building does not get properly removed like it is supposed to. My guess is that it has to do with the toxic leak event but I'm not 100% sure.

**Comment by savagesach** [comment]
I pushed a fix for this, it just needs testing to make sure it worked

**Comment by Cairo-Fischer** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/110961821/c52786b9-bac6-48fc-8603-0c4d3dbfc19a)
Before
![image](https://github.com/jj248/RealmsInExile/assets/110961821/050185cc-d754-4e30-b3d4-534c955c1649)
after
Works
