### ISSUE TITLE
Loc Error in Riddermark puppet decision

### ISSUE THREAD

**Issue by Hendrix1337x** [jj248/RealmsInExile#1033]
It doesn't show Eomer and Theodred's names in the requirements for the decision
![image](https://github.com/jj248/RealmsInExile/assets/154389264/4ef3a49a-0689-4026-8c06-83c5bc045dac)

**Comment by jj248** [comment]
It certainly used to!

**Comment by savagesach** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/86676697/fb956c49-e706-4683-a4bc-50eaf53fc4f0)

**Comment by Cairo-Fischer** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/110961821/f5ddd7e2-0b45-4663-8db6-ada4da3e9022)
Fixed
