### ISSUE TITLE
Aragorn and his empires get Male Only succession law

### ISSUE THREAD

**Issue by Hendrix1337x** [jj248/RealmsInExile#1037]
i was told this isn't how it's supposed to be
![image](https://github.com/jj248/RealmsInExile/assets/154389264/8a9ac499-4f33-468e-8a94-95e02b7fc478)

**Comment by savagesach** [comment]
I pushed a fix, this needs to be tested

**Comment by Hendrix1337x** [comment]
This appears to be fixed.

<details>
<summary>Click to Expand</summary>

![image](https://github.com/jj248/RealmsInExile/assets/154389264/c083c3d0-6812-4342-b177-5f44f33a4b22)

![image](https://github.com/jj248/RealmsInExile/assets/154389264/7fa7e4f3-55b8-46a7-823d-413aff0a5f4e)

![image](https://github.com/jj248/RealmsInExile/assets/154389264/491e0582-e073-4ebf-92bf-29868d800575)

</details>
