### ISSUE TITLE
Destroying Mordor force converts Saruman to white hand

### ISSUE THREAD

**Issue by Hendrix1337x** [jj248/RealmsInExile#1044]
Using the **Random AI Behaiviour** game rule. If Saruman does not fall into darkness and remains good, whenever one uses the destroy mordor decision, upon succeeding he automatically converts to the cult of the white hand. I assume this is not intended
![image](https://github.com/jj248/RealmsInExile/assets/154389264/019b7f01-d470-49bf-97c6-4a858093c861)

Also, it is not part of the demands that get enforced upon winning the war at least from what i can see as in the pictures below
<details>
<summary>Click to expand</summary>

![image](https://github.com/jj248/RealmsInExile/assets/154389264/c8df42bc-8497-445d-a0e0-78483209a053)

![image](https://github.com/jj248/RealmsInExile/assets/154389264/23d8e0e3-dc7c-4bd7-bcc3-eace2729b5d5)

</details>

**Comment by leadsupport** [comment]
This has been fixed, closing
