### ISSUE TITLE
Gondor CoAs using Uruk CoAs

### ISSUE THREAD

**Issue by MattTheLegoman** [jj248/RealmsInExile#106]
Duchies, counties and baronies are using Uruk CoAs because the Uruks start landed there. They should initially have Gondorian CoAs.

Won't fix baronies in Realms 2.1. Mark this done when duchies and counties are complete.

**Comment by MattTheLegoman** [comment]
ToDo: create barony CoAs in Gondor and Mordor.

**Comment by jj248** [comment]
I don't think creating barony CoAs in these areas is a great use of our limited time, so shifting this to v3.0 pipeline.

**Comment by jj248** [comment]
Ditto comment above - moving to v4.
