### ISSUE TITLE
"Full Tolerance" doctrine automatically given on faith creation

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#1062]
Faiths gain a "Full Tolersnce" doctrine when created or reformed, that makes them friends with everybody. Dont think it can be removed.

I havent encountered this recently so i cant provide screenshots, but we've had at least one additional report - please recreate.

**Comment by Hendrix1337x** [comment]
Does not seem to be the case any longer, keeping this open in case there's a similar report again though.

<details>
<summary>Click to Expand</summary>

![image](https://github.com/jj248/RealmsInExile/assets/154389264/4f5ff448-0c44-432e-90a6-c166fb91caf5)

![image](https://github.com/jj248/RealmsInExile/assets/154389264/c24c0154-b92e-4733-9245-45815003c59d)

![image](https://github.com/jj248/RealmsInExile/assets/154389264/6208d398-d8f4-4cf1-965e-4c1bf84725c4)

</details>

**Comment by Jaco-Daan** [comment]
Seems to have been fixed, closing
