### ISSUE TITLE
Nimphelos artifact description localization broken

### ISSUE THREAD

**Issue by Lewa263** [jj248/RealmsInExile#1063]
I used the console to give myself the artifact Nimphelos after sending an adventurer to Belegost and getting nothing. Then I saw that its description is broken. Looking at the localization file, there's a whole sentence that isn't here. I think it's because there isn't any game concept defined for Belegost.

![2024_03_03_4](https://github.com/jj248/RealmsInExile/assets/18605346/943bc822-c40b-4161-bff4-e9625322739c)

**Comment by BriceLeduc** [comment]
Fixed, thanks. https://github.com/jj248/RealmsInExile/commit/7d3a6372857e91f3d96e608192342fbc1714bcdd
