### ISSUE TITLE
Subterranean holding GUI does not display plague resistance

### ISSUE THREAD

**Issue by Lewa263** [jj248/RealmsInExile#1068]
With patch 1.12, there is a new line in the holding GUI that displays plague resistance. This has not been included into the mod's overwritten GUI for subterranean holdings.

See the Plague Res. line shown below Supply Limit on this aboveground Dwarven holding:
![2024_03_10_2](https://github.com/jj248/RealmsInExile/assets/18605346/e1edf229-da78-4478-b2c1-b740896468c6)
versus the lack of that on this underground Dwarven holding:
![2024_03_10_3](https://github.com/jj248/RealmsInExile/assets/18605346/a16d4c8c-26e3-4642-ae3a-4f07d0cd9e95)

**Comment by Lewa263** [comment]
The subterranean holding GUI also doesn't show plagues or legends currently spreading in that holding. The little colored diamonds with the disease or legend icon on them, like in this holding here that has two legends and a plague.
![2024_03_26_4](https://github.com/jj248/RealmsInExile/assets/18605346/7c66a738-157d-49ec-be0d-aae86474f38a)

**Comment by Jaco-Daan** [comment]
This has been fixed, closing

**Comment by Lewa263** [comment]
Nothing has changed, so I don't know why you're calling this fixed.

**Comment by Jaco-Daan** [comment]
Did you test it? One can clearly see the legend and the disease in the underground county view here. Closing
![20240417212655_1](https://github.com/jj248/RealmsInExile/assets/62937916/0cfbf132-e74b-4dac-98eb-03181ca26f73)

**Comment by Lewa263** [comment]
That second part that I noticed later is fixed, yes. Now we need to fix the part that is in the title of this issue and the first part that I reported.

**Comment by Jaco-Daan** [comment]
Fixed in latest push, thanks, closing
