### ISSUE TITLE
Wulfgar is shown as having Adornaen culture on the Horse and Rider bookmark

### ISSUE THREAD

**Issue by Lewa263** [jj248/RealmsInExile#1070]
Wulfgar has regular Dunlending culture, but the bookmark claims otherwise. I think that counts as localization, not scripting, but maybe I chose the wrong label.
![2024_03_10_5](https://github.com/jj248/RealmsInExile/assets/18605346/c95e1683-1819-4e1a-9af3-764060159d18)

**Comment by cmrobinson** [comment]
Sorry for the in the log here, I was getting my gpg signing figured out.

**Comment by Jaco-Daan** [comment]
This has been fixed, closing

**Comment by Lewa263** [comment]
Nothing has changed, so I don't know why you're calling this fixed.

**Comment by Jaco-Daan** [comment]
Ohh, I see now the commit was made on a fork? For whatever reason. Easy enough fix

**Comment by Jaco-Daan** [comment]
Fixed
