### ISSUE TITLE
Heritages need `is_shown`

### ISSUE THREAD

**Issue by Lewa263** [jj248/RealmsInExile#1071]
Cultural heritages have an `is_shown` now, so that needs to be added to the mod's heritages to prevent there being a list of every heritage when diverging or hybridizing cultures. See the bug report on the Discord here: https://discord.com/channels/751097183448727552/1214793844780965899

**Comment by BriceLeduc** [comment]
fixed c9dc258f079ff4ba188ed54ee95dad8198d875d6

**Comment by Jaco-Daan** [comment]
This has been done, closing
