### ISSUE TITLE
Problems with Erebor-Dale defensive alliance and Huz Margoz War In The North

### ISSUE THREAD

**Issue by Lewa263** [jj248/RealmsInExile#1082]
I've run into a problem involving both the defensive alliance system and Huz Margoz's decision-started war against Dale. This save was started this afternoon, in between commits 8f37caa and adb34d0. I foolishly failed to save or get any screenshots right before the war, so I'll have to make do with what I can screenshot from right before finishing it.

Sometime after King Bain's death, Dale and Erebor no longer had a defensive alliance. That was the case when I used the decision as Huz-Margoz to begin the "War In The North". Erebor was uninvolved in that war.
![2024_03_18_3](https://github.com/jj248/RealmsInExile/assets/18605346/9e143c6b-7cde-4c06-bc3c-9bef0eec9e0c)

At some point during the war, King Bard acquired a new defensive alliance with Erebor, who still did not join.
![2024_03_18_4](https://github.com/jj248/RealmsInExile/assets/18605346/1b229c23-ac73-4a6a-8d85-b564eecd9068)

Additionally, the defensive alliance doesn't show up for Dain.
![2024_03_18_5](https://github.com/jj248/RealmsInExile/assets/18605346/8d97cfe5-0e8b-4072-a40f-18ee292d3244)

Then, when I won, Dain was killed and de jure Erebor was decolonized, all without having participated in the war.
![2024_03_18_6](https://github.com/jj248/RealmsInExile/assets/18605346/5011ec1a-e0ef-4ebb-89ef-8c26f19a3b55)

**Comment by Lewa263** [comment]
Oh, that war also gives Huz Margoz both the kingdom and duchy of Erebor even though they've been returned to wilderness. That seems unintended.

**Comment by Jaco-Daan** [comment]
This has been dealt with, closing
