### ISSUE TITLE
Merge of Court Historian and Court Chronicler penalizes non-DLC owners

### ISSUE THREAD

**Issue by Lewa263** [jj248/RealmsInExile#1084]
Previously, this mod had its own court position named Court Historian that was used for the Historical Endeavour activity. Legends of the Dead came with a new court position called Court Chronicler that was used for Legend stuff. Those positions were merged in the Beta, which makes sense. The problem, though, is that the Court Chronicler is only available to players who own the DLC. If a non-LotD-DLC-owner tries to do a Historical Endeavour activity, an event will try to assign them a Court Chronicler even though that court position is invalid for them. It may be necessary to revive the Court Historian only for those without the DLC. See bug report on Discord here: https://discord.com/channels/751097183448727552/1218553047807037500

**Comment by BriceLeduc** [comment]
Yes, unforeseen consequence of the merge. I'll just use the antiquarian for players who don't own the DLC

**Comment by BriceLeduc** [comment]
061e7768f4794a41e56ef1040e45b56cbdb1922a
