### ISSUE TITLE
Return of the King events give all of Steward's court artifacts to player Aragorn

### ISSUE THREAD

**Issue by Lewa263** [jj248/RealmsInExile#1086]
If the player is Aragorn instead of the Steward when Aragorn becomes King, then the player is given all of the Steward's court artifacts. Not just the Throne of Gondor and the Palantir, but also the Hurinionath house and Ostomirionath dynasty banners, the Black Chair of the Stewards, and anything else the Steward acquired in those 19 years. The artifact transfer works correctly when the player is the Steward, where only the Palantir and Throne are given to the King and the Steward keeps his own things.

**Comment by BriceLeduc** [comment]
Could you test that again please ? I think my fix should work : the Steward title is destroyed instead of being transferred to Aragorn.

**Comment by Lewa263** [comment]
The artifacts are now transferred correctly. I tested from my 3018 save that I made yesterday, switching to be Aragrn, Denethor, and observer during the events. In every case, Denethor kept his stuff.

However, all of Gondor's vassals now become independent when Aragorn takes the throne, leaving him with only Denethor's land and what he had in Arnor.

**Comment by savagesach** [comment]
I reverted the fix, so gondor will no longer explode

**Comment by Jaco-Daan** [comment]
This issue has been fixed, as can be seen in the SS's below. While playing as Aragorn, I fired the event and only the necesarry artifacts transferred
![20240417211658_1](https://github.com/jj248/RealmsInExile/assets/62937916/c39bf592-2cd7-453c-a98b-63163090ad13)

![20240417211709_1](https://github.com/jj248/RealmsInExile/assets/62937916/b42bff6d-7797-4ac7-80fa-64741ead9754)
