### ISSUE TITLE
Trespassing Neighbours event (id `orcs.0015`) doesn't check for existence of neighboring orcs

### ISSUE THREAD

**Issue by Lewa263** [jj248/RealmsInExile#1090]
The event `orcs.0015` does not have any check in its trigger block for the existence of a neighboring orc, but then selects a random one in the immediate block to save as a scope. The event options all have effects involving this scoped neighboring orc, who may or may not exist.
![2024_03_22_1](https://github.com/jj248/RealmsInExile/assets/18605346/31df14f8-dfc3-41df-b119-a7ee27349efd)

**Comment by Jaco-Daan** [comment]
This issue has been fixed, and the appropriate trigger has been added
![20240417211954_1](https://github.com/jj248/RealmsInExile/assets/62937916/a420e9ac-122a-4aed-bfa2-6d38f195ff3f)
