### ISSUE TITLE
Axe that Walks is expedition-coded but is handicapped after using them

### ISSUE THREAD

**Issue by BriceLeduc** [jj248/RealmsInExile#1093]
The Axe-that-Walks is being advertised as _the_ ideal character for going on Dwarven expeditions.
Expeditions can only target underground counties.
However, his culture has the "Surface Dwellers" tradition, meaning he is handicapped when holding Delvings.

We're encouraging players to play the character one way, and we're punishing them for doing just that

**Comment by Jaco-Daan** [comment]
So this has been fixed, closing
