### ISSUE TITLE
Aladdin fake prince/princess event fires for Elves

### ISSUE THREAD

**Issue by Lewa263** [jj248/RealmsInExile#1094]
I've twice been invited to Grand Weddings for one of Elrond's sons marrying a "_, Fabulous She" fake foreign princess. Should that Aladdin event (id `court.0108`) be blocked for Elves? It feels wrong for them (though I'm no lore expert), and the conditions of there needing to be a same race kingdom outside of diplo range mean that the spawned prince/princess can end up with a culture that doesn't belong outside of Valinor.

**Comment by BriceLeduc** [comment]
I've defined the event like this, it's fine. The vanilla event isn't realistic either. Anyway Elves rarely ever marry so it adds a few weddings

**Comment by BriceLeduc** [comment]
The addition of Thani-Hazad will add more variety to the ppssible cultures
