### ISSUE TITLE
Generic legend seed that all rulers seem to have now (also with broken localization)

### ISSUE THREAD

**Issue by Lewa263** [jj248/RealmsInExile#1095]
![2024_03_26_3](https://github.com/jj248/RealmsInExile/assets/18605346/15481a1c-4fe6-4f88-8d24-7b836aea3d0c)
Whichever ruler I start as, there's a legend seed listed that has this same broken loc. The name of the legend is somewhat randomized. I loaded up CK3 without mods and was not able to find this legend seed on any of the rulers, even the ones who don't have their own specific legend seed. So I believe that the existence of this seed everywhere is a bug, and then its localization being broken is a secondary bug.

**Comment by BriceLeduc** [comment]
What do you mean by randomised ?

**Comment by Lewa263** [comment]
This appears to have been fixed. I can't find that legend seed on anyone now.
