### ISSUE TITLE
Elven Vanquish Darkness CB effect missing Forodwaith and Arnor

### ISSUE THREAD

**Issue by Lewa263** [jj248/RealmsInExile#1097]
The Elven Vanquish Darkness CB installs new non-evil rulers for the land targeted in the war using the scripted effect `vanquish_darkness_generate_new_holder_culture_and_faith` in the `lotr_elf_effects.txt` file. This is done by checking which empire (or sometimes kingdom) the targeted titles fall into. However, there is no set culture and faith for the de jure empires of Forodwaith or Arnor. The effect falls back on Gondorian culture and Erulaitale faith for these parts of the world. Forodwaith does start with subterranean orcs, and their land cannot be given to Gondorians, causing it to become depopulated instead (see bug report on Discord: https://discord.com/channels/751097183448727552/1223675028910899250).

**Comment by Lewa263** [comment]
I saw that Forodwaith was added to the effect in the 4b6a943 commit by setting the culture and faith to Lossoth and their faith, but that doesn't solve the problem reported in the Discord. A Lossoth ruler will still be unable to hold subterranean titles, and there are subterranean orcs in Forodwaith.

**Comment by Jaco-Daan** [comment]
This has been fixed, since the Vanquish Darkness CB can't be used underground, closing
