### ISSUE TITLE
Former ruler of Annuminas is given only settlements, has Unsettled government

### ISSUE THREAD

**Issue by Lewa263** [jj248/RealmsInExile#1098]
When the ruler of Annuminas is moved to rule the surrounding counties after Aragorn becomes king, the old ruler is given only settlement holdings and is given Unsettled government. VakuAnkka reported this a few days ago in the Discord (https://discord.com/channels/751097183448727552/751097880101650532/1223356774405636136), and I have now encountered it too.
![2024_03_31_2](https://github.com/jj248/RealmsInExile/assets/18605346/7d9fca0c-1804-48cf-ad66-271ec5b9888c)
![2024_03_31_3](https://github.com/jj248/RealmsInExile/assets/18605346/44983a3d-1ace-448f-9d3f-732f00a39a4a)

**Comment by Jaco-Daan** [comment]
This has been fixed, confirmed by one of the community members playing the Open Beta. Closing
