### ISSUE TITLE
Dor Giril dynasty of Belfalathrim characters all have tier 3 Numenorean blood

### ISSUE THREAD

**Issue by Lewa263** [jj248/RealmsInExile#1109]
The Dor Giril are an unlanded dynasty of Belfalathrim culture. Every living member and their lowborn spouses all have tier 3 Numenorean blood.
![2024_04_10_3](https://github.com/jj248/RealmsInExile/assets/18605346/082e8c2e-6b87-46e4-adfc-3160d97aeb18)
One of the Aredhels shown in this screenshot is not part of the Dor Giril dynasty or married to any of them, but does have the script character id `dynasty_dor_giril87`, so if all of the `dynasty_dor_giril` characters in the history file get their blood diminished, it should fix her as well.

**Comment by Jaco-Daan** [comment]
Easy fix, closing
