### ISSUE TITLE
Dwarven Expeditions create aboveground Delving holdings

### ISSUE THREAD

**Issue by Lewa263** [jj248/RealmsInExile#1113]
I reported this on the Discord, and the 5d4a1b9 commit was meant to fix it. Then it was reported on the Discord after the Beta was updated: https://discord.com/channels/751097183448727552/1229129982366715974 I checked again myself, and it is not fixed.
![2024_04_14_1](https://github.com/jj248/RealmsInExile/assets/18605346/200bfbdb-fd05-4270-9b32-71d8110ba48e)

**Comment by Jaco-Daan** [comment]
This has been fixed, closing

**Comment by Lewa263** [comment]
Still a problem on the master, reopening.

**Comment by Jaco-Daan** [comment]
Fixed, turned out I only fixed the delving/castle problem for the AI Argan, and not the player
