### ISSUE TITLE
Scripted character templates for corsairs and dunedain don't add numenorean blood for them

### ISSUE THREAD

**Issue by Pickrone** [jj248/RealmsInExile#1119]
![2024-04-15](https://github.com/jj248/RealmsInExile/assets/106013191/d4bb6c6b-cc21-4266-95ce-33decdfc8e52)

Scripted character templates for corsairs and dunedain should add numenorean traits for them, but they don't.

**Comment by Lewa263** [comment]
Is there any evidence of these not working? The only place that these templates are used is in some events for Dunlendings. I played a Dunlending a few weeks ago and got a generated Gondorian with Numenorean blood that way.

**Comment by Pickrone** [comment]
Almost every random character with Gondorian culture should have at least tier 1 blood of numenor, but after starting new game you will never see them.

**Comment by Hendrix1337x** [comment]
Across numerous test runs and playthroughs i always end up seeing randomly generated characters with the numenorean trait (However they are exceptionally, and i mean exceptionally rare)
