### ISSUE TITLE
Underground Ruler Designer Crash

### ISSUE THREAD

**Issue by leadsupport** [jj248/RealmsInExile#1120]
If a custom character is created in a Subterranean domain with an overland culture, the game will immediately CTD when you click the finalize button. I have attempted to resolve this by making them unplayable, like Valinor, but that doesn't get checked until after you finalize. The only way to fix this seems to be by editing the Finalize button GUI element, which is possible but unfortunately outside my skillset.

**Comment by Jaco-Daan** [comment]
Should be fixed, pushing to testing

**Comment by Jaco-Daan** [comment]
This has been confirmed as fixed, closing
