### ISSUE TITLE
Underground Holding UI Issue

### ISSUE THREAD

**Issue by leadsupport** [jj248/RealmsInExile#1124]
When hovering over any section of the underground holding UI aside from an enabled button, it only shows plague resistance, even if you are not hovering over the plague resistance section of the UI. This prevents hovering over province modifiers, terrain types, and disabled buttons to see effects and requirements
![image](https://github.com/jj248/RealmsInExile/assets/127911521/40a0bbfb-b502-4ccd-849a-ccad381d147c)

**Comment by Jaco-Daan** [comment]
Fixed, accidently copied the GUI code outside of where it should be
