### ISSUE TITLE
Struggle ending event has unfitting localization for Maglor

### ISSUE THREAD

**Issue by Lewa263** [jj248/RealmsInExile#1127]
Maglor gets a shot at defeating the Balrog as part of his event chain, and if successful, the Struggle ending event comes up. It still has all the usual text as if it were a Dwarf who accomplished it, though, so Maglor is said to be crowned King of Moria and all that. There is already a `triggered_desc` variant for this last paragraph for a Dwarf who dies killing the Balrog, so it would only take somebody writing another for Maglor as the sole non-Dwarf who can end it.
![2024_04_25_2](https://github.com/jj248/RealmsInExile/assets/18605346/96848d9d-da89-4c29-8438-bbdf6b1bb442)

**Comment by Jaco-Daan** [comment]
Getting Vector to write this for me now, closing.
