### ISSUE TITLE
Assassination/Intrigue Balance?

### ISSUE THREAD

**Issue by VectorMaximus** [jj248/RealmsInExile#131]
As brought up in chat, something to think about balance-wise.

griglich — Today at 4:14 PM
Is there going to be any adjustments on scheme power re: this? Playing as Sauron for example, I was able to get rid of my high martial score opposing Gondorian lords through Murder schemes, including both of Denethor's sons. That could enormously cripple an elf realm given that they won't remarry.

griglich — Today at 4:17 PM
Making it weaker could bring other options closer to the fore for players, though, and it would be good for multiplayer games as well to not have to rely on a gentleman's agreement.

**Comment by JukeJukestar** [comment]
I personally think sauron's (and some other main characters') stats should be nerfed. The intrigue system was designed for a great schemer to have intrigue stats in the higher 10's and a master schemer to be in the 20's. The system breaking with a 50+ intrigue character is to be expected.
Sauron isnt a regular, random ruler and should have extra high stats, but his current ones at game start are ridiculous when you consider that they will naturally further improve as the game continues and he picks up more skills and perks on his own.

Its very appealing to give all the main characters amazing stats but the game wasn't designed around every character being an absolute god. In my personal opinion saurons stat spread at game start should be nerfed all around, while the nazgul's "main attributes" should be nerfed by around 10 aswell.

**Comment by jj248** [comment]
Let's deal with this as part of 3.0.  We'll need to have a proper think through of stat values anyway when we get to implementing the elves which could end up OP by their nature.

**Comment by JukeJukestar** [comment]
close?
