### ISSUE TITLE
Sauron can die from a botched treatment

### ISSUE THREAD

**Issue by ercarp** [jj248/RealmsInExile#20]
_Reported by **GasPOGne** on Discord._

Sauron died from a botched treatment in this person's game. The odds of this happening should be extremely small given his health and disease resistance bonuses, but if possible, we should probably try to prevent it from happening altogether.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/78575425/113494388-699eaa80-94f0-11eb-9ea0-4790ff274c4a.png)

</details>

**Comment by jj248** [comment]
Or indeed from other more mundane methods:
"Can you look into Sauron being KIA as well? In one of my games, Sauron got off'd by a 4-prowess she-orc"

**Comment by jj248** [comment]
These characters shouldn't be getting ill or sick anyway, but to be safe I've removed them as candidates for court physicians to treat.

**Comment by JukeJukestar** [comment]
Consider closing, havent seen this happen exept in the general "immortal character dies due to event added in new dlc" sort of way
