### ISSUE TITLE
Pirate republics based on Res Publica

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#211]

**Comment by jj248** [comment]
Not going to have time to do it justice in v2.2, should comment out RP from current dev build and move to v3.0.

**Comment by Remerod** [comment]
I agree, this should be a feature that is not rushed, but something that is really thought about

**Comment by jj248** [comment]
Done.

**Comment by JukeJukestar** [comment]
Make the "found republic" decision invisible for now until its fixed
(currently you can take it, but you wont get any special republic UI stuff and I believe the realm stays in primogeniture)

**Comment by VectorMaximus** [comment]
All Res Publica stuff should be invisible for now.

**Comment by JukeJukestar** [comment]
Closing this for now, perhaps we can reconsider this sometime in the future when PDX inevitably releases the Republic DLC
