### ISSUE TITLE
The Last Alliance of the Númenórean Realms decision

### ISSUE THREAD

**Issue by RedArkady** [jj248/RealmsInExile#228]
Once you have diplomatic contact with Gondor (a challenge in itself), there could be a Decision to create a permeant alliance with functionality similar to the Oath of Eorl. It would refer to the Debt of Elendil ("Macilion of Silmalondë bids you repay the debt of Elendil") and the Ship-king alliance, but would be framed within the context of the War of the Ring - Sauron is back, it's the End Times, the people of Eru must hang together or hang separately. It could perhaps require Living Legend status to enact. As Vector suggested when we discussed this earlier in the year, it could be more 'quid pro quo' than the Oath of Eorl - you can request help, and if it's granted then the other kingdom owes you - and would suffer extra penalties of they don't repay the Debt when called on.

**Comment by JukeJukestar** [comment]
Should be an activity where the Ruler of Bellakkar sails to gondor as an activity - possibly using the sailing framework

With some minor challenges like Umbareans trying to intercept your ships or a storm forcing you to turn around/ maybe get wounded

**Comment by jj248** [comment]
Let's reconsider as part of 2.3 / 3.0.

**Comment by savagesach** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/86676697/74638246-5ba5-4b54-875b-84901c931b4b)
![image](https://github.com/jj248/RealmsInExile/assets/86676697/315c7be0-67d0-43a7-93ee-7676ee8ed6f2)
The Bellakar alliance decision works as intended.
