### ISSUE TITLE
Unite the Faithful Realms decision

### ISSUE THREAD

**Issue by RedArkady** [jj248/RealmsInExile#229]
Decision mechanic to peacefully unite Bellakar and Gondor through marriage.
-would combine abdication with a post-crusade-style 'play as another character' option.
-your character or player heir must be married to Gondor's ruler/heir
-your character/player heir must have an eligible heir with Gondor's ruler/heir
-the decision would then become available to abdicate and grant your titles to your heir (or your husband)
-you would then have the choice to play as your heir OR Gondor's ruler.

**Comment by JukeJukestar** [comment]
I feel making gondor even stronger may be a bit too powerful - maybe an alliance is enough for them to help eachother

**Comment by jj248** [comment]
Let's reconsider as part of 2.3 / 3.0.

**Comment by Jaco-Daan** [comment]
Can this issue not be merged with issue #228? They essentially both do the same thing with different approaches

**Comment by JukeJukestar** [comment]
- You need to verify if you need to update all geographical regions including felaya or bellakar to account for the duchies no longer being the same if they shift into the duchy of felaya
- You need to update the "subjugate bellakar" and "subjugate the bay of felaya" decisions for Abrakhan to account for  the kingdomsnilulonde/ bellakzen/ felaya no longer existing
- You need to update the "Refound the Katajate" decision to account for the kingdom of felaya no longer existing

**Comment by Jaco-Daan** [comment]
This has been finished, closing for now
