### ISSUE TITLE
An early Review of Bellakar and the Bay of Tûlwang 

### ISSUE THREAD

**Issue by Remerod** [jj248/RealmsInExile#232]
After having problems with my pull I was thinking on what to play out next and ended up play Bellakar and the region around Bay of Tûlwang 

**Bellakar**

* _It's Flag and map colour not Teal_ :P

 So Starting as High King Nîlûhîn. Playing around in Bellakar i can quickly see it has a very Good position in the start of the game, they have both the north and east as natural expansion, especially against the tribals in their de jure lands of Nîlûlondê.
And with Royal Courts coming up, i can see their realm focus a lot more internal stuff! I think it will come along great.

But there are a couple of things that i've noticed that i think could be improved upon:

* Almost every Landed and Unlanded Noble in Bellakar is married, there are a few that ain't but it isn't just a problem there, the realms around you marries their offspring's of quickly. As High King Nîlûhîn i don't feel like i have a "natural" betrothal option for my little princess to one day to marry. i also played around 10 years with Thôn An-Khârlôkh and Ray, and not as much there still is a lot of old folks married and not that many young ones unmarried. While I think that it's good not to force the players heirs into a marriage, having some "optional" railwaying path of potential suitors would not be bad either, especially for a grand realm like Bellakar. 

* Both my Wife and Mother is magnificent nobodies, they don't have any dynasty, and unless there is some big lore reason for this i think most people would expect the high kings of Bellakar to marry nobility?

* While AI Bellakar won't expand to fast, at start, which is kind of good, the reason to this is because they can only declare religious wars. But in the players hands, well you find ways. If you now have to get high piety fast expanding will be very easy for the players, You are clearly the power house in the south west in the beginning of the game, and you should have some early threat towards you. Because "in my opinion"at the moment you kind of are Byzantium with out a Abbasid, you kind of have your "Seljuk" with Abrakhan later on in the game. And while you can argue that Thôn An-Khârlôkh is the abbasid, they are not that "currently" to me.
- Thôn An-Khârlôkh always splinter apart for me, in basically every game i've played and useally early on to, like withing 10-20 years, while that might not be bad for "their" gameplay, it is for Bellakars in my opinion.
-While Bellakar do get raided it's mostly from the independent realms in Qarsa and Aukar, and for this to be a real threat I would like to see more of the Mardrûak corsairs and I see some of the northern Tûlwanf have the corsair faith, would nice if they raided Bellakar, Because they haven't raided me yet, nor have i seen them do so in an observer game i runned for 50 years.

* Some details on the 50 years observer game
-The kingdom of Tûlwang, made by a new branch from the Anbalûkkhôrôhîn broke out from Thôn An-Khârlôkh, have proven more of a challange to bellakar 35+ years after start then Thôn An-Khârlôkh ever was.
-by 3040 Abrakhan is no way near Bellakar although they border ray.
-The realms inside Qarsa and Aukar raids Bellakar more then any one else.
-some internal populist and liberty wars.
-so while 50+ years into the game Bellakar will have more natural opponents they certainly lack a real threat in the start. (and have yet come into conflict with Abrakhan)

Seeing Bellakar's state made me interested in how Thôn An-Khârlôkh was.

**Thôn An-Khârlôkh**
Starting as Storm-Marshal Gimilkhâd, I played a quick 10 year to get an view on Thôn An-Khârlôkh early games perspective. Thôn An-Khârlôkh definitely seems very interesting from the internal perspective as holding your realm together, which will probable even more built upon with Royal Courts. Interal conflict is a lot more common here then Bellakar, with being the minority in both religion and culture there is a lot to do inwards in the early game. Especially when i see AI Thôn An-Khârlôkh breaking apart almost always. I had some fun 10 years playing as Storm-Marshal Gimilkhâd.

But there are a couple of things that i've noticed that i think could be improved upon:

* As with Bellakar, There are no "real" early external threats. 
- You can declare war for "raid for captives" against the realms eastern neighbors, but not on bellakar. You don't have to fear from Bellakar, because they probably won't declare a holy war at you, the other "Major" power would be Ray but they are not that great of a threat. 

* Do we want the Capital Khorsâj to be on a lone Island with a waterway as the only to reach it? or should there be a bridge or two to it?

* Religion, i think the temple barony holders should have a cooler title then "baron", that is more in line to the description to the faith of Batân an-Aphan
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/147152535-8bc623a3-0d72-486e-b73a-6473fd6ebcc3.png)

</details>

* This is not necessarily an issue but I feel like why i don't mind it myself there is a lot of barony hold filled counties down in An-Balkûmagân, to me it make it seem like they are "richer" in people then Gondor because of this. If that is intended that's fine, but if we wanna make Gondor seems "bigger" then perhaps some barony holds should return to "no holding", this would also allow us to build them up ourselves with time.

I also checked out how Ray was

**Ray**
So Starting as King Vâtalinar, I  played Ray for 11 years because i was interested in the different starting positions of the bay of Tûlwang. With a great economy to boost it! Ray have definitely a great Starting position, it has a great realm size, with very interesting neighbors around them and a great economy to boost it!

But there are a couple of things that i've noticed that i think could be improved upon:

* It's not a mayor thing for ray but they can mostly do holy wars in the region beside de jure. But since they are economical focused and have their religious turmoils "theme" i don't think it's super important to change either, but noteworthy to mention.

* Big religious turmoils, inside your realm. While this could remain as it is now because and still be interesting, it could certainly be build up to something very interesting if developed upon. 
-The religious turmoil do leave the player a feeling of wanting to know more! i feel like if the religions and the backgrounds on how the religious diversity came to be the way it is in the realm are fleshed out some more with maybe some events Ray could be extremely interesting. And it doesn't have to be an outright war but i feel there should be some great turmoils, scheme or diplomatic advances between King Vâtalinar, Mardat of Sûza-Rîy and Dêlasîmor II of Iunástîy.

* While playing just 2 years, I've started around 800-900g i think and made almost up to 1.7k gold. this can easily spiral out of control, Ray literately makes more then 3 times both Bellakar and the storm host. So i feel maybe they need a small economical nerf

**Summary**
While the Kingdom of Ray could remain the same and still be interesting, I feel Both Thôn An-Khârlôkh and Bellakar suffers from not having an early Threat. 
Bellakar have many areas to expand upon but those areas wont be a "threat" to them in the early game, even 50 years into the game there is no real threat, not from the Tedjin confederacy, because they won't advance rapidly towards them enough and they'll probably comes into feuds with Umbar instead(let it be noted that I've not played with a bellakar friendly tedjin though), Thôn An-Khârlôkh will probably have broken apart, Abrakhan have probably just gotten to Ray but Ray could probably hold them off by themselves and while Qarsa and Aukar might have formed during the 50 years they would never truly be a threat to Bellakars existence.
Thôn An-Khârlôkh threat is in their internal conflict and it's eastern neighbors wanting to take advantage of this, but in the players hands this won't probably a big issue. A player could probably unify and hold the realm together while expanding east fast and easily so.
For making Bellakar harder perhaps an idea could be to form maybe either of Qarsa and Aukar into a kingdom or have a titular one present at start and have them trying to weaken Bellakar with a big war constant harder raids. But the easiest solution to both Bellakar and Thôn An-Khârlôkh lack of threats in my opinion would be to force them more into a Byzantium vs Abbasid theater, have there be an early war with them, let them have either some claims on each other or an natural war casus belli, perhaps Thôn An-Khârlôkh can naval raid them and Bellakar gets a "sack Thôn An-Khârlôkh" casus belli from it. Either way as it stands of now Both Bellakar and Thôn An-Khârlôkh are **Easy** and if that's it's intend it's all fine, but if wanting some more interesting conflict & gameplay in the Bay of Tûlwang they need to come form "probably" Bellakar, Thôn An-Khârlôkh and Ray because nations like Abrakhan and Tedjin confedracy won't interact to much in the region, at least not in the first 50 years of the game start. 

**On A Sidenote**
* There are to many with the title name of "high Lords" between Ray, Bellakar and the storm host, some cultural distinction between the titles would be very flavorful and nice :)

**Comment by JukeJukestar** [comment]
Very old Game Review, closing - reopen if needed
