### ISSUE TITLE
Iconic settlements holding style

### ISSUE THREAD

**Issue by Remerod** [jj248/RealmsInExile#239]
**Introduction:**

So i am mostly making this suggestion assuming people don't know about this feature I've stumbled upon, hoping it could add this the artistic take for the mod if liked.

So in Normal ck3 you can halve Great Works appear in the world, Like the Coliseum in Rome or Hagia Sophia in Constantinople, like the pics below. 
<details>
<summary>Click to expand</summary>

Coliseum in Rome
![image](https://user-images.githubusercontent.com/79544635/148275080-0fbc07bd-9407-4684-ade3-cb210c4ca61f.png)

Hagia Sophia in Constantinople
![image](https://user-images.githubusercontent.com/79544635/148275017-31ec6822-f240-4dbf-b9df-53b16e9ea739.png)

</details>

And the mod have obviously already utilized these features (I assume) with places like Stone of Erech... in Erech and Edoras (Castle model) in Edoras
<details>
<summary>Click to expand</summary>

Stone of Erech
![image](https://user-images.githubusercontent.com/79544635/148275450-f18f8e6b-ffe1-4533-b526-e0f08baf0f93.png)

Edoras (Castle model) in Edoras
![image](https://user-images.githubusercontent.com/79544635/148275614-3fe03dd5-83ec-4a4e-9c60-0c7b24c89fb4.png)

</details>

But something i haven't seen in this mod but have in an other is this feature used in an other way. And correct me if i'm wrong or if there is a reason for this! 

**Example & Reason for my suggestion:**

In the Mod **The Kingdom of Heaven: Third Crusade** they've made the special model for "great works" replace the whole barony holding to my understanding, as shown in bellow Jerusalem example, along with some other examples with other stuff i would like to suggest

**Jerusalem** 
<details>
<summary>Click to expand</summary>

Jerusalem
![image](https://user-images.githubusercontent.com/79544635/148276428-0cb58ccb-7a54-4db2-a75e-a5809b096620.png)
Here we can see Jerusalem having a beautiful new model to represent the important city. the **Green circle** ones are level 4 forts, and being the generic holding models, they are identical to the **red circle** one (Jerusalem) what differentiate the two hold between the **purple arrows** are that the **green circle** one have 2 less dev and the **red one** also have an unique building/great works.
The **Blue circle** ones are not part of the hold but part of the terrain. So to me it seems that you can do unique holding models for just one hold with special building/great work?

</details>

**Cairo**
<details>
<summary>Click to expand</summary>

Cairo
![image](https://user-images.githubusercontent.com/79544635/148276587-5b7ec8de-c5e0-49ca-9c78-76b4f6f9c7d2.png)
With Cairo they've made an massive terrain city/holdings doodads around it to make it look grandiose. Like it's the same with their Cairo, as the Jerusalem example. It's the same fort level as the other one across the Nile (**purple arrow**), the **green circle** ones are the normal models for their culture (the one across the Nile, **purple arrows** have a special building the pyramids though). Cairo (**the red circle**) has a different model compared to the **green circle** generic ones. the map terrain city/hold doodads (or what to call them, the **blue circle**), really looks great around Cairo, I really think this art direction they've chosen to take looks awesome 

</details>

**Constantinople** 
<details>
<summary>Click to expand</summary>

Constantinople 
![image](https://user-images.githubusercontent.com/79544635/148284181-ebdffd89-184b-4768-a52b-22843bd5198c.png)
Here we can see a normal holding (**green circle**) for Constantinople but with a grandiose terrain city/holdings doodads around it (**Blue circle**), same as Cairo. It looks great to me

</details>

And while all of my example's is primarily from The Kingdom of Heaven: Third Crusade, i know that mods like The Fallen Eagle: The Dawn of the Dark Ages also have a bigger Rome look with the terrain doodads style.

**Suggestion:**

So i don't know how hard it would be to take on this style, with the assumption that it won't be to hard and take to much time I would suggest some places that i think could benefit from this style;

Edoras
<details>
<summary>Click to expand</summary>

Making Edoras (castle Model) the Hold
![image](https://user-images.githubusercontent.com/79544635/148278400-4bfc544e-01cd-4cdf-a9a8-f6ce74d48bc8.png)
I think Making Edoras (castle Model) the Hold (Shown with the **red Arrow**) would look awesome and if you introduce the elements from Cairo and Constantinople terrain city/hold parts doodad's from their to this respective blue circle examples i think we could get a really well looking iconic place! (not that it isn't now though!)

</details>

Isengard
<details>
<summary>Click to expand</summary>

Isengard hold
![image](https://user-images.githubusercontent.com/79544635/148278953-450e8b9a-6865-45c9-8e60-8e55bfaa8d98.png)
the current model of Isengard looks fantastic, I really like it's size! If with this technique that the Jerusalem example offers and you could still use the same size for the Orthanc model, i think making it the primary hold would look very nice!

</details>

Umbar
<details>
<summary>Click to expand</summary>

Umbar outskirts
![image](https://user-images.githubusercontent.com/79544635/148279557-9d0c9784-45ed-4fd4-aaec-f75cc605c9e7.png)
So for Umbar my suggestion would be with the **blue circle** terrain doodad examples from Jerusalem and Constantinople mostly. While a unique model would not be bad i think umbar could look a lot more impressive with some small terrain city doodad outside the hold, this would make it look bigger and show it's importance better on the map in my opinion! And if the castle hold of Minasthalion get's in the way/make it to clustered it could always move a bit (**orange arrow**) but i don't think that would be necessary.

</details>

Hîdar
<details>
<summary>Click to expand</summary>

Oasis of Hidar
![image](https://user-images.githubusercontent.com/79544635/148280687-f1be0c3a-bc07-4050-bdaf-d32f040c2ff1.png)
Taking Inspiration from the mod AotR new map from Hîdar Source: https://www.moddb.com/mods/the-horse-lords-a-total-modification-for-bfme/news/preview-maps-of-80
I think we could give Hîdar a great work as i dunno _marvelous oasis_ or _ancient oasis city/castle_~ something in that line. Since in the AofR info of it it is mentioned to have originally been built by the numenoreans of old, I think giving it the umbaren ascetic (to specify, just for that hold, around the **red circle**) and have some terrain city doodads with the native ascetic (to show that it have been built upon by the natives since) around the lake/oasis (around the **blue circle**). I think making Hîdar more special gives some extra flavor for the south eastern "Far Harad" that is not necessarily tied to Abrakhan.

(And on a separate note not tied to this suggestion necessarily, could be cool to have the Lordship/Duchy of Dârsalan a republic could be cool, since we have them playable now with the cooperation with res republica, to get some cool harad republic. But that's just a minor suggestion)

</details>

So while i'm not to knowledgable on the modding part i would assume you would only need to look on how the mod _The Kingdom of Heaven: Third Crusade_ how done it, (And by no mean am i trying to make it sound that it's simple, i know a lot of work is put down into these stuff!).
I think my suggestion would work well with the artistic scope of the mod, with already fantastic bigger then hold models in the game such as Minas Thirith and Minas Morgul/Ithil. I hope at least some of my ideas have caused some inspiration!

**Comment by jj248** [comment]
We've been discussing this in #mapping - might be something we can explore.  I think right now though we focus on v2.2 release and push this to v3.0.  Moving.

**Comment by jj248** [comment]
Let's push this to v4.
