### ISSUE TITLE
Explore addition of dark servant lifestyle

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#250]
https://discord.com/channels/751097183448727552/857542930902417408/932978330964213761

**Comment by jj248** [comment]
Need permission to use the lifestyle artwork: https://www.artstation.com/artwork/aR5Klz

**Comment by jj248** [comment]
Pushing to v3.0

**Comment by jj248** [comment]
Pushing to v4.0

**Comment by Jaco-Daan** [comment]
Closing this with permission form Jamie, closest thing we'll _ever_ get to this is _maybe_ something to do with sorcery
