### ISSUE TITLE
Raid for Captives CB - more uses for prisoners

### ISSUE THREAD

**Issue by Remerod** [jj248/RealmsInExile#259]
I'm tired :P i saw this during today's mp and tested it out in the latest update of the mod, i think the CB is broken becouse of some religious tenant, might be wrong. it's still broken . (Edit: i might been a little sloppy with the details the war you declare is finished within a day as shown on the pictures, tried a couple of times, same results. it probably have to do with some religious tenet or how the cb is tied with something)
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150659116-75307f8d-76bd-45e5-9c03-334849fe9368.png)

![image](https://user-images.githubusercontent.com/79544635/150659133-00ba1a51-4c58-40f8-890e-7e131e46f23a.png)

![image](https://user-images.githubusercontent.com/79544635/150659139-10fc26cd-f43c-4228-bca3-1ac5ddf98e1e.png)

![image](https://user-images.githubusercontent.com/79544635/150659154-ea4a588a-4fbb-4a9f-b23d-498c513f899f.png)

</details>

**Comment by jj248** [comment]
This is due to a rather simplistic implementation of the Slave Raiding CB.  The Tenet enables the Flowery War CB but does not enable human sacrifice.  However, the Flowery War invalidates if neither side is into human sacrifice.

Also, all the CB's localisation points towards the war being for the purpose of sacrifice... 

This would suggest that we need a custom raid for captives CB.

**Comment by jj248** [comment]
Fix pushed.  @Remerod - ready to test.

**Comment by Remerod** [comment]
So great news, the CB seems to be working! although testing me out have left me a bit confused.  

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/151256183-226a694e-4104-4684-8007-bba2b5c6980e.png)

![image](https://user-images.githubusercontent.com/79544635/151256233-bb1c602b-58bd-4e48-9ab8-e4466abd4533.png)
So the rewards from this CB is mainly **Prisoners** and **Prestige** 

![image](https://user-images.githubusercontent.com/79544635/151256399-961b124c-e442-474b-bf33-659a40985818.png)
This tenet is telling me to go raid for **wealth**, **prestige** and **prisoners**.
But what is my main reason for prisoners? because executing them just give me dread, i guess i can ransom them for money though. 

![image](https://user-images.githubusercontent.com/79544635/151256665-fd7abb70-57f9-4d09-84ee-90ed1ab3d82a.png)
But i gain no Piety from this, and the Storm-host "Main" conquest route are threw holy wars, which you need piety from. And from what i can see the Storm-host have no obvious way to gain piety, which making calling holy wars very hard. So if the intend for the Storm-host to just  gain wealth and prestige but not expanding then this make's sense i guess. 

![image](https://user-images.githubusercontent.com/79544635/151257771-026ad3d7-8c06-4b7d-9782-ef81a674b48b.png)
But if their intent is to expand, then in my opinion they will be needing to have access to the **Conquest country & duchy** CB which cost prestige, which they would be able to accumulate with the **Raid for Captives** CB! To me giving them these CB makes the most sense when considering their expansion intentions with how the  **Raid for Captives** CB currently works. 

And on an Suggestion note, With the **Raid for Captives** CB, there is a chance you'll use this a lot, which will lead to you getting a lot of prisoners, should they have something special to do with prisoners other then the base mechanics? Maybe the religious Slave Raiding tenet would give you the option to sell them to slavery (for when the lord you captivated them from won't pay) which could give them a death modifier such as "sold into slavery". 
</details>

**Comment by jj248** [comment]
Bug is confirmed fixed from testing.  Rest is just suggestions for additional features so I'll push that to v3.0.
