### ISSUE TITLE
Units on the edge of provinces

### ISSUE THREAD

**Issue by Jermanlordy** [jj248/RealmsInExile#272]
Units in Simza and Whân-nevi appear on the edges of the provinces instead of around the holdings.

![image](https://user-images.githubusercontent.com/96250463/151715296-817d129c-7007-4f64-bdd4-b2545269721f.png)

**Comment by Jermanlordy** [comment]
units also are far away from holdings in Castle Holding of Arajran, County of Mârud,

**Comment by jj248** [comment]
These seem to have been fixed largely by someone, so thanks.  But more generally, it appears as if there's an issue with the unit's label when standing still being offset from the unit itself.  The label appears to prefer to be just to the right of the holding.

I wonder if this is a case of vanilla not expecting the unit to be anywhere but that position and so our more 'stylistically' placed unit locators are out of sync with that.

I'll make two commits.  The first to fix just Marud which is out of whack.  And the second being an experimental one using the auto-generated locators for unit stacks but will need tester feedback to make sure it hasn't thrown anything off massively.  If it does, I'll revert and we can push to v3.0 to consider as it could be a big job!

![image](https://user-images.githubusercontent.com/26043074/155721446-dff351d6-06f9-420b-80a1-bd51f79cdc42.png)
![image](https://user-images.githubusercontent.com/26043074/155721501-5a39e10c-b5a3-403e-852c-d8ab79ce9df2.png)
![image](https://user-images.githubusercontent.com/26043074/155721972-d1e0e001-7b1c-47f9-8cc3-222277ca80a8.png)

**Comment by jj248** [comment]
So experimented with the generated locators - they place the units right on top of the place in the centre of the province that it would place the holding.  In this case it's clear that the unit label is set just to the right of the new holding location (and so must be tied to it).

Pushing to v3.0 and not committing the generated file as this needs more thought.

**Comment by jj248** [comment]
Pushing to v4.
