### ISSUE TITLE
Concept: War of the Ring Gamerule

### ISSUE THREAD

**Issue by Remerod** [jj248/RealmsInExile#288]
There have been some players wishing for a game rule where the War of the Ring Narrative is turned off. While not maybe the most important feature i can see why people would want that, while myself really enjoy(and i mean "really") the story narrative, some players wish for a more sandbox game play. And to be fair, the feature was in our predecessor, ck2 middle earth mod. 

<details>
<summary>Click to expand</summary>

How CK2 Middle Earth mod did it: 
![image](https://user-images.githubusercontent.com/79544635/152472632-5fee52c5-0ae5-4dc7-b76b-86682c41a181.png)
event's on

![image](https://user-images.githubusercontent.com/79544635/152471908-5d9a9dd3-3079-4044-b04a-247548b367f1.png)
Event's off

</details>

So having all "story" driven event's tied to this would allow us to differentiate "normal" & "custom" events vs our "story" events. I don't know how hard it would be to make this rule, but i think i do get that if it is something we would want one day it would be easier to implement earlier then later no?

**Comment by Jaco-Daan** [comment]
So since we've started adding this to all the story driven events, I'm closing this, can be opened in the future for whatever reason. closing
