### ISSUE TITLE
Eastern Rohan Rework

### ISSUE THREAD

**Issue by Foadar** [jj248/RealmsInExile#292]
Although this has already been somewhat discussed, I think it wise to formalize this into an issue.

For 3.0, after the areas closest to Rohan are in, the upper reachers of the Anduin around Rohan should be reviewed.

Things that spring out :

-Tol Brandir

-Field of Celebrant.

-Argonath in a single county ? 

-Ability to form old Gondorian borders.

Feel free to note further things.

**Comment by JukeJukestar** [comment]
- Leofrings now have clan histories, are no longer placeholders
- Northeastern Rohan is still independent - I think its in a good state so Rohan has to work a bit to reclaim its full borders
- Dejure setup seems to be in a good state now, with the duchies and kingdoms making sense
- There is an ability to restore the old gondorian borders in rohan

Some things that can still be considered:
- There is still very little dynasty history in rohan itself, Eoforings dont have any titles historically
- Argonath hasnt really been considered, no real way to remake it with no barony directly next to it

**Comment by JukeJukestar** [comment]
As we step towards release, I am closing this issue for now - in my humble opinion the dejure setup, dynasties etc are in a decent state.
An Argonath overhaul would be an interesting idea for the future, but for now we are mostly done with connecting Rohan with Rhovanion.
