### ISSUE TITLE
Concept: Black Numenorean Culture Traditions

### ISSUE THREAD

**Issue by Remerod** [jj248/RealmsInExile#294]
I was thinking of some cool idea tradition/s for the Black numenoreans so i thought i'd share them (it ended up as 3). I added some picture i took inspiration from around my suggestion, you can find them here [Traditions](https://ck3.paradoxwikis.com/Traditions)

# Black Numenorean Tradition
So i was thinking on how some Traditions for the Black Numenoreans and similar could work. This traditions should be for those who still claim The Black Númenóreans were the descendants of the king's men among the numenoreans, who are not counted among the Elendili. 

I ended up adding a lot, but there are some vanilla traditions that have a lot to, like **Tribal Unity** or **Byzantine Traditions** but made sure some negative effects made it in.

**Black Numenoreans**
The Black Númenóreans, initially named the King's Men, were a fallen group of Númenóreans descended from those who were loyal to the Númenórean Sceptre but in opposition to the Valar and relations with the Elves. Cruel oppressors and overlords over the more primitive Middle Men of Middle-earth. As the Numenoreans of old were colonizing the continent, they survived the Downfall of Númenor. 

* Characters are more likely to marry characters with the _Black Numenorean_ tradition, _Numenoreans in Exile_ tradition &/or the **Remnant Numenorean Blood**, **Strong Numenorean Blood**, **Pure Numenorean Blood** & **Numenorean** traits. 

 −50 Marriage Acceptance towards character with none of the _Black Numenorean_ tradition, _Numenoreans in Exile_ tradition &/or the **Remnant Numenorean Blood**, **Strong Numenorean Blood**, **Pure Numenorean Blood** & **Numenorean** traits. 
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/153729123-d7ea7057-536e-4723-90ce-e7cdfdaffa5f.png)

</details>

* Can Raid and Raid Overseas

* +25%Army loot capacity
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/153727385-65739f7c-2143-4858-bd56-1b25d99baff6.png)

</details>

* −15 Elendili Faiths Opinion (if this is possible?) 

* +50% Short Reign Duration (this is negative)

*−35% Cultural Acceptance Gain (this is negative)

* Can enact the Primogeniture law
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/153727692-03ef31ef-8fb2-49a6-aea0-dde01dba6835.png)

</details>

# Numenor blood tradition 

So there is a lot of culture's that use and have Views on Numenorean Blood, so i thought it was good to make a traditions that was as neutral as possible, So people like Umbarias, Gondorians, Arnornians and other could have more custom made ones for them. 
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/153726860-9e7a266c-b4f6-4d1c-b1b2-e1e1ab2da3e6.png)

</details>

**Numenoreans in Exile** 
The Númenóreans "Adûnai", "Westmen" were the men of Númenor, those descendants of the three houses of the Edain who had settled the Island Realm of Númenor in the Second Age. The Land of the Star gifted it's people with prolonged life, and while the land itself have sunken and are now Atalantë, (meaning "the Downfallen") It's blessed blood still linger in the heirs that survived in the different colonies the former island realm formed throughout Arda, gifting these decedents with longer life and greater prowess. 

* Positive attitude towards character with the **Remnant Numenorean Blood**, **Strong Numenorean Blood**, **Pure Numenorean Blood** & **Numenorean** traits. 

* +0.5 Monthly Prestige for **Remnant Numenorean Blood**, **Strong Numenorean Blood**, **Pure Numenorean Blood** & **Numenorean** traits.

* The **Remnant Numenorean Blood** trait is more common

* +1% Chance to be born with the **Remnant Numenorean Blood**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/153727038-a4c6027f-5d31-4b6a-bed8-f50e8aa019d6.png)

</details>

# Dark Servant
I though that we could give the Ulairi/Nazgul a tradition that would sometime gift them with cool guests/servants, i thought there was a thing that could add stuff easily but it appeared that was just making the "Wandering Mystic events are more likely" so well, i continue writing it but i understand it this one is a bit complicated to just throw in. 

**Dark Servant**
"Competent people like Syâr-Rhul the black vizar & the mouth of Sauron are drawn to serve **The Shadow**" (could not come up with a good text for the tradition

* +2 Number of Knights

* +3 Learning for _Renown Sorcerer_ characters

* +1 Prowess per Level of Devotion

* a "Wandering Mystic events are more likely" but make one that gives you a wandering character with either Black Numenorean Tradition, or the _Renown Sorcerer_ trait. That are all either of the **Forces of Evil** or Adûniac Faiths. (possible also make it so they get cool Uruk character also) 
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/153728267-04e87c07-c89d-4738-ab67-c0f55288861e.png)

</details>

# Please share if it's bad or good ;)

**Comment by Foadar** [comment]
Me and Vector have talked about specific cultural traditions. Something to that degree will be worked on sooner rather than later. I also intend to merge some of the traditions that are present in the base game into these Numenorean traditions, to force ''good'' traits more often as say, Gondorians. Same for other cultures.

**Comment by JukeJukestar** [comment]
This seems like a good idea, although Id like two add 2 things:

1. Black Numeonrean Tradition: The Piracy stuff shouldnt be included in the tradition as they can just have the pirate tradition. This way they wont have too few tradition (or too many culture effects) and a divergent/ hybrid culture further inland can choose to no longer value piracy.

2. Negative Elendili Faith opinion doesnt belong in there since they could be elendili religious, in which case they would dislike eachother.


In general I am afraid that merging traditions into special ones too often can lead to certain cultures stacking a huge amount of modifiers and traditions

**Comment by Remerod** [comment]
1. sure

> 2. Negative Elendili Faith opinion doesnt belong in there since they could be elendili religious, in which case they would dislike eachother.

It's based on the `−15 Different Faith Opinion` modifier, and meant to discouraged becoming elendili and encourage conflict between the two, but maybe there could be a modifier "unless elendili faith yourself" but in my opinion you should be able to be black numenorean and elendili at the same time, or at least heavily discouraged to

**Comment by Remerod** [comment]
> In general I am afraid that merging traditions into special ones too often can lead to certain cultures stacking a huge amount of modifiers and traditions

this is true, but it's also true that cultures shouldn't be balanced equally, a lot cultures in vanilla are better then other ones, that's part of the easy vs head gameplay balance

**Comment by RedArkady** [comment]
Small comment, but just to agree that we shouldn't be attaching religious opinion modifiers to cultures. It's a totally legitimate player path for Black Numenoreans to convert to Eruist faiths, and they shouldn't be left in a situation where they dislike other people of Eruist faith if they make that conversion.

**Comment by jj248** [comment]
Ditto - sending to testing to confirm if this is all done as the suggestion largely came from testers.  I suggest if we're missing anything that we split it out and create new more discrete issues.

**Comment by Remerod** [comment]
> Ditto - sending to testing to confirm if this is all done as the suggestion largely came from testers. I suggest if we're missing anything that we split it out and create new more discrete issues.


I believe only the **Black Numenorean Tradition**, i'll review the other 2 and see if i'll make them issues or not soon (hopefully before this weekend

if anything else the **Black Numenorean Tradition** have already made it into the public release

**Comment by jj248** [comment]
If there's anything else to do on this, please can you assign it to v4 as I'm loathe to add more work to the docket for v3 when we're trying to narrow it down.

Just close this issue when all considerations done.  Thanks! <3

**Comment by Remerod** [comment]
well i only done 1 of 3 (but maybe 2) but i'll move it to 4

**Comment by savagesach** [comment]
what am I exactly supposed to test here, the black numenorean tradition is already in the public release and there's nothing to test for the other 2 traditions. I recommend this be moved either to the in progress or non release critical category

**Comment by jj248** [comment]
Looks like this should have been moved to v4.  Thanks Nem.

**Comment by Jaco-Daan** [comment]
Since this had already been added, closing
