### ISSUE TITLE
Suggestion: Better character background artwork for the forces of evil

### ISSUE THREAD

**Issue by Remerod** [jj248/RealmsInExile#295]
So currently in game we've have these character background for the forces of Evil characters.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/153733476-0295645e-62d7-441a-9d69-9f3bf128ed20.png)

![image](https://user-images.githubusercontent.com/79544635/153733482-e48e7e8f-19eb-42ed-a010-a9612cabcfa1.png)

![image](https://user-images.githubusercontent.com/79544635/153733483-7a8bbc58-554e-4d8d-b519-11b7006959b6.png)

</details>

And with the recent Gondorian throne room i was thinking surely we could do better? 
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/153735915-fc6fee27-3498-468e-9c0c-990542ad94e4.png)
Gondor throne room (am i correct in assuming that this is a pic taken from our custom made gondorian court room?)

</details>

I think it would do a lot for the mod if we could get some background art like these into the game
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/153734631-190a8928-13eb-47de-8b3d-e1cc2b75fd13.png)
tried to find this art piece without the ui, kinda impossible but it's from **Lord of the Ring: Rise of War** so we can't probably use it anyway. But it would work very well for the Isengard background if we find something similar! 

![image](https://user-images.githubusercontent.com/79544635/153734855-4c044cf0-a18d-41bc-af0c-f90f28b86e9e.png)
Just as above this is also from **Lord of the Ring: Rise of War** so while maybe not usable it still as a very good aesthetic of how a good mordor-ish throne room could look like, and if we find something similar it would be great in my opinion. 

![image](https://user-images.githubusercontent.com/79544635/153735559-27532d0f-597a-4dab-a88b-dd9db3e3c70a.png)
have yet to play the game but apparently there are some cool throne rooms in Middle-Earth:Shadow of War

</details>

So while i did not give any concrete art to work with, it would add a lot in my opinion for the forces of evil if they got some spooky artwork backgrounds to the their characters. And while this maybe might have always been the case, i just felt it was worth to write about if it was not on anyone's mind.

**Comment by Remerod** [comment]
maybe if we got a clean one of the Lord of the Ring: Rise of War they could be reshuffled in like artbreeder or something similar?

**Comment by jj248** [comment]
This is done.  Closing.
