### ISSUE TITLE
Equipping artifacts is reflected in portraits

### ISSUE THREAD

**Issue by RedArkady** [jj248/RealmsInExile#298]
Explore linking clothing models such as headgear to artifact models - can this be done? We already have models e.g. the crown of Gondor that ideally we would use for both.

**Comment by jj248** [comment]
Totally possible.  Just need to decide what assets you want to do it for and whether you want to replace existing way they're shown to make them truly unique or in addition.

You'd use the any_equipped_character_artifact in a portrait modifier to implement.

Maybe one to hash out the details for in a Discord discussion thread @RedArkady ?

**Comment by jj248** [comment]
Let's leave this to v4.  It's not hugely essential.
