### ISSUE TITLE
Sugestion: Female Haradric Ruler 

### ISSUE THREAD

**Issue by Remerod** [jj248/RealmsInExile#301]
**Reason**
So i really like our Current setup of Near Harad! and don't neccicerly want it to change. Having said that, I've recently looked a bit into the game the Lord of the Ring: Rise to War and one of the commanders in that game is a female Haradrim. And for the sake of diversion I think adding a female ruler when there is a ..."licensed game" (or is it? Tt's made by warner bro's at least who have the license to make lotr games... omg why am i making this suggestion, the game don't even have a _wikipedia_ page! xD ) is a good addition to an area where there no hard canon lore establishment. 
 
**Yusraa**
Yusraa is the leader of one of the Haradrim tribes of the southern lands of Near Harad. In this part of Middle-earth, martial prowess is revered above all. On account of Yusraa - many killed enemies and defeated competitors. Truly, the path to the pinnacle of power in the Haradrim army is not easy. 
Source: https://wisegeek.ru/aaf/the-lord-of-the-rings-war
<details>
<summary>Click to expand</summary>

![Yusraa Warlord in southern haradrim 3](https://user-images.githubusercontent.com/79544635/154801638-2d9d3323-a4f8-4e1b-887e-9044f2b70f35.jpg)

![Yusraa Warlord from souther near harad  lotr ROW 2](https://user-images.githubusercontent.com/79544635/154801645-03a1b161-fc65-4874-9a45-0ced47e73ef3.jpg)

![Yusraa Warlord from souther near harad  lotr ROW 1](https://user-images.githubusercontent.com/79544635/154801647-f0cb2486-1076-4804-9a35-872f50cda7b5.jpg)

</details>

**Suggestion of placement**
So where to put her then, the LOTR:RTW says that she is from "southern" Near Harad, so does that mean in Near Harad or bellow it, because we do not know if their lore acknowledge "Far Harad". And they don't give much lore placement as the games commanders can be/rule anywhere in the "evil" factions. But for the sake of being Near Harad, then i have 3 possible location where it would fit in and her being a Khäz-gramaze faithful.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/154802371-463c43da-c762-4d7e-ab3d-ef84685bd87f.png)

</details>

_Tafas_
Maybe the worst of my 3 suggestions, they start in a war in aid of Pezarsan at game start.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/154801881-53ac204f-e72e-404c-a86b-e40faffe0bfb.png)

</details>

_Peka_
So i might be wrong, but to my knowledge this is a very minor character? it could be a good place to just, well place her.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/154801909-94312c5e-b601-4cef-a975-b92791ff671b.png)

</details>

_Zakakha_
So placing Yusraa is Zakakha is probably the best one of my suggestions (But the one i like the least because i really like my giant Chieftain Uregh there! xD ). This area is pretty large, with expansion opportunities both west, east and a possible harder north. And would serve her LOTR:RTW lore of Being a Warlord as a tribal. So i unfortunately would place her here. 
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/154801947-8d80a593-a67a-48b9-b9ca-44f4f8af399c.png)

</details>

So again, I am mostly making this Suggestion because i think adding more female rulers is a good thing, even if the male dominated haradrim fits thematically. But giving the option as playing as a female ruler would ad to the diversion of Characters in the area of the Mod. which i generally thinks a very good thing.

**Comment by VectorMaximus** [comment]
I am not particularly opposed to the thought by any stretch - as you said, most of those aforementioned lords are just dummies (or at least have no particular backstory), so yeah, a particularly conniving Haradrim lady rising to power isn't outside the bounds of possibility.

**Comment by JukeJukestar** [comment]
Put her as the 5 y/o daughter of the giant warlord in Pezarsan
