### ISSUE TITLE
1.5.1 compatch. Ruler animation get stuck.

### ISSUE THREAD

**Issue by Remerod** [jj248/RealmsInExile#334]
So launched the game, and went away for an hour before fiddling around. Then i noticed that some of the rulers get static in their character/ruler uni view. I manage to notice one that was doing it's animation but got stuck in the animation loop. the spouses don't seem to have this problem. Moving around till you find a ruler that is not stuck un-stucks the other rulers till they get stuck in their animation again. (I've also restarted the game to make sure it was not just me leaving the game unpaused for an hour that messed with my comp). 

![image](https://user-images.githubusercontent.com/79544635/157781120-ac558d37-5b8e-4340-870b-e8774d7832f7.png)

**Comment by jj248** [comment]
PDOX issue - should now be resolved.  Testing to confirm.

**Comment by JukeJukestar** [comment]
Havent been able to replicate this. Should we close?
