### ISSUE TITLE
Dúnedain of Evendim 5.0

### ISSUE THREAD

**Issue by Jermanlordy** [jj248/RealmsInExile#338]
So when chatting in lore i saw that Arvedui could have had multiple sons so, Perhaps in Evedim the Dúnedaín there could be led by a descendant of one of the other sons of Arvedui as like a cadet branch like with the Halamirionaths.
(if so can i make the DNAs :D)

**Comment by VectorMaximus** [comment]
Basically what Red has suggested before, and I'm in support of it, myself. Allows for a Dunedainic restoration that isn't Aragorn in the cards.

**Comment by Jermanlordy** [comment]
yea thats what came to mind when talking about there being possibly more sons and more then just Aragorn and Halbarad and Elegost as choices for a northern restoration would be dope

**Comment by jj248** [comment]
This doesn't need to be an issue on github.  Closing.
