### ISSUE TITLE
Concept: Rise to Mordor/The Dawnless Days Assets

### ISSUE THREAD

**Issue by Remerod** [jj248/RealmsInExile#339]
So I was recently given a key to Attila, By Caesar. And he requested some help to pick which assets would be best to add into our mod. So I've made this suggestion list in hope of helping with that.

## Dale
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/158315788-0004b83d-602b-404b-abd5-03b3ce109d9c.png)
Unit: Dalian Swordsmen

![image](https://user-images.githubusercontent.com/79544635/158315843-66ae85c1-d90c-4cd9-89cc-2d0f9f5d24dd.png)
Unit: Laketown Guards.

Conclusion: I dunno which one of these are best, the **Laketown Guards** certainly are more recognizable from the hobbit movies, but the **Dalian Swordsmen** look very nice and look more "knightly". Either way both units have kind of a captain unit in them, which could work as for the higher rulers to use. 
</details>

## Rhovanion and Dorwinion
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/158315031-bc54c6a0-4467-490a-8ca9-5a56c76a300a.png)
Unit: Rhovanion Regents. I feel like these would make a decent asset for the "normal" cultures around rhovanions, like the leofrings, woodmen & Éowealafa. while there are the assets of these, the bronze, iron and golden, i feel bronze and iron ones works best, maybe an empire could get the golden one.

![image](https://user-images.githubusercontent.com/79544635/158315409-2fcb7fd2-3b51-4b45-a6a0-2131f634ae20.png)
Unit: Vineland Guards. I feel these would work well for Dorwinion, they have like a mixture of easterlings, gondorian, dwarven and dale like theme, which i think fits them. 

</details>

## Woodland Realms
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/158316408-c639a506-9e40-4fb7-98d3-f2956b931aa3.png)
Unit: Elvenking's Riders. here we have Thranduil (which we kind of already looked at). but i think the other riders would be a good candidate for princes and rulers armours?

![image](https://user-images.githubusercontent.com/79544635/158316573-3d854409-efdc-40d7-aacf-2fd27317ecf2.png)
Unit: Lasgalen Blades. Here we see the more silver looking armour again, just as  Elvenking's Riders leading the other. But i do think these golden/bronze ones look very good, and is thematically looking like the standard the hobbit: battle of the five armies ones. so i think they make for a good standard armour for the lasgalen/woodland realm elves!

</details>

## Gondor
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/158315558-167449c7-011d-4f3c-a54e-7ede1deecb91.png)
Unit: Gondor Cavalry. Gondor have the most head assets i think, but they still lack a body armour kind of thing. I think these units armour would make a nice Gondorian knight!

</details>

## Easterlings
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/158317150-6aa7eab1-bcf1-4211-b57c-77d1602624d6.png)
Unit: Clan Guards. I do think these guys would make the Best "Standard" armour for Rhûn!

![image](https://user-images.githubusercontent.com/79544635/158317304-81566dda-4856-4ef7-9283-84aa5a2d5e57.png)
Unit: Lókë-Rim Macemen. There is also these guys! 

![image](https://user-images.githubusercontent.com/79544635/158317382-753ec25d-ada6-4379-b8b1-92fd33864551.png)
Unit: Warlords of Rhûn. So these are the more.. Leading elite units. I'm not the biggest fan of them being the elite. But i do like the helm, and if that can been made golden like the rest, i think the helm could be a very good Ruler kind of helm alongside with some of the other armours. 

Conclusion: I think the standarm armour should be either **Clan Guards** or **Lókë-Rim Macemen**, with maybe and golden version of the helm the **Warlords of Rhûn** use, but that would require some extra work i assume, so maybe not?

![image](https://user-images.githubusercontent.com/79544635/158316850-bab98a7d-2ec9-4de2-9896-7c433fb55a7a.png)
Unit. Rhûnic Savages. I think these armours would be really nice for the tribes in Rhûn!

![image](https://user-images.githubusercontent.com/79544635/158317806-362b0223-b968-4388-9067-cdf08ea654bf.png)
Unit: Khamûl (Black Easterling Retinue). Khamûl the Easterlings armour! would be nice to have. The other dudes is pretty dope to, but i dunno where they would fit, maybe for Dol Guldurs evil men?

</details>

## Haradrim
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/158318039-34cc3b37-918d-4056-92b9-2a87d320e0b7.png)
Unit: Serpent Spearmen. These dudes look great, and would make for a good knight type of thing.

![image](https://user-images.githubusercontent.com/79544635/158318291-b2dabeaf-3782-40a7-befc-63ea30e35ea7.png)
Unit: Camel Riders. These does also look amazing, especially the 2 I've marked with green, they would also make amazing knights!

![image](https://user-images.githubusercontent.com/79544635/158318409-3ea569ce-0b2a-4ec3-918c-cb5b02c50756.png)
Unit: Serpent Guards. So I think these armours would make amazing ruler armours, Sulâdan have been described in differant sorces to be hiding his face with such a mask, so i think for at least the Khäz-gramaze (the sauron align faith of harradrim) would look amazing with these. 

Conclusion: Either of the **Serpent Spearmen** & the **Camel Riders** unit armours would make good haradrim armours! but the Serpent Guards ones would make good ruler ones!  

</details>

## Umbar
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/158318789-6150dee8-3cce-4e46-8f0e-2a7804bffb14.png)
Unit: Adûnakhôri. these would make as amazing Umbar knight armours!!!! Amazing i tell you!!! Very Castamiri influenced.

![image](https://user-images.githubusercontent.com/79544635/158318878-12037d9e-8aa2-477a-929d-6be4102de69d.png)
Unit: Umbar Usurpers. these could be good low tier ones, but not as important.

![image](https://user-images.githubusercontent.com/79544635/158318986-f708f9a1-67b4-41d8-a28b-f506b72b3a88.png)
Unit: Corsairs Marines. These would be a good look for the "corsairs of Umbar, we could give the Mardrûak cultures this look.

</details>

**Comment by Remerod** [comment]
I'm currently working on https://github.com/MattTheLegoman/RealmsInExile/issues/347 that is tied to this issue!

**Comment by Remerod** [comment]
I am in planing on making a wiki on the subject about getting armour into the game, but i have yet to finesse the process myself yet.  But basically you need to follow the steps on this wiki page i wrote, [Getting Assets into the Mod](https://github.com/MattTheLegoman/RealmsInExile/wiki/Getting-Assets-Into-the-Mod). the important part is to do the 3.1 step as otherwise you won't be able to save the mesh (but i guess you can save it as a .blend file till that moment). But i be of course happy to aid a hand in VC on the "server" if people wanna learn how to do this!

**Comment by Jaco-Daan** [comment]
We don't really have a 3D artist that can look at this, and according to Owl it's really more work than its worth, since the models aren't that detailed, closing for now
