### ISSUE TITLE
Concept: Main Easterling Religion

### ISSUE THREAD

**Issue by Remerod** [jj248/RealmsInExile#351]
### Background
So I was thinking of what kind of religion the easterling's would follow, there is a lot of themes, of Sauron, dragons, plains and sorcerers and  minor cults all over, so i was thinking of how to incorporate those into one thing. 

### Base Information
Information on different easterling faiths I've based my suggestion on.
<details>
<summary>Click to expand</summary>

[Kerkassk](https://notionclubarchives.fandom.com/wiki/Kerkassk), also known as The Plains-God, was a mythical being that was worshipped as a deity by several [Easterling](https://notionclubarchives.fandom.com/wiki/Easterling) Tribes.Kerkassk was later revealed to be a secret identity of [Sauron](https://notionclubarchives.fandom.com/wiki/Sauron) invented by him to bind the Easterlings to his service.The Role of the Kerkassk had also been occupied by the [Ringwight](https://notionclubarchives.fandom.com/wiki/Ringwight) [Oraishapek](https://notionclubarchives.fandom.com/wiki/Oraishapek) for several times. 

Utumkôdur the Dragon-goddess, also known as Utumkôdur the Golden, was one of the greatest Dragons to survive the First Age, akin to Ancalagon. She had left Angband even ere the War of Wrath had begun, charged with scouting and terrorizing the Far East. Upon the defeat of Morgoth, she was bereft of purpose, and wandered the far east, eventually settling in the peaks of the Orocarni. Utumkôdur could perhaps be named the wisest of the Dragons, or at least less ireful and more pragmatic in her greed and cunning. She descended from the mountains and taught Men much of Iron, and they revered her and offered her tribute, and the Dragon-Lords and people of Wômawas Drûs ever after revered her name. The Wômaw claim that she grew to love them fiercly as her own children, though those of the West who know of Dragons look upon this with skeptisim. Whatever the truth, her aid and guidance is no myth, and the people of Wômawas Drûs grew mighty and proud under her tutelage. However, even a Dragon is not forever, and Utumkôdur was slain in a great clash with the Eagles of the East, with whom she had long quarreled over the peaks of the Orocarni. Since that day, the Wômaw have ever held that the Eagles are an ill omen, and revere even now the memory of their beloved Dragon-mother. 

[Kor-Sharhaigûn](https://notionclubarchives.fandom.com/wiki/K%C3%B4r-Sharhaig%C3%BBn) was an [Easterling](https://notionclubarchives.fandom.com/wiki/Easterling)-[God](https://notionclubarchives.fandom.com/wiki/God) revered by the [Asdriags](https://notionclubarchives.fandom.com/wiki/Asdriags).He was believed to be their name for [Morgoth](https://notionclubarchives.fandom.com/wiki/Morgoth). 

[Hûr-Iriga](https://notionclubarchives.fandom.com/wiki/H%C3%BBr-Iriga) was the [god](https://notionclubarchives.fandom.com/wiki/God) of light or day in [Asdriag](https://notionclubarchives.fandom.com/wiki/Asdriag) [religion](https://notionclubarchives.fandom.com/wiki/Religion).He was opposed to [Kôr-Sharhaigûn](https://notionclubarchives.fandom.com/wiki/K%C3%B4r-Sharhaig%C3%BBn) the Lord of the Night. 

The [Akshum-oymalv](https://notionclubarchives.fandom.com/wiki/Akshum-oymalv) or Night-warders were [sorcerer](https://notionclubarchives.fandom.com/wiki/Sorcerer)-[priests](https://notionclubarchives.fandom.com/wiki/Priests) who first appeared in [Second Age](https://notionclubarchives.fandom.com/wiki/Second_Age) [Rhûn](https://notionclubarchives.fandom.com/wiki/Rh%C3%BBn) among the [Shrel](https://notionclubarchives.fandom.com/wiki/Shrel)-[Easterlings](https://notionclubarchives.fandom.com/wiki/Easterlings) who served the [Dark Lord](https://notionclubarchives.fandom.com/wiki/Dark_Lord) [Sauron](https://notionclubarchives.fandom.com/wiki/Sauron). With the end of the [Third Age](https://notionclubarchives.fandom.com/wiki/Third_Age) the Night-warder's legacy survived among the [Logath](https://notionclubarchives.fandom.com/wiki/Logath) tribe. 

[Cult of the Long Night](https://notionclubarchives.fandom.com/wiki/Cult_of_the_Long_Night) 
Tucked away at the Western end of the [Emyn Engrin](https://notionclubarchives.fandom.com/wiki/Emyn_Engrin) (S."Iron Hills") lived a secretive society of [seers](https://notionclubarchives.fandom.com/wiki/Seer) and [mystics](https://notionclubarchives.fandom.com/wiki/Mystic) dedicated to the Cult of the Long Night (BS."Fai-Barzguyat").  They called their principal home [Nahald Kudan](https://notionclubarchives.fandom.com/wiki/Nahald_Kudan) (E."Secret Holes").  They had other enclaves or redoubts in population and trading centers throughout the region.  Overtly they lived in a cluster of shale-over-wooden-frame conical homes and offered comfort to travelers in this part of the world.  They would identify themselves as the Hermits of Nan Morsereg.  They were identified by white woolen shifts.  Should someone actually don their garb, the feel of human hair against their skin would be disconcerting, if not horrifying.  The hermits asked probing questions about travel conditions and items of interest.  Burly servitors would offer food, a warm fire, and homebrew to any who stayed with them.  Should a weary traveler accept, they would find the hospitality loosen their tongue and guarded information spilled out unbidden.  The Cult's members were typically very subtle with strangers until they could extract knowledge of their allegiance and motives.  Covertly they sought to gain adherents and contacts throughout the regions surrounding [Mirkwood](https://notionclubarchives.fandom.com/wiki/Mirkwood).  This strategic location permitted them to interact with the [Asharag](https://notionclubarchives.fandom.com/wiki/Asharag) [Orcs](https://notionclubarchives.fandom.com/wiki/Orcs), caravans and wains of [slaves](https://notionclubarchives.fandom.com/wiki/Slave) and [soldiers](https://notionclubarchives.fandom.com/wiki/Soldier) headed to [Angmar](https://notionclubarchives.fandom.com/wiki/Angmar) from tributary [Easterling](https://notionclubarchives.fandom.com/wiki/Easterling) tribes near the [Sea of Rhûn](https://notionclubarchives.fandom.com/wiki/Sea_of_Rh%C3%BBn).  They had contacts throughout the Northern portions of Mirkwood incuding [Dale](https://notionclubarchives.fandom.com/wiki/Dale), [Long Lake](https://notionclubarchives.fandom.com/wiki/Long_Lake), [Methelburg](https://notionclubarchives.fandom.com/wiki/Methelburg), [Framsburg](https://notionclubarchives.fandom.com/wiki/Framsburg) and into Angmar proper.  The key [leaders](https://notionclubarchives.fandom.com/wiki/Leader) received regular communiques from [Dol Guldur](https://notionclubarchives.fandom.com/wiki/Dol_Guldur).  They worshiped [spirits](https://notionclubarchives.fandom.com/wiki/Spirits) of the dark and only the inner circle knew the actual name of the deity whereby they derived their powers, [Sauron](https://notionclubarchives.fandom.com/wiki/Sauron).  They studied the darkness surrounding the [stars](https://notionclubarchives.fandom.com/wiki/Stars) and the dark of the [moon](https://notionclubarchives.fandom.com/wiki/Moon).  

The inner circle of this group called themselves the Zunghúri (BS."Piercing Lords").  They were exceedingly skilled in their respective fields and not to be taken lightly.  They were fond of [drugging](https://notionclubarchives.fandom.com/wiki/Drug), torture, and subsequent sacrifice of anyone deemed an opponent and taken in by their guise as [healers](https://notionclubarchives.fandom.com/wiki/Healer) and [hermits](https://notionclubarchives.fandom.com/wiki/Hermit). 

[Fist of Dark Sorcery](https://notionclubarchives.fandom.com/wiki/Fist_of_Dark_Sorcery)
The Fist of Dark Sorcery ([Ul.](https://notionclubarchives.fandom.com/wiki/Ulgathig):"Ramanin") was a [Sauronite](https://notionclubarchives.fandom.com/wiki/Sauronite) [cult](https://notionclubarchives.fandom.com/wiki/Cult) active in [Rhûn](https://notionclubarchives.fandom.com/wiki/Rh%C3%BBn) in the 17th century TA. It openly acted to bring [Sauron](https://notionclubarchives.fandom.com/wiki/Sauron)'s will into [Middle-earth](https://notionclubarchives.fandom.com/wiki/Middle-earth). Though it operated well out of reach of western factions such as the [Gondorians](https://notionclubarchives.fandom.com/wiki/Gondor) or the [White Council](https://notionclubarchives.fandom.com/wiki/White_Council), the fist was very well connected with other [dark cults](https://notionclubarchives.fandom.com/wiki/Dark_cults) which operated more under cover such as the [Witches of Angmar](https://notionclubarchives.fandom.com/wiki/Witches_of_Angmar) or the [Guldur Sorcerers](https://notionclubarchives.fandom.com/wiki/Guldur_Sorcerers). Most of the fists Members were [Easterlings](https://notionclubarchives.fandom.com/wiki/Easterlings), among them many [Asdriags](https://notionclubarchives.fandom.com/wiki/Asdriags). The Fist later was able to indoctrinate the [Sarshen Meltek](https://notionclubarchives.fandom.com/wiki/Sarshen_Meltek), which brought the [Balchoth](https://notionclubarchives.fandom.com/wiki/Balchoth) under the shadow of [Dol Guldur](https://notionclubarchives.fandom.com/wiki/Dol_Guldur). 

[Guldur [Sorcerers](https://notionclubarchives.fandom.com/wiki/Guldur_Sorcerers) 
The Sorcerer Caste of [Dol Guldur](https://notionclubarchives.fandom.com/wiki/Dol_Guldur) recruited their Acolytes from many different peoples: [Easterlings](https://notionclubarchives.fandom.com/wiki/Easterlings), [Northrons](https://notionclubarchives.fandom.com/wiki/Northrons), [Dorwinrim](https://notionclubarchives.fandom.com/wiki/Dorwinrim), and even the occasional [Black Númenóreans](https://notionclubarchives.fandom.com/wiki/Black_N%C3%BAmen%C3%B3reans). They called themselves Kîshothî (B.S."Advocates") or Laugashî (B.S."Sorcerers") and acted as the ambassadors, [priests](https://notionclubarchives.fandom.com/wiki/Priest) and henchmen of the [Necromancer](https://notionclubarchives.fandom.com/wiki/Necromancer) or his puppet-ruler (usually one of the [Nazgûl](https://notionclubarchives.fandom.com/wiki/Nazg%C3%BBl), [Khamûl](https://notionclubarchives.fandom.com/wiki/Kham%C3%BBl) the Shadow of the East). Some of the mightier Guldur Sorcerers were "rewarded" with "immortality" and had become [Ringwights](https://notionclubarchives.fandom.com/wiki/Ringwights). 

[Sarshen Meltek](https://notionclubarchives.fandom.com/wiki/Sarshen_Meltek)
The Sarshen Meltek (Ior. "Crimson Order") were a religious [order](https://notionclubarchives.fandom.com/wiki/Order) among the [Balchoth](https://notionclubarchives.fandom.com/wiki/Balchoth). In their origin they had been a group of tribal [priests](https://notionclubarchives.fandom.com/wiki/Priests) and [prophets](https://notionclubarchives.fandom.com/wiki/Prophet) who had come under the influence of the [Fist of Dark Sorcery](https://notionclubarchives.fandom.com/wiki/Fist_of_Dark_Sorcery). Led by the Sarshen Meltek, the Balchoth fully fell under the Shadow of [Dol Guldur](https://notionclubarchives.fandom.com/wiki/Dol_Guldur) and it's [sorcerer](https://notionclubarchives.fandom.com/wiki/Sorcerer)-priesthood.

</details>

### My Suggestion
So i wanted to incorporate certain elements into the religion
 Base elements Sketch for a Easterling religion; 

- Kor-Sharhaigûn & Hûr-Iriga. Creates the world, stuff get down, and both are no longer around.

- Dragons. In the age of myth/past the Dragon roamed the plains as it's migtiest rulers (as Kor-Sharhaigûn's mightiest creature) some whom impassed wisdom/strength on worthy champions. (maybe some dragon skeletons here and there?)

- Priest & prophets. Long history of cults in the region, a branch of Sarshen Meltek still lingers on in this faith.

- Kerkassk (Sauron) the plain god. Successor of  Kor-Sharhaigûn & Hûr-Iriga. The “tengri”/overlord god/spirit of the steppes.

So here is some base skeleton text for what their religion could be about and how it incorporates into a Sauronic flair without being outright cult of the lidless eye.
**Description sketch:** 
_In the Beginning Kor-Sharhaigûn, lord of night & Hûr-Iriga, lord of day did stuff and created a Glorius World, but other lesser gods/spirits (valar) and their armies (of elves) destroyed the balance, stole shards of light from Hûr-Iriga and vanquished the great  Kor-Sharhaigûn. Beings aligned to Kor-Sharhaigûn/the night like the Dragons(Lôke) still roamed the lands and held the (elves & other Valar aligned) begins at bay & would occasional grant favors for the worthy champions. Most of the beings of Darkness was scattered till the time that Kor-Sharhaigûn mightiest follower returned as his successor, Kerkassk.  Kerkassk as both Kor-Sharhaigûn & Hûr-Iriga true heir, takes dominion of both light and dark, where he lords over all “plains” above in dark clouds in the sky engulfed in the light of creation, forming (a draconic eye?). While he would command begins of darkness in his war against the userpers of light he will lord over humanity, begins of both light and dark and At times he would bestove visions/prophesies to his red clad  prophets/priests/sorcerors ”Laugashî” (not necessary real ones) to bring back the order of old and fight against the (valar) & their servants, till the time where he can call fourth the long night, where he and the faithful will finally defeat & banish the usurpers of light and usher in a paradise of Perfection upon the world._  

This still need's rewriting, but it's a start on something

**Comment by Remerod** [comment]
Some of this religions could still be made heresies and so on, i'll keep this issue open for now, but my intent is not to work personally on this for a while, since i have other priorities for now. I'll close this if i find this unlikely to be done before the release of 3.0

**Comment by Jaco-Daan** [comment]
Since were a long way from looking at this again, closing. Can always re-open if we ever go further east.
