### ISSUE TITLE
Suggestion for Hadorim hunting events

### ISSUE THREAD

**Issue by BriceLeduc** [jj248/RealmsInExile#355]
To be added to normal hunting events, for Hadorim cultural pillar : 
Event n°1  you come across a marauding band of Misty Mountain Orcs : 
 - option 1 : fight the leader yourself (duel)
 - option 2 : give battle with your escort (martial challenge, better chances for hunter and open terrain expert to win)
 - run away

Event n°2 (maybe check whether your realm borders Fangorn ?): your prey escapes into Fangorn forest :
- option 1 : enter and give pursuit (chances to be wounded by the Huorn)
- option 2 : send someone else to catch it
- option 3 : go home

**Comment by Jermanlordy** [comment]
il start working on this in the evening

**Comment by Remerod** [comment]
I've asked @BriceLeduc to use this suggestion for a possible contribution for new people wanting to join

**Comment by BriceLeduc** [comment]
Event 1 coded by Fredsch
