### ISSUE TITLE
Easterling armour / clothing

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#374]

**Comment by Remerod** [comment]
for anyone that wanna start on this and use the rise of mordor/dawnless days assets there is some suggestion on what to use here https://github.com/MattTheLegoman/RealmsInExile/issues/339 and i do have access to them and kind of know how to get them into the mod

**Comment by jj248** [comment]
Closing this as we won't get it for v3 and we can just re-open as an ad-hoc work item when we get the 3D artist resource to do it.
