### ISSUE TITLE
Crafting activity and lifestyle

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#390]
Crafting activity designed to be lore-friendly for elves (and in the future dwarves) to engage in.

Activity would allow characters to be able to create their own artifacts, with control over exactly what it is they are creating and the benefits that it might have.  Quality will determine on skill in crafting and materials used.

Cost of activity will be time and material costs.  We could even have crafting materials as inventory items, with events to try and source materials.  Certain artifacts might require certain materials and some materials might confer greater bonuses to the final item (e.g. a Mithril Sword vs and Iron Sword).

Benefits of activity will be skill progression and the final crafted item itself.  This could either be used by the character or sold (for profit or loss depending on item quality).

An accompanying lifestyle can be created to focus on and give buffs to the activity in things like:

- Material costs
- Item quality
- Crafting time
- Available recipes
- Chance of success
- Resale value
- Material availability

Could have multiple trees focusing on different forms of craft (e.g. metalcraft, woodcraft, gemcraft, 'magic'-craft).  We may be able to give racial bonuses / affinity to certain forms too (e.g. dwarves are good with metal, Noldor with gems, Silvan with wood etc).

Activity would be available to all characters and likely tied to the learning attribute.  Longer lifespan characters will have greater time to become better at their crafts (which ties in nicely with elves, dwarves and maiar being great craftsfolk).

We may wish to nerf the quality of generic items that can be found or purchased through events and adventurers to make investing time in this activity worthwhile.  The player should feel like they're able to really create great items of power at the highest levels.

**Comment by MattTheLegoman** [comment]
**Realms Lifestyles**
In this design document I have various lifestyles based on The One Ring.

https://1drv.ms/w/s!AmqiKhKRhel2gsNX0Fz5aUN1lYZwnQ?e=OO7ry0

Artisanship Lifestyle (page 11) is relevant here, with the potential for four focuses: Artificing, Sorcery, Storytelling and Music.

**Comment by jj248** [comment]
Honestly, this is a lot of work.  Let's push it to v4.  It's on theme for the dwarves creating things anyway! :)

**Comment by Jaco-Daan** [comment]
Making a mental note here to look at this alongside Jamie.

**Comment by jj248** [comment]
@Jaco-Daan to merge with v4 dev branch.
@jj248 to add uber interactions.
Someone to organise community query!

**Comment by Jaco-Daan** [comment]
Since this has been added (aside from odd bugfixes and so on) closing
