### ISSUE TITLE
Testing Sailing: New shores, River Sailing, Piracy

### ISSUE THREAD

**Issue by josejuanmartinez** [jj248/RealmsInExile#400]
We need to test the sailing events, since we have added much content there.

Things to check:
## Sailing with not a northern-apysaic coastal nation.
- Check that you can go to a "voyage of exploration", giving you the options to explore:
   - the Shores of Middle Earth (Gulf of Lhun, the White Hills, you can ignore the others since they were already there in previous releases)
   - the Rivers of Middle Earth (Anduin, Harnen).
   - You can ignore Meneltarma since that was also in the previous releases.

Check all the events work properly in Anduin, Harnen river exploration, as well as Gulf of Lhun and The White Hills chai

You can ignore the following events:
- Random at sea events (present in previous releases)
- Random at dock events (present in previous releases)

## Sailing with a northern apysaic nation.
You will see, that, apart from "voyage of exploration" you will get "go on a raid".
- Check the raid chain event, that includes Piracy at sea and Piracy on coastal shores.

Also, go over Anduin and Harnen, and check more options for those events are present (sabotaging things mainly).

**Comment by JukeJukestar** [comment]
There are far too many "Rhudaur explorers" and other nicknamed rulers on the map, change the events that give nicknames to only have a small chance to do so

**Comment by JukeJukestar** [comment]
Changed the event:
It now checks wether you already have a nickname, and its only a 30% change to get troll seeker or rhudaur explorer if not.
Ideally this would need more polishing haha
