### ISSUE TITLE
Concept: "Sagas" - Northron alternative for Explore History

### ISSUE THREAD

**Issue by BriceLeduc** [jj248/RealmsInExile#406]
Events for both northron and hadorim heritages, similar to the explore_history events :

Those are mainly oral cultures and the event should reflect that : you call a bard to the great hall to tell the tales of the glorious ancestors (3rd age only), if possible the style should emulate old Saxon/Germanic sagas. Beowulf, Siegfried, etc

There should be distinct corpus of sagas for each heritage. An option to access the other heritage's sagas could be unlocked if the ruler has the Scholar trait, or his court poet is of the correct heritage

Ideas of sagas : 
- for Hadorim : the Ride of Eorl, the Death of Scatha, Helm Hammerhand and Wulf of Dunland
- for Northron : Bard and the Dragon, the Battle of Five Armies, something about Dale and Dorwinion (One Ring RPG or MERP)

**Comment by JukeJukestar** [comment]
I'd love to pick this up someday, maybe in 4.0

**Comment by RedArkady** [comment]
This is a nice idea but a lot of work, we should probably make a call on whether it's going to be moved over to the 4.0 project Git of whether we bin it for the time being to avoid Git bloat?

**Comment by Jaco-Daan** [comment]
Since this is not likely to be a thing in the near future, closing. This has been benched for a while
