### ISSUE TITLE
Easterling CoA Emblems

### ISSUE THREAD

**Issue by Remerod** [jj248/RealmsInExile#408]
# Easterling CoA
So I've been told that we need suggestions for Easterling CoA, so i put something together. Do not that i am not suggesting the flags/emblem should be used where I've taken them, i only want to showcase where i found them all, it's the emblem and flags themselves I'm showcasing. 

Most designs are from other Mods, but also from games, WETA and some community made ones. 

### Weta Design
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/163013890-eac177a4-fbd8-431a-9bb0-91a294c57e5b.png)
Weta design of the Easterlings 1

![image](https://user-images.githubusercontent.com/79544635/163013964-c4cd9a29-a1a7-4552-821c-d70c9ef0e256.png)
Weta design of the Easterlings 2

In the Eu4 lotr mod they have the igath having this flag, which i think fits

</details>

- [ ] Weta design of the Easterlings

### MERP 
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/163014291-4c004b1c-59d9-4045-aa00-6963c56b01d9.png)
Asdriags

![image](https://user-images.githubusercontent.com/79544635/163014412-b3839d5c-6239-4152-8116-152a3d16bf38.png)
MERP Axeeasterlings or Hatholhoth or Hatholrim emblem

![image](https://user-images.githubusercontent.com/79544635/163014470-5708e9b2-1abf-429a-bf88-73e0773fcb73.png)
MERP Chy

![image](https://user-images.githubusercontent.com/79544635/163014525-a16b8035-3873-48fe-b3fb-d4971d713e39.png)
MERP flag of Sagath

![image](https://user-images.githubusercontent.com/79544635/163014561-54be1009-5443-4b37-98cb-2d5411d45f0f.png)
MERP Kýkuryan

![image](https://user-images.githubusercontent.com/79544635/163014608-1d6f7133-a311-4d81-9ee8-1a0df60afba2.png)
MERP Logath

![image](https://user-images.githubusercontent.com/79544635/163014658-6da3e790-c0c8-4aeb-9d35-c59200eedffc.png)
MERP Lothrag

![image](https://user-images.githubusercontent.com/79544635/163014717-c2607e58-2c59-4ed4-935c-89a179732a13.png)
MERP Magriags

![image](https://user-images.githubusercontent.com/79544635/163014771-c509d7e1-9acc-4356-aa0a-7254a0dbe393.png)
MERP Odhriags

![image](https://user-images.githubusercontent.com/79544635/163014811-5cb0aec8-9d59-46cb-9998-1a513d979909.png)
MERP Urgath

</details>

- [ ] Asdriags emblem
- [ ] MERP Axeeasterlings or Hatholhoth or Hatholrim emblem
- [ ] MERP Chy emblems
- [x] MERP flag of Sagath
- [ ] MERP Kýkuryan
- [ ] MERP Logath
- [ ] MERP Lothrag
- [x] MERP Magriags
- [x] MERP Odhriags
- [x] MERP Urgath

### LOTR Rise to War
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/163014113-bcae457d-abe0-4be7-a144-dc6351a0ee5c.png)
I really think this flag & colour scheme fits the golden realm

![image](https://user-images.githubusercontent.com/79544635/163014206-6263d9fa-82e5-46a8-845b-5de060937a18.png)
maybe some emblem design can be made form this? 

</details>

- [x] Rise to War Easterling Star emblem
- [ ] Rise to War  totem design emblem

### Ck2
Flags from the ck2 lotr mod
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/163014913-9221f268-8190-442d-8dde-4bc878323c37.png)
Athav flag

![image](https://user-images.githubusercontent.com/79544635/163014982-6e63c1cb-35d9-4341-8745-a162f679470d.png)
ck2 Balchoths Flag

![image](https://user-images.githubusercontent.com/79544635/163015020-a9ce79ea-2ca9-495c-85d1-2dbe7c436e37.png)
ck2 Dol Dagor Flag

![image](https://user-images.githubusercontent.com/79544635/163015063-688bdd08-b35a-4ab9-9096-5be455988696.png)
ck2 Ehwatthrumavuld Flag

![image](https://user-images.githubusercontent.com/79544635/163015119-de6fc708-100b-497a-bff4-2dbad50cd7ce.png)
ck2 Gathod Flag

![image](https://user-images.githubusercontent.com/79544635/163015155-f6fb04e2-86c7-4ca8-8190-54424141e247.png)
ck2 Mispar Flag

![image](https://user-images.githubusercontent.com/79544635/163015185-d438c494-2679-4ab4-92e0-b789db681361.png)
ck2 Mistrand Flag

![image](https://user-images.githubusercontent.com/79544635/163015232-83661f8b-bb77-4dac-b3da-68323a649b65.png)
ck2 Nuruvar Flag

![image](https://user-images.githubusercontent.com/79544635/163015269-ed201f33-5ff2-4d7e-acfd-7ddfa8b62a1c.png)
ck2 Sagath Flag

![image](https://user-images.githubusercontent.com/79544635/163015314-da63a5b0-e144-4671-9980-773429ff2ffd.png)
ck2 Sagathaburh Flag

![image](https://user-images.githubusercontent.com/79544635/163015373-035145ef-81d3-4168-9692-8045df2729ef.png)
ck2 Sagathavuld Flag

![image](https://user-images.githubusercontent.com/79544635/163015413-ab8e291c-4eb5-4ea4-8d21-15c8c8cbd125.png)
ck2 Uldovhar Flag

</details>

- [ ] ck2 Athav flag
- [ ] ck2 Balchoths Flag
- [ ] ck2 Dol Dagor Flag
- [ ] ck2 Ehwatthrumavuld Flag
- [ ] ck2 Gathod Flag
- [ ] ck2 Mispar Flag
- [ ] ck2 Mistrand Flag
- [ ] ck2 Nuruvar Flag
- [ ] ck2 Sagath Flag
- [ ] ck2 Sagathaburh Flag
- [ ] ck2 Sagathavuld Flag
- [ ] ck2 Uldovhar Flag

### EU4 LOTR mod
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/163015488-4e1906f9-cc7d-4387-abf1-0993e73e8e08.png)
EU4 Asdriags Flag

![image](https://user-images.githubusercontent.com/79544635/163015519-57c3735d-0d70-49ed-aa89-6a40886217e2.png)
EU4 Brygath Flag

![image](https://user-images.githubusercontent.com/79544635/163015572-78904110-ec3d-485a-80f7-1bb60b6efbbd.png)
EU4 Magriags Flag

![image](https://user-images.githubusercontent.com/79544635/163015603-99dc0548-67a0-468b-a17c-f0abf4201405.png)
EU4 Nurn Flag

![image](https://user-images.githubusercontent.com/79544635/163015641-4e12efbc-22b1-44b8-ac0e-c8b9fc66075c.png)
EU4 Odhriags Flag

![image](https://user-images.githubusercontent.com/79544635/163015663-b506d595-f2ec-47cb-a1e5-b80bf74081a8.png)
EU4 Rycolis Flag

</details>

- [ ] EU4 Asdriags Flag
- [ ] EU4 Brygath Flag
- [x] EU4 Magriags Flag
- [ ] EU4 Nurn Flag
- [x] EU4 Odhriags Flag
- [ ] EU4 Rycolis Flag

### Imperator lotr mod
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/163015717-ee744a9b-f669-4f9e-8869-398cc1ef45f1.png)

</details>

- [x] Imperator lotr mod emblem

### Age of the Ring
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/163015788-39548516-960b-468e-a5e3-17b3c8877d94.png)
Age of the Ring Mod Easterling Kataphrakts Flag

</details>

- [x] Age of the Ring emblem

### Rise to war/The Dawnless days
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/163015854-d691aabd-f5df-4c2b-b496-fc332afed930.png)
rise to war-clan Axemen-cool design

![image](https://user-images.githubusercontent.com/79544635/163015902-4caa3aab-4d26-46e0-914e-a4117694a808.png)
rise to war-clan raiders-cool design

![image](https://user-images.githubusercontent.com/79544635/163015950-6ceaab89-8698-4f27-b171-0557c892ebbf.png)
rise to war-clan spearmen-cool design

![image](https://user-images.githubusercontent.com/79544635/163016000-54b3123a-4a9b-4dab-a11e-68f9dc4143e4.png)
rise to war-rhunic savages-cool tattoo designs, could be made CoA designs.

![image](https://user-images.githubusercontent.com/79544635/163016092-18e65d52-2f43-4257-9df5-a4dcc791f96f.png)
rise to war-wainrider chiefs-cool design1

![image](https://user-images.githubusercontent.com/79544635/163016131-7b25420d-bae7-4178-81aa-c2c8cdbe182f.png)
rise to war-wainrider chiefs-cool design2

![image](https://user-images.githubusercontent.com/79544635/163016172-32996146-ca70-4c90-8131-9b0bd8b5c639.png)
rise to war-wainrider chiefs-dragons

![image](https://user-images.githubusercontent.com/79544635/163016208-b8b7866c-ace3-42c5-9a20-e94b14e47a6d.png)
rise to war easterling concept art with flags

![image](https://user-images.githubusercontent.com/79544635/163016239-bda59d4d-15f3-46fe-b01b-04a5798cb80a.png)
rise to war easterling concept art with flags2

</details>

- [ ] rise to war-clan Axemen-cool design
- [ ] rise to war-clan raiders-cool design
- [ ] rise to war-clan spearmen-cool design
- [ ] rise to war-rhunic savages-cool tattoo designs, could be made CoA designs.
- [ ] rise to war-wainrider chiefs-cool design1
- [ ] rise to war-wainrider chiefs-cool design2
- [ ] rise to war-wainrider chiefs-dragons
- [ ] rise to war easterling concept art with flags
- [ ] rise to war easterling concept art with flags2

### WB Shadow of War
I really like this deisgn for the banner!
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/163016304-8dd77267-f69c-470b-974e-7104af3708ab.png)
WB shadow of War 1 Easterling_Banner1

![image](https://user-images.githubusercontent.com/79544635/163016327-9f11ccde-30c7-47d0-acf5-0b5a6b33a1f6.png)
WB shadow of War 2 Merchant_King

</details>

- [ ] WB shadow of War 1 Easterling_Banner design

### Games Workshop LOTR
Both officals and community made models
<details>
<summary>Click to expand</summary>

**Officals**

![image](https://user-images.githubusercontent.com/79544635/163016457-7ff27f8d-1b95-4d9c-8d5d-800ab0e9d366.png)
Games Workshop easterling flag1

![image](https://user-images.githubusercontent.com/79544635/163016483-9782f6d0-6f6d-4343-a45f-93f37a4962a1.png)
Games Workshop easterling flag2

![image](https://user-images.githubusercontent.com/79544635/163016539-3a920947-5f5e-4084-b788-cc06ced058e1.png)
Games Workshop easterling helm emblem, could be made into a simple coa emblem.

**Community**

![image](https://user-images.githubusercontent.com/79544635/163016719-a6675de2-a6ee-4c10-92ad-3af4e6ec0012.png)
Games Workshop easterling fan made unit emblem

![image](https://user-images.githubusercontent.com/79544635/163016771-b657e029-0754-4a32-ba35-5e2e724c83cb.png)
FB warhammer community miniature 1 flag, really cool design on the flag in my opinion
https://www.facebook.com/lordoftheringsminiatureGW/photos

![image](https://user-images.githubusercontent.com/79544635/163016918-7441d2c7-0a3c-4fb3-9062-b6e617bbe38d.png)
FB warhammer community minature 2 shield emblem. the shield emblem would really make a cool coa emblem!
https://www.facebook.com/lordoftheringsminiatureGW/photos

![image](https://user-images.githubusercontent.com/79544635/163017024-368157f2-4258-44aa-9ac7-2ab683eec674.png)
FB warhammer community minature 3 shield & flag emblem, more of the above footage.
https://www.facebook.com/lordoftheringsminiatureGW/photos

</details>

- [x] Games Workshop easterling flag1
- [ ] Games Workshop easterling flag2
- [ ] Games Workshop easterling helm emblem, could be made into a simple coa emblem.

- [ ] Games Workshop easterling fan made unit emblem
- [x]  Kerkassk (FB warhammer community miniature 1 flag, really cool design on the flag in my opinion)
- [ ]  Dragon-orobos-thing (FB warhammer community minature 2 shield emblem)
- [ ]  Double-Dragon-orobos-thing (FB warhammer community minature 3 shield & flag emblem, more of the above footage.)

**Comment by Remerod** [comment]
Oh i fought the last part in the Warhammer part i added was community made, but it was apperently from their community site! and a real unit they are adding, [Lead Your Easterlings to Certain Victory With the Awe-inspiring Dragon Emperor of Rhûn](https://www.warhammer-community.com/2022/03/14/lead-your-easterlings-to-certain-victory-with-the-awe-inspiring-dragon-emperor-of-rhun/)

**Comment by Remerod** [comment]
Found this which is pretty cool, great emblems material for CoA in my opinion. 
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/163655657-f13e17fd-420c-4a77-9f20-5e0606d28409.png)

</details>

**Comment by Remerod** [comment]
Another one
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/163695216-0600d7e7-0800-4b72-a052-3d471773edbe.png)

</details>

**Comment by jj248** [comment]
I certainly think these are in a good enough state for release. <3

Closing.

**Comment by jj248** [comment]
At @Remerod 's request, keeping this open for further expansion later.  Moving to v4.

**Comment by jj248** [comment]
@Remerod - does this still need to be open?

**Comment by Remerod** [comment]
Yes, there are plenty which can be done, but i'll try to add checkers so we know which are done. As we need more emblems then just the easterling stars which are the majority of the emblems for the easterling now

**Comment by Remerod** [comment]
test
[ ]

**Comment by Remerod** [comment]
Of course we don't need them all but there are plenty that could be done like ´Kerkassk symbol and oroboros design, in my opinion.

But with check marks would make it a lot easier to see what we currently have and if we should make some more

**Comment by Jaco-Daan** [comment]
Since most of them have been implemented, closing this issue
