### ISSUE TITLE
3d model for Smaug's Skull 

### ISSUE THREAD

**Issue by Remerod** [jj248/RealmsInExile#410]
we have this skull artifact in, and i think it need's a proper model

![image](https://user-images.githubusercontent.com/79544635/163253194-0c388b33-3dc5-4bc9-9894-f7fdcd17a4fa.png)

So if this is good enough for now i can probably get it in

![image](https://user-images.githubusercontent.com/79544635/163253302-79294ca1-e35a-4c2b-b4d9-8c5b47977eb9.png)

But is no artifact master as of no, so will postpone this to later

**Comment by jj248** [comment]
Let's postpone to v4.

**Comment by Rewinged** [comment]
How big would the skull be? I'm trying to think how it would fit in the courtroom. I imagine it would be too large to make sense anywhere... maybe wall mounted would work better?

**Comment by BriceLeduc** [comment]
I was thinking furniture size, about the size of a diwan

**Comment by BriceLeduc** [comment]
To be put in the furniture/statue slot. Right now it's in a chest

**Comment by jj248** [comment]
I'm not convinced it's worth putting in. Quality is pretty low too, regardless of the issues with making it a reasonable size. If you really wanted to put it in, making it a tooth would be more reasonable to render as a court artifact.
