### ISSUE TITLE
Gondor never declares War

### ISSUE THREAD

**Issue by RedArkady** [jj248/RealmsInExile#417]
He tends not to attack, even when he'd win with allies' help. Leaves expansion to his vassals. Need to boost boldness, zealotry, or whatever it takes to make him less cautious.

**Comment by JukeJukestar** [comment]
One way to help with this may be changing his personality traits a bit?
The recent update made AI personality far more important in how they act. I was thinking the same thing for Abrakhan maybe.

Question is, how do we determine what traits make the AI agressive (and still fit)?

**Comment by RedArkady** [comment]
We discussed this recently. Boldness and zealotry are apparently the two key factors. He's already maxed out on boldness through his Brave trait, and we don't want to make him a zealot. I think there are ways of doing hidden modifiers, but a) I don't know how and b) I get the impression that they're unpredictable. Tobzyn said that in Way of Kings the last_stand CB is set up to make it more likely that a particular character will use the CB, so if anyone has access to that code and could share it here we could have a think...

**Comment by RedArkady** [comment]
Similarly there was talk of boosting AI likelihood by boosting the figure below to, say, 200, but Tobbzyn was concerned that the AI might declare war while already at war (though I thought the AI couldn't declare war while tis troops were raised, as with player characters...)

        add = {
            every_in_list = {
                list = target_titles
                if = {
                    limit = { 
                        scope:attacker = { 
                            this = character:lineisildur42
                            }
                        }
                        scope:defender = { 
                            faith_is_evil = yes
                        }
                    }
                    add = 200
                }
            }
        }

**Comment by jj248** [comment]
I've added AI modifiers to Anduril to reduce rationality and increase zeal AI modifiers.  Let me know if you want anything else implementing to try and combat this @RedArkady .

**Comment by RedArkady** [comment]
Still seems to be a problem. Even if you console-kill Sauron Aragorn does nothing - not even for his de jure. Does plenty of colonising though.

**Comment by RedArkady** [comment]
I don't think we should underestimate how big a problem is. It makes non-Gondor runs rather broken, as no-matter how strong Gondor's allies are it's irrelevant if Gondor won't pursue victory. Remedying this feels pretty central to the overall balance of the mod, thematically and gameplay-wise.

**Comment by RedArkady** [comment]
Appears to be affecting all Gondor rulers (not vassals).

**Comment by savagesach** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/86676697/7c259692-d7e5-478d-87d6-2a02429c6542)
this is already known, but I just wanted to mention it in the git issue. ai aragorn is definitely more aggressive, but he never retakes ithilien because now he's free to use the destroy mordor decision whenever he feels like it

**Comment by savagesach** [comment]
on that note, sauron keeps using holy wars for anorien instead of the actual invade gondor decision, so I think a fix for ai is definitely needed to make the decisions actually used as they should be
