### ISSUE TITLE
New event backgrounds SFX

### ISSUE THREAD

**Issue by BriceLeduc** [jj248/RealmsInExile#419]
There are a bunch of new event backgrounds in-game, courtesy of Ralph.
As Matt noted, they are in need of a new lighting setup.

Someone who knows their way around lighting should take a look at it and make new SFX files

**Comment by jj248** [comment]
Low priority - don't suggest we cover this in v3.  One for v4 nice-to-haves.

**Comment by Jaco-Daan** [comment]
This has been done to my knowledge, closing
