### ISSUE TITLE
Elven Government and Holds

### ISSUE THREAD

**Issue by Remerod** [jj248/RealmsInExile#420]
# Introduction
So there been some talk a great while ago that making Elves a different government and give them different holds would help making them less interested in "human" holdings, but while some people have been on board on that there haven't really been any concrete suggestions, so here is mine! 

### Elven Holds

**Elven Halls** – castle like, places of big importance and more concentrated areas of crafting, military and governance.

**Elven Groves** – a combination of cities and temples. Representing more rural areas, where the more common elves live producing food and culture. 

**Temples** – I don’t think Elves need a temple like holding type, from my understanding there’s never really been a temple like structures for the valars, at least not to the extension that a whole community is held by a priest and their seat of power. they revere them in other ways. So, I think a theocracy for elves are un necessary. 

I feel like 2 holding types, Elven Halls & Elven Groves would represent all that elven settlement representation would need. Elven halls could be all from Rivendel, Grey havens to Thranduil's Halls and other “walled/stone built fortresses and settlements” while Elven groves would represent the other more rural areas like [Cor Angálaladh]( https://notionclubarchives.fandom.com/wiki/Cor_Angaladh) in Mirkwood, [Haldirith]( https://notionclubarchives.fandom.com/wiki/Haldirith) in Lothlorien or [Celondim]( https://notionclubarchives.fandom.com/wiki/Celondim) in Lindon. 

### Elven Government

Maybe we’d could name it something like **Elven Courts** or **Elvish Hierarchy**, maybe a name in Quenya or Sindarin?

I’m pretty sure in vanilla clan government allows their “counts” to hold both castles and cities, and we could do the same for the Elven government, giving the lords/counts the ability to hold either Elven Halls or Elven Groves. Or differentiate the two, if so then the Elven Halls would probably be the more dynastic one while the Elven Groves could be more “governmental” like, maybe even on a timed charge, so they lose the title like after 25-50 years and the lord could choice a new ruler for the area, spicing up the Elven gameplay a bit. Maybe having a timed title ownership overall for count levels could be a thing for the elven government?

**Comment by Remerod** [comment]
Suggestion for potential buildings are welcome, will probably add some myself an other day

**Comment by VectorMaximus** [comment]
So, after discussion on the discord, this is my suggestion.

One basic holding type, the _Elvish Sanctuary_. These are meant to incentivize playing tall.

Once per duchy, you may take a level 4 Elvish Sanctuary and upgrade that into an _Elven Stronghold_. These are places like Caras Galadhon, Thranduil's Halls, Imladris, etc. Each duchy may only have one Elven Stronghold. This is to reflect the tendency to have a single strong major settlement in large areas for Elves, surrounded by land held more tenuously or sparsely.

Once per kingdom, you may then take a level 4 Elven Stronghold and upgrade that holding into an _Elven Metropol_. These are true cities of the Eldar, great and mighty, akin to Mithlond, Menegroth, Gondolin, and Tirion at their heights.

**Comment by jj248** [comment]
This has been implemented with limitations as set out in #507 .  Moving to testing.

**Comment by JukeJukestar** [comment]
related to #803

**Comment by Remerod** [comment]
I'll leave it open for a little while longer till stuff in https://github.com/jj248/RealmsInExile/issues/803 is fixed?

**Comment by savagesach** [comment]
This issue was only open until 803 is closed, and now 803 is closed. I think this issue can be closed as well.

**Comment by jj248** [comment]
Wonderful - closing.
