### ISSUE TITLE
Gundabad - Crypt of Skorg and mantle of Ashdurbúk decision and events

### ISSUE THREAD

**Issue by Remerod** [jj248/RealmsInExile#423]
### Introduction
So this is related to the work with https://github.com/MattTheLegoman/RealmsInExile/issues/337 .  Currently to form the Ashdurbúk title you need to hold 2 holy sites. But I’m thinking it would be more interesting to tie the title into the lore of Gundabad, making it a “decision” to embark on a dark and revered quest where one is deemed worthy of the title of Ashdurbúk.

### Some Lore bits from NotionClubArchives
So here are some lore related texts relevant to gain the title of Ashdurbúk.

**Skorg’s Conquest of Gundabad**
Sent by the Dark Lord Sauron, the great orcish general Skorg was sanctioned by his Master to assault Gundabad. During his mostly successful campaign Skorg found, with a small recon force in the vicinity of Mukarg's last refuge, Skorg was attracted by the [Ulûkai](https://notionclubarchives.fandom.com/wiki/Ul%C3%BBkai) whom was among the vicinities loot and Skorg seized the evil gem, before swiftly sending a courier bearing news of its finding to Sauron. Upon his return to the main host he found it in confusion and disarray - as it was the custom of Orcs lacking their chieftain. The power of the Ulûkai combined with a few Dush(sorcerers/priests) dispatched by his pleased Master soon gave the General control again and formed the mass of barbaric warriors into a quite capable and effective fighting machine. The relative vicinity of the Dark Lord wearing the One Ring further motivated the Orcs to an unheard-of discipline.

As Saurons main Legion’s fought against Eriador. Skorg have been given more resources and complete charge of the Northern armies, tasked with killing the Dwarves/Gazat. After a long campaign Skorg finally takes Gundabad from the Dwarves/Gazat. Though much of the original architecture was retained, Skorg left his mark on Gundabad by reforging it with a signature Orcish style, refining edges into sharp razors, adorning walls with skulls and bones, constructing wooden towers, ramparts, bridges and other machines and fashioning himself and his bloodline a massive awe-inspiring crypt; he became the first Lord of Gundabad. The Orc king's achievements which granted the Dark Lord a firmer grip over the northern lands, Skorg was bestowed upon the title of Ashdurbúk by Sauron's and taken into his confidence as part of his Black Council - his circle of chief agents who aided him closely in his aim to suborn the majority of Arda. In the aftermath of a long reign as a petty tyrannical regent of Sauron, Skorg passed away. He was the only evil ruler of Mount Gundabad to die non-violently.

**The Ulûkai of Morgoth**
At the end of the First Age, the Black Enemy faced the inexorable and inescapable vengeance of the Valar, and their judgment exiled him to the Void, barred from the Circles of the World until the end of time. Yet Morgoth had a presentiment of his doom — for was he not also in origin an exalted Vala, however fallen? Secretly, he hoped that one day he might return through the Door of Night for the final contest of the fate of Arda, if only a residue of evil survived in the world after his defeat. Thus, in the last prideful span of his reign in Angband, before the Valar struck, Morgoth crafted a truly heinous artifact, the Ulûkai. A huge [gem](https://notionclubarchives.fandom.com/wiki/Gem), multicolored and ever shifting in hue, the Ulûkai seems to pulse with a horrid life of its own. It is the very essence of evil, embodying a portion of Morgoth's own foul being, and it thereby partakes of a power beyond the comprehension of the Children of Iluvatar. So strong is the aura of Darkness it radiates that even without spellcraft its force can be vaguely perceived, while any user of power attempting to divine its true nature must save against a 10th level spell attack or be immediately drained of all power points. The function of the Ulûkai is simply to spread evil. From wherever it is concealed, darkness emanates like everwidening ripples in a pond, engulfing the surrounding lands. No one "controls" the Ulûkai; rather, it permits itself to be used by beings that it deems of sufficient power to serve its ends. If its possessor is not entirely evil to begin with, every month that he or she is in the vicinity of the artifact requires resisting a spell to avoid succumbing to Darkness. This spell begins at 10th level and steadily rises in increments of 2 to 50th level. It is not necessary that one actually bear the Ulûkai to make use of its powers and to be affected by its force. Once the artifact is claimed by laying hands upon it, thereafter it can only be renounced if its possessor is not yet entirely evil, and succeeds in resisting the 50th level curse that keeps the unfortunate individual in thrall, or finds a way to destroy
the Ulûkai. The powers that the Ulûkai confers on its possessor, which can be invoked as often as desired, are as follows: 
**Domination**. By exerting a will to mastery, one can subjugate the minds of creatures of lower level whose levels are in total less than or equal to one's own. Thus, a 20th Level Uruk Warrior could overpower 20 1st level beings or one creature of 19th level. Each
of the creatures so dominated will do whatever is demanded, having lost independent will. Dominated beings may attempt to resist the spell, subtracting the level of the caster from the resistance roll, to break free. If resistance fails, domination continues
for so long as the possessor of the Ulûkai continues to concentrate; if he is stunned or otherwise distracted, the spell is broken.
**Shadow Perception.** All things and beings within the realm of shadows, illusions, and the invisible are revealed in their true forms as though in brightest day. While this power is being exerted, however, sight in the normal manner is dimmed and rendered hazy
(-30 to perception). 
**Focused Will**. Much as Morgoth and Sauron, although to a far lesser degree and varying with innate power, the possessor of the Ulûkai acquires the focused will necessary to rule over masses of evil beings and monsters, driving them to cooperate in ventures and to reproduce. This power makes it possible for an individual to rule effectively in a huge domain of Darkness such as Mount Gundabad. Using the power of focused will, one can effectively command as many evil beings as one has levels, multiplied by
1000. Where Sauron could control a force of 240,000 troops or the Witch-king 60,000, a 20th level Goblin-king can rule no more than
20,000 Orcs at one time. Focused will differs from domination in that the beings subject to the focused will retain the power of
independent action and individually are capable of betraying their master; they are merely motivated in accord with the ruler's
general desires and will be thrown into confusion at his death. 
**Power Enhancement**. Any user of spells possessing the Ulûkai enjoys a x8 power point multiplier and full knowledge of all evil spells as high as his current level. Non-spell users, such as the typical Goblin-king, cannot derive this benefit, but instead acquire Mastery of Arms, the ability to wield any melee weapon as
effectively as though it were the primary weapon choice, and never to fumble a stroke. 
**Unlife Warding**. All undead beings will recognize the possessor of the Ulûkai as their superior if of lower level, or their coequal ally if of the same or higher level. They will not attack the warded being, and if of lower level can be subjected to domination. The presence of this awesome artifact in Mount Gundabad is no accident, and indeed helps to account for the endurance of this evil realm. Skorg's escape from Angband with the Ulûkai was one of the last schemes of Morgoth, who shrewdly guessed that an Orc might be ignored by the Valar and so win through where a more powerful bearer would surely be intercepted. As the first possessor of the Ulûkai, Skorg was able to found a lasting domain of Darkness, and each Goblin-king that meets the dreadful scrutiny of Skorg's wraith also lays his hands on the gem and partakes of the powers of the Ulûkai during his reign. For thousands of years, unknown to all but the Goblin-kings of Mount Gundabad and their High Priest, the Ulûkai has lain here, while Morgoth languishes outside the Circles of the World. In a very real sense, Mount Gundabad, its Orcish denizens, and their lords exist to perpetuate the evil that the Black Enemy first spawned in Middle-earth. Although the Ulûkai is beyond price, no one will be able to identify it as any known form of gem, and thus, should it ever be stolen, it probably will prove unsalable. As an artifact, it cannot be destroyed by any normal means. Disposing of it, should it ever be taken from the Crypt of Skorg, would be a major quest in itself.

(the DnD artifact powers are not super relevant, but I include them because of lore)

**Merp Gundabad**
The Crypt of Skorg. Greatest secret of Mount Gundabad, this
hidden cavern is the dread of the First [Ashdurbúk](https://notionclubarchives.fandom.com/wiki/Ashdurb%C3%BAk), as it has been for all of his predecessors since the founding of the Orc city. Only the Orcish monarch and the High Priest of Darkness are aware of its location; to other Orcs, it is merely a rumour of awful terror. The Crypt is lightless and contains but a single object: a huge sepulchre of black marble, upon which in silver Orcish runes, using the Black Speech, is written: Here lies Skorg, first Ashdurbuk in Mount Gundabad, once and ever the true Master of the North. At each of the four corners of the crypt, the marble is fashioned into the dreadful image of a Balrog. The lid of the tomb can only be removed by the combined strength of at least eight powerful Men or Uruk-hai. Within rests the skull of a huge goblin — Skorg himself — and a strange, multi-hued gem as large as a Great Eagle's egg, the Ulûkai of Morgoth. Intruders will be fortunate indeed to ever make that discovery, for the spirit of Skorg, burdened as it was with innumerable crimes, never left the city it created to pass into the Void. It remains within the crypt. Each new Goblin-king is compelled by the priesthood to spend the first night of his reign in the Crypt of Skorg. The next day, either he emerges with his right to rule confirmed — or never emerges at all (not possessing the ruthless strength necessary to succeed to Skorg's mantle). Anyone other than a Goblin-king or the High Priest of Darkness who enters the Crypt of Skorg will encounter the evil spirit (it appears in 10 rounds; immediately if the sepulchre is touched) which seeks immediately to destroy intruders. The Wraith of Skorg is 30th Level, with 350 hits, AT PI/19, DB 120, Attack +220 with a great scimitar as ethereal as itself. The ghost can only be hit with enchanted weapons, and all encountering it must save at -50 or flee
in terror. In no case will the Wraith pursue foes beyond the Crypt. Should it be destroyed, it can reform in one day provided that the Ulûkai of Morgoth is not removed.

**Hûdhsunga**
The Hûdhsunga (Orc."Soul-capture") was the rite of passage, as well as mental and emotional birth, for every Orc-Imp. Unlike and unknown to most other races orcs were born as soulless animals with a Hröa (Orc."Maushat", lit."Flesh") but no Fëa (Orc."Frúm"). Therefore, after surviving their notoriously brutal development, each Imp was to undergo the rite of Hûdhsunga in which the tribe’s conjurers summoned an Orc-spirit to enter the young goblin’s physical body. These Fell souls were homeless spirits of orcs who had died and, being evil in nature, had refused to enter the Halls of Mandos (Orc: Skator, “Hell") and who were otherwise forced to exist as poltergeists (Orc."Gogoli"). These spirits could be of various origins (chiefly corrupted Elves or Men but rarely Demonic spirits as well) and retained a vague imprint of their original nature, which may be a contributing factor in the consistent nature of Orcish behaviour, though most of an Orc’s memories and personality developed over time. All orcs who did not undergo the rite of Hûdhsunga, would remain soulless monsters, equal only to Trolls in intelligence. With this in mind, the orcs, in a twisted sense, saw this as a form of immortality, even superior to that of the Elves.

**Lore Conclusions**
It would not be out of a stretch to say that Skorg was one of the most famous and revered orc in all the ages, not just by the fact of his conquest, but of his independent rule, where there had been few ones earlier as most orc would have been under a thumb of a darker power/maia. But Skorg is also incredibly famous because of the legacy he left behind, bot with the conquered fortress which have been in orc control for millennia and because of the vast lines of orcs that claim heritage from him.

The Ulûkai is an immensely important artifact for the mountain orcs, for it has ties to the first dark lord himself. One can probably draw parallels to the dwarves Arkenstone or the Elves Silmarils. Whatever the “power” levels  can be compared, each race deep fascination with a gem maybe can be.

The Crypt of Skorg is a great monument of reverence by the majority of orcs in the North.

By orcish Gundabad traditions, to bear the Mantle of the title of Ashdurbúk, you need to embark on an ritual at the site of the crypt of Skorg, (and if each [Ashdurbúk](https://notionclubarchives.fandom.com/wiki/Ashdurb%C3%BAk) takes the gem with them after the ritual)  where the unholy gem Ulûkai is returned by the “High Priest of Darkness” when the previous Ashdurbúk perish. This ritual can be lethal the participant.  

There is lore substance to support of [Orc](https://notionclubarchives.fandom.com/wiki/Orc) spirits still lingering around, both with the orcish word for Fëa, Frúm and with the orcs spirits rejecting the halls of mandos(hell) and living on as poltergeists (Orc."Gogoli"). Whatever this is true or not, some stories are based on truth, and whatever orcs are corrupted elves, other corrupted forms of life or something else, I think some of us would agree that the stories that some lesser maia became orcs. So, it’s not unthinkable that Skorg could have been one of the few Orcs around that had a stronger “Frúm” then other orcs, and thus could have his Spirit “contained” within the Crypt where his remains still linger, continuing on as a form of “undeath” maybe manifested by the dark unholy energies by the Ulûkai. 

### Event idea
To gain the title of [Ashdurbúk](https://notionclubarchives.fandom.com/wiki/Ashdurb%C3%BAk)(which is the titular head of faith for the Cult of Ulûkai, d_ulukai) the current/former Ashdurbúk is dead or rather when there is no one else claiming the title. you need to venture fourth on a dark quest, pilgriming deep in the darkest chasms of Mount Gundabad and discover the unholy location of the Crypt of Skorg, where the participant needs to perform a ritual. This ritual includes facing the Spirit/Wraith/poltergeist of the first Ashdurbúk, Skorg under the presence of the unholy gem artifact the Ulûkai. By this unholy pair the participant most be deemed worthy, the participant needs to survive a “night?” during this trial. What the trial contains when facing the Spirit/Wraith/poltergeist Skorg and the unholy gem the Ulûkai. If the participant succeeds, they emerge as the new Ashdurbúk, if they fail, they dead! 

While maybe not super important now, I’m thinking of making the caliph like title of Ashdurbúk that currently exist as a titular duchy title, d_ulukai (whom serves as the head of faith title) into an emperor title. When the current holder dies, the “heir” has a “limited” time where they can perform the ritual, before the d_ulukai is destroyed, if this then is an empire title, and for the sake of argument, the empire holds 3 kingdoms with 3 separate characters holding these kingdoms under an empire title, the other 2 kingdoms would now be free from the former empire holder. 
Still, even if the empire thing is done or not, it would still be an important relevance to hold the title of Ashdurbúk or just be a common King/Overlord. 

**Things that might be relevant**
I’m thinking of making an “Sayyid” like trait, a Descendant trait which is given to all the decedents of Skorg. And if this is the case, then maybe one of the criteria of taking the Ashdurbúk decision is that you need to have this trait. 
Update: I have now created the “Sayyid” like Descendant trait, it's called Skorbúk and traces the characters bloodline back to Skorg.

Making an Artifact of the Ulûkai. Seeming as it as a very big role in the Cult of the Ulûkai it seems fitting it maybe be made into an artifact, if this is the case, I would assume it would be important factor in this Decision/Event 
Update: I've created the Artifact now

### Ending words
Currently I’m not adequate in making this kind of Decision/Event, so if anyone want to help me with it, then that would be great. Otherwise, I’ll return one day to this when my skills been improved.

**Comment by Remerod** [comment]
I wanted to add some core comments from a lore discord discussion, so the topic is remembered.

**Me:**
_If anything i see the Ulûkai as some "failed" creation by morgoth, trying to imitate the silmarils, failing in his mind and locking/throwing it inside some treasure room in angband which was internally looted before it's fall_

(Most likely it was [Mukarg](https://notionclubarchives.fandom.com/wiki/Mukarg) whom looted the artifact, but for the sake of our arguments, of Skorg being the first, we can just have it that the gem was sealed in a chest/box or something, which would have made Mukarg unaware of it's true value). 

**VectorMaximus:**
_Sure - how does this sound to you. While they must make their way through the physical perils of getting to the tomb, when they finally lay hands upon the Ulukai with the intent of mastering its power for their own, they must grapple with the covetous spirit of Skorg, who held it first and even in death covets it fiercely. If they are successful, the spirit of Skorg reluctantly subsides back into the Ulukai until the next challenger should come... If they are unsuccessful, the spirit of Skorg and the Ulukai will consume their souls._ 

_Well, in this case its a dark artifact which cursed its first bearer and ever after tries to eat more poor saps, instead of a Dark Lord's soul-jar 
which is the part of the Ring I really want to avoid_

**Comment by jj248** [comment]
We'll properly focus on Gundabad in v4 - shifting this to there,
