### ISSUE TITLE
Learn Sorcery Revamping

### ISSUE THREAD

**Issue by josejuanmartinez** [jj248/RealmsInExile#425]
## Allowing characters to learn sorcery.

- Gseg: a good question should be: who will be able to do dark sorcery?
- Matt: Any human or other species who converts to Forces of Evil. All Maias who are "evil", some Uruks, but I don't know how many Uruks.
- Jamie:You might include orc followers of the Red Eye Cult (Naukdshu-Fai) as their flavour is that they dabble in magics and sorcery.
- Gseg: Piety >=3

## Characters with Sorcery learn
- Evil Maiar
- Nazgul
- Sorcery trait

## What happens when triggered the decision?
See "Dark Ritual". Add GUI

Matt: A character starts the Sorcery Activity, they immediately get a preparation event where they can choose where they will be focusing their sorcery. Either at home or at a random choice of available terrains.

After a while they get an event with random choices from the list. The choices are affected by the location and what is available to the character.

## Buildings to boost Sorcery?
Not clear.

From Gseg: 
```
Holy Place: You get a bonus from your controlled holy places availables.
   - Holy Place 1: Better Sorceries
   - Holy Place 2: 20% discount in Piety
   - Holy Place 3: Better chances of Great Succes
   - Holy Place 4: Change the cost of piety for gold
   - Holy Place 5: No Failure
Chances:
   - Failure 12.5%
   - Succes 37.5%
   - Critical Succes 37.5%
   - Great Succes 12.5%

The Wilds
Chances:
   - Critical Failure 6.3%
   - Failure 25%
   - Succes 37.5%
   - Critical Succes 25%
   - Great Succes 6.3%

Home
Chances:
    - Failure 25%
   - Succes 50%
   - Critical Succes 25%
```

From Vector:
```
I’m unsure about the first 3 - those aren’t necessarily things I think of for ‘sorcery’.
Perhaps it could be something like:
Forge Morgul-Weapons
- create terrible weapons of ruin and dread to equip your troops with...
```

## Vanilla Witchcraft leads into Sorcery
Matt: I'm thinking that Witchcraft as it is in CK3 can be something that can lead into Sorcery.

## Resurrecting the GUI
To show the Practice Sorcery UI

**Comment by josejuanmartinez** [comment]
Working so far:
- [X] Learning Sorcery Decision (Sorcerer Tier I) 
- [X] Sorcery GUI with all spells
- [X] Events triggered by spells
- [X] Selection of location where to cast the spell
- [ ]  Learning Sorcery Decision (Sorcerer Tier II)

**Comment by josejuanmartinez** [comment]
@jj248  I think all is finished. I will recheck.

**Comment by jj248** [comment]
Sounds like this is ready to test.

**Comment by Jauffr** [comment]
All this is currently Commented out. This should go back to in progress

**Comment by jj248** [comment]
@BriceLeduc

**Comment by Jaco-Daan** [comment]
Since we're talking about learning sorcery in a different way, closing. Can always create a different issue if need be
