### ISSUE TITLE
Suggestion: Ruins

### ISSUE THREAD

**Issue by Remerod** [jj248/RealmsInExile#426]
### Introduction
So I was thinking of doing some Idea tinkering for Dol Guldur, but this is something I been thinking for a while and I thought I needed to expand and share on this. I think we should introduce a Ruin hold-mechanic thing-ma-gig. Ruins would be a “destroyed” holding that can be repaired similar to how wilderness are colonized (relevant to [Wilderness Wiki](https://github.com/MattTheLegoman/RealmsInExile/wiki/Wilderness-and-colonization) & https://github.com/MattTheLegoman/RealmsInExile/issues/396). It would be a cool feature overall that could be used for both Dol Guldur and anybody

### Why Ruins?
LOTR is riddled with ruins, from Ithilien to Arnor, they are a very iconic part of the setting. While this could maybe be represented as “buildings” I think making it into my suggested content would make it so much more, it would allow us to show the world/setting from other angles and I think including them would give a new type of “challenges” & gameplay which I think would be very fun for everyone. 

### Idea
So my idea is that Ruins would work as both the “wilderness” holding in the unsettled/wilderness government and “settled” holding as of when you colonize. My idea is that Ruins where once a “feudalized” holding type (while true that tribal land leaves archaeological remains, I think for this system tribal don’t fit into the ruin type) that have been destroyed by an enemy attack.

We’d introduce a new war cb mechanic that can “destroy” enemy lands. But who would use such cb? I assume in situations of like when orc vs humans fight, I don’t see gondor “destroy” & raze Harauze to the ground, but orcs would definitely do that to gondorians and vice versa. So, we could have 2 different version of this cb, like Lasgalen would maybe want to “destroy” gundabad, leaving it as a ruin wilderness (that would need to be colonized by some faction), while the which-king might want to destroy and hold the duchy Forithilien that gondor holds above him. So one cb would make it into a ruined wilderness while to other would ruinize it but you’d still hold onto it in your realm.

So how is it different from the Settlement holding type? Well for once, I would see to be a quicker way to “restore” then it is to colonize a new region, also a ruin holding would be more fortified place that already have foundations and maybe fortifications, thus giving it a more strategic relevance. And I could see a system where “Humans” take more negative modifiers for holding a ruin but would be quicker to restore it then say orcs, that would be more comfortable living in a ruin but take a lot longer in restoring them. So, this would make it so, that gondor would want to quickly restore ruins, but not hold to much of it, while orcs would be more comfortable to hold many ruins, but would take a lot longer in restoring them to proper holding types. 

So, with this system I can see us flesh out areas like ithilien and Arnor (in the feature), Ithilien would be fleshed out with ruins from Osgiliath to the borders of de jure Mordor, making it an area that you’d need to invest more heavily to restore, even if you win against Mordor, which would give longer gameplay relevance for the area. And Arnor is riddled in ruins (lore wise) and having ruins to colonize might be “smarter” than “normal” wilderness, this would make it more “strategic” then already to chohce we’re to colonize. And overall “Restoring” ruins would be a smarter thing to do then colonizing a random area. 

### Conclusion 
So while I personally see a lot of great stuff with this there might be some negative? So, what are the Pro’s & Cons with this suggested system;

`-` Work, as we would need to mod this, even while we have a system from wilderness (it’s not completely done) and this would require more work and might be a ”feature creep” for 3.0
`-` Might be hard to get AI to understand and use such CB’s and restoring mechanics.
`-` Might be hard to mod how a former city holding, now ruin becomes a a city again and not a temple or castle and so on.

`+` A lot “Lore” & gameplay flavour for this system, to showcase places like Osgiliath and maybe Dol Guldur as more ruinous places worth investing longer time in. 
`+` This could be a thing where “Orc” gameplay gets chance to shine, as they would probably be more likely to “ruin”ize the world then orders.
`+` expanding on already existing the colonizing mechanic and adding more gameplay places to “invest” resources in.
`+` New CB’s and strategic tools to use, as a player would now choose to conquer, ruinize and conquer or destroy and create a wilderness border between themselves and their enemies. 

So maybe there is something I’ve missed here, but I think this would generally be fun gameplay and you could do a lot with this, say “destroy Mordor” could completely destroy the Barad-dûr barony (maybe you can do that to with wilderness now) but overall adds new stuff to do, “I” think it’s worth investigating and discussing upon at least. Hopefully other people will think so to. 
****

**Comment by Remerod** [comment]
A "semi-related_thought" by Jamie https://github.com/MattTheLegoman/RealmsInExile/issues/139

**Comment by JukeJukestar** [comment]
Certainly an interesting idea, you could even have a random event for a one-county orc realm to be created in a ruin randomly until they are driven out.

I feel like the best way to make this work would be for it to go hand in hand with an orc government

**Comment by jj248** [comment]
This is basically Wilderness.  Closing.
