### ISSUE TITLE
Wanted: Pilgrimage Unique Events

### ISSUE THREAD

**Issue by Remerod** [jj248/RealmsInExile#433]
So me and VectorMaximus was watching this streamer begging us for pilgrimage, and Vector seemed inclining to reactive them again. 
So this mean we are in **need** for unique Pilgrimage Events for the "majority" of our religions! 

Basic info of what a Pilgrimage is:

![image](https://user-images.githubusercontent.com/79544635/175719807-62a5ede6-0380-413c-9be4-86d9304d394f.png)

Picture taken from [Here](https://ck3.paradoxwikis.com/Decisions#Go_on_a_Pilgrimage)

VectorMaximus recently added [this](https://github.com/MattTheLegoman/RealmsInExile/commit/81203a684ec63153f99ca2913bce84bc8187ee65) pilgrimage which you could look at for inspirations

Since I've not done one myself i can't speak on the difficulty of this, but i don't think it's to hard but do remember to make some proper **lore** research when writing this and discuss your ideas with others.

**Comment by VectorMaximus** [comment]
Feel free to ping me if you want ideas/inspirations for holy site specific events

**Comment by Kyrenic** [comment]
You can now only go on pilgrimages to sites held by your faith type (good/evil) and neutral faiths.

Pilgrimages have now been added to:
- Eithel Ulmo
- Orthanc (Good Saruman, Walk of the Ents, and evil faiths)
- Imrazôr's Hallow
- Pelargir (Erulaitalë and Kings Men)

**Comment by JukeJukestar** [comment]
Seems to be working! Ive gone on several pilgrimages. It would be nice to get more unique events in the future (something i might work on myself even!), so I wont close this and instead move it to suggestions.

**Comment by JukeJukestar** [comment]
It seems that none of them trigger correctly anymore.
I hope its not my fault since I added a new event (Sairtheod) a bit ago!
I dont know why this is broken but it would be great if someone could take a look.

**Comment by jj248** [comment]
@JukeJukestar - am I right in thinking you got this fixed today and it can be moved to Testing?

**Comment by Remerod** [comment]
* Imrazôr's Hallow - tested, works
* Pelargir/Eithel Ulmo (isent this just pelargir?) -tested, works for (Erulaitalë and Kings Men)
* Orthanc - tested, not sure this working correctly

![image](https://user-images.githubusercontent.com/79544635/234993628-9f2ed400-fb0e-442a-984c-1aed5c737b92.png)

"evil" pilgrimage to orthanc

![image](https://user-images.githubusercontent.com/79544635/234997746-de71cd92-7593-4d99-bd04-ee16ab7d00c8.png)

"good" pilgrimage to orthanc

**Comment by Remerod** [comment]
thinking ortanc is not working i'm moving this to bugs, but if i'm wrong then this is good to close?
