### ISSUE TITLE
Adapt the "Murders at Court" event chain

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#442]
![image](https://user-images.githubusercontent.com/76008882/178212464-60949192-50db-4394-96b5-7f250b08d927.png)

The "Murders at Court" event chain is a vanilla event chain in which three members of your court are killed one by one. It usually ends with the death of a close family member (my wife in my game) and there are several endings in which you either catch the serial killer or he gets away.
Often times its a close family member like your heir.
The event chain does not seem to factor in personality traits for the serial killer so even a compassionate forgiving person can be the killer.

With elves coming up in 3.0, this single event chain could devastate your game as you can only have a few kids at most. Patching it to never happen for elves, nazgul and anyone else who it doesnt make sense for would also be an option but it would be quite tedious, so I would personally suggest its removal.

**Comment by BriceLeduc** [comment]
Murders at court have been disabled for Elves, and Nazgûl and Maiar characters have been excluded from potential victims.
