### ISSUE TITLE
Suggestion/Issue Abrakhân/The Golden King MAA

### ISSUE THREAD

**Issue by Remerod** [jj248/RealmsInExile#448]
Written a bit in a hurry so might missed some details~

So a lot of complaints have come that **Abrakhân** or rather **The Golden King** can't recruit the special MAA of the region,
Not even the _Guards of Abrakhân_. I do believe that Abrakhân gets special MAA from their missions, but those are limited and can not be recruited later to my understanding.

So it would be nice if the missions actually unlocks getting to recruit more MAA or maybe give the **Mask of the Golden King** the ability to recruits  _Guards of Abrakhân_. Another possibility is that we unluck all/some of them in the **Cult of Zigûr** with a special religious tenet. Now this just was a little idea of mine, and i am aware that maybe this is not possible.

Either Way a lot of people feel that they want to be able to recruit more of the flavored MAA of the region and we should look into resolving this

**Comment by Jermanlordy** [comment]
Abrakhan cant recruit Guards of Abrakhan but if they start with a Guard of Abrakhan you  can upgrade it to its max level and it will work though

**Comment by Remerod** [comment]
well, only if you play as the Golden King right? or do all vassals start with the guard?

**Comment by Jermanlordy** [comment]
1 pustic vassal and 2 independent pustic nations and then also harwenal start with guard of abrakhan but cannot make any more they can only upgrade

**Comment by jj248** [comment]
@JukeJukestar - you did an Abrakhan rework, was this considered?  Is it complete?

**Comment by Jaco-Daan** [comment]
Since this is similar to the Abrakhan rework issue, closing. Also thing it's been partially implemented
