### ISSUE TITLE
Orc/Evil cultural Titles

### ISSUE THREAD

**Issue by Remerod** [jj248/RealmsInExile#451]
# Introduction
So been inspired by some orc stuff lately (might be tied to certain new colour rework) So took a look on potential new cultural flavored title names

# Orc – Special Titles

High King/Emperor – Ashdurbúk(https://notionclubarchives.fandom.com/wiki/Ashdurb%C3%BAk) Leader of the Gundabad orcs

# Orc/Evil - Hierarchy  Titles

**Emperor** – Tyrant 
Tyrant - in a close sense a tyrant was a sole-ruler or autocrat, in the hierarchy of Sauron's empire however the Tyrant was his Masters highest ranking Lieutenant who was appointed to supervise the lesser Kings and Chieftains of a Greater subdicision of Saurons dominion.For example [Saruman](https://notionclubarchives.fandom.com/wiki/Saruman) had been offered the position of the Tyrant of the West, which would have made him Sauron's highest lieutenant, supervising the entire [Westlands](https://notionclubarchives.fandom.com/wiki/Westlands) with all of its local rulers. 
shown in [Hierarchies_and_Ranks](https://notionclubarchives.fandom.com/wiki/Hierarchies_and_Ranks)

**King** - Ûgong, shown in [Hierarchies_and_Ranks](https://notionclubarchives.fandom.com/wiki/Hierarchies_and_Ranks)
**Prince**- Durbúk, , shown in [Hierarchies_and_Ranks](https://notionclubarchives.fandom.com/wiki/Hierarchies_and_Ranks) 

**Duke** - [Durub](https://notionclubarchives.fandom.com/wiki/Durub_(Title)) (or."Ruler") also Durbúk or Durba in some dialects.

**Count**- [Hûr](https://notionclubarchives.fandom.com/wiki/H%C3%BBr) was an [orcish](https://notionclubarchives.fandom.com/wiki/Orcish) title referring to a [Chieftain](https://notionclubarchives.fandom.com/wiki/Chieftain) or [Lord](https://notionclubarchives.fandom.com/wiki/Lord).

**Temple Holder** – see priest

**Mayor** – Zot shown in [Hierarchies_and_Ranks](https://notionclubarchives.fandom.com/wiki/Hierarchies_and_Ranks)

**Baron** – [Drartûl](https://notionclubarchives.fandom.com/wiki/Drart%C3%BBl) 

**High Chieftain** – [Goth](https://notionclubarchives.fandom.com/wiki/Goth) (orc."Master")

**Chieftain** – [Shakh](https://notionclubarchives.fandom.com/wiki/Shakh_(title)) ([BS](https://notionclubarchives.fandom.com/wiki/Black_Speech)."Lord")

# Other orc/evil titles

**Council Positions**

**Chancellor** – [Khaunúlor](https://notionclubarchives.fandom.com/wiki/Khaun%C3%BAlor) 

**High Priest** - Fha-Laugash (B.S."High-Priest")
**Priest** - Laugashî (B.S."Sorcerers") could be used as priest I guess? In MERP they acted as ambassadors, [priests](https://notionclubarchives.fandom.com/wiki/Priest) and henchmen of the [Necromancer](https://notionclubarchives.fandom.com/wiki/Necromancer) or his puppet-ruler.
Or maybe for specifically orchish priest we use [Dush](https://notionclubarchives.fandom.com/wiki/Dush-hai) as we already used this term before. 
**Untitled priest** - Smalaugashî (B.S."Acolytes") maybe something we can use.

**Marshal** - Gonon BS. For Warlord, from MERP-Dol Guldur I believe. 

**Steward** – [Gothûl](https://notionclubarchives.fandom.com/wiki/Goth%C3%BBl) (orc. "Steward, lieutenant";Lit."Servant of the Master")

**Spy Master** – Maybe Burgûl-Hûr (Burgûl-Shadow Hûr- Master, Chief) or maybe Durub-Burgûl which would be like Shadow-master which kinda follows in line of [Durub-atha](https://notionclubarchives.fandom.com/wiki/Craftsman) - master craftsman

**Knight** – This one was a little hard, maybe just plain “[Uruk](https://notionclubarchives.fandom.com/wiki/Uruk) - great warrior Orc” or maybe something to use with the word [Dog, Daug](https://notionclubarchives.fandom.com/wiki/Dog_(Soldier-Orc)) – Soldier/Warrior
Hûrdaug - 'Master Warrior' - By Vector

**General** – [Urdânuk](https://notionclubarchives.fandom.com/wiki/Urd%C3%A2nuk)

**Courtiers**

**Senechal** - Hrizgthraki (B.S. "Pain-bringers"; lit. "Overseers") from MERP-Dol Guldur I believe but also shown in [Orcish](https://notionclubarchives.fandom.com/wiki/Orcish?so=search). Or [Gothsnaga](https://notionclubarchives.fandom.com/wiki/Gothsnaga) - literally "slave lord".

**Personal Champion** – [Roshatar](https://notionclubarchives.fandom.com/wiki/Rroshatar) (orc-"Chief-Warrior")

**Personal Bodyguard** – [Rog](https://notionclubarchives.fandom.com/wiki/Rog_(orcish_Rank)) (Or."fast-one") was an [orcish](https://notionclubarchives.fandom.com/wiki/Orcish) term designating a higher ranking orcish [Warrior](https://notionclubarchives.fandom.com/wiki/Warrior) or [Guardian](https://notionclubarchives.fandom.com/wiki/Guardian).A Chief Guardian was called "Krual-Rog". Or maybe Rogtar which is a Veteran? According to shown in [Hierarchies_and_Ranks](https://notionclubarchives.fandom.com/wiki/Hierarchies_and_Ranks)
Or Orgabu – Bodyguard from [Orcish](https://notionclubarchives.fandom.com/wiki/Orcish)

**Comment by Remerod** [comment]
I've given a go ahead with this, so moving this to non-critical for now

**Comment by jj248** [comment]
I've got a strong aversion to using obfuscating title names.

**Comment by jj248** [comment]
Pushing to v4 to consider when we have a lot of orcs to add.

**Comment by Jaco-Daan** [comment]
We've implemented our cultural flavorization for goblins in v4, so this issue seems to have been handled, closing
