### ISSUE TITLE
Easterling battle arenas

### ISSUE THREAD

**Issue by Remerod** [jj248/RealmsInExile#453]
# Introduction
So this idea sprung to me based on some buildings in LOTR: Rise to War and the Golden Army system in MERP. The Idea is basically giving the Golden realm Battle Arenas where Dragon knigts can shine and develop. 

### Background
**LOTR:Rise to War**
So LOTR:Rise to War have a place that really look like a Coliseum, yet is a market for some reason? Wtf is that based on, a American shopping mall? Anyway I really like the style of it and it gave me the idea a arena like building would fit the Rhûn easterlings, seeing as they where warlike tribes which went into warlike civilization/Army with a state if we go with the Golden Realm rule.
 
![image](https://user-images.githubusercontent.com/79544635/181786377-6994f2da-dcf2-4a7f-8168-a10f5b46f7b3.png)
 
**MERP the Golden Army**
The Golden Army, Great Eastern Army, Glittering Host or Lôke-Rim, in lore are mainly controlled by two orders - he [War-Priests](https://notionclubarchives.fandom.com/wiki/War-Priests) and the [Dragon-Knights](https://notionclubarchives.fandom.com/wiki/Dragon-Knights), Which is both ruled by a supreme ruler the Lôke-Kân in MERP lore. 

So The Dragon Knights were the epitome of the [Easterling](https://notionclubarchives.fandom.com/wiki/Easterling) warrior castes, having honed their skills beyond the ken of ordinary men. Their proficiency with a blade was unparalleled, making them excellent warriors to lead the Easterlings into battle.

So are all of these knights of the same class/caste/status?  We do know that the [Lôke-Innas Rim](https://notionclubarchives.fandom.com/wiki/L%C3%B4ke-Innas_Rim) very the greatest of the Dragon Knights.

And people like [Amdûr the Lord of Blades](https://notionclubarchives.fandom.com/wiki/Amd%C3%BBr), [Baisheuin](https://notionclubarchives.fandom.com/wiki/Baisheuin) & [Warlog](https://notionclubarchives.fandom.com/wiki/Warlog) whom mainly are from 
[Middle-Earth Strategy Battle Game - Games Workshop](https://middle-earthstrategybattlegame.com/) seems to have “risen” in their ranks to prominence in their lore.

### The Idea
So my idea is to have special-flavoured Buildings for the golden realm that would be some sort of Arena, where we would implement maybe a system like ck2 battle societies, where the Golden Army Dragon Knights would fight and rise in rank. I also hope we could tie this to the special Dragon realm UI- mechanic to keep the realm together. Like it would be cool that you would need to be a Dragon Knight to even be liable to be a successor of the Golden realm. 

**The Arena**
So the Arena would be a building in your county capital which would allow you to hold a Arena match/tournament Decision. It would start a event where several champions could fight several matches with ultimately one winner, not all that partake needs to die but it could be cool if some did. And maybe this would be a way to recruit Dragon Knight to your court. You as the ruler could either participate, or maybe you could only participate if your liege holds such an event? It could actually be cool if we disabled recruit knights/champions so that the golden realm would be reliant on this system. 

**The ranking & Hierarchy in the Golden realm**
So maybe we could make a ranking system for the Dragon Knights with 3-5 ranks and where you need to be either one of these or the top of these ranks to be able to inherit the golden realm and take certain council positions.

This I feel would enforce the Golden Army theme, in that it’s not a normal empire, it would also help killing characters off, which would give it a more dynamic internal political system. And I feel this could work well with the “keeping the Golden Realm together” mechanic we’re developing, maybe holding Arena matches is one of the things that holds the realm together, as people would come to spectate. Maybe if your weak a unlanded character that’s a Dragon Knight could challenge your rule within the laws of the golden realm.

### Conclusion
I don’t think this Arena & Dragon Knight system would make the game unbalanced or anything and it would greatly help make the Golden realm together with the “keeping the Golden Realm together” mechanic a very different & thematic compared to the other realms. And while maybe this is not super based on the lore I still think it would fit in as it does not go against it, the easterlings where warlike tribes which went into warlike civilization, having Battle Arena matches in such societies makes sense to me.

**Comment by Remerod** [comment]
So after a discussion with Vector on discord we've agreed to move away from the Dragon-knight aspect and rather do it then as a event in these Arenas/coliseums where new warriors prove their mettle (which could give negative or positive modifiers to levies depending on the result), making it a warrior culture flavor thing and for already proven warriors to seek status/honour and these is how you recruit your champions/(normal knights) and maybe once in a while there could be a big realm wide tournament(like normal knight tournaments). Dividing it up it to be small local arenas and big realm wide ones

And it would be cool if it would be expected of the nobility themselves or when their young comes of age to participate, but as you say maybe that could be a cultural tradition thing

**Comment by Remerod** [comment]
# Some New thoughts
So after our discussion i've trued to fine tune what the event should be about, the mechanics and the flavor.

### Inspirations:
Adopted from the earlier Etruscans, perhaps by way of Campania, gladiatorial games (munera) originated in the rites of sacrifice due the spirits of the dead and the need to propitiate them with offerings of blood. They were introduced to Rome in 264 BC, when the sons of Junius Brutus honored their father by matching three pairs of gladiators. Traditionally, munera were the obligatory funerary offerings owed aristocratic men at their death, although the games did not have to be presented then. Elected aedile in 65 BC, Julius Caesar commemorated his father, who had died twenty years before, with a display of 320 pairs of gladiators in silvered armor (Pliny, XXXIII.53: Plutarch, V.9). Still mindful of [Spartacus'](https://penelope.uchicago.edu/~grout/encyclopaedia_romana/gladiators/spartacus.html) rebellion, a nervous Senate limited the number of gladiators allowed in Rome (Suetonius, X.2). In 46 BC, after recent victories in Gaul and Egypt, Caesar again hosted elaborate games at the tomb of his daughter Julia, who had died in childbirth eight years earlier (together with stage plays and beast fights, they included the first appearance of a [giraffe](https://penelope.uchicago.edu/~grout/encyclopaedia_romana/gladiators/giraffe.html)). The display was criticized, however, for its extravagance and the number slain, including several of Caesar's own soldiers, who protested that none of the money was being allotted to them (Dio, XLIII.24).

So while the gladiatorial amphitheaters are an inspiration those who participate would be less as "gladiators" but more as warriors trying to prove themselves to be knights/champions so in a sense this would be more similar to minor knight tournaments, but whit's it's own flavor spin onto it, but that aren't to strange, battle arenas are a pretty common troupe in fiction. 

So either way, Hopeful we could build a story similar to how the gladiator one but tying it to rhûn and maybe even have it pre-Kesserak faith. 

### Tradition based. - (Need Name, well the entire "battle arena" theme need a better name)
The tradition will depict that these culture have lived in a war like society for long where the strong are the most respected ones

### Buildings. 
The tradition will enable a special building type, the Arenas, which will have different tiers, allow for more warriors joining the event and some military boost to armies.

### Enables through decision.
So to get to use the arena and gain warriors you would need to enable it through a decision

Stuff that enabled the “type” of arena/tier of event
-tribal/no building – available through tradition
-building lowest tier requirement
-building highest tier requirement.
-special locations, either holy sites or special buildings.

### Flavour for the events
* Generic arena flavor - for standard arena stuff
* Golden realm flavor - for standard arena stuff, is enabled if & inside the golden realm if it exist
*Special realm event(like a tournament) where all can participate in (takes place in a special locations, either holy sites or special buildings, and if none of these are available, the top liege’s capital).


### Who can participate?
-the player/enabler of the decision
-vassals and courtiers (if vassal you can get invited to your lords event)
-friends, guests & lovers

-Two special orders(dragon knights & priests), they might help sponsors the event but might try to recruit the victors to themselves, which might robe you of the better warriors
The Dragon order will be represented as an theocracy (for now) so maybe for now it’s not possible for both the Dragon Knights and the Dragon Priest to be represented, but when we can we should try to have both present trying to recruit the victors for themselves. And in the future we could have the dragon priest be represented by the clergy while the Dragon Knights is represented by something else. 

But let it be noted that the (dragon knights & priests) is the least important thing to get right, as it will mainly be a flavour thing + a hurdle in getting your champions/knights

### The Mechanic 
Instead of a recruit champions decision the cultures with this tradition will be enabled to recruit warriors from an arena/proving ground fight. The one enabling the event will have to “host” the occasion. Different condition will leave to mediocre to more grand events. Several new character will span and some existing people are allowed to join the occasion. There would be 1-3 “winners” of the event whom you could choice one from, other character might also want to gain some of the victors(maybe there will be some bidding, but maybe not- the host should get the first option to choice and in worst case an option might pop up where other characters ask to host to get the warrior/victor).

* hosting the event, should be a short event chain before the arena start, deciding the factors/condition that should take place.
-the host should choice a place where the arena commence 

* characters that help Hosts, the main host can get vassals, friends and others to help co-host the event, these characters will then also be able to choice some warriors from the victors and might ask for those, if you say no you might get a negative modifier or something similar, I also hope to enable 2 orders that want to help sponsor stuff.

* For the fight themselves will be shorter ai versions of the duel(unless you play yourself?) and or maybe take inspiration from the vanilla Chariot racing blue & red team event. 
This generally describes the base mechanic, but there should also be a special “tournament” decision which (maybe) all characters of the realm are affected by. 

* “Maybe” there should be some kind of Hierarchy/ranking mechanic, which gives better warriors depending on what rank they have in the arena system. Like low tier building would give low rank warriors, while high tier building would allow for higher tier warriors to combat. And people can rise (or die) in this ranking system. But this might maybe make it unnecessarily complicated. If we do it though, we could make it so that the highest ranked warriors are the only ones allowed to participate in the “tournament” event 

### Gains
So what will you gain by doing this flavor decision? 
-Warriors, characters who’ll that can join your ranks of champions/knights
-(Maybe) army boosts, the event can represent that some of the people participating in the arena could boost your army.
-Piety, the tradition makes it so that people want these kind of event to take place and see them as “religious events” 
-If the host have a prestigious event then people who participate in the audience will get opinion boost of you

**Comment by Remerod** [comment]
Scope of the recruitment/battle mechanic

level 1 Arena activity - no building
You hold a local fighting skirmish looking for champions among your ranks, invite no others. around 4 combatants

level 2 Arena activity -Battle Arena 1
You hold a "battle arena" looking for champions among your ranks (and new spawned ones), family and friends can join. around 6 combatants

level 3 Arena activity - Battle Arena 2
You hold a "battle arena" looking for champions among your and your vassals ranks (and new spawned ones), a small  amount of vassal, family and friends can join. around 8 combatants

level 4 Arena activity - Battle Arena 3
You hold a "battle arena" looking for champions among your and your vassals ranks (and new spawned ones), a bigger amount of vassal, family and friends join. around 10 combatants

**Comment by jj248** [comment]
Suggest we park this until at least v4.

**Comment by Jaco-Daan** [comment]
Since no one is working on this and this issue is kinda defunct, closing
