### ISSUE TITLE
Suggestion: Tolfalas expansion

### ISSUE THREAD

**Issue by Kyrenic** [jj248/RealmsInExile#455]
In this expansion I plan to add the following things to the island of Tolfalas:
- Rename Toltir to Dol Aerrochben.
- Rename Hithugarth to Nen Gilros.
- Rename Gilros to Moorlands.
- Rename Uphar to Tol Aduial.
- Special building in Caras Tolfalas called something along the lines of "Port of Caras Tolfalas".
- Special building in Dol Aerrochben called something along the lines of "Watch at Dol Aerrochben".
- Decision to develop the island and tame the wilderness, which would give extra development.
- Lower the starting development from 14 and 12 to 4 and 3.
- Reduce amount of starting buildings.
- Reduce starting level of the holdings.
- Add level 1 trade port in Caras Tolfalas.

### Dol Aerrochben (Currently Toltir)
Dol Aerrochben was home to a fortification that housed the Master of the Straits, a royal officer responsible for guiding ships through the nearby narrow straits. It was also the link to the mainland, ferrying post and runners to the mainland. A few miles northeast of Dol Aerrochben stood a great beacon, acting as a lighthouse to passing ships in the night. At the summit of Dol Aerrochben stood the Twin Towers, two commanding towers of which little is known of their function, apart from that it housed the Master of the Strait

The facilities were abandoned in T.A. 2050, only being reestablished again in F.A. 52, after the start of the game.

I think four buildings would suffice in Dol Aerrochben:
- Ruins of Dol Aerrochben
- Beacon of Dol Aerrochben
- Twin Towers of Dol Aerrochben
- Dol Aerrochben: Master of the Straits

### Caras Tolfalas (Gobel Tolfalas)
Caras Tolfalas was a major harbor in the time of the ship-kings, being one of the major military harbors guarding against corsairs from the south. In ancient times, the seat of the warden of Tolfalas was situated here, and major harbor fortifications were also present.

Caras Tolfalas was abandoned by T.A. 2471, and after that it was used as a temporary base of operations by the corsairs and Harûze, but neither established a permanent presence on the island. The town was wholly restored in F.A. 52, after the start of the game.

I think three buildings will suffice here:
- Ruins of Caras Tolfalas
- Lond Tolfalas
- Gobel Tolfalas: Seat of the Warden

**Comment by Remerod** [comment]
It would be helpful to have some backstory/research on the things that you want to add. Is it based on anything lotr lore related and if not does it take inspiration on anything else? It's always a good idea to mention these things when proposing adding new content

**Comment by Kyrenic** [comment]
Alright, will edit the issue to add these when I've got some time

**Comment by Remerod** [comment]
For instance Caras Tolfalas has 3 names
* Caras Tolfalas ([S](https://notionclubarchives.fandom.com/wiki/Sindarin). "City [of] Tolfalas")
* Lond Tolfalas (S. "Haven [of] Tolfalas")
* Gobel Tolfalas (S. "Fort [of] Tolfalas")
Taken from [Caras Tolfalas](https://notionclubarchives.fandom.com/wiki/Caras_Tolfalas) so maybe this port special building would better be called Lond Tolfalas?

Doing or asking help with people on research/lore is always good and one of the reason why doing issues like this is a good idea ;)

**Comment by Remerod** [comment]
I would recommend reading some of these;
**MERP Sea-lords of Gondor chapter 13. Tolfalas** found [here](https://drive.google.com/drive/folders/1FXb75Mrz2Zsz7ijJXykR--uvvnOtDx8Y)
Maybe **MERP Heavens of Gondor** while it's not about Tolfalas it's about the heavens of gondor and will give insight on the culture/themes of the area. can also be found in the above link [here](https://drive.google.com/drive/folders/1FXb75Mrz2Zsz7ijJXykR--uvvnOtDx8Y)
**Notionvlub Archives:** [Caras Tolfalas](https://notionclubarchives.fandom.com/wiki/Caras_Tolfalas) & [Tolfalas](https://notionclubarchives.fandom.com/wiki/Tolfalas) 
**TolkienGateway:**  [Tolfalas](https://tolkiengateway.net/wiki/Tolfalas)

Most if not all of these sources can be found on our internal wiki [Available-Lore-Sources](https://github.com/MattTheLegoman/RealmsInExile/wiki/Available-Lore-Sources)

Do note though that not all of these lore's does necessarily fit into our "Realm" lore and having a chat every now and then with our "Loremaster" Vector is a good idea! At least after you've planned something together to see if it fits in the mod

**Comment by Remerod** [comment]
> Alright, will edit the issue to add these when I've got some time

Am looking forward to hear your ideas on Uphar & Toltir

**Comment by Kyrenic** [comment]
Toltir will likely become Dol Aerrochben and Uphar will likely become Tol Aduial, still working the research. Do I edit the issue with new research or post it as a comment?

**Comment by Remerod** [comment]
> Toltir will likely become Dol Aerrochben and Uphar will likely become Tol Aduial, still working the research. Do I edit the issue with new research or post it as a comment?

which ever you prefer. I edit a lot myself. But it's always good to keep records

**Comment by Kyrenic** [comment]
It keeps automatic records in the edits dropdown right?

**Comment by Remerod** [comment]
i'm uncertain

**Comment by jj248** [comment]
Weirdly niche and disproportionately complex for such a small area.  Closing.
