### ISSUE TITLE
New borders and baronies for Tolfalas

### ISSUE THREAD

**Issue by Remerod** [jj248/RealmsInExile#456]
# Introduction
So there was some talk and an Issue https://github.com/MattTheLegoman/RealmsInExile/issues/455 on Tolfaras  and that made me want to read into it a bit, and it made want more for it as it seems we are lacking certain aspects of the lore for it! And this issue is just for that! 

### Maps
Here are some maps i've been using to research my proposal
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/182048953-ce083dfb-2a60-45b6-b620-d8d7eb72890e.png)
Lindëfirion map

![image](https://user-images.githubusercontent.com/79544635/182048977-008d55e2-e1db-42d2-b938-673efd86494e.png)
MERP map

![image](https://user-images.githubusercontent.com/79544635/182048985-fb605f67-e101-4528-9a75-671bc1dea551.png)
Our Current Realm Map, 2 counties with 7 baronies in it

![image](https://user-images.githubusercontent.com/79544635/182049093-63c53683-0e06-4dc2-a2d7-09935f84a8a6.png)
I'm not sure where this is from, but it's found on [NotionClubArchives Tolfalas](https://notionclubarchives.fandom.com/wiki/Tolfalas?file=Tolfalas.jpg) I think it would be interesting to have a more dynamic mountain ranges on Tolfaras as it is described as a volcanic, harsh and an inhospitable place! 

</details>

# Proposal
So my proposal will change some barony locations, add some new baronies and add a county 
### Proposed Map changes
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/182048279-eea2c046-89cb-4f7c-b3b3-fce5b2edb885.png)
Light Green - more forest jamie!!!
Brown - a little more mountainous

</details>

So my idea expands a bit on the already existing baronies, moves them around and add a new county! Which i was hoping we could make into a wilderness! As much of Tolfaras is described as such, but i thought it could be fun to have a colonizable colony here, since the lore supports it

**Blue** county of _Fortolfaras_. Currently Toltir is the main barony, i propose that either Nen Gilros who is lorewise known as a settlement with people to be the new main barony or possible either Dol Aerrochben or Bardin Iaur
1.  [Nen Gilros](https://notionclubarchives.fandom.com/wiki/Nen_Gilros) ([S](https://notionclubarchives.fandom.com/wiki/Sindarin). "Star-spray Water") in our mod it is on the western shore, but it's always described to be part of the east coast as far as i can read. So i propose we rightfully move it there! 
2. [Bardin Iaur](https://notionclubarchives.fandom.com/wiki/Bar_Iaur_D%C3%ADnen) this would replace Toltir, who i am not certain what's it's based on? And for the barony to be slightly moved a bit down. Bardin Iaur is both placed on the MERP & Lindëfirion map. The manor is described an a keep the soldiers under the warden in Caras Tolfalas would use sometimes
3. [Nenmarros](https://notionclubarchives.fandom.com/wiki/Nenmarros) so for some reason our mod have places Nen Gilros(or rather just gilros) here, when it supposed to be on the eastern coast. Nenmarros was built by the [Númenóreans](https://notionclubarchives.fandom.com/wiki/N%C3%BAmen%C3%B3reans) in the [Second Age](https://notionclubarchives.fandom.com/wiki/Second_Age) as an extra [fort](https://notionclubarchives.fandom.com/wiki/Fort) to guard the [Bay of Belfalas](https://notionclubarchives.fandom.com/wiki/Bay_of_Belfalas) and the entrance to the [Anduin](https://notionclubarchives.fandom.com/wiki/Anduin) But was later abandon. But the numenorean masonry has preserved much of the ravage of time. 
4. [Dol Aerrochben](https://notionclubarchives.fandom.com/wiki/Dol_Aerrochben) (S. "Hill of the Sea-knight") was an islet off the northeastern tip of [Tolfalas](https://notionclubarchives.fandom.com/wiki/Tolfalas). This islet possessed a fortification that housed the Master of the Straits, the royal officer responsible for guiding ships through the nearby narrows. Adding this barony might mean that we need to make the islet slightly bigger

**Red** _Hartolfaras_
1. [Caras Tolfalas](https://notionclubarchives.fandom.com/wiki/Caras_Tolfalas) fine where it is
2. Alôra already in the mod, i dunno where the name comes from but on the Lindëfirion map the settlement is located west of the river rather then east, so moved it a bit
3. [Tol Aduial](https://notionclubarchives.fandom.com/wiki/Tol_Aduial_(Tolfalas)) Already in the Mod but called Uphar, The isle even have it's own map, form a MERP module i believe (look bellow)
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/182047834-4cf427fb-15ac-4ee6-9474-e3b0f8d2324a.png)
Tol Aduial (S. Dusk Isle)

</details>

**Dark Green** - Wilderness of Western Tolfalas. I dunno a good name for it, but i'm sure we'd come up with one with no problem!
>Aearîfram - sea-cliff-wall, based on your description of it having high shear cliffs

-proved by Vector
1. Based on MERP map, there is a Tower/beacon here, and thus could serve as a potential barony. No name i can find though.
> Airnarthan is 'lonely beacon'

-Proposed by Vector
2. Tol Daur is the island just of the west-coast of Tolfalas, it's named as such on the Lindëfirion map and seems like a good place to place a Barony
3. Eithor, already in the Mod, dunno where the names from but could potentially be moved a bit down as shown in my proposal?

Also as some maps above show it wouldn't hurt to add some more forests and rugged mountainous ridges alongside the map! It also mentions studded with black cliffs and a steep series of foreboding peaks, So having some inaccessible shores would be nice to show this! maybe specifically on the more desolate westerns side! I think it would make the place a lot cooler!

# Conclusion
While i don't think Tolfaras is definitely bad currently or anything, it is a very interesting area. Adding some more (secondary) lore friendly areas would make it more interesting, also adding a western wilderness area to it i feel would ad a whole new dynamic to the area!  I see these changes as a improvement on the isle and one we can afford to make for 3.0!

**Comment by VectorMaximus** [comment]
I have no major objections to the changes proposed here. Not a personal high priority, so don't know when we'll get around to it, but certainly worth adding to the list! The Dunedain holy site of [Imrazôr's Hallow] (https://notionclubarchives.fandom.com/wiki/Imraz%C3%B4r's_Hallow) will resultingly be in [Nenmarros](https://notionclubarchives.fandom.com/wiki/Nenmarros), as will its accompanying wonder.

**Comment by Remerod** [comment]
> I have no major objections to the changes proposed here. Not a personal high priority, so don't know when we'll get around to it, but certainly worth adding to the list! The Dunedain holy site of [Imrazôr's Hallow](https://notionclubarchives.fandom.com/wiki/Imraz%C3%B4r's_Hallow) will resultingly be in [Nenmarros](https://notionclubarchives.fandom.com/wiki/Nenmarros), as will its accompanying wonder.

Oh i agree with the [Imrazôr's Hallow](https://notionclubarchives.fandom.com/wiki/Imraz%C3%B4r's_Hallow) ! and yes I agree that it is not a top priority, It's mainly something for the later stages of our Development on 3.0 if there is time :)

**Comment by Remerod** [comment]
This is just a side note, and i am not saying we should make this a special works! But we could add a small map object and Make a new Drûghic Holy Site. So i am basing this on [Caichail Pûchel](https://notionclubarchives.fandom.com/wiki/Caichail_P%C3%BBchel) It's a potential holy ruin atop a mountain, we could make the barony of [Nenmarros](https://notionclubarchives.fandom.com/wiki/Nenmarros) the holy site and maybe add a small Egyptian pyramid on a mountain top as seen in the pictures bellow 
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/182050758-925e1f12-5911-4811-b77c-4f82c178eaaa.png)
I believe this is [Caichail Pûchel](https://notionclubarchives.fandom.com/wiki/Caichail_P%C3%BBchel)

![image](https://user-images.githubusercontent.com/79544635/182050778-0e4b3d07-213d-4922-861e-17d1c8082477.png)
picture over the mountain and structure and a Caichail-puckel man

![image](https://user-images.githubusercontent.com/79544635/182050800-e36452f2-6b10-4ed8-b3cc-07595e29b54a.png)
Overview of Caichail puchel

</details>

I think it could be fun for our Drûedain players to have something to aim for! Heck why not even make it a Honnin holy site :P 
But again, this is just a very minor suggestion to my overall issue

**Comment by Remerod** [comment]
Seems most folks are ok with this, so i am moving it from a suggestion to a non-release critical!

**Comment by jj248** [comment]
This feels disproportionate to me.  @VectorMaximus - thoughts?  Feels to me like what we have is just fine.

**Comment by Remerod** [comment]
i don't understand, we talked about this in a VC like half a year ago Jamie and then you seemed up for it?

**Comment by Remerod** [comment]
this would also be a good issue for anyone wanting to try mapping, as it is a small thing. As i know a couple of people have been asking to do

**Comment by Jaco-Daan** [comment]
Closing, since this is clearly a defunct issue. Tolfalas isn't supposed to be a major area (it's even supposed to be largely abandoned IIRC), closing
