### ISSUE TITLE
Galadriel's Mirror 3D asset is bugged

### ISSUE THREAD

**Issue by BriceLeduc** [jj248/RealmsInExile#458]
Galadriel's Mirror 3D asset does not show in court, there's something wrong with the file.

**Comment by jj248** [comment]
Ditto this one @MattTheLegoman - I'm at the limit of what I can do.  The model looks just fine and dandy in Blender: 
![image](https://user-images.githubusercontent.com/26043074/213154213-0030eed8-f9b9-4521-ae3c-cab4cc5228c3.png)
