### ISSUE TITLE
Decision to remove Orc buildings.

### ISSUE THREAD

**Issue by Kyrenic** [jj248/RealmsInExile#468]
Currently, it's very hard to remove Orc buildings, as the AI tends not to replace them. It's a very expensive, both money, time and realm integrity wise since you have to directly own the counties and baronies to be able to replace buildings.

### Decision
The benefits of a decision are:
- Easier to make
- No GUI editing required

### Button
The benefits of a button are:
- Looks better
- Able to decide per barony

**Comment by JukeJukestar** [comment]
Notes I'd like to add

- shouldnt be avaiable immediately after conquest so the orcs have a chance to retake their lands
- should require not having an orc liege or top liege
- could require the county not to have orcish culture so you have to convert it first or "free the populace"
- could require a minimum of 95 control to represent the free peoples establishing themselves
- should factor in nazgul, maia and istari holding orc holdings without wanting to replace them
- could add a modifier that makes buildings cheaper for a decade or so
- could remove development

**Comment by Remerod** [comment]
I think this is something we should deal with, so i'll move this to non-release critical

(i'll do say that one way to solve this is if non-evil people who conquers evil counties raze them and make them into wilderness, or razed then instantly colonized lands)

**Comment by Jaco-Daan** [comment]
This has been dealt with. Seems that the AI weighting was screwed and has been fixed. Closing
