### ISSUE TITLE
Suggestion: Add an extra character stat called "Willpower"

### ISSUE THREAD

**Issue by Kyrenic** [jj248/RealmsInExile#472]
I think willpower is a major factor in Lord of the Rings lore, and it being represented sort of like prowess, not that influential but still there would be very cool. It would require us to rewrite a lot of stuff to properly integrate it though. Just an idea, let me know what y'all think!

**Comment by Remerod** [comment]
I get what you mean but Isn't like.. Learning representing this or could be. I duuno what to think, you have given no sugestion or example of how this would work in the game

**Comment by JukeJukestar** [comment]
Closing this for now, if we ever want to implement this I suggest a suggestion thread
