### ISSUE TITLE
Gondorian cultures expansion and rebalance

### ISSUE THREAD

**Issue by Gideones** [jj248/RealmsInExile#484]
**Premise**

_Sources used: New Notion Club Archives, Tolkien Gateway, MERP #2020 Southern Gondor: The People_

While Gondor is one monolith block (except Belfalas and Ithilien) in terms of culture, the question is “why Daen people of Gondor are not represented?” arise. Accepting the idea that the main part of Daen are integrated and intermixed with Dunedain, it’s better to admit that some of them are not intermixed (using as source MERP Southern Gondor The People) due to gameplay reasons.
Main goal of this suggestion is interesting gameplay and standardization and unification of Gondorian cultures. 
According to this suggestion, Gondorian culture is represented by tradition “Legacy of the South-Kingdom” which gives MAAs, Numenorean architecture innovation and greatly reduced opinion penalty for Mende Anduya marriage, while Mende Anduya tradition represents direct heritage and association with Dunedain.
Main Gondorian culture is represented by “Gondorian” culture - people who are direct descendants of Dunedain and which absorbed local cultures to the point that people accept themselves as Numenorean descendants. Local cultures represent intermixed heritages greatly affected by Daen with their own specific MAAs and bonuses.

Suggested cultures:
1. Gondorians - as it was said above, main Gondorian culture, which represents Dunedain-based culture.
2. Amronost - Sindarin speaking Gondorians.
3. Belfalathrim - Gondorians intermixed with coastal folk in the Belfalas region.
4. Ithilwaith - Gondorians intermixed with Northerners and Daen, separated from the Gondorian proper culture due to the advance of Mordor’s forces (100 years ago - until that were not very distinct from Gondorians proper).
5. Harondorim - Intermixed with Daen and Haruze culture, formed 200 years after establishment of Harondor province (T.A.1050)
6. Orodbedhrim - Dunedain influenced Daen culture. Mainly presented in the Western part of Gondor, but the enclave exists in Belfalas.

Changes in gameplay are affecting creating helpful tooltips and connection of innovations with traditions, also rebalance of Gondorian roster (and with this gameplay).
The Gondorian roster is blocked from getting generic bowmen, armored footmen, spearmen and cavalry, instead having their own improved costly variants, which represent that the Gondorian military is not the same as other Men military and more advanced one. 
Local cultures have their own additional variants which allow local cultures to form specific rosters:
1. Gondorian roster - Armored footmen have the improved variant, spearmen and archers are replaced to more advanced variants too (main point is increased toughness and screen which represents heavy armor). Gondorians also can’t recruit light cavalry, which represents their focus on infantry. Heavy cavalry is costly, but can be recruited.
2. Belfalas roster - Belfalas peninsula has access to elite heavy cavalry and “medium” cavalry, which allow to form a more cavalry oriented roster.
3. Ithilien roster - rebalanced rangers which can be recruited if Gondorian character holds Ithilien county.
4. Harondor roster - improved skirmishers and access to light cavalry, which represents mobile forces which are needed in this stretched region.
5. Orodbedhrim roster - give cheap medium-quality variants of skirmishers and archers. As a drawback, Orodbedhrim characters can’t recruit cavalry, representing lack of pastroal lands in mountains. Gondorian characters can recruit Orodbedhric units freely, expanding roster by use of cheap infantry.

**Changes:**

<details>
<summary>Changes in Innovations - DONE</summary>

1. Numenorean Architecture and Ancient Numenorean Architecture haven’t tooltips, it’s not understandable what they are even doing. Should add tooltips.
2. To connect Numenorean architecture and gameplay - Legacy of Southern Kingdom should give access to Numenorean Architecture while Mende Anduya should give access to both Numenorean Architecture and Ancient Numenorean Architecture. This represents that local gondorian cultures are not descendants of Dunedain and can’t build their advanced structures, while direct Dunedain descendants can build them.

</details>

<details>
<summary>Changes in Traditions and MAA - DONE</summary>

**Legacy of the South-Kingdom:**
- Changes in MAA:
  - Gondorian Footmen - heavy armored infantry:
    - Size: 100 (recruited 5)
    - Type: Heavy Infantry
    - Damage: 35
    - Toughness: 28
    - Screen: 12
    - Counters Skirmishers (0,5), Spearmen
    - Terrain effects: 
      - Farmlands: Toughness 8
    - Cost: 100 for creation, 0.45 low maintenance
    - Description: Clad in heavy armor, common foot soldiers of Gondor are considered to be one of the best warriors of Men due to their discipline and determination.
  - Gondorian Spearmen - heavy armored spearmen:
    - Size: 100 (recruited 5)
    - Type: Spearmen
    - Damage: 26
    - Toughness: 28
    - Screen: 10
    - Counters Light Cavalry, Heavy Cavalry, Monster
    - Terrain effects: 
      - Pikemen effects
      - Farmlands: Toughness 8
    - Cost: 100 for creation, 0.40 low maintenance
    - Description: Armored spearmen of Gondor are equipped with long spears about nine feet long and form the backbone of the modern Gondorian military.
  - Gondorian Bowmen - heavy armored archers:
    - Size: 100 (recruited 5)
    - Type: Archers
    - Damage: 26
    - Toughness: 18
    - Screen: 8
    - Counters Skirmishers
    - Terrain effects:
      - Hills: Damage 8, Toughness 4
      - Plains: Damage 10
      - Farmlands: Toughness 8
    - Cost: 80 for creation, 0.35 low maintenance
    - Description: Equipped with heavy armor and heartwood longbows, wearing quivers on their hips, Gondorian bowmen are considered to be an elite among the archers of Men.
  - Gondorian Horsemen - heavy armored costly cavalry (represents small numbers):
    - Size: 50 (recruited 5)
    - Type: Heavy Cavalry
    - Damage: 112
    - Toughness: 40
    - Pursuit: 16
    - Screen: 12
    - Counters Archers, Skirmishers (0,5)
    - Terrain effects:
      - Armored Horsemen effects
      - Farmlands: Toughness 15
    - Cost: 250 for creation, 0.95 low maintenance
    - Description: Traditionally few in numbers, the Gondorian cavalry is composed of experienced horsemen armed with the finest weapons and armor.
  - Gondorian Marines - good armored skirmishers:
    - Size: 100 (recruited 5)
    - Type: Skirmishers
    - Damage: 19
    - Toughness: 22
    - Screen: 12
    - Counters Heavy Infantry, Spearmen
    - Terrain effects: 
      - Hills: Damage 4, Toughness 6
      - Plans: Damage 4, Toughness 6
      - Farmlands: Damage 6, Toughness 8
    - Cost: 85 for creation, 0.40 low maintenance
    - Description: Lightly armored soldiers accustomed to fighting against corsairs, these warriors form the backbone of the Gondorian coastal levies.
    - Special note: Can be recruited only in coastal holdings.
  - Armored Footmen, Pikemen, Bowmen, Crossbowmen, Light Horsemen and Armored Horsemen can’t be recruited - this creates a situation where Gondor relies on its heavy armored soldiers in the first place, and has limited access to cavalry. At the same time, most of Gondor’s enemies are relying on skirmishers and monsters, which allows Gondor to counter them. Main part of troops is replaced by more advanced but costly variants, which at same time has lowered cost due to the effect of traditions. That creates the effect of the most advanced military in Middle-Earth. Crossbowmen are removed for balance purposes - making heavy armored units the hardest enemies of the Gondorian military. Gondorian marines provide good skirmishers in coastal holdings, which is mainly flavor at this point and they can be freely removed. Terrain bonus in farmlands represents acustoming of Gondorians with civilized terrain and gives bonus in defending their own inhabitant lands. 
  - Present types of Gondorian MAA (Fountain Guards for every Gondorian ruler, Gondorian rangers etc.) are removed. Reasons are: Gondorian rangers are not common military and the main part of TA gondorian rangers serves in Ithilien. Fountain Guards, while presented as units in most of Middle-Earth games, is pretty stupid unit - guys shouldn’t leave Minas Tirith without great need and their numbers should be limited to point of them being represented as order.
- Legacy of the South-Kingdom is a core tradition of all Gondorian cultures (it’s what makes them Gondorian in the first place) and as such any Gondorian culture (Belfalathrim, Ithilien etc.) have this tradition. This is the main point of rationalization of Gondorian cultures.
- Add effect - no cultural acceptance penalties in baronies with culture with the same tradition. Can’t convert cultures with the same tradition too. Reduces Mende Anduya mariage acceptance modifiers towards this heritage (instead of -75 gives -25).

**Ithilien Subterfuge:**
- Changes in MAA:
  - Rangers of Ithilien:
    - Size: 50 (recruited 5)
    - Type: Archers
    - Damage: 62
    - Toughness: 8
    - Pursuit: 16
    - Screen: 28
    - Counters Archers, Skirmishes, Monsters (0,5)
    - Terrain effects: 
      - Hills - as present 
      - Forest - as present
      - Farmlands: Toughness 8, Screen -10
    - Cost: 100 for creation, 0.55 low maintenance
    - Description: Dressed in camouflaging green and brown and fighting chiefly by stealth, the Rangers of Ithilien are experts in waging guerrilla war.
  - Gondorian Soldiers are removed.
  - Ithilien rangers are rebalanced from OP to a more logical variant - by reducing their numbers, and have a pretty big cost for maintenance (just imagine supply routes to their hideouts). Gondorian soldiers are removed because of rationalization.
  - Special note: Ithilien rangers can be recruited if the character holds a county with Ithilien culture, not only by characters of Ithilien culture.
- Gives bonus to all Ithilien characters: Supply Capacity +50%

**Belfalathrim Chivalry:**
- Changes in MAA:
  - Swan-Knights:
    - Size: 50 (recruited 5)
    - Type: Heavy Cavalry
    - Damage: 140
    - Toughness: 50
    - Pursuit: 32
    - Screen: 24
    - Counters Skirmishers, Archers, Monsters
    - Terrain effects:
      - Armored Horsemen effects
      - Farmlands: Damage 20, Toughness 20
    - Cost: 300 for creation, 1.20 low maintenance
    - Description: Nobles of Numenorean origin, these elite knights on huge gray warhorses are the finest horsemen of Gondor, famed for their courtesy and martial skills.
  - Belfalathrim Horsemen - very costly “medium” cavalry:
    - Size: 50 (recruited 5)
    - Type: Light Cavalry
    - Damage: 48
    - Toughness: 36
    - Pursuit: 28
    - Screen: 26
    - Counters Archers, Skirmishers
    - Terrain effects: 
      - Light Cavalry effects
      - Farmlands: Damage 8, Toughness 12
    - Cost: 200 for creation, 0.75 low maintenance
    - Description: Esquires and knights originating from the Belfalas peninsula are famous for their courtesy and riding skills and compose the main part of the Gondorian cavalry.
  - Amrothian Archers and Amrothian Pikemen are removed due to rationalization and gameplay. Archers and Pikemen are represented by standard Gondorian Archers and Pikemen.
  - Belfalathrim Horsemen can be recruited by characters of all Gondorian cultures who hold lands with such cultural tradition.
  - Overall Belfalas region has access to improved cavalry, which makes their MAAs very balanced. As a countermeasure, their cavalry is very costly.

**Harondor Resilience:**

- Changes in MAA:
  - Harondorim Footmen - good dryland-oriented skirmishers:
    - Size: 100 (recruited 5)
    - Type: Skirmishers
    - Damage: 17
    - Toughness: 22
    - Pursuit: 10
    - Screen: 16
    - Counters Spearmen
    - Terrain effects: 
      - Light Footmen effects
      - Hills: Damage 4, Toughness 6
      - Drylands: Damage 10, Toughness 12
      - Desert: Damage 6, Toughness 8
    - Cost: 65 for creation, 0.35 low maintenance
    - Description: The lightly armored warriors of Harondor bear the duality of their origins - they are armed in the manner of the Haruze and prefer hit and run tactics, but retain the discipline of the Dunedain.
  - Harondorim Horsemen - good dryland-oriented light cavalry:
    - Size: 100 (recruited 5)
    - Type: Light Cavalry
    - Damage: 26
    - Toughness: 21
    - Pursuit: 35
    - Screen: 40
    - Counters Archers (0,5), Skirmishers
    - Terrain effects: 
      - Light Horsemen effects
      - Drylands (instead of light horsemen effect): Damage 20, Toughness 10
      - Desert: Damage 10
    - Cost: 100 for creation, 0.50 low maintenance
    - Description: Accustomed to harsh conditions of Harondor, these horsemen are mainly recruited from local tribes and trained in the Gondorian manner.
  - Gondorian Soldiers and Gondorian Rangers are removed.
  - Can’t recruit Light Footmen and Light Horsemen.
  - Harondorim Footmen and Horsemen can be recruited by any Gondorian character who holds Harondorim county.
  - Overall Harondorim MAAs are oriented on cheap (compared with standard Gondorian roster) infantry and have good light cavalry, which helps to compose a reliable army.
- Bonus to Desert Warrior trait instead of Rough Terrain Expert because Harondor is more desert than hills. Same goes for recruitment and bonuses - i.e. instead of hill ones, it should be desert ones.

</details>

<details>
<summary>Changes in Cultures</summary>

**Ithilien** - [source](https://notionclubarchives.fandom.com/wiki/Ithilwaith)

- Name: changed to Ithilwaith
- Traditions: Dexterous Fishermen removed, Mende Anduya removed, Legacy of the South-Kingdom added.
- Origin: Diverged from Gondorian in 6901
- Description: Since the Shadow of Mordor kept away the indigenous tribesmen, many of the Ithileans claims to be of high Númenórean descent, but many of the rural Folk of northern and southern Ithilien also has Daen and Haradrim ancestors. Over time, as Númenórean blood mixed with that of Daen, Northmen, and Haruze, many Ithileans could only claim a hint of Númenórean ancestry.
In the past, the Ithilian nobles tried to live as if they were at the royal court in their everyday lives. Their dress and behavior were similar to those in the royal household, recalling ancient Númenórean custom. The commoners were respectful of their elders and fanatically devoted to their families, the most important factor in their life. The family ties of the folk of Harithilien are legendary, and many vendettas had been fought over them.
In the recent years most of Ithileans fled west across Anduin from the terror in the East. Those that remain are fierce people who will fight to the last to defend Gondor and their homeland from encroachment.
- Change in counties’ cultures: Telumendil culture is changed to the Ithilean culture. Represents refugees from Ithielien (i have no doubts that they are settled all across Gondor, but this area probably has the majority of refugees to the point of them being dominant, since the area is just across Anduin).
- These changes represent that the main part of remaining Ithileans are not descendants of Dunedain, but are under their great influence (to the point of full assimilation). Dexterous Fishermen is removed due to transferring part of its bonus into Ithilien Subterfuge and bonuses from Legacy of the South-Kingdom which already represent close ties with sea.

**Belfalathrim** - [source](https://notionclubarchives.fandom.com/wiki/Dor-en-Ernil#The_Inhabitants):

- Traditions: Mende Anduya and Seafarers removed, Legacy of the South-Kingdom added.
- Origin: Formed from Gondorian and Daen in 5801 (random number, after formation of Amronost culture)
- Description: The distinctive nature of the aboriginal Daen presence on the peninsula contributed equally to the success of Belfalathrim hierarchy. The forbidding aspect of Belfalas' coasts deflected the majority of pre-Downfall Númenórean contacts with the Daen people. This prevented the development of the sphere of cultural influence that exists elsewhere in southern Gondor.
After the establishment of the Princedom of Dol Amroth, pockets of native lowlanders were swiftly absorbed by the feudal estates. The remainder of what became the peasantry of Belfalas derived from the migration of Gondorian commoners. 
The vast majority of Belfalas' population are proud and dignified in bearing. Excellent horsemen and diligent workers, the Belfalathrim make up the ranks of the Dol Amroth cavalry, and many enemies have been set to flight by their coming.
- This represents that the main part of Belfalathrim folk is of local heritage (Danan Lin, Coastal People) although is heavily mixed with dunedain settlers to the point of being fully assimilated, while Amrothians are more directly related to Dunedain.

**Amronost:**

- Traditions: Bound by Faith removed, Legacy of the South-Kingdom added.
- Origin: Formed from Gondorian and Sindar.
- Description: The people of Dol Amroth bear a nobility reminiscent of Númenor of old. The greatest city in Gondor after Pelargir and Minas Tirith, the fair folk of Dol Amroth stand in these dwindling days as an example of the ancient nobility and strength of Men.
As elsewhere in southern Gondor, the population of Dor-en-Ernil contains both Númenorean and Daen elements. To a peculiar degree, however, these groups have remained relatively separate and unmixed. The initial Númenórean colonization of the peninsula was essentially aristocratic and, hence, pure-blooded in character. The result was a much more sharply-defined cleavage between the Númenorean rulers and the Daen subjects.
- Change in counties’ cultures: Edhelion is Amronost. Represents that it’s part of Dunedain heritage.

**Harondorim** - [source](https://notionclubarchives.fandom.com/wiki/Men_of_Harondor):

- Traditions: Legacy of the South-Kingdom added.
- Aesthetics: 
- Fashion: Northern Apysaic (in black/white colors?)
- Origin: Formed from Gondorian and Donan in 5083 (near of 200 after establishment of Harondor province)
- Description: The common Harondor folk are descended from Númenórean colonists and various Daen peoples of the coasts of Belfalas Bay, with most in Harondor possessing some Haruze blood. Physically, they differ little from the inhabitants of Ithilien or Lebennin, but they speak in Westron with a distinct local accent, and their lifestyles show the colorful influence of their Haruze neighbors. 
The Harondorim are known to their Gondorian kin as the 'Outhame,' a Westron term for outsiders. They accept this label because they are well aware of their status as immigrants in the homeland of their fathers and eccentrics in the heartland of their culture. Rugged and individualistic from long years of defending themselves in the oft-contested realm of Harondor, they tend to populate the regions closer to Gondor. 
- Special notes: Lords of Methir and Neporos are Gondorians. Represents that they come from Dunedain heritage rather than mixed with Daen/Haruze culture.
- Change in counties’ cultures: Methir is Gondorian culture. Represents that area is mainly inhabited by Gondorians and not “Outhame”.
- Changes represent closer ties of Harondorim with Haruze cultures.

</details>

**Additions:**
<details>
<summary>New Culture</summary>

**Orodbedhrim** - [source](https://notionclubarchives.fandom.com/wiki/Lamedonians), [2nd source](https://notionclubarchives.fandom.com/wiki/Orodbedhrim), MERP 2020 Southern Gondor: The People. Mainly represents Lamedoneans, but using a broad term so we can cover all hill-men of Gondor.
**Reasoning**: Gondorian Daen culture looks pretty interesting in the context of local Gondorian cultures. This culture has a specific flavor based on Daen cultural origins and preservation of it (clan structure) and at the same time is very civilized due to Gondorian influence. For the purpose of making this culture to be used not only in Lamedon, but outside of it is used the broad term Orodbedhrim. In gameplay terms the culture also should be less advanced compared with Gondorian one, which means that playthrough for it can be challenging (and a little frustrating for the Gondorian ruler). At the same time, possible MAAs can expand the suggested above rebalance of the Gondorian military, creating a balanced roster.  

- Names: Orodbedhrim; Orodbedhric
- Description: Those of Daen-folk who came under the influence and government of the Dunedain, the Danan Lin (“People of Learning”), are known in Gondor as Orodbedhrim (“Mountain-dwelling Folk”). While some of Orodbedhrim are living in secluded mountainous areas and avoid Gondorian influence, most of them have strong association with Numenorean culture. 
The Orodbedhrim is the longest surviving strain of the ancient Daen peoples, though they are so influenced by the Dunedain that they, in fact, ceased to be Daen. They still maintain their clan structure, mainly because the Gondorians appropriated it to organize the Orodbedric regions and integrate them into the realm. At the same time, the Daen-folk of Gondor adopted most of the customs of the Dúnedain and speak a variant of Daenel influenced by Westron.
- Ethos: Communal
- Heritage:Daen Heritage
- Martial: Men Only
- Language: Daenel
- Aesthetics:
  - Naming practice: Eredrim
  - Architecture:Numenorean
  - Fashion:Gondorian
  - Coat of Arms:Numenorean
  - Military equipment: Continental European (we probably should rename this one)
- Origin: Formed from Gondorian and Eredrim in 5001 (random number)
- Counties with culture: Erech, Curcenis, Tarlang, Rendul, Andhen, Imristo, Tathrendalf, Rhandir (represents limited migration in the past of Lamedonians to the side of Anfalas), Udul, Glorfalc, Pinnornost, Delutham, Annon Wain, Bar-Erib, Dudhrandur ([source](https://notionclubarchives.fandom.com/wiki/Belfalas))
- Cultural title names - Default Clan tiers (even for feudal lords - because their clan organization)
- Innovations: Second and early third age are finished, third age innovations: hoardings, advanced bowmaking, men-at-arms, heraldry, scutage, windmills, land grants.
- Traditions: Legacy of the South-Kingdom, Clans of Gondor, Hill Dwellers, Strong Kinship

**Clans of Gondor** - unique regional trait

- Hill and mountain holdings of this culture provide additional defender advantage
- Rough terrain expert trait is more common
- Additional bonuses for commander and personality traits in hills
- Decision to recruit hill commanders
- Unique MAA:
  - Gondorian Clansmen - cheap moderately good hills-oriented skirmishers:
    - Size: 100 (recruited 5)
    - Type: Skirmishers
    - Damage: 18
    - Toughness: 16
    - Screen: 16
    - Counters Heavy Infantry
    - Terrain effects: 
      - Forest: Damage 10, Toughness 10
      - Hills: Damage 12, Toughness 12
      - Mountains: Damage 12, Toughness 12
    - Cost: 55 for creation, 0.25 low maintenance
    - Description: Equipped and armed by clans, these soldiers are trained by Gondorian standards and compose the backbone of  levies in mountainous Gondor.
  - Orodbedhric Bowmen - cheap moderately good forest/hills-oriented archers:
    - Size: 100 (recruited 5)
    - Type: Archers
    - Damage: 29
    - Toughness: 12
    - Counters Skirmishers
    - Terrain effects: 
      - Forest: Damage 12, Toughness 8
      - Hills: Damage 10, Toughness 6
      - Mountains: Damage 8, Toughness 6
    - Cost: 65 for creation, 0.3 low maintenance
    - Description: Orodbedhric hunters and militiamen are famous for their archery skills and often recruited by the lords of Gondor.
  - Can’t recruit Light Footmen, Gondorian Bowmen and Gondorian Horsemen.
  - Gondorian holders of counties with Orodbedhric culture (i.e. owner is of different culture with the Legacy of the South-Kingdom) can recruit from their roster without suffering penalties (such as removal of Gondorian bowmen etc.)
  - Overall Orodbedhrim roster lacks cavalry due to mountains and hills being not the best areas for them, but at the same time local variants of troops are much cheaper than Gondorian soldiers which allow to recruit them en masse. 

**Special note:** 
New religion “Danan Lin” is used in many of new Orodbedhrim counties. This religion represents a greatly influenced by the Dunedain religion of Daen peoples (source is MERP Southern Gondor: the People).

- Names: Danan Lin; Follower of the Danan Lin Faith; Peoples of the Danan Lin Faith 
- Description: Having learned the names of the Valar and Mayar from their Numenorean mentors, the Danan Lin people attribute to these powers local characteristics with which they are more familiar. Greatly influenced by the Dunedain, the Danan Lin honor the national festivals and holy days of the Faithful, but add many of their own ancestral customs and beliefs to the teachings. They believe that the Valar take a much more immediate and involved role in the affairs of day-to-day life than most of Dunedain would grant.
- Unreformed Gwathuirim Faith
- Holy Sites: Minas Tirith, Erech, Harrowdale, E Gynd, Dol Amroth
- Main Doctrines: Male Oriented, Lay Clergy, Righteous, Echoes of Ainur
- Marriage doctrines: Monogamous, Disallowed divorce, Legitimization of Bastards, Close-Kin Taboo
- Crime doctrines: Shunned same-sex relations, Criminal Deviancy, Shunned male/female adultery, Close kin is criminal kinslaying, Criminal Witchcraft, 
- Clergy doctrines: Recruitment clerical function, only men clerical gender, Temporal revocable clerical appointment, allowed clerical marriage
- Tenets: Adorcism, Astrology, Adaptive
- Changes in religion of counties:  Erech, Curcenis, Tarlang, Rendul, Andhen, Imristo, Tathrendalf, Rhandir, Udul Bar-Erib and Dudhrandur are Danan Lin; Delutham, Annon Wain and Pinnornost are Daen Coentis. Represents that latest areas, despite being greatly influenced by Gondorians, are of Daen Coentis heritage and do not infleunced at same level as their Eastern counterparts.

</details>

**Comment by jj248** [comment]
This feels like it's in a good enough state for v3.  Will leave un-closed to reassess properly in v4.

**Comment by jj248** [comment]
@VectorMaximus - can you take a look and see if there's anything work keeping this open for?

**Comment by Jaco-Daan** [comment]
Since it's been decided how our cultural structure will be for Gondor, closing
