### ISSUE TITLE
Elves - additional decisions

### ISSUE THREAD

**Issue by Shammien** [jj248/RealmsInExile#489]
**“Establish the high kingdom of Eryn Lasgalen”** - Lasgalendrim decision

The decision must have some short flavorful text regarding the cleansing of Mirkwood, renaming it Eryn Lasgalen and re-establishing the old splendor of the Woodland Elves during Orophers reign.

**CONDITIONS:**

- You are an Independent Ruler
- You completely control Mirkwood (all territory inside the forest’s borders, including colonizing the wilderness within the forest)
- Resettle Amon Lanc (Elven culture conversion of Dol Guldur)
- Your Level of Fame is The Living Legend
- Cost 5000 Prestige
- Regrow the Silvan Gardens of Amon Lanc (special building that cost 2500 gold, takes 5 years to build, requires Elven Refuge 6, Elven City)

**EFFECT:**

- You gain the title of Eryn Lasgalen, you become a mighty Arandor/Rìandor (includes a very flavorful, magnificent and intricate coat of arms).
- Your dynasty gains 3000 Renown
- Amon Lanc becomes the De Jure Realm Capital
- + 10 development in Realm Capital
- Dynasty gains the “Legacy of Oropher” modifier for 50 years. Effect;
                  - 10 % less maintenance cost of Silvan Rangers, Greenwood Swordsmen, Theladagnyr, Gilded Guard, Greenwood Archers 
                     and Royal Elf Riders
                  - Defender Advantage + 10 when fighting inside the forest
                  - Elven settlement speed + 10 % (culture conversion)

**“Claim Amon Lanc for Laurelindòrenan”** - Galadhrim decision

The decision must have some short flavorful text regarding tearing down the walls of Dol Guldur and cleansing the southern part of the forest, renaming it Amon Lanc claiming it for Laurelindòrenan.

**CONDITIONS:**

- You are an Independent Ruler
- You have the Title “Lothlorien”
- Resettle Amon Lanc (Elven culture conversion of the region formerly known as Dol Guldur)
- Your Level of Fame is The Living Legend
- Cost 5000 Prestige
- Regrow the Silvan Gardens of Amon Lanc (special building that cost 2500 gold, takes 5 years to build, requires Elven Refuge 6, Elven City)

EFFECT:

- You gain the title High Kingdom of Laurelindòrenan. You become a mighty Arandor/Rìandor. (Amon Lanc, formerly kingdom title Dol Guldur, becomes De Jure part of the High Kingdom of Laurelindòrenan together with Kingdom of Lothlorien.)
- Your dynasty gains 3000 Renown
- + 10 development in Realm Capital
- You gain the title; “Lady of Light” / “Lord of Light”
- Dynasty gains the “Light of the Forest” modifier for 50 years. Effect;
                       - 10 % increase maintenance damage of galadhrim Wardens, Galadhrim Warriors, Galadhrim Sentinels, Galadhrim 
                          Archers, Knights of Amroth
                       - Defender Advantage + 10 when fighting inside the forest
                       - Elven settlement speed + 10 % (culture conversion)

**Comment by VectorMaximus** [comment]
So, my two cents - after thinking it over, I do have to agree with separating out the Vale from the Wood. Historically, there is no period where the two were united politically, perhaps save in the most distant of pasts when the Nandor wandered freely through the woodlands of Rhovanion and Eriador, before the coming of Men.

The special building in Amon Lanc would be the final upgraded level of Dol Guldur (because a province can only have one special building).

**Comment by Remerod** [comment]
I agree with most of this but

> Amon Lanc becomes the De Jure Realm Capital

I'm not "against" Amon Lanc becoming the de jure capital of the empire, but it should not be the "standard" outcome. Why would Thranduil move his shit down to a "cleansed" place when he have lived over 2 millennia at his current place.

It could be an option, sure, i to would think that be cool "but" there is no "lore" reason for this to be the logical conclusion.
Perhaps we could add something like what gondor have, they can move their de jure capitals around, heck maybe we could add an options for the woodsmen to have one? 

Also i'm uncertain how the woodsmen fits into this, are we proposing the middle kingdom in mirkwood where the woodsmen live to be added to the new vale empire? It would be nice to have the woodmen stance cleared up

**Comment by Shammien** [comment]
It "becomes De Jure" Realm Capital, it does not say it becomes the Realm Capital. It becoming de jure is a nod to the old kingdom of Eryn Galen during Orophers time. It does not move, it is only de jure (due to historically being that). If the player actually moves his capital there... Well it is up to the player.

**Comment by VectorMaximus** [comment]
No. The central kingdom in Mirkwood would remain part of Greenwood. Essentially this is the proposal for the dejure at game start:
![image](https://user-images.githubusercontent.com/79318177/187088100-efbaae12-c9db-4c3f-be3a-fc16f96b782b.png)

**Comment by VectorMaximus** [comment]
Well, with Gundabad in the vale until we add the mountain empires in 4.0 with the Dwarves

**Comment by Shammien** [comment]
Yeah ventral part still in Greenwood, or just: All parts of Mirkwood (forest proper) remains in Greenwood :P I do not think I partitioned the central part out in my proposal?

**Comment by VectorMaximus** [comment]
The other alternative being discussed is to rebrand (and slightly recolor) Greenwood into the imperial title of _Wilderland_, which cannot be formed under normal circumstances, with decisions for people dwelling within its boundaries to make new empires.

**Comment by Shammien** [comment]
That seems reasonable. Wilderland that consists of 5 kingdoms (3 from Mirkwood and 2 from the Vale). But still, keep the abovementioned flavor-decisions for the elves so that they can partition out the woods in to their own woodland empire. Sp then the Wilderland empire-title would only have 2 kingdoms left if the player/AI succeeds in establishing Eryn Lasgalen or  Laurelindòrenan.

**Comment by VectorMaximus** [comment]
After further discussion (apologies for those of you who can't see the dev chat!) we'll move forward with dividing the empires into the Vales and Greenwood.

**Comment by savagesach** [comment]
I've played both lorien and woodland realm for a while, and both decisions work as intended. I think this issue can be closed
