### ISSUE TITLE
2D Art: Holding art for Orcs/Evil

### ISSUE THREAD

**Issue by Remerod** [jj248/RealmsInExile#491]
We have awesome background art for gorgoroth/volcanic plains 
![image](https://user-images.githubusercontent.com/79544635/188340204-5531fcab-e149-46a6-b953-ceac5c4323b0.png)

But we don't have stuff for orcs or evil cultures
![image](https://user-images.githubusercontent.com/79544635/188340223-88f91523-7ce6-493c-a4e8-1e1cc48d3974.png)

So what would be needed foremost is art for Castle & tribal holdings, cities and temple secoundary. 
If we could gain that the flavour of the mod would greatly improve and the immersion deepen!

(weta design art is recommended, i believe the 3d holdings they have is based on the models from the Age of the ring mod, who use Battle for Middle earth styles aka weta based ones)

**Comment by jj248** [comment]
Let's push to v4

**Comment by Jaco-Daan** [comment]
We have a new issue encompassing all 2D art we still need for v4, closing
