### ISSUE TITLE
2d: Texture for Yellow mountains 

### ISSUE THREAD

**Issue by Remerod** [jj248/RealmsInExile#493]
So we need a good texture for yellowish mountain type, something good for [Tûr Betark (Ap. "Yellow Mountains")](https://notionclubarchives.fandom.com/wiki/T%C3%BBr_Betark). Jamie has been saying that something with [feldspar](https://en.wikipedia.org/wiki/Feldspar) would be good, here some examples of feldspar mountains; 

![image](https://user-images.githubusercontent.com/79544635/188735810-2e26e0b1-5e1b-4ff5-a596-a2eadecf8b1c.png)

![image](https://user-images.githubusercontent.com/79544635/188736031-888434f3-7c11-4da7-9031-46aef7b6854a.png)
Akaba mountains

![image](https://user-images.githubusercontent.com/79544635/188736214-cc229dc4-a467-4e28-bfba-e9606bbd9987.png)
feldspar mountains

![image](https://user-images.githubusercontent.com/79544635/188736750-419fc1da-b56e-4ce7-abef-647329306015.png)

![image](https://user-images.githubusercontent.com/79544635/188736979-9f476c82-d297-4740-bfe3-1b84499b3694.png)
Back at the Kingman Feldspar Mine (Kingman Feldspar Quarry

Some other examples of yellow mountains;

![image](https://user-images.githubusercontent.com/79544635/188737237-2a6a1b1a-c272-4c70-b855-d5835a26f8db.png)

![image](https://user-images.githubusercontent.com/79544635/188737385-9683f782-9ad6-4284-90df-6e66f8341550.png)

![image](https://user-images.githubusercontent.com/79544635/188737434-552f2c34-1077-492b-bc14-6e0b0fe700a2.png)

yellow mountain pictures in china

![image](https://user-images.githubusercontent.com/79544635/188738413-452d5a8a-928e-4cc7-a816-0c8f128c7676.png)
Sunset, Namibia. Purple And Yellow Mountains Of The Namib Desert

![image](https://user-images.githubusercontent.com/79544635/188738985-1bfb5b4b-b8bb-4c86-9e48-e84dd20d74b9.png)
[Capernaum & Mount Arbel | Israel's Good Name

![image](https://user-images.githubusercontent.com/79544635/188737703-29981a06-da4d-465a-8792-85031905f903.png)
OIL painting Yellow rocky mountains

![image](https://user-images.githubusercontent.com/79544635/188738769-02a0a4b9-4816-4795-834f-80f20cef6ee3.png)
Desert Sunset Landscape Background Wallpaper Illustration Stock Illustration

**Comment by jj248** [comment]
One for v4 when we get to looking at mountains more closely.

**Comment by Jaco-Daan** [comment]
Seems we've gone in a different direction, i.e., not using different textures. Closing this issue.
