### ISSUE TITLE
Events ; Dale flavourish decision

### ISSUE THREAD

**Issue by MathieuGFB** [jj248/RealmsInExile#496]
I would like to suggest a decision linked to a couple of events to fill a game with Dale.
In the One Ring RPG 1st Edition, the authors detailed a great celebration happening every year to celebrate the fall of Smaug. It happens in Esgaroth and there are several events.

My idea would be to create a decision for the king of Dale (as long as he is from a culture with a Dalish specific heritage and hold directly or indirectly Esgaroth) which can be taken, let say, every ten years, costing money and giving prestige and firing a set of events. Very close to what exist for vikings and their blot.

The first event would be a presentation of the celebration, with three possible decisions : participate to an archery tournament (based on prowess and / or martial), to a chess tournament or to a poetry one. Maybe a fourth decision to skip tournament ?
The second step would be the result of the tournaments and after that, I was thinking to add a couple of random flavour event, like for the sailing events. You could meet a noble dwarf in Esgaroth, buy something exotic in the market, meet a local famous bowman, ...

Feel free to make comments, suggestions, criticisms...

**Comment by JukeJukestar** [comment]
This seems fun, maybe I will find the time to pick it up post-release

**Comment by Jaco-Daan** [comment]
Closing this since... To&To DLC...
