### ISSUE TITLE
Elven flavour events

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#509]
Addition of a good number of elven flavour events.

**Comment by Jaco-Daan** [comment]
Moved this to testing as all the localization has been finished:
Events are realms_galadhrim_filler.100 - 108, realms_lasgaladhrim_filler.001 - 205, realms_gondor_filler.100 - 105

**Comment by Remerod** [comment]
Tested;

**realms_galadhrim_filler.100 - 108** 
Pictures, event 104, 106 and 108 have bugs
<details>
<summary>Click to expand</summary>

realms_galadhrim_filler.100
![image](https://user-images.githubusercontent.com/79544635/234734095-ff4c6733-e1ea-463a-a95c-7b3e9a3dd9aa.png)

all 3 choices have text

realms_galadhrim_filler.101
![image](https://user-images.githubusercontent.com/79544635/234734290-836a5cde-9030-4ee8-9992-672dac0dab1f.png)

both choices have text

realms_galadhrim_filler.102
![image](https://user-images.githubusercontent.com/79544635/234734359-9513ff12-789b-481d-a58f-982050a5fe5f.png)

both choices have text

realms_galadhrim_filler.103
![image](https://user-images.githubusercontent.com/79544635/234734492-7076ed83-b0cc-4576-beab-39703b61f028.png)

realms_galadhrim_filler.104
![image](https://user-images.githubusercontent.com/79544635/234734615-5eab3ba8-1290-47f8-9ce4-3fbd219c6929.png)

Is not working

realms_galadhrim_filler.105
![image](https://user-images.githubusercontent.com/79544635/234734738-f8de0609-63d3-44f5-ab10-771f8d4c101d.png)

realms_galadhrim_filler.106
![image](https://user-images.githubusercontent.com/79544635/234734817-3aba1ab7-fce0-40e7-9b61-7734f00bb638.png)

realms_galadhrim_filler.107
![image](https://user-images.githubusercontent.com/79544635/234734899-011c68d5-e497-43e9-8738-9b1aea0b2fde.png)

Event name is not working

realms_galadhrim_filler.108
![image](https://user-images.githubusercontent.com/79544635/234734975-0c4ff888-e117-4c2e-97c9-993c393162cc.png)

</details>



**realms_gondor_filler.100 - 105**
The only event that dosent have error is event 100, check pictures for more details.
<details>
<summary>Click to expand</summary>

realms_gondor_filler.100
![image](https://user-images.githubusercontent.com/79544635/234735358-1446c53f-a226-4b48-a97c-aa1f91810a54.png)

bot choices have flavor text

realms_gondor_filler.101
![image](https://user-images.githubusercontent.com/79544635/234735446-1be5306b-ae3b-4b90-8f86-5054f2e443c5.png)

error in text and in the choice

realms_gondor_filler.102
![image](https://user-images.githubusercontent.com/79544635/234735533-b590fbff-be23-41b2-a7e7-74ae0b4c8ffe.png)

2 errors in the text

realms_gondor_filler.103
![image](https://user-images.githubusercontent.com/79544635/234735608-f1e5b0eb-3da6-450c-83dd-fac83ee16eae.png)

1 error in the text

realms_gondor_filler.104
![image](https://user-images.githubusercontent.com/79544635/234735691-2d4880ac-6122-4283-8c66-ba1890848c9c.png)

error in text and in the choice

realms_gondor_filler.105
![image](https://user-images.githubusercontent.com/79544635/234735773-4d604908-1ccf-4687-83b8-45d6eef90d91.png)

error in text and in the choice

</details>

**realms_lasgaladhrim_filler.001 - 205**
Are you telling me that there is 205 events!?!?!?!?!
I need clarification before testing these

**Comment by Remerod** [comment]
Event realms_lasgaladhrim_filler.100 does not work

![image](https://user-images.githubusercontent.com/79544635/234854194-ec5c9a84-5f32-4734-83cc-543cdce30824.png)

**Comment by Remerod** [comment]
I've tested the event realms_lasgalendrim_filler.100 - 102 & 200 - 205 now (who you spelled wrong!)
All seems to be working localization wise
<details>
<summary>Click to expand</summary>

event realms_lasgalendrim_filler.100
![image](https://user-images.githubusercontent.com/79544635/234856666-14052e1f-59a3-4d22-be84-21991b63cc31.png)

Finally got it to working, seems to work fine

event realms_lasgalendrim_filler.101
![image](https://user-images.githubusercontent.com/79544635/234857364-65e9c5e2-a69c-4498-850f-ba1ea09fe730.png)

localization seems to work

event realms_lasgalendrim_filler.102
![image](https://user-images.githubusercontent.com/79544635/234857621-206ff9c6-72e5-46c7-967c-39ed89f2747e.png)

localization seems to work

event realms_lasgalendrim_filler.200
![image](https://user-images.githubusercontent.com/79544635/234857906-d3b2cdf8-9574-4c3b-82ee-6c90cf9cde2d.png)

localization seems to work

event realms_lasgalendrim_filler.201
![image](https://user-images.githubusercontent.com/79544635/234858053-85419c74-9aa0-4ead-b958-ea7e9f6c8cf8.png)

localization seems to work

event realms_lasgalendrim_filler.202
![image](https://user-images.githubusercontent.com/79544635/234858173-e7beb9bd-b644-4394-b4e6-74e03efad714.png)

localization seems to work

event realms_lasgalendrim_filler.203
![image](https://user-images.githubusercontent.com/79544635/234858291-ab7fabe9-5a93-49ea-9286-3149ba852616.png)

localization seems to work

event realms_lasgalendrim_filler.204
![image](https://user-images.githubusercontent.com/79544635/234858437-3bd4298f-fa2a-4ada-9df5-48284d51ff3b.png)

localization seems to work

event realms_lasgalendrim_filler.205
![image](https://user-images.githubusercontent.com/79544635/234858556-b93fd8bf-394e-498e-8542-7eec312627f8.png)

localization seems to work

</details>

**Comment by Remerod** [comment]
I've now tested (localization wise) all the events @Jaco-Daan have asked of us to test
I have not tested (or rather given any thoughts to) whatever the rewards are fitting and so on

But either way since there where some bugs with the localizations i'll move this issue to bugs

**Comment by Jaco-Daan** [comment]
Since there have been no more issues report + the localization issues were fixed, closing this
