### ISSUE TITLE
Elven ethnicity variety and gaunt female fix

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#515]
Add additional variety to base elven template for e.g. hair colours, height for avari etc.

**Comment by jj248** [comment]
Should also look to make pregnant elves show pregnancy.

**Comment by jj248** [comment]
This should now be dev-complete.  @VectorMaximus to take a look over, ensure ethnicities are assigned correctly and look good.  We also need to decide on whether to show all the sub-ethnicities in the ruler designer (I've left them showing for now for testing and ease of visualising them).  If we do, we'll need to localise them.

Dead elves should no longer be gaunt and pregnant elves now have growing tummies over a period of nine years.

**Comment by BriceLeduc** [comment]
![image](https://user-images.githubusercontent.com/98077354/226727507-c2c43165-b692-450d-8699-8b3fec2cafd2.png)
Elven ladies are no longer all gaunt, and look properly pregnant
