### ISSUE TITLE
Gundabad - Drive men from the Vale decision

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#525]
Decision to take once you've taken over the Anduin Vale to get rewards and unlock random goblin invasions of nearby territories from the mountains.

Note - will want to be able to announce this to all players and to take these raids away if Gundabad gets beaten back.

**Comment by jj248** [comment]
We'll properly focus on Gundabad in v4 - shifting this to there,

**Comment by Natsuki-best-girl** [comment]
couldnt do cb :( but otherwise i added so gundabad expand their rather pathetic kingdom size by eating langwell and give them more troops to play around

**Comment by savagesach** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/86676697/209f35f0-5da0-4ed2-8f1c-0847726871e6)
this decision works, but should be a global event rather than a normal event

**Comment by savagesach** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/86676697/f8802f0a-4628-4daf-85fc-6793c42c0303)
never mind it's already a global event. However the avenge the battle of the five armies decision does not give any event or any noticable reward

**Comment by savagesach** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/86676697/4bba9437-8425-4e87-95cb-04bb6165d63d)
okay so the decision gives a reward, it's just not much. If this is intended, the issue can be closed

**Comment by Jaco-Daan** [comment]
Closing this issue for now. Seems we added a few initial decisions. We can open this issue or create a new one once we decide to properly focus on Gundabad.
