### ISSUE TITLE
Gundabad - Art for Skorbuk trait

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#527]
Missing art currently.  Something like orc hands holding an evil dark crystal.

**Comment by Remerod** [comment]
So in vanilla you have the Sayyaid trait, which basically says Sayyaid (i think).

![image](https://user-images.githubusercontent.com/79544635/194784390-22bc614d-c969-40b0-89e9-4700d6425e27.png)

So my idea is that the Skorbúk traits will spell "Skorbúk" using black speech (which uses [Tengwar](https://en.wikipedia.org/wiki/Tengwar) as a base. But you know, this is something that orcs would have written for millennia so maybe we would need to "uruk-ify" it a bit, so basically do it a bit more bastardly. 

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/194785202-8994f66e-ba15-4eb8-a1b5-1315aae908f9.png)
black speech alphabet

![image](https://user-images.githubusercontent.com/79544635/194785184-c48528f8-2daf-43d4-ab6a-cbe36f69363c.png)


![image](https://user-images.githubusercontent.com/79544635/194784974-da425a1f-da13-4cfe-b90e-58b3b0745f8d.png)
cave painting of the eye symbol, you can clearly see here that they are not good good

![image](https://user-images.githubusercontent.com/79544635/194785016-0b16ef0e-c6d7-483d-9746-50693f7d6eee.png)
this is from warcraft 3, i'm not saying to use this but i'm thinking inspirational how stuff is written on a stone wall these kind of look nice

![image](https://user-images.githubusercontent.com/79544635/194785092-83e7321d-16d5-449f-8dec-7a3167749807.png)
human cave art

</details>

**Comment by JukeJukestar** [comment]
Small update: gave it one of the orc commander trait icons as a placeholder, we still need a proper one

**Comment by Remerod** [comment]
I imagine that the image would look like the warcraft painting somewhat (look a stone tabled with red paint) or like that eye of sauron picture above (so see my ugly paint try)

![ugly paint skorbuk](https://user-images.githubusercontent.com/79544635/227667278-57c18139-a12b-4d52-98a1-7ebc0ea1ec7e.png)

**Comment by Chief305** [comment]
made a tablet for the icon background just need a text for it 

![orc tablet2](https://user-images.githubusercontent.com/99970173/227667714-e87f3715-a506-4163-913b-99a3b6dacf42.png)
