### ISSUE TITLE
Evil Isengard event chain rework

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#536]
Revamp event chain to be more robust and to have multiple branching paths.  Note that good Saruman altlore will be covered in a separate issue.

**Comment by JukeJukestar** [comment]
Related to #537 #285 #285 #362

**Comment by JukeJukestar** [comment]
minor note (I know its still in development)
- Hillmen should reconvert to Turthalis / Krabnazerh from white hand once saruman dies (similar to the death of sauron conversions

**Comment by jj248** [comment]
Batting this back to testing after implementing suggestions in #581.

**Comment by JukeJukestar** [comment]
It would be really cool if there was a special outcome for the rohan event chain if they are defeated militarily, where a large host of the remaining rohirrim migrate northeast
Either to resettle the vale and become vassals of king Grimbeorn, or even to resettle central Rhovanion.

This would be a lot of work though, perhaps better invested elsewhere for now

**Comment by JukeJukestar** [comment]
Some suggestions to make your puppet ruler in the Riddermark more stable:
- Have the event where you choose a new ruler give all counties in the Folde a large buff to control.
- convert some counties in Western Rohan to Dunlending if a Dunlending Puppet is installed (since they resettle those lands)
- Give the new Dunlending/ Uruk-Hai ruler some starting gold

**Comment by savagesach** [comment]
I just played through the entire evil isengard event chain and it works for the most part. There is an issue though where if you submit to sauron, you don't actually get any lands west of the anduin.
![image](https://user-images.githubusercontent.com/86676697/220991212-a925857e-1cf6-43c1-990d-bae33fac4c45.png)

**Comment by savagesach** [comment]
for reference, the anorien land was taken after I submitted to sauron, I switched to him to get him to declare the war

**Comment by savagesach** [comment]
![image](https://user-images.githubusercontent.com/86676697/221025407-ae703b06-2a8b-47de-8e42-357ca8954787.png)
![image](https://user-images.githubusercontent.com/86676697/221025460-52ea054b-b96c-4dd4-8299-fbeae03bd65d.png)
the decision works as intended, this however is only as long as vassals holding titles west of the anduin don't also hold other titles

**Comment by savagesach** [comment]
![image](https://user-images.githubusercontent.com/86676697/221026024-42bb2b04-91e3-4162-96e3-bddd3b041c62.png)
for example see here, basically it's the same issue as the abrakhan request lands decision

**Comment by jj248** [comment]
The AI should now hopefully be smarter and ensure titles East of Anduin are not granted as shown above.  Ready to test.

**Comment by savagesach** [comment]
I can confirm Sauron properly transfers over titles from his vassals without giving the vassals themselves.
![image](https://user-images.githubusercontent.com/86676697/222008336-11879a59-e9a1-4d46-b81d-1ddea2940c27.png)

**Comment by jj248** [comment]
Great - thanks.  Closing as the rest of the fixes are contained in #612
