### ISSUE TITLE
Ensure courts correctly assigned

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#556]
Ensure assigned royal courts are appropriate for all cultures.

**Comment by jj248** [comment]
Hadorim heritage cultures should now be getting the Rohan court.

**Comment by BriceLeduc** [comment]
Elves are still getting the Dunedain court

**Comment by Remerod** [comment]
> Hadorim heritage cultures should now be getting the Rohan court.

this doesn't seem to working

**Comment by Remerod** [comment]
> Elves are still getting the Dunedain court

this is fixed though, they now use generic western

**Comment by Remerod** [comment]
I havent checked all cultures but i don't think there is any game thematically breaking court atm moment (unless we want to fix the hadorim thing) 

while we could keep the issue to make sure for the future, i do think it's ready/good enough for release
