### ISSUE TITLE
Final review of new cultures

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#557]
Final pass of cultures to ensure we're happy with geographic extent, history and traditions.  Actions as follows following review:

- [x] #655
- [x] #654
- [x] Consider Wildmen Adventure Innovation scope.
- [x] Framlings: Add Hill Dwellers, Add Isolationist, Remove Martial Admiration.
- [x] Increase Eotheod culture innovations to be in line with Valemen.
- [x] Defended Enclosures and Hidden Refuge traditions obtainable by all - restrict.
- [x] Add Deep and Mallorn Forest to Sacred Groves, Forest Fighters, Forest Folk and Hidden Refuges tradition.
- [x] Make People of the Bow and Adaptive Skirmishers mutually exclusive.
- [x] Add Expert Artisans to Dalringi.
- [x] Dorwinionrim to get Egalitarian, Replace City Keepers with Agrarian, Add Swords for Hire.
- [x] Warriors of Fame and Field - remove merc bonuses.
- [x] Rhovanionrim - add Warrior Culture, Replace Martial Admiration with Trials by Combat.
- [x] Logath - Replace charismatic with forest folk.
- [x] Ulgath - Replace Horse Breeders with Collective Lands.
- [x] Igath - Replace Pastorialists with State Ransoming.
- [x] Magriag - Replace Eunuchs with Trials by Combat.
- [x] Variag - Replace Hit and Run with Ritualised Friendships.
- [x] Nurniag - Replace Artisans with Frequent Festivities.
- [x] Title Case for Gorgoroth Plains Dwellers.
- [x] Sort out Remerod's wayward orc traditions - Dush-Hai Cabal, Gorgoroth Plains Dwellers, Legions of Gundabad.
- [x] #653
- [x] Umaiar & Fallen Istari - Add By the Sword.
- [x] Review descriptions of Nurniag, Variag, Logath, Kazgumhoth, Penni, Ulgath, Asdriag.
- [x] Add missing descriptions for Odhriag and Magriag.

**Comment by JukeJukestar** [comment]
https://cdn.discordapp.com/attachments/751097880101650532/1028753249265791088/unknown.png

https://cdn.discordapp.com/attachments/751097880101650532/1028753249592954980/unknown.png

https://cdn.discordapp.com/attachments/751097880101650532/1028754079410815006/unknown.png

Gundabad cultural descriptions are still very placeholder-ish, @Remerod

**Comment by JukeJukestar** [comment]
![image](https://user-images.githubusercontent.com/76008882/215509542-29bfcf07-c758-42d4-8c07-991351c170b2.png)

The Dorwinion tradition is really OP, especially the 50% reduction in merc cost. (For reference, heres the "Swords for Hire" tradition by itself)
![image](https://user-images.githubusercontent.com/76008882/215510006-e5db9511-8347-45fb-a144-15a45dec528d.png)

Remove all the stuff relating to mercs and raiding as well as the culture opinion stuff.

**Comment by jj248** [comment]
Actions from cultural review implemented.  Now passing to testing.  Also be on the lookout for any cultural traditions not working, able to be combined in weird or broken ways, or missing something Realms-specific (e.g. terrain types).

**Comment by JukeJukestar** [comment]
I hereby decree this finished for now. (by my power as regular tester with no authority to declare anything)
