### ISSUE TITLE
Finalise bookmarks

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#561]
Need to update bookmark maps and highlights for both Rhavanion and Gondor (for Khand).

Additionally, some CoAs are missing in Rhovanion BM.

**Comment by JukeJukestar** [comment]
Consider adding gundabad to the bookmark, if its not already too crowded

**Comment by jj248** [comment]
Makes sense to me to have dwarves in their own bookmark.  Orcs & Dwarves theme with:

- Dwarves of Moria
- Dwarves of Erebor
- Dwarves of the Iron Hills
- Gundabad Orcs
- Goblins of Moria
- Goblintown?

**Comment by jj248** [comment]
(naturally would be a v4 thing)

**Comment by VectorMaximus** [comment]
Dwarves of the Iron Hills and Erebor likely under one tag, with another one for the Dwarves of the Grey Mountains (Nordinbad from War in the North).

**Comment by RedArkady** [comment]
- For some reason Moria and the Iron Hills are highlighted when hovering over Grimbeorn.
- Should Grimbeorn be positioned a little lower on the bookmark screen? 
- Argument for Grimbeorn not to have the 'The Old' nickname here - he gains it later via event when he hits 70
- Anduin is misspelled 'Anduain'
![image](https://user-images.githubusercontent.com/20355423/218262067-0ea7120f-cfae-458a-ac1e-3aa6dcfe1235.png)

**Comment by jj248** [comment]
> * For some reason Moria and the Iron Hills are highlighted when hovering over Grimbeorn.
Yup, that's with @MattTheLegoman to correct.  We'll have Dwarves on a separate bookmark.  This, along with shifting of the highlighted realm colours to broadly match their in-game colours.

> * Should Grimbeorn be positioned a little lower on the bookmark screen?
Probably, but I'm waiting for the realm highlight to be added to fit it better.

> * Argument for Grimbeorn not to have the 'The Old' nickname here - he gains it later via event when he hits 70
Sure, I have no issue with that.

> * Anduin is misspelled 'Anduain'
It's been labelled as 'Vales **of the** Anduain', which makes it sound like Anduain is a name for a people and may be intentional?  But I know of no lore source that names them as such and we don't use that terminology in-mod.  So probably best to just have the label as the canonical 'Vales of Anduin'.

**Comment by JukeJukestar** [comment]
- Galadriels Hair is wrong since we changed it (if you own Fates of Iberia)
