### ISSUE TITLE
Adaptation of BP1 events

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#563]
We should run through BP1 events to ensure they're appropriate for Realms and adapt these where needed.

**Comment by BriceLeduc** [comment]
I've added triggers to restrict events starting seduce and murder schemes for Elves, Maiar and Nazgul

**Comment by JukeJukestar** [comment]
Whats the status on this? I havent encountered any issues with it so far
This may be one of those issues we just keep on the back-burner and fix anything that comes up during gameplay

**Comment by Jaco-Daan** [comment]
Since we've had no more issues either on official or beta, closing
