### ISSUE TITLE
King in the Golden Hall event chain

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#566]
Coding of the attached chain.
[LotR_Realms_in_Exile_KingintheGoldenHall.xlsx](https://github.com/MattTheLegoman/RealmsInExile/files/9727972/LotR_Realms_in_Exile_KingintheGoldenHall.xlsx)

**Comment by jj248** [comment]
Push to v4.

**Comment by JukeJukestar** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/76008882/11be5a55-4065-4eb5-867c-b38779d6ab14)

Event chain is bugged. Got it randomly when playing Umbar.

**Comment by Jaco-Daan** [comment]
Finished with this event chain. The event chain should have several pathways down which you can go.

The triggers (what you need for the event to fire) are the following (in no discerning order of course)

- Character has held Edoras for **at least** 10 years
- Your culture is the descended form the Eothed culture
- You should not have had this event in the past 10 years (i.e., This event, at maximum, can only fire every 10 years)

rohan.2100 is the id of the event which start the event chain and you should have 4 options.

1. Ride out to the plains
2. Head to the stables
3. Train with the recruits
4. Return to your hall (ENDING THE EVENT CHAIN)

Option 1. will take you out on the plains where you will get 3 options to prevent your horse from throwing you off its back. And each option should lead to its own event window which will in turn lead to an ending event where you return to your hall.
Option 2. will take your character to the stables where you get 3 options in terms of who you want to inspect, which will each have its own event window which will all lead to the same ending event window.
Option 3. will

**Comment by Jauffr** [comment]
The event didn't trigger after 25 years total playing as Theoden. so it shouldn't have appeared in the first ten, but it never showed up during the next 15 years where it could have as I held edoras and the kingdom

**Comment by Jaco-Daan** [comment]
Fixed above issue, ready for testing

**Comment by Jaco-Daan** [comment]
Tested, works. Closing
