### ISSUE TITLE
Early Isengard Rework Review (18.11.22)

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#581]
Alright, I did an early campaign as Saruman - mostly testing the evil route with intrigue rohan, will probably expand this later for the other routes. Keep in mind Isengard is still very WIP! This is just feedback for its continued development

# **GENERAL STUFF, DESIGN PHILOSOPHY**
- Generally try to deal with direct tax bonuses a bit more often than percentage based ones, so theres a solid base for the 75%+ tax increases to work with. Giving flat monthly bonuses will also be harder to abuse for snowballing than purely using percentages
- When dealing out event armies, always remember they are only mildly useful since event armies will be gone after even just a few smaller battles
- Evil Saruman starts with no knights and cant recruit any since they cost a lot of money, fallen istari should have "strength in numbers" instead of "only the strong" like orcs do
- Reduce Sarumans knight recruitment cost by ~50%?
- Make the decisions for AI Saruman easier, perhaps even auto-trigger them at a certain date so players are more likely to see Uruk-Hai and such
- The player will use all of their money on the special decisions for the first 5-10 years of the game, recruiting few MAA and building few buildings during this period. One of the later decisions/ events should give a large reduction to MAA recruitment cost (Perhaps even 50%?), and a lesser one to upkeep
- Consider making Isengard a mountain province so it is more defensive and can use slave mines (which are really really good)

# **GENERAL Pre-ROHAN ASSAULT DECISIONS AND EVENTS**
- Can only use the "Gaze into Palantir" decision once after the initial event
- Random "The Dark Tower" palantir event offers the option to submit to sauron, despite either already being saurons slave or renouncing his overlordship
- "The Two towers" decision gives a bonus (10% levy mainly) so it should cost some prestige instead of giving prestige.
- "The Two Towers" should maybe have a reduced fame requirement so you can take it before conquering Mordor

# **DUNLENDINGS**
- (Unsure if this is the case already) Wulfgars and Thrydans decision should take their opinion of Saruman into account
- Thrydan should not accept vassalization if he is sarumans rival
- "Enemy of the dunlendings" modifier should be lesser. -25 perhaps and a large direct hit with landed rulers.

- Generally, the Dunland unification wars work pretty well.
- Thrydain should not call Saruman to war for his county conquests, for the AI this means he will always raise his troops and thus never get any money to use on decisions
- Creating the Kingdom of Dunland normally should not lock you out of the decision to crown a king and get the empire
- Crowning a King of Dunland should give that king a strong positive opinion buff, like granting a kingdom would
- Becoming "Friend of Dunlendings" should increase cultural acceptance with fallen istari quite a lot 

# **URUK-HAI**
- Generally speaking: "Create Uruk-Hai" decision is a very robust system, works well!
- Rebalance Uruk-Hai berserkers: Increase size to 50, nerf damage and defense
- Remove Uruk-Hai ballista: Saruman already has vanilla siege weapons and (if chosen) special sappers
- Create follow-up event a few years later, summons 3 good uruk-hai commanders/knights (most of yours are other flavors of orc, dunlendings and fallen istari)
- One of the events should convert Isengard (And Riverwatch if controlled) to Uruk-Hai

- Forges of Isengard: instead of 50% gold, give a solid flat gold income buff as well as a lesser percentage based one.
- Forges of Isengard should upgrade Isengard to Deep Storehouses, or give cash if the player already did this

# **ROHAN**
- Influencing King Theodred should require him having a positive +40 opinion of you, or having a hook on him instead of just prestige
- Installing a Puppet in the Riddermark should have "hold the kingdom of the riddermark" instead of completely controlling it, so it can be taken after the conquest without going to war with some leofrings at the borders
- Often times, your new Puppet Ruler in the Riddermark will be completely annihilated by revolting Rohirrim lords
- To reduce peasant revolts, give the Rohirric faith a large fervor hit (-50 perhaps?) if Saruman successfully turns it into a puppet state

# **WHITE HAND**
- Establishing the White Hand should convert all lidless eye Vassals and counties within Isengard, Dunland and Rohan (restricted to these areas so you cant game it by conquering mordor first)
- Decision should require lvl 3 devotion and some piety
- Its a cool idea to found a holy order immediately, but this is actually a huge penalty as it takes away your secondary castle holding in Isengard, thus heavily reducing your income
- As a new upstart faith, saruman should get a conversion speed buff since the default speed is slow (~14 years per county)
- Rework head of faith title ("Overlordship of The Council of the White Hand") to "White Council"?
- Barad-Dur and Minas Morgul should be holy sites since they are your other two options for your tower
- White Hand needs a bit of a tenet rework, hedonistic doesnt really fit Saruman. Check #362

**Comment by jj248** [comment]
Changes made:
- Fixed Gaze Into Palantir decision only being available in year 3001.
- Excluded Saruman and Sauron from submission to Sauron Palantir event.
- Added prestige cost to Two Towers decision, removed prestige reward.
- Reduced fame tier requirement for Two Towers decision by 1 level.
- Dunlending Petty Kings will now always refuse Saruman if rivals and accept if friends.
- Reduced Enemy of the Dunlendings modifier opinion penalty with Dunlendings to -30.
- Candidate Dunlending King will only call Saruman into wars against Dukes.
- Crown King of Dunland now also available if you have the Dunland kingdom title.  Also now need at least one dunlending vassal.
- Added the vanilla +90 opinion buff for granting a Kingdom title on Dunland King decision.
- Becoming Friend of the Dunlendings now gives +50 cultural acceptance between Fallen Istari and Hill/Herd Dunlendings.
- Removed Uruk-hai ballista MaA.
- Added 3 additional decent knight candidates to your court as part of the Berserkers event.
- Riverwatch set to Isengard Dunlending.
- Creating the Uruk-hai now changes culture in Isengard to Uruk-hai to spawn more uruk-hai characters.
- Industrialisation decisions now also add a flat gold bonus to the Barony of Isengard.
- Changed alternative requirement for Installing a Puppet in Rohan from completely controls Rohan to holds title of Rohan.
- Have given new Puppet King of Rohan a big dread boost when AI and have dropped Rohirric faith's fervour on puppet decision.
- White hand faith conversion should now convert more provinces (all lidless eye, 80% of own, 33% of vassals')
- Barad-Dur and Minas Morgul added as holy sites for White Hand.
- Some slight tweaks to White Hand doctrines and tenets.

**Comment by jj248** [comment]
@JukeJukestar - see above.
@BriceLeduc - we might want to add some more appropriate cultural titles for Saruman than 'Overlord'.

**Comment by jj248** [comment]
Related to #536

**Comment by JukeJukestar** [comment]
`decision_bolster_the_uruk_hai has ai_check_interval that's negative or unset. Setting to 0 instead`
error log seems to have found an error with the uruk-hai decision, the AI might not use it from what this looks like

**Comment by jj248** [comment]
Updated
