### ISSUE TITLE
Custom art for "Play as any ruler" button

### ISSUE THREAD

**Issue by BriceLeduc** [jj248/RealmsInExile#585]
1.8 has brought an overhaul of the bookmarks screen, with new art for the "Play as any ruler" button.
Concept for Realms : similar style as vanilla, with a Man, an Elf, a Dwarf and an Orc.
Man or Elf should be female, as the other two are less obvious.

**Comment by jj248** [comment]
Pushing to v4.

**Comment by Jaco-Daan** [comment]
This is really more a concept than something that needs to be done, closing this for now until we get actual 2D artists
