### ISSUE TITLE
Elven holdings

### ISSUE THREAD

**Issue by MathieuGFB** [jj248/RealmsInExile#599]
In the current release, elven holdings have several issues: 

1. It is impossible to build new refugees from the ground outside of the county you begin with. Moreover, it is not tied to the capital county as moving the capital to another county does not fix the issue. 
[Screenshot 1](https://media.discordapp.net/attachments/751097880101650532/1061580414780711032/20230105113154_1.jpg?)
[Screenshot 2](https://media.discordapp.net/attachments/751097880101650532/1061580415007207554/20230105113149_1.jpg?)

2. The task of the elven steward to convert the culture and the religion of a county converts also the holding but gives the new refuge an extra slot to construct buildings. New refugees (sanctuary stage) should have only three of them, but in this case, they have four slots.
[Screenshot 3](https://media.discordapp.net/attachments/751097880101650532/1061581615668678767/20230102224927_1.jpg?)

3. It is impossible to upgrade the elven career more than the second stage.
[Screenshot 4](https://media.discordapp.net/attachments/751097880101650532/1061582240850653224/20230104002115_1.jpg?)

**Comment by jj248** [comment]
I cannot replicate 1:
![image](https://user-images.githubusercontent.com/26043074/213199630-025019ba-d687-468d-893a-5b0a6f8a382c.png)

I've fixed 2.

I've fixed 3.

Back over to testing. @MathieuGFB

**Comment by savagesach** [comment]
1. I am able to build new elven refuges without issues, this works as intended
![image](https://user-images.githubusercontent.com/86676697/221322322-33a2e271-eaba-41f7-8391-c625753c82f4.png)
2. New elven refuges still start with 4 building slots, that needs to be patched
![image](https://user-images.githubusercontent.com/86676697/221330391-c0eebd24-568d-466d-af42-dbbbcca1fad4.png)
![image](https://user-images.githubusercontent.com/86676697/221330419-1d8592af-6036-4aab-986a-dec251920b47.png)
3. I do not know what an elven career is, but assuming it's the elven mines, they can be upgraded to max level now. This works as intended
![image](https://user-images.githubusercontent.com/86676697/221330593-1064b3d8-1af4-4047-8460-d8454b616019.png)

**Comment by Jauffr** [comment]
Interesting. I have not had any issues with extra holding slots while playing Nelornieth 
![Screenshot 2023-02-24 191416](https://user-images.githubusercontent.com/108106660/221330900-463a0a23-e866-4c84-971e-a86916ddc520.png)
![Screenshot 2023-02-24 191426](https://user-images.githubusercontent.com/108106660/221330903-0fa94f11-6674-40e3-9c4a-0bb4884fd9ca.png)
![Screenshot 2023-02-24 191440](https://user-images.githubusercontent.com/108106660/221330906-9b4bf6dd-98a5-4ce7-a978-8612028f7e7b.png)

**Comment by savagesach** [comment]
that's because the issue is not with building new elven refuges, it's with having provinces converted to elven refuges either by settling or by conquering orc provinces

**Comment by savagesach** [comment]
also your own picture proves my point, just look at kugavod again. Kugavod should not have 4 building slots as a level 1 elven refuge

**Comment by savagesach** [comment]
sorry I misread

**Comment by Jauffr** [comment]
The first two pictures are from newly settled lands and the last one is from an extra holding I built

**Comment by savagesach** [comment]
so I've done some more testing and I figured it out. The issue is not with settling by using the councilor, the issue is only with settling by colonization and the orc-elf mechanics
![image](https://user-images.githubusercontent.com/86676697/221331925-0bd8ce9c-e805-40c6-bd66-99c4af52d988.png)

**Comment by jj248** [comment]
Bravo - will move back to bugs to be fixed.

**Comment by jj248** [comment]
These should hopefully now be caught.  Pushing back to testing.

**Comment by Jauffr** [comment]
Issue can be closed. Working as intended for both purged and colonized counties 
![Screenshot 2023-02-28 181033](https://user-images.githubusercontent.com/108106660/222019296-a96e7d6f-8a00-486e-8407-f83aaba5eca9.png)
![Screenshot 2023-02-28 181119](https://user-images.githubusercontent.com/108106660/222019305-8ca13bc1-1bb2-404e-a219-927e314508eb.png)

**Comment by jj248** [comment]
Bravo - merci!
