### ISSUE TITLE
Dol Guldur - Men at Arms

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#602]

**Comment by jj248** [comment]
Just to note, I'm not touching the two existing units for them in the MaA rebalance, given they could benefit from a fresh look when thinking about the unit roster for DG as part of this.

**Comment by jj248** [comment]
Added Morgul Wights to all undead and also added Blighted Trappers and Giant Spiders specifically to an undead character ruling the Dol Guldur county.

Ready to test.

**Comment by JukeJukestar** [comment]
closing for now since they are working correctly, maybe we can get art for them in the future.

**Comment by Remerod** [comment]
I disagree, i think art is vital and missing it, especially for super unique units as wights hurt us, we should get some art even if it's bad

**Comment by Remerod** [comment]
they've gotten art now so i'm closing this (i guess they've been tested to)
