### ISSUE TITLE
Wilderness characters appear in events

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#611]
Wilderness characters can appear in events, especially when template characters are created using culture and faith of a county.

![image](https://user-images.githubusercontent.com/26043074/213015325-c062c7b3-6d00-4b83-a985-c108df3a693d.png)

**Comment by jj248** [comment]
It might be time to render the wilderness characters and kill all but the OG Wilderness character on an annual pulse.

**Comment by VectorMaximus** [comment]
Yep. Simplest path to me is give them a small namelist for the culture (with the OG Wilderness's name having a 0 chance of showing up - see vanilla weighting for names appearing in cultures), have them render, then kill on a yearly pulse.

**Comment by jj248** [comment]
I'm just going to keep a list of affected events here for testing purposes:

- chancellor_task.1001
- ep1_flavor.2040

**Comment by BriceLeduc** [comment]
While using the diplomacy lifestyle I regularly receive letters from Wilderness characters

**Comment by jj248** [comment]
Have made it so that Wilderness characters are actually rendered and named now, should they be generated by events.  Not ideal, but much better than invisible nameless characters.  They should look pretty poor and basic and be culled in the regular culling pulse of Wilderness characters.

![image](https://user-images.githubusercontent.com/26043074/219665714-4ad8917c-0063-48b7-a854-26b65c532163.png)

I've also pushed a temporary naming of the wilderness title to 'The Wilds' which renders that name over wilderness on map to get feedback on what people think of this.  I thought I'd hate it, but it's not as bad as I thought it'd be...

![image](https://user-images.githubusercontent.com/26043074/219666106-b1371471-0314-4097-b2f7-b20254de37b1.png)

Passing to testing for feedback on gameplay.

**Comment by BriceLeduc** [comment]
![image](https://user-images.githubusercontent.com/98077354/226206858-2138f063-cb36-450a-8b59-f40ca1ba4ee2.png)

**Comment by RedArkady** [comment]
I'm still getting wilderness offering to exchange letters.

**Comment by BriceLeduc** [comment]
> I'm still getting wilderness offering to exchange letters.Just pushed a fix for that
