### ISSUE TITLE
Good-Aligned Isengard Content

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#612]
Content for Isengard who does not go evil.

Also to do for existing evil content:

- [x] Decision to generate Uruk-hai characters.
- [x] Give a hook on Grima.
- [x] Fix new court lack of character in event.
- [x] Ensure all evil content localisation done (including isengard.0015 and isengard.0016 and isengard.0289). Closing here, covered in #839 
- [x] Fix timeout on Rohan war.
- [x] Review Orthanc Special Building + Loc.
- [ ] Review old content.
- [x] Any future war with Rohan... within 5 years **of it starting**.
- [x] Differentiate 'Mines of Isengard' modifiers.
- [x] Add imprisonment to Humble Isengard.
- [x] Make Grima unable to marry.
- [x] Have event war trigger cancel any truce.
- [x] In Rohan victory against Saruman - give Isengard to them and clear modifiers.
- [x] Make sure player Sauron is asked if they want to intervene.
- [x] Trigger Puppet off if Rohan war begun.
- [x] Only show Two Towers if go against Sauron.
- [x] Consider granting of titles across Anduin if Sauron is player.
- [x] Horror second option show chances of failure.
- [x] Humble Mordor should destroy head of faith title for Sauron, unland Nazgul. #796

**Comment by jj248** [comment]
Also to do:

- [ ] Give Orthanc the Gondorian Court.

**Comment by JukeJukestar** [comment]
Why do we want the Nazgul to stay lidless eye? I thought they would become servants of saruman if he humbles mordor

**Comment by JukeJukestar** [comment]
isengard.0015 and isengard.0016 are unlocalized

**Comment by savagesach** [comment]
![image](https://user-images.githubusercontent.com/86676697/233745714-263ffd0f-d1aa-4f6d-b761-22a20a84a77d.png)
just wanted to mention that good isengard is unable to fully upgrade the special building

**Comment by savagesach** [comment]
I'd also suggest that the ainur faith be changed to equal from male dominated. Previously it didn't matter since saruman always went evil, but if the religion is now relevant for good saruman, I think this should be updated.
![image](https://user-images.githubusercontent.com/86676697/234110910-07f61207-c94e-442f-817b-a99c94394ecd.png)

**Comment by savagesach** [comment]
![image](https://user-images.githubusercontent.com/86676697/234112419-feae1076-9b24-4c71-be70-dcb353b9d047.png)
![image](https://user-images.githubusercontent.com/86676697/234112831-4f6590d3-3556-4c42-8323-b36f1665a49b.png)
also I'm not sure if you know or not, but the white council code currently only works if you are best friends, not normal friends

**Comment by jj248** [comment]
Huh - good spot.  Those triggers look to be misbehaving, so I've just set this to now require a high opinion of Saruman.

**Comment by savagesach** [comment]
cool, also I think the tuition fees should apply for the isengard academy, not just the new academies

**Comment by jj248** [comment]
> cool, also I think the tuition fees should apply for the isengard academy, not just the new academies

It does, doesn't it?

**Comment by jj248** [comment]
![image](https://user-images.githubusercontent.com/26043074/234138858-666983de-354f-4923-acca-712cd9a8533a.png)

**Comment by savagesach** [comment]
oh yeah you're right, I just didn't see it

**Comment by Jaco-Daan** [comment]
Jaime said he'll create another issue whenever he gets around to fleshing the good-aligned Saruman content, closing
