### ISSUE TITLE
Starting trial by combat results in a CTD

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#622]

**Comment by BriceLeduc** [comment]
Also happens with humans

**Comment by jj248** [comment]
Last part seen to work for an elf:

![image](https://user-images.githubusercontent.com/26043074/215782212-2e5fee13-08f6-42e7-bf5f-32a66686fb27.png)

**Comment by jj248** [comment]
> Also happens with humans

I can't replicate for humans... do you know who it broke for? 
![image](https://user-images.githubusercontent.com/26043074/215783360-3fc42c61-d1cd-4aac-84ec-f01e8a4ac76b.png)

**Comment by BriceLeduc** [comment]
I've seen it happening during the post song battle duels, both with Elves and Humans

**Comment by BriceLeduc** [comment]
And standard duels too, I've seen it with Gondorians, Grimbeorn, the king of Dale, etc

**Comment by jj248** [comment]
OK - I think I have a good guess as to the cause of this.  Commenting these lines out from 'configure_start_single_combat_effect' stops the CTD: 
![image](https://user-images.githubusercontent.com/26043074/215786163-4717e836-7e55-4ff5-82d2-6ce45527a06d.png)

I assume this has something to do with bows being added to set_signature_weapon_effect, so will leave it to you to investigate @BriceLeduc.

> I've seen it happening during the post song battle duels, both with Elves and Humans

I'm pretty sure that this uses single combat too, so it's not surprising.

**Comment by BriceLeduc** [comment]
that's right, it's firing configure_start_single_combat_effect

**Comment by BriceLeduc** [comment]
yes, I'll have a look

**Comment by jj248** [comment]
I can't reproduce this anymore, so it looks like the change Brice made has fixed.  Passing to testing to confirm.

**Comment by Commander-Sol** [comment]
Confirming it still occurs, but only when your character does not have a weapon artefact equipped. Tested both ways, with different characters and weapons.

**Comment by JukeJukestar** [comment]
Still happening.

**Comment by jj248** [comment]
Pushed a potential fix for this.

**Comment by JukeJukestar** [comment]
```[12:29:01][jomini_script_argument.cpp:189]: Compiling source for configure_start_song_battle_effect failed for unknown arguments: sb_INITIATOR, sb_ATTACKER, sb_DEFENDER. At common/scripted_effects
[12:29:01][jomini_eventtarget.cpp:548]: More than one colon in event target link 'var:scope:duel_loser' at  file: common/scripted_effects; fix_variable_error line: 4
[12:29:01][pdx_persistent_reader.cpp:252]: Error: "Unknown trigger type: var:scope:duel_loser, near line: 5" in file: "common/scripted_effects; fix_variable_error" near line: 6
[12:29:01][jomini_script_system.cpp:263]: Script system error!
  Error: set_variable effect [ Invalid script name scope:duel_loser was used ]
  Script location: file: common/scripted_effects; fix_variable_error line: 7
[12:29:01][jomini_eventtarget.cpp:548]: More than one colon in event target link 'flag:scope:duel_loser' at  file: common/scripted_effects; fix_variable_error line: 7```

found this in error log, may be relevant.

**Comment by savagesach** [comment]
I tested trial by combats and they are still broken. They cause ctds when you click may the best man win

**Comment by savagesach** [comment]
I tried verifying game files to see if that would fix it, but now they cause ctds right after challenging people to trial by combat

**Comment by jj248** [comment]
Okay, let's try again.  Hopefully this fixes it!

**Comment by Jauffr** [comment]
Combat still crashes the game. As soon as I click "let the best man win" The game crashes violently
![Screenshot 2023-02-28 180140](https://user-images.githubusercontent.com/108106660/222018282-bf3d394f-e528-490b-bf35-5fbd38214418.png)
![Screenshot 2023-02-28 180204](https://user-images.githubusercontent.com/108106660/222018286-1f67cb17-9744-499a-8f39-2f3050a30b9f.png)

**Comment by jj248** [comment]
FFS. *pain*

**Comment by Chief305** [comment]
i think this may be fixed because trial by combats dont crash my game ive tried with four characters

**Comment by savagesach** [comment]
I can confirm trial by combats are definitely not fixed. I tried it with the new git update and it still resulted in a CTD

**Comment by jj248** [comment]
I've tried with multiple characters through multiple ways of starting a combat.  And I can't reproduce it at all.  I need specifics of how to reproduce the error or I'll never be able to fix it. :(

**Comment by savagesach** [comment]
![image](https://user-images.githubusercontent.com/86676697/229380321-193e9330-7efa-4e68-9084-6fda35c4de3e.png)
![image](https://user-images.githubusercontent.com/86676697/229380344-81a773e8-dd84-4e76-bf9a-580ade53c045.png)
literally the first trial by combat I attempted resulted in a ctd when I clicked may the best man win

**Comment by BriceLeduc** [comment]
The crashes only happen when the "May the best man win" option is selected. In the following event, the duelists wear their armour, which they don't in the first event (they are however already holding their weapon).
The crash may come from a clothing asset

**Comment by savagesach** [comment]
![image](https://user-images.githubusercontent.com/86676697/234406590-1dfdf02b-761b-4c62-b131-c7d19ff86a39.png)
![image](https://user-images.githubusercontent.com/86676697/234411737-e2c672d1-1a6b-433a-802d-d4cd1092d208.png)
![image](https://user-images.githubusercontent.com/86676697/234412225-e4ed0678-2292-48c2-847c-fc14d67d655e.png)
Trial by combats work now, although they feel a lot less common than they used to be.

**Comment by jj248** [comment]
Keeping this open given significance and unpredictability of it all.  Keep an eye out for it please people.

**Comment by savagesach** [comment]
can we lower the priority of this issue to medium please? critical makes this issue seem really important when realistically the issue's already been fixed and we're just looking for crashes now as we play

**Comment by savagesach** [comment]
I have not had a trial by combat ctd in a while, but it can still be an issue. As a result, I decided to lower the priority for now
