### ISSUE TITLE
Change "Subjugate Nafarat" decision, have Empire of Abrakhan founded if Empire of Nafarat is held

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#634]
In almost every single game currently, the Black Viziers descendants manage to found the Empire of Nafarat, but they dont get the empire of Abrakhan. This has been an issue since we released far harad - you can make the empire of nafarat before ever taking the decision to get abrakhan.

My suggestion is to remove the empire title from the "Suburgate Nafarat" decision and instead just make it so if a Cult of Zigur/ Lidless Eye character holds e_nafarat it flips to e_abrakhan.

Another change we should make is so the "Golden King" head of faith title can only be made by a Nazgul, so the Black Vizier isnt considered "Golden King" anymore.

I realize Abrakhan very much isnt the focus of 3.0, but it should be in a working state when we release instead of being broken.

**Comment by jj248** [comment]
Suggest we pick this up again in v4.

**Comment by JukeJukestar** [comment]
implemented a while ago, whoops! thanks jauff for the reminder
