### ISSUE TITLE
Valinor Warfare - Valinor Rulers attack eachother

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#636]
![image](https://user-images.githubusercontent.com/76008882/215797386-b10f71bd-db8c-4a95-8f33-5f41d22ffd0a.png)

In this example they are using the ducal conquest CB, which is unlocked via a diplomacy perk.

**Comment by jj248** [comment]
Should hopefully be fixed.  Ready to test.  If you spot any wars, make sure to note the type.

**Comment by Remerod** [comment]
I played for 10 years (2 times) as Ar-adunaim and then a third time as a **observer** for a 100 years and they didn't declare on each other, but some wacky stuff happened (like Lotlorien inheriting Tirion, check details bellow)

i couldn't see any wars break out

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/219289423-afdf0aaa-8fd8-458c-be74-2ebd7d3da7c6.png)
I could personally(as a player in valinor) make a claim in valinor 

![image](https://user-images.githubusercontent.com/79544635/219289558-21053f21-6582-49d9-b163-cbc0aa0d3096.png)
Which made me be able to declare a war

![image](https://user-images.githubusercontent.com/79544635/219292755-bbac45bb-a096-4e1c-9397-4039b85f7c98.png)
Peasant Revolt in Paradise

![image](https://user-images.githubusercontent.com/79544635/219291753-26c1c742-d5dc-4cd3-b056-d58159e033ee.png)
in my observer run i saw that Tol Eressëa made claims again Bar Monthil on the western tip of the Gondorian empure de jure

![image](https://user-images.githubusercontent.com/79544635/219296288-2f29b21c-c7c9-457e-9f73-bd6adc6819f4.png)
As Tirion also seems to have done later

![image](https://user-images.githubusercontent.com/79544635/219296924-1ece9670-20f3-4054-82f6-9ff3dbfb6ad3.png)
Also we have two rulers in Valinor with the nickname; "the Rhudaur Explorer", i assume this is from the sailing events? maybe we need to disallow those for Valinor?

![image](https://user-images.githubusercontent.com/79544635/219297296-25c896c9-d6b6-498a-ac8f-af61a5815819.png)
hahahahahahahahaha... maybe we should just disallow nicknames if possible? :P

![image](https://user-images.githubusercontent.com/79544635/219300587-bc8094fc-f911-4653-91cb-4250b8de7b6f.png)
lol

</details>

**Comment by jj248** [comment]
Moving back to Bugs.  I'll take a look.

**Comment by JukeJukestar** [comment]
Fixed Rhudaur Explorer btw (I think)
