### ISSUE TITLE
Wilderness counties don't localise on upgrade

### ISSUE THREAD

**Issue by RedArkady** [jj248/RealmsInExile#643]

**Comment by RedArkady** [comment]
Province title doesn't change from 'Wilderness' to e.g. 'Lordship' on upgrading.

![image](https://user-images.githubusercontent.com/20355423/216434468-d67f9f5a-e732-48f9-8808-0ed375a2e474.png)

**Comment by jj248** [comment]
Should be fixed, ready to test.

**Comment by BriceLeduc** [comment]
![image](https://user-images.githubusercontent.com/98077354/218255617-e2de0ee2-af28-48ef-9461-27204bf2f1bf.png)
All secondary baronies of colonised counties retain the "ruin" CoA

**Comment by Jauffr** [comment]
This is almost fixed. Only thing remaining is that any secondary holdings you build will be given the ruins COA
![Screenshot 2023-03-22 155434](https://user-images.githubusercontent.com/108106660/227047676-dd41fefa-c554-40e2-bcb1-567c53c07647.png)
![Screenshot 2023-03-22 155446](https://user-images.githubusercontent.com/108106660/227047683-f7b04909-fcf0-469e-81a4-64544c57dc66.png)
![Screenshot 2023-03-22 155457](https://user-images.githubusercontent.com/108106660/227047685-92737f6f-f945-41df-be64-519cf947fa6a.png)
![Screenshot 2023-03-22 155601](https://user-images.githubusercontent.com/108106660/227047686-de089abf-a7e2-4d82-a02a-11ebb50b703f.png)

**Comment by Remerod** [comment]
I concur on this, literately tried this yesterday but never got around to check the secondary holdings CoA things, I'll move this to Bugs :)

**Comment by jj248** [comment]
OK - tweaked so that all baronies in the county should get a CoA generated, ready to test.

**Comment by savagesach** [comment]
![image](https://user-images.githubusercontent.com/86676697/233799675-523b3b2b-6046-4c06-9a39-6a0954d6bf8b.png)
![image](https://user-images.githubusercontent.com/86676697/233799683-b185cc26-18a7-4752-8918-efef3a5e200e.png)
![image](https://user-images.githubusercontent.com/86676697/233799704-b599bdd3-f06d-421f-9293-2d8d357e8243.png)
secondary baronies in counties now have generated coas

**Comment by jj248** [comment]
Thanks - closing.
