### ISSUE TITLE
Lore characters prone to getting immersion-breaking stress coping mechanisms

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#650]
I've added a blocker for AI important lore characters to stop them from getting stress threshold effects to avoid the likes of Drunkard Aragorn and Rakish Faramir.

**Comment by jj248** [comment]
For future reference, character flag to use in histories is:

> ai_immune_to_mental_breaks

Ready to test.

**Comment by JukeJukestar** [comment]
I think this should be the case for AI only - let the player deal with stress normally

**Comment by VectorMaximus** [comment]
It is - it only exempts the characters when controlled by AI.

**Comment by savagesach** [comment]
I was testing the effects of stress on elves and if you want players to experience stress breaks, it's not working at all. I couldn't experience any stress breaks even when I gave myself 300 stress with commands.
![image](https://user-images.githubusercontent.com/86676697/221401655-33f89dcd-5aaf-4c36-a2e2-f3bb89291389.png)

**Comment by jj248** [comment]
This is a seperate issue to elven stress. This issue deals with ensuring certain lore characters don't get stress break traits as the AI.

**Comment by Jauffr** [comment]
I havn't seen any drunkard Saruman's or Thranduils in weeks now, while I used to see them all the time. I have been actively paying atention to this issue in my observer games over the past week and can not remember ever seeing a rakish Galadriel within the past month

**Comment by savagesach** [comment]
I also agree with this, I haven't seen any issues either

**Comment by jj248** [comment]
Great!  Enough for me to be happy with closing this.
