### ISSUE TITLE
Recover Calenardhon Decision Overhaul

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#657]
The decision is rather clunky and missing some important checks in my opinion.

- Does not account for if Gondor has a truce or Alliance with the target (be it the king of rohan or their liege)
- should trigger at all if Saruman uses intrigue to make the King of Rohan his puppet, since they are still in power?
- The code to find a new rohirrim king to install should be made better.
- There should be a cost
- Perhaps there should be a "cooldown" before it can be used so Gondor cannot fire it immediately after someone claims Rohan before they have any time to consolidate it? Unsure about the balancing there

**Comment by RedArkady** [comment]
- it does account for a truce. The decision can't be launched if you have one, and it tells you why in the tooltip in the normal way.
- the puppet thing should be accounted for in the decision criteria. The Decision won't show if the k_rohan title holder is Rohirric, has Dunedain heritage, or is of the House of Eorl.
-"The code to find a new rohirrim king to install should be made better." - there is no such code.
-We could add a cost, open to suggestions as to what would make sense here.
-I don't think a cooldown is necessary, but if it's demonstrably creating problems then we can reconsider, but let's not mess with it while you're unsure.

**Comment by jj248** [comment]
Ready to test.

**Comment by RedArkady** [comment]
The CB is launching but the war is immediately invalidated. Is this because it's targeting the king of Rohan rather than his liege (Saruman)?

![Crusader Kings III Screenshot 2023 02 21 - 18 12 03 60](https://user-images.githubusercontent.com/20355423/220426589-93030f8a-f4a1-418d-bd46-82afefb668c6.png)


![Crusader Kings III Screenshot 2023 02 21 - 18 09 39 24](https://user-images.githubusercontent.com/20355423/220426620-53851251-966f-421f-85a7-a2fb402b034c.png)

**Comment by RedArkady** [comment]
Yeah I think that's it. The decision works if you console Rohan independent of Saruman before taking the Decision.

**Comment by jj248** [comment]
I've hopefully fixed the above by now declaring war on the top liege if Rohan holder is not independent.

**Comment by savagesach** [comment]
the reclaim calenardhon decision is broken. It only shows up if Saruman personally takes Rohan for himself. If Saruman decides to give the kingdon of rohan to anyone with rohirrim culture, the decision won't appear for Gondor. The decision needs to check if rohan has a liege, and if so what that liege's culture and religion are

**Comment by savagesach** [comment]
![image](https://user-images.githubusercontent.com/86676697/221269637-385baa8e-12f5-40c6-9005-18d1312037e8.png)
![image](https://user-images.githubusercontent.com/86676697/221270031-f5f68cc3-81c0-4fbd-973c-376f189e5fbb.png)
notice how the decision disappeared when grima became king

**Comment by jj248** [comment]
This cancelled because Grima is Rohirrim.  I've now updated the triggers so that it won't show if the ruler is Rohirrim and non-evil faith, rather than just Rohirrim.

**Comment by savagesach** [comment]
This works as intended
![image](https://user-images.githubusercontent.com/86676697/222007779-ac50f8d4-b58f-4eda-a9ad-b471df60da63.png)

**Comment by jj248** [comment]
Excellent - I'm wary to work more on this, so if it sounds like it's in a decent spot now, let's close and act on any more feedback that comes back on it as a separate issue.
