### ISSUE TITLE
Ruler Designer Review

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#658]
Actions following review:

- [x] Some ethnicities start as bald - likely an issue in the Custom Hair file.
- [x] Add cultural description tooltip
- [x] Unnamed and visible Wilderness Culture / Faith
- [x] Check all v3 ethnicities are present
- [x] Add basic Dwarf ethnicity
- [x] Elves can look old or fat in designer and change hair colour
- [x] Orc beards appear for elves

**Comment by jj248** [comment]
Done and ready to test.

**Comment by Remerod** [comment]
* Some ethnicities start as bald - likely an issue in the Custom Hair file.
-i don't understand... some etnicties looks bald in the ruler design? please clearify

* Add cultural description tooltip
-do you mean this?

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/219305551-aeabfeb6-cf1d-4b56-887f-b613b5412457.png)

</details>

* Unnamed and visible Wilderness Culture / Faith
-i don't get it... you suppose to be able to play wilderness in ruler designer???? please clearify

* Check all v3 ethnicities are present
-which ones?

* Add basic Dwarf ethnicity
-while i can find a culture in the ruler designer i cant find a ethnicity (please also write what it's called)

* Elves can look old or fat in designer and change hair colour
-Seems to work fine 👍 

* Orc beards appear for elves
-does not work and in fact i can't seem to find the orc beards i did anymore for any character (well i only tested orcs)

I've tested what i think was asked of, but it was super unclear what's needed tested, "ready for testing" from a checklist is not descriptive on what's need tested, please write a more detailed version on what's need to be tested

**Comment by jj248** [comment]
Apologies if the above was unclear.  It was my action-list for things that needed to be addressed / fixed.  So specifically what needs to be tested:

- [ ] No ethnicities in Ruler Designer generate as always bald.
- [ ] The culture's description now appears in the culture tooltip.
- [ ] We had no localisation for Wilderness culture / faith, so these should now no longer be blank.  Unfortunately, we can't make these unselectable.
- [ ] Ethnicities are present covering the new regions: Elven types, Rhunnic, Northron.
- [x] Dwarf ethnicity we didn't go for in the end, saving that for v4.  They're just using Dunedain for now.
- [ ] Elves can look old or fat in designer and change hair colour
- [ ] Elves no longer get beards when generating new looks for them.

**Comment by ryyde** [comment]
Sindar still get beards generating new looks.

**Comment by jj248** [comment]
> Sindar still get beards generating new looks.

Really?  Are you _absolutely_ sure?  I cannot replicate this at all!

**Comment by BriceLeduc** [comment]
> Sindar still get beards generating new looks.

If you mean Cirdan that's on purpose

**Comment by savagesach** [comment]
I do not understand what I'm supposed to test here. the issue says all tasks are done, but jamie's comment says there's still some things left to test.
