### ISSUE TITLE
Black Breath revamped

### ISSUE THREAD

**Issue by BriceLeduc** [jj248/RealmsInExile#662]
Black Breath has been moved from a modifier to an illness. As all illnesses, it should only affect Orcs and Men

It can be acquired in one of 3 ways : 
- losing a single combat against a Nazgûl
- as a knight or a commander against a Nazgûl (same as being wounded/maimed/killed in battle)
- through the Black Breath sorcery spell.

It can only be healed by (taking into account either the liege or the court physician): 
- An Elf
- A member of the Elrosionath dynasty

Only the risky or mystic treatment options will cure it completely.
No-one heals from the Black Breath on their own.

What needs to be tested : 

- [ ]  Does the illness occur in all 3 situations ?
- [ ] Are only Orcs and Men affected ?
- [ ] Does the game recognise it as an illness (firing physician events etc)
- [ ] are the conditions for healing met ?

**Comment by JukeJukestar** [comment]
![image](https://user-images.githubusercontent.com/76008882/218106049-4fa38bdc-a497-481e-af0e-88353615dc35.png)

The old modifier is generating a lot of errors.
As for the actual trait, it seems to work in regards to loc, effects etc, but its hard to test how good it actually works. Will keep you updated

**Comment by BriceLeduc** [comment]
good spot, I'd missed one § to edit in the sorcery file. That should now be fixed

**Comment by Jermanlordy** [comment]
i have no idea how this works or how to test it would you mind elaborating on how to get and cure it?

**Comment by BriceLeduc** [comment]
I thought the initial post was clear. It can be acquired :
 - by losing a single combat against a Nazgûl 
 - during battle (same as "wounded" or "maimed") if the character is either a knight or a commander and there's a Nazgûl in the other army
 - through one of the sorcery spells.

If you want to check the healing mechanics, just add the trait black_breath

**Comment by Remerod** [comment]
So in the https://github.com/jj248/RealmsInExile/issues/661 i've stated that `through the Black Breath sorcery spell.` spells don't show whom they affect so currently that's hard to test before we fixing that up :)
