### ISSUE TITLE
Elvish Temples bugged - Incomplete trigger

### ISSUE THREAD

**Issue by ryyde** [jj248/RealmsInExile#669]
![9](https://user-images.githubusercontent.com/124939126/218324697-22e47db4-91e9-4e54-9858-ab754acc3dde.jpg)

Elven

**Comment by ryyde** [comment]
Also i don´t know why my heir lost the third pillar of culture, its the court language. But maybe i am not informed of that mechanic.

**Comment by JukeJukestar** [comment]
Bit more of a description would be nice. How did you obtain this temple? Elves arent supposed to make temples Im pretty sure.
Im assuming its from a Royal Court Event?

**Comment by jj248** [comment]
Exactly - more details please!  Also be sure to assign new bugs to the v3 project, otherwise they're just going to get lost in the ether.

**Comment by ryyde** [comment]
This temple was built by itself, i didnt recognize anything until it was there sorry. "Hold Court" dialogue maybe was the reason.
All i also see it that its disabled and not sure why. Should not happen.

**Comment by Remerod** [comment]
@jj248 (Jamie) testers can't assign rolls unless they have privilege change/develop the mod (which Juke for instance have) Any tester (reading this) making a bug issue should ping me or Juke to add them ;)

**Comment by Remerod** [comment]
> This temple was built by itself, i didnt recognize anything until it was there sorry. "Hold Court" dialogue maybe was the reason.
 All i also see it that its disabled and not sure why. Should not happen.
 
 it does seems likely it's a court event, to bad you couldn't remember which

**Comment by ryyde** [comment]
maybe if you look close you see the player husband owns it not me

**Comment by Jauffr** [comment]
I have not seen this happen in a month. Is it worth keeping this issue open now? I think it should at the very least be lowed to a very low priority now, if not closed. I do think it should just be closed now though

**Comment by BriceLeduc** [comment]
Issue looks solved from tester reports
