### ISSUE TITLE
Review orc purge on title gain

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#671]
This code seems to be quite inefficient with user reports of CTDs or hanging game for long periods.

Furthermore, it appears to be throwing exceptions to the error log.  See: https://discord.com/channels/751097183448727552/932061945350197279/1074691182090780744

**Comment by jj248** [comment]
https://discord.com/channels/751097183448727552/751097696223494224/1077755387358486578

**Comment by jj248** [comment]
I've pushed a tweak to the code that should hopefully improve stability.  Need to test that purge still works when good faiths take over orc lands, and whether it appears to be faster / more stable.

**Comment by Jauffr** [comment]
Will not purge when a good faith conquers orcish counties. Elves still function however

![Screenshot 2023-02-28 175609](https://user-images.githubusercontent.com/108106660/222017874-035d9d9b-6882-4da2-a049-c45297c6401f.png)
![Screenshot 2023-02-28 175724](https://user-images.githubusercontent.com/108106660/222017877-cebe4656-ba87-451f-ba0e-46fcccbb2b9b.png)
![Screenshot 2023-02-28 175941](https://user-images.githubusercontent.com/108106660/222017883-d2f30c2d-3318-40fd-92ab-752d018da60d.png)

**Comment by jj248** [comment]
> Will not purge when a good faith conquers orcish counties. Elves still function however

Apologies, I should have been clearer with my definition of the issue.  This is for characters when taking over new lands.  It should be deposing any new orc vassals and then killing any remaining orc courtiers / guests or letting them escape to the character pool.

**Comment by Jauffr** [comment]
I see. I was still thinking about the conversation that happened a day ago about good faith characters converting orc counties the same way elves to. So this made me think it was referring to that. I can confirm that this functions as intended as well though. In my time playing as the Framlings I had that happen plenty. Juke always escaped to the wilds though

**Comment by jj248** [comment]
This only got updated last night.  The aim was to optimise what we already had, rather than add new functionality.  Hence this comment above:

> Need to test that purge still works when good faiths take over orc lands, and whether it appears to be faster / more stable.

**Comment by Jauffr** [comment]
Orc purge on title gain works for good faiths as well as elves now. I think this can be closed
![Screenshot 2023-03-22 162516](https://user-images.githubusercontent.com/108106660/227052190-8335b495-2634-426c-bd30-70c2fdff02a0.png)
