### ISSUE TITLE
Make AI Nurniags not faith convert Nurnoth provinces

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#680]
The Nurniag AI should be tweaked so they dont faith-convert Nurnoth provinces - it doesnt make sense for them to impose the Nurniag faith on the Nurnoth

**Comment by jj248** [comment]
Fix implemented - let me know if they stop doing it.  Over to testing.

**Comment by Jermanlordy** [comment]
The Nurnoth there religion is still being converted but not to the Nurniag Religion but to the Shakhburzdagi religion

**Comment by jj248** [comment]
I suggest we don't do any more on this personally - any objections?

**Comment by JukeJukestar** [comment]
nah lets close
