### ISSUE TITLE
Vanquish Darkness Wars Bugged

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#695]
- They dont have a Target title. This means that conquering the objective does not give any ticking warscore, neither does not conquering it.
- The resulting rulers have 0 control on their counties. They should be given a good ammount of control on each county as well as a some starting cash
- The faith and culture choice should be improved. Ill try to tackle this personally

**Comment by jj248** [comment]
I'm confused - it looks like they're getting ticking warscore? 
![image](https://user-images.githubusercontent.com/26043074/220089088-8817336f-0a04-4f64-8f42-d15207f51710.png)
Ditto on the Duchy version:
![image](https://user-images.githubusercontent.com/26043074/220089774-cbcb6cfd-8918-4b6e-9155-41563f54ef2a.png)

**Comment by jj248** [comment]
Made a commit to cover the first point here.

**Comment by savagesach** [comment]
while the cb now works for liberating an entire duchy, I still can't see any target titles on the map
![image](https://user-images.githubusercontent.com/86676697/221114842-b563269f-a5ef-4686-acc9-834d9c90a0f4.png)
![image](https://user-images.githubusercontent.com/86676697/221114889-0a93b6cd-c2e2-4942-b598-e6eac53078b5.png)

**Comment by jj248** [comment]
Huh.  Odd.  I'll look into it...

**Comment by jj248** [comment]
Looks like this is just because they don't give a title to the attacker on victory, which is what is used to highlight the provinces.  I've tweaked to make this show regardless.

I've also made a couple of changes while I'm in there, restricting to neighbouring lands and to allow nearby defender-faith rulers to jump in.

Pushing back to testing.

**Comment by Jauffr** [comment]
Issue can be closed. It shows the correct holding you are warring for and it gave the option for neighbors to join if they were withered court. He almost did, but I won the war too quickly

![Screenshot 2023-02-28 050501](https://user-images.githubusercontent.com/108106660/221853522-7af63c31-05de-4e8e-9902-8069c78bd79a.png)
![Screenshot 2023-02-28 051014](https://user-images.githubusercontent.com/108106660/221853537-9a3641eb-eb06-47c5-baf4-d6538c6b0741.png)
