### ISSUE TITLE
Path of the Dead wilderness

### ISSUE THREAD

**Issue by Remerod** [jj248/RealmsInExile#697]
**Missing Mechanic Explanation**

So apparently we've made it so you can't build holdings in the baronies of "Path of the dead" and Dwimorberg in the county of Dunharrow (Gríma's hood). And while these seems lore fine to me and all there really isn't really anything that tell the player any reason why that they can't build a holding there (other then maybe a personal guess if you know the lore).

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/219986780-abbbbcbb-4761-4ad7-bbc7-d8a11a7c3c43.png)
Showing you how it looks in the province of question

![image](https://user-images.githubusercontent.com/79544635/219986864-dabcac29-d289-487c-a4f7-d5f9b0f82d55.png)
picture telling you how it normally looks

</details>

This issue was brought up by an user on discord, and i have discussed this with Vector and we both agreed that this need to be rectified this for the great masses of our mod and make this lore flavour know the them. 
Suggestion; maybe a red text coming up when you click on the holding construct button explaining why you can't build there or some modifiers explaining as long these are here no holdings can be constructed in these baronies. 

![image](https://user-images.githubusercontent.com/79544635/219987450-b3d2053c-0264-4837-96bc-36e250673018.png)

**Comment by jj248** [comment]
I'm going to remove this altogether as it feels somewhat arbitrary, even if a little lore friendly.  I think gameplay outweighs lore here.

**Comment by RedArkady** [comment]
Should the Path of the Dead be wilderness with a unique blocker?

**Comment by VectorMaximus** [comment]
I can see the argument there - it wouldn't cause any major ugly border issues to my knowledge either.

**Comment by RedArkady** [comment]
If no-one gets there first I can implement that at the weekend and we'll see how it looks.

**Comment by jj248** [comment]
My main argument against this is scope creep. It'd require more unblocker events, and reworking titles / associated history, and province map.

Maybe best left until v4 when we're looking at mountains anyway?

**Comment by VectorMaximus** [comment]
Sure, that's a fair counterpoint. Revisit in 4.0 seems reasonable.

**Comment by RedArkady** [comment]
Just a quick check while we're talking about it... can the ability to colonise a particular wilderness county be easily locked to a particular dynasty? Because if so we could just lock it to the Line of Isildur without any actual blockers or related events, and do a bigger rework later, maybe with event troops. I'd be happy to do the history work. Very happy if you'd prefer to kick it all to 4.0 though.

**Comment by jj248** [comment]
> Just a quick check while we're talking about it... can the ability to colonise a particular wilderness county be easily locked to a particular dynasty? Because if so we could just lock it to the Line of Isildur without any actual blockers or related events, and do a bigger rework later, maybe with event troops. I'd be happy to do the history work. Very happy if you'd prefer to kick it all to 4.0 though.

I'm going to be strict on limiting new content this close to a proposed release date, especially with so many outstanding bugs in testing etc.  So let's push to v4 and deal with it then.  But agreed, it should be possible and feels like a neat tie-in to the lore.

**Comment by jj248** [comment]
Closing as this should be captured in White Mountains mapping.
