### ISSUE TITLE
Wilderness gets random claims through chancellor event

### ISSUE THREAD

**Issue by blackbird5598** [jj248/RealmsInExile#698]
had a event where my chancellor had accidentally given the men of the wilds a claim on one of my titles

![image](https://user-images.githubusercontent.com/125709421/219988205-32e5cedb-f63e-4843-af8d-73140970de28.png)
lor had accidentally given the men of the wilds a claim on one of my titles

**Comment by Remerod** [comment]
in the future try to have a descriptive text of why it's wrong, nothing in the title or your text actually describe a problem, you only describes what's happening, now i can easily guess what this event mean, but a tester should never make a report where you have to assume or guess what they mean

**Comment by jj248** [comment]
I've pushed a fix.  In this case the description was enough for me to get the idea of the problem.  Pushing to testing.

**Comment by JukeJukestar** [comment]
Note that we also have to check the reverse option - you getting a random claim on a wilderness county due to incompetent wilderness chancellor

**Comment by Remerod** [comment]
I've not seen this since the fix, nor have i heard any of the testers having to deal with this, so i think it's good to close, with the possibility to reopen it if reoccurs again
