### ISSUE TITLE
Portrait modifiers becoming defunct after character death.

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#71]
We're currently using a character flag to signify that they are a custom character and so have a predefined appearance.  Specifically, we have a "has_character_flag = has_scripted_appearance" check in the portrait modifiers and a "add_character_flag = has_scripted_appearance" effect in each custom character's history.  However, this doesn't seem to carry over to death and so modifiers are lost.

Steelkeep on the Discord suggested adding a custom trigger, which I've confirmed as working: https://discord.com/channels/751097183448727552/779430398374969354/835177631329812490

However, scripted hair and beards files might be able to be modified too.

**Comment by jj248** [comment]
Will not have time to address in v2.1.  Moving to backlog for v2.2.

**Comment by jj248** [comment]
No real time to devote to thinking about this, but would definitely be nice to get in for v3.0.

**Comment by jj248** [comment]
Pushing this to v4.

**Comment by JukeJukestar** [comment]
This is a vanilla issue PDX itself likely has to step in to solve.
