### ISSUE TITLE
Independent Wilderness settlement counties return to being invisible

### ISSUE THREAD

**Issue by RedArkady** [jj248/RealmsInExile#716]
In some circumstances, mostly where a kingdom is conquered I think, territories held outside the de jure kingdom can become independent. I've seen several cases of this happening with Wilderness counties, at which point they remain settlements with a holder but the colour returns to being invisible rather than being allocated another colour.

**Comment by JukeJukestar** [comment]
This is also the case when they are a vassal.
We can fix this by assigning them normal colors. Since they are normally under the Wilderness kingdom ruler, it shouldn't break anything (hopefully)

**Comment by RedArkady** [comment]
Not sure what you mean... if the AI gives wilderness to a vassal it shares the overall realm colour. Or do you mean if a wilderness county held by a vassal (which they shouldn't be...) goes independent?

**Comment by jj248** [comment]
With the changes made by @VectorMaximus last night and me adding missing Duchy CoAs this morning, this should be resolved.  Ready to test.

**Comment by Remerod** [comment]
I'm not entirely sure what y'all mean (a picture would have helped) But i've seen no colonized country become invisible as wilderness are when hold by a ruler that colonized it. and i've seen colonized that get abandoned go back being colonized

So i think this is good to go?

**Comment by JukeJukestar** [comment]
This is referring to fully colonized counties (regular holdings) that become independent or become vassal counts being invisible on the map because the title's map color is not changed.
I think a solution would also be to just give all wilderness counties regular colors, they should be invisible anyways because they are held by the Wasteland King

**Comment by Remerod** [comment]
> I think a solution would also be to just give all wilderness counties regular colors, they should be invisible anyways because they are held by the Wasteland King

@JukeJukestar does that mean you have confirmed it's not working? since Jamie said:

> With the changes made by @VectorMaximus last night and me adding missing Duchy CoAs this morning, this should be resolved. Ready to test.

**Comment by JukeJukestar** [comment]
I have not yet, thats why I didnt say I tested it.

His explanation of how he fixed it doesnt really make any sense at all.
