### ISSUE TITLE
Elven Mannish Feudatories

### ISSUE THREAD

**Issue by VectorMaximus** [jj248/RealmsInExile#718]
This is something that would be nice to have but not critical.

Essentially, Mannish vassals to Elves would automatically and always have a vassal contract that make it so that they don't provide levies to their liege, but instead can possibly be called to war (based on opinion and the like).

**Comment by jj248** [comment]
Would be doable I think, but I'm wary of the call to war aspect... mainly because I know the power of vassal swarms from EU4... 😅 And I'm not sure that Elves need a buff to their martial abilities.

**Comment by VectorMaximus** [comment]
Yeah, I'm open to hearing alternatives for a balanced alternative. I just don't think it makes sense for human vassals to provide levies to their top liege (Elven) which then are treated with the Elven levy bonuses.

**Comment by JukeJukestar** [comment]
Hear me out - they join defensive wars only, that would reduce vassal swarm

**Comment by Jauffr** [comment]
I couldn't agree more. Helps prevent a vassal swarm, but also ads a neat flavor to the way human and elf rulers interact. I should note that it is still an issue where elf rulers randomly generate humans that follow the elven faiths to grant counties to though and likewise for human rulers

**Comment by jj248** [comment]
- non-elf feudal vassals of elves are always set to zero levy contribution tier and cannot be raised, on vassal gain action. We could probably just zero this out and retain the levels as non-functional, but the the AI might negotiate things for zero benefit.
- non-feudal, non-elven vassals of elves have their levy contribution level = 0.

**Comment by jj248** [comment]
I'm still wary of inviting a vassal swarm of non-elf vassals to elven defence, partly because... hell, that's OP. But also because the AI already struggles to assess to strength of elves with their small troop numbers but high troop quality, without it also having to assess the potential strength of the swarm.

Willing to debate that point on Discord, but pushing this to testing.

**Comment by JukeJukestar** [comment]
> * non-elf feudal vassals of elves are always set to zero levy contribution tier and cannot be raised, on vassal gain action. We could probably just zero this out and retain the levels as non-functional, but the the AI might negotiate things for zero benefit.
> * non-feudal, non-elven vassals of elves have their levy contribution level = 0.

Make sure it also cant be raised by the chancellor task or random events where vassals promise you higher obligations in exchange for something

**Comment by JukeJukestar** [comment]
![image](https://user-images.githubusercontent.com/76008882/226999966-7f3784be-c6e4-4825-ac56-82ac24208174.png)

- Custom Tooltip is glitched.
- Since elves cannot convert humans, remove the "Religious Rights" obligation as its useless

**Comment by jj248** [comment]
![image](https://user-images.githubusercontent.com/26043074/233611754-45693906-5009-42b1-ac74-989680f205ab.png)

Should now be fixed - trigger and removed Religious Rights obligation for non-elven vassals of elven lieges.

Ready to test.

**Comment by savagesach** [comment]
![image](https://user-images.githubusercontent.com/86676697/233699470-41c335fc-2a68-4a52-a060-3ae9a2a4e015.png)
![image](https://user-images.githubusercontent.com/86676697/233699746-89fe7a62-d3f0-452d-95b6-0a583fef4d7c.png)
Feudal contracts work as intended, and neither tribal nor feudal human vassals give levies to elven rulers
