### ISSUE TITLE
Reduce Headgear choice to reduce mod size

### ISSUE THREAD

**Issue by BriceLeduc** [jj248/RealmsInExile#721]
Here's the list of some of the categories of headgear that would't suffer from reduced choice :
Uruk-Hai helmet (x4!) + 2 Grunt + 2 Beserker
Northern Adunai Helms (5 versions ! + BN + 2 Southern adunai)
Northron Noble Circlet (x6!)
Simple Circlet (x8!)
Dale Helmet (basically 4x the same + Northern Banded Helmx2)
Dale Nasal Helmet (x4)

**Comment by JukeJukestar** [comment]
Not sure if this is still the case but a week ago we also had like 15 different unlocalized headgear we ported over from somewhere else
