### ISSUE TITLE
Reforming faith causes CTD

### ISSUE THREAD

**Issue by savagesach** [jj248/RealmsInExile#723]
I wanted to reform my faith and clicked the warmonger pillar, and the game instantly crashed to desktop.

**Comment by savagesach** [comment]
turns out it's not just the warmonger tenet, clicking any of the tenets when you're trying to reform religion causes a CTD

**Comment by savagesach** [comment]
okay turns out verifying ck3 files and trying again fixed the issue, this can be closed

**Comment by savagesach** [comment]
forgot to reopen this issue, it's still active and has been for a few weeks now

**Comment by BriceLeduc** [comment]
Identical to issue https://github.com/jj248/RealmsInExile/issues/771, closing this one
