### ISSUE TITLE
Gundabad gets Orc duels to the death

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#724]
Gundabad gets Orc Duels to the death. This seems like an unintentional oversight since Remerod said that the orcs should usually rule for decades to centuries - currently kings lats 10-30 years roughly usually

**Comment by jj248** [comment]
Pushing this to v4 as it's not a huge issue for v3's scope.  But I'm sure it's something that @Remerod will want to weigh-in on.

**Comment by JukeJukestar** [comment]
We changed Gundabads lore to no longer have a 4.000 year old dynasty. can close
