### ISSUE TITLE
It is possible to fabricate claims on the Elven Rings

### ISSUE THREAD

**Issue by savagesach** [jj248/RealmsInExile#726]
It is currently possible to spend prestige and fabricate a claim on all three elven rings. This is an issue because with claims, you can get the rings by declaring war for them.
![image](https://user-images.githubusercontent.com/86676697/221041708-5ed88674-8e75-4f1e-979c-c4a9b562878d.png)

**Comment by BriceLeduc** [comment]
I pushed a fix for that, ready for testing

**Comment by savagesach** [comment]
I can fabricate claims on every artifact except Nenya, this issue can be closed.
![image](https://user-images.githubusercontent.com/86676697/222001467-a3538779-eeaa-406e-aee6-c6ec22a66611.png)
