### ISSUE TITLE
Undying character murdered

### ISSUE THREAD

**Issue by Jauffr** [jj248/RealmsInExile#728]
Gorshag "the massive" has murdered Sauron. Gods know how he managed that. Gave Khamul "the shadow" which is interesting
![Screenshot 2023-02-23 202344](https://user-images.githubusercontent.com/108106660/221084582-759b64c4-ff5c-4f63-b5ee-4e1ee0e5a140.png) 
![Screenshot 2023-02-23 202259](https://user-images.githubusercontent.com/108106660/221084576-d0b7ecbf-a661-4ece-b6b5-b21d888da986.png)

**Comment by jj248** [comment]
Classic Gorshag...

**Comment by jj248** [comment]
Not sure what we can do about this really...
