### ISSUE TITLE
Orc death duels can trigger several times at once

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#731]
In a recent game, once the cooldown for orcs challenging the ruler passed, I got seven of death duel invitations at the same time, leading to an instant game over. This is probably because the character flag is assigned at the wrong moment, someone should take a look at the event

**Comment by jj248** [comment]
I've put a 5 year cooldown on these now.  Please test. <3

**Comment by savagesach** [comment]
even though I can't actually fight any of the duels, I can confirm that the duels do not trigger several times at once

**Comment by jj248** [comment]
Bravo - closing.
