### ISSUE TITLE
Elves converting faith

### ISSUE THREAD

**Issue by Jauffr** [jj248/RealmsInExile#736]
Making an issue on this to make sure it isn't forgotten about. Elven characters currently do not have a blocker on converting faith on their own and on 50% of observer games, one or more elven independent characters will convert to a nearby human faith
![Screenshot 2023-02-24 193006](https://user-images.githubusercontent.com/108106660/221331789-8eff1eff-bd1c-40ff-bdff-c034ee9d655e.png)

**Comment by JukeJukestar** [comment]
Wonder how or why they do it. the AI tends to never convert faiths usually unless via stress event and such

**Comment by Jauffr** [comment]
There is an event that I think is responsible. I can't remember its name though. Its something like "a balanced argument" "a fair point"
Its an event where a wanderer from a nearby faith tries to convince your character to convert their faith. The first option is to convert. I can't remember its name, but I am almost certain that it is responsible, because you are most definitely correct about the AI having little interest in converting faiths

**Comment by jj248** [comment]
Novel Perspectives ? @Jauffr

**Comment by Jauffr** [comment]
I have yet to see it happen again. I don't know why it was happening so often for a while, but now never shows up @jj248

**Comment by jj248** [comment]
Oh okay then!  Let's close and revisit if it ever happens again.
