### ISSUE TITLE
"Far From Home" event can fire for members of other races

### ISSUE THREAD

**Issue by Jauffr** [jj248/RealmsInExile#744]
The "far from home" event fired for me while playing the framlings. It consisted of orcs from Gundabad being willing to adopt my faith and join me. This event should most likely be prevented from firing for characters who don't share the same species as the wanderers
![Screenshot 2023-02-26 211539](https://user-images.githubusercontent.com/108106660/221509006-e5d956e7-a193-43ed-85e8-ce84bdaaab9a.png)

**Comment by JukeJukestar** [comment]
Any idea what the event ID is? If you encounter it again please check, just use your "enable debug mode" button which every tester should have

**Comment by jj248** [comment]
I believe @BriceLeduc pushed a fix for this this morning.  Moving to testing.

**Comment by Jauffr** [comment]
Anytime I've seen the event since it has been working correctly. The fix seems to have done its job. Closing now
