### ISSUE TITLE
AI Sauron, Elves and Nazgûl should not switch court language

### ISSUE THREAD

**Issue by BriceLeduc** [jj248/RealmsInExile#747]
They always end up switching to Westron

**Comment by Remerod** [comment]
From my long observer games i haven't seen them switch, i have not heard any other testers mention this either. So it seems fine.

Had a shout to jamie that we should make it so **Orcs don't switch to Sindarin** (so waiting to close before we get that)

**Comment by Jaco-Daan** [comment]
Don't see why orcs shouldn't be allowed to swap court language, and since the issue seems to be solved, closing
