### ISSUE TITLE
Orcs retreat when conquered by Humans

### ISSUE THREAD

**Issue by wFredsch** [jj248/RealmsInExile#749]
- ‘Good’ humans auto convert Orcish provinces on conquest, using the same system as the Elves
- Orc ‘Ravage the Land’ task needs to be increased in speed and priority for the AI.

**Comment by jj248** [comment]
Vector tells me this was implemented.  Ready to test.

**Comment by savagesach** [comment]
![image](https://user-images.githubusercontent.com/86676697/233717312-fd7d07cf-7b98-4655-b06d-e329f1bc2448.png)
![image](https://user-images.githubusercontent.com/86676697/233717407-26959d17-42b4-4b63-b561-d8448cc59849.png)
![image](https://user-images.githubusercontent.com/86676697/233717450-0c7ef7fa-ee8b-4fef-a227-920ae730242d.png)
After testing, it is confirmed that only good faith rulers can auto convert orc provinces. However, I think the orc ravage the land task should be available to sauron and nazgul as well
![image](https://user-images.githubusercontent.com/86676697/233717953-15ae6eee-5282-46ad-9972-c904a6bd64d8.png)

**Comment by jj248** [comment]
As suggested, I've made is so that the action is available to Fallen Maiar, Nazgul and evil istari who have created the Uruk-hai. :)

Will definitely need testing as I had to tweak a fair bit of code to handle the forbidden cultures. @savagesach

**Comment by savagesach** [comment]
![image](https://user-images.githubusercontent.com/86676697/234093774-d641be14-034d-45cd-96b3-7b91eac0b7ef.png)
![image](https://user-images.githubusercontent.com/86676697/234093841-99ce8f9b-ba9a-4548-aff5-3de90bb8d6bc.png)
![image](https://user-images.githubusercontent.com/86676697/234093926-e53a84cd-a774-4749-a69c-33e6df3332e2.png)
the action is available to orcs, but not nazgul or sauron

**Comment by jj248** [comment]
Are you sure you took the latest pull @savagesach ?
![image](https://user-images.githubusercontent.com/26043074/234123584-e01fd968-5d3a-4c88-9bbe-78922bef120e.png)
![image](https://user-images.githubusercontent.com/26043074/234123628-2d51c9d7-0df8-4952-bdf9-cac594382aa6.png)

**Comment by savagesach** [comment]
![image](https://user-images.githubusercontent.com/86676697/234124610-22121581-e294-49f9-80c5-9ae24e0d468f.png)
![image](https://user-images.githubusercontent.com/86676697/234124666-7d478d94-9b72-41c3-a8bb-208dc9ca667f.png)
this also works now

**Comment by jj248** [comment]
Great - thanks.  Closing.
