### ISSUE TITLE
New Royal Court Events for Elves

### ISSUE THREAD

**Issue by wFredsch** [jj248/RealmsInExile#751]
https://discord.com/channels/751097183448727552/1077866777368858655

**Comment by BriceLeduc** [comment]
Current progress :

# hold_court_lotr.0001 # A Drunken Sommelier
# hold_court_lotr.0002 # Tight-Lipped Adventurer (a.k.a Thorin&Co)
# hold_court_lotr.0003 # An Unfamiliar Face (Time Flies!)
# hold_court_lotr.0004 # A Lost Friend
# hold_court_lotr.0005 # When I get that feeling (I need Elven Healing)
# hold_court_lotr.0006 # A Brigand in the Rough
# hold_court_lotr.0007 # Insistent suitor

OK for 3.0 release, potential for more
