### ISSUE TITLE
Fortress required for Framsburg building

### ISSUE THREAD

**Issue by savagesach** [jj248/RealmsInExile#752]
I'd like to complain about a literal fortress building being required to build the great stables of fram. not only is the requirement way too harsh considering the amount of money and time needed to go from tribal to motte to concentric castle, the actual fortress upgrade also requires machicolations. All this leads to the building not being usable for at least 50 years. Considering the fact that this is supposed to be rebuilding a previously made structure and the bonuses are not overpowered, I do not see the need for this requirement to be as steep as it is.
![image](https://user-images.githubusercontent.com/86676697/222010283-42f1e751-e46a-4c4b-b67e-73819edf0e7f.png)
![image](https://user-images.githubusercontent.com/86676697/222010388-fb9939d4-79db-402c-8c7c-5e437ed0049e.png)
![image](https://user-images.githubusercontent.com/86676697/222010636-98a677c8-3d2b-4940-a657-084177e5c38a.png)

**Comment by savagesach** [comment]
Understood, I'm not sure whether the building should require being feudal or not, but I'd say either having a fortified tribal hold or a level 1 castle should be good

**Comment by RedArkady** [comment]
Have fixed the loc and turned it down to Level 1. Let's keep it at feudal as I think Juke changed the Eotheod Kingdom decision to make them feudal, and it feels like a reasonable thing to expect them to have. Feel free to close this if the changes are working for you.

**Comment by savagesach** [comment]
I tested this and I'm satisfied with how the changes are now. This works as intended.
