### ISSUE TITLE
Give the duke of Mistrand title revocation protection 

### ISSUE THREAD

**Issue by Jauffr** [jj248/RealmsInExile#756]
Mistrand is meant to represent the heart of the moderates of rhun and they served that function well for a while during development. Now however, something has caused Zhamik to revoke it almost immediately on game start. He then hands out his previous holdings to his wife and child. Any future Loke-Khans revoke the land again and take it for themselves. While it is an excellent city and I would do the same in their shoes, this city is meant to represent a strong hold out of traditional Igath power and moderate foreign policy that simply can't happen if it is revoked
![Screenshot 2023-03-02 034958](https://user-images.githubusercontent.com/108106660/222407727-21b75858-868b-4150-ba39-85cab26eb7ef.png)

**Comment by JukeJukestar** [comment]
done. Ready to test.

**Comment by Jauffr** [comment]
Issue can be closed. Working as intended. He still has title revocation protection and all of his titles nine years into the game. Even with a change of Loke-khan he keeps them
![Screenshot 2023-03-03 155837](https://user-images.githubusercontent.com/108106660/222850267-fdcd2371-365b-4f36-8f83-b711dbc96dbf.png)
