### ISSUE TITLE
Court event can convert Vassal to Elven Culture

### ISSUE THREAD

**Issue by savagesach** [jj248/RealmsInExile#757]
It turns out there is a court event that has a chance of converting a non elven vassal to elven culture. This is clearly not supposed to happen.
![image](https://user-images.githubusercontent.com/86676697/222624997-a6879704-8bd3-4840-9c6a-784af579497e.png)

**Comment by savagesach** [comment]
Luckily I had an earlier save so I can get the event data
![image](https://user-images.githubusercontent.com/86676697/222625659-031d86c1-f021-454a-8d6f-2e5bbc7cb073.png)
![image](https://user-images.githubusercontent.com/86676697/222625605-e40b30ab-a445-413d-aeed-4950a19d3882.png)

**Comment by JukeJukestar** [comment]
Should no longer trigger for immortal characters and elves. Also checks if both targets have the same race, i.e. two orcs or two druedain

**Comment by JukeJukestar** [comment]
I think I'll just close this since you cant really test it.
Reopen if it happens again
