### ISSUE TITLE
Tooltip prompting "Declare war on Wilderness" is visible

### ISSUE THREAD

**Issue by BriceLeduc** [jj248/RealmsInExile#758]
As Thranduil the de jure duchy war on "Men of the Hills" wilderness shows up
It's even shown in notifications

This should be disabled, even though you can't actually declare the war

![image](https://user-images.githubusercontent.com/98077354/222727054-801e5714-7964-4f26-bc72-df35a1e23dc9.png)
![image](https://user-images.githubusercontent.com/98077354/222727104-3e90efa2-043b-4838-8dcc-8c56de153ac5.png)

**Comment by jj248** [comment]
Should no longer appear.  Ready to test - see if you can declare war any other way and, if you can, make sure it invalidates immediately.
![image](https://user-images.githubusercontent.com/26043074/223100282-27b44716-f5ee-4749-bba0-a9d0fdcc52b3.png)

**Comment by Jauffr** [comment]
I can't seem to find a way to declare war on wildernesses anymore. I won't close this just yet in case others want to weigh in their thoughts and experiences though. I'll close it if no one posts in a day
![Screenshot 2023-03-22 183013](https://user-images.githubusercontent.com/108106660/227068627-d3f3b1f7-572d-4cd4-93a4-f46f41a55a77.png)
![Screenshot 2023-03-22 183034](https://user-images.githubusercontent.com/108106660/227068632-2591990c-ce93-4df2-a9d2-a9bc8d77be48.png)

**Comment by savagesach** [comment]
turns out whatever fixes have been made to wilderness only made things worse, now anyone can declare war on wilderness
![image](https://user-images.githubusercontent.com/86676697/232244956-0316a322-dcac-4872-b39b-8b4e8a3a1230.png)

**Comment by Remerod** [comment]
You can also see that the wilderness UI is also broken in @savagesach picture, as the Wilderness is there as a normal character. So something has gone very wrong

**Comment by savagesach** [comment]
![image](https://user-images.githubusercontent.com/86676697/232251563-f10cbaf6-ac72-4788-8add-a6d4be1f631d.png)
so I updated to the latest version and apparently it's fixed now. I'll do some more tests but I think we're good
