### ISSUE TITLE
Mercenaries for the new cultures are broken

### ISSUE THREAD

**Issue by Jauffr** [jj248/RealmsInExile#761]
Mercenaries in the north use incorrect MAA for their culture

![Screenshot 2023-03-07 073209](https://user-images.githubusercontent.com/108106660/223453012-d2efeff9-a326-4948-b28f-f638bbb4d56a.png)
![Screenshot 2023-03-07 073227](https://user-images.githubusercontent.com/108106660/223453020-53294612-76eb-483f-b1ee-547241f8199d.png)
![Screenshot 2023-03-07 073256](https://user-images.githubusercontent.com/108106660/223453028-3a84edff-3da0-4cae-9d9f-f91e27e26cc1.png)

**Comment by jj248** [comment]
I agree - that's my understanding at least.  Closing, but let me know if you think I'm mistaken and I'll re-open.
