### ISSUE TITLE
Longbow competitions is still usable as a cultural tradition

### ISSUE THREAD

**Issue by Jauffr** [jj248/RealmsInExile#762]
The longbow competitions tradition is from vanilla and it enables the recruitment of and strengthening of over time for longbowmen. Realms disables the longbowman unit, yet the tradition remains. If the tradition is to stay in the mod, I say it should have a repacement bow MAA to make it functional
![Screenshot 2023-03-07 074448](https://user-images.githubusercontent.com/108106660/223456626-0b1f3c55-3d4c-4352-bb4b-71daba3f8b5a.png)

**Comment by jj248** [comment]
Should now be culled - over to testing.

**Comment by savagesach** [comment]
I have been unable to find any cultures with the longbow tradition or get it through reforming cuture. I think this issue can be closed
