### ISSUE TITLE
Sauron doesn't culture convert elves

### ISSUE THREAD

**Issue by Jauffr** [jj248/RealmsInExile#765]
Sauron conqueres lothlorien, but doesn't convert the counties automatically. Therefore he decides its a good idea to hand the lands out to local elves. This is a problem because he doesn't have any evil elves on hand. This causes him to revoke the land, however he still doesn't have any evil elves so he just hands it back like an absolute monkey
![Screenshot 2023-03-09 111814](https://user-images.githubusercontent.com/108106660/224120965-920f5ea6-a95c-4869-9082-d3f31f8da9fa.png)

**Comment by Jauffr** [comment]
This problem is worse than I thought. It extends to anyone who would want to replace elves with someone with a different faith. In this example. A vassal of the golden realm managed to take a county off of Nelornieth. As a result the Loke-Khan repeatedly began to revoke and hand out the title to local elves again and again. There is no happy solution to this I fear. None other than making evil faiths make elves flee on conquest, or for elves to somehow be given title protection, which would feel forced
![Screenshot 2023-03-09 215458](https://user-images.githubusercontent.com/108106660/224227236-4e59014d-de0b-4ba7-b9c0-06e1c7110071.png)

**Comment by VectorMaximus** [comment]
For now, my view is that we should extent the 'Elves Flee' mechanic to all dark-aligned faiths. This is in parallel to the proposal to expanding the 'Orcs Flee' mechanic to all good-aligned faiths. Which makes sense - Elves and Orcs respectively are the ones most intrinsically bound with their ideological faction.

Would need to test to see how 'People Apart' faiths treat Elves they conquer though - most such faiths are pluralists, so they have minor opinion penalties even to hostile faiths.

**Comment by VectorMaximus** [comment]
And also make it so that if Elves reconquer a county with the 'Hidden Elven Refuges' modifier it will auto-flip back to them.

**Comment by jj248** [comment]
Okay.  Commit above makes these changes:
- Elves should now be booted out by fallen maiar conquerors too
- added additional logic to ensure non-capital baronies are converted too and the settlements should be unconverted

I'm a little hesitant of extending this to all dark-aligned faiths though.  Let's discuss on Discord.

**Comment by Jauffr** [comment]
Elves get auto converted properly by Sauron and now all evil faiths
![Screenshot 2023-03-22 154129](https://user-images.githubusercontent.com/108106660/227045026-9f0b33dc-6c70-454a-8e43-e5e38ce54d55.png)
![Screenshot 2023-03-22 154155](https://user-images.githubusercontent.com/108106660/227045031-a945599c-bcf1-4709-ae06-b80974246eac.png)
![Screenshot 2023-03-22 154107](https://user-images.githubusercontent.com/108106660/227045042-24dd6c2d-94c4-4eb7-9c32-05c8bbb9d26c.png)

**Comment by Jauffr** [comment]
Elves also convert back lands that have the modifier on non orcs 
![Screenshot 2023-03-22 154501](https://user-images.githubusercontent.com/108106660/227045536-d2f1e261-08d2-48ab-8a17-330c8ff2f832.png)
