### ISSUE TITLE
Dorwinion election stewardship cap

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#766]
I believe there should be a cap on the ammount of vote strength you can get from stewardship as a master merchant, maybe capping around 20 or 25 skill strength (40-50 vote strength)

**Comment by JukeJukestar** [comment]
Edit: The mechanic where master merchants are more powerful than realm masters was intended

**Comment by Jaco-Daan** [comment]
This has been fixed a while ago, Winelords are now more on-par with Master Merchants, closing
