### ISSUE TITLE
Elven Hybrid cultures lose longevity bonus

### ISSUE THREAD

**Issue by BriceLeduc** [jj248/RealmsInExile#767]
Apparently cultural hybrids of elven cultures make Elves mortal
![image](https://user-images.githubusercontent.com/98077354/224646443-5c5edbc6-f169-4ed8-afa0-0cd38bd939ba.png)

**Comment by jj248** [comment]
Blocked AI elves from diverging or hybridising - should hopefully resolve this.

**Comment by Remerod** [comment]
I'll post the same thing i said in https://github.com/jj248/RealmsInExile/issues/779

https://github.com/jj248/RealmsInExile/issues/779#issuecomment-1480236499

so up to you @jj248 if you think we need more general testing or not
