### ISSUE TITLE
Titles can be granted to women despite faith doctrine

### ISSUE THREAD

**Issue by savagesach** [jj248/RealmsInExile#768]
![image](https://user-images.githubusercontent.com/86676697/224715166-2df920ad-5c6f-4af5-a05a-9c8fdb095d2d.png)
I was testing framlings and I found out somehow I'm able to grant titles to women despite the male dominated faith doctrine explicitly forbidding title granting.

**Comment by savagesach** [comment]
bruh it gets even weirder
![image](https://user-images.githubusercontent.com/86676697/224716419-0df015fb-82d9-49b8-9a96-cf0ee6fb8732.png)
![image](https://user-images.githubusercontent.com/86676697/224716476-bb1cbaf0-69c3-4b88-87f2-bbfa6c4dbf5c.png)

**Comment by jj248** [comment]
This should now be fixed.  Ready to test.

Be on the look out for the AI suddenly granting elven colonies to non-elves and vice versa as that may be affected.

**Comment by savagesach** [comment]
This works as intended
![image](https://user-images.githubusercontent.com/86676697/226799228-89c25622-8de8-47f3-9c0e-d947b9a91f29.png)
