### ISSUE TITLE
Crash when creating new faith

### ISSUE THREAD

**Issue by Jauffr** [jj248/RealmsInExile#771]
When creating a new faith, the game will crash if the player selects some doctrines to be changed. The two I've noticed so far, being adaptive and pastoral isolation

**Comment by Jauffr** [comment]
@jj248 This is what I was talking about in discord. These two doctrines at least cause the game to crashwhen you select them while creating a new faith. Specifically when I and others  tried with these two Talethrim faiths
![Screenshot 2023-03-22 183721](https://user-images.githubusercontent.com/108106660/227069408-12e3a7d2-902b-4920-9498-1d04a80edfc0.png)

![Screenshot 2023-03-22 183709](https://user-images.githubusercontent.com/108106660/227069398-9569b03c-9fff-4f58-8d70-9601c918a298.png)

**Comment by BriceLeduc** [comment]
See also https://github.com/jj248/RealmsInExile/issues/723

**Comment by savagesach** [comment]
![image](https://user-images.githubusercontent.com/86676697/234983180-cf6f2ccf-053e-4471-bcef-0e9c8da9408b.png)
why did no one tell me this issue was fixed

**Comment by Remerod** [comment]
wait, so since https://github.com/jj248/RealmsInExile/issues/723 is fixed is this also fixed?

**Comment by savagesach** [comment]
723 was closed because we didn't need duplicate issues

**Comment by savagesach** [comment]
just to be clear, now changing tenets no longer causes my game to crash.

**Comment by Remerod** [comment]
ok, closing this issue then
