### ISSUE TITLE
Custom Tenet for Elven Faiths

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#773]
This would allow them to meditate, as well as another effect, possibly relating to holy sites.

**Comment by JukeJukestar** [comment]
Implemented now.
The tenet is a mix of "Inner Journey" and "Pacifism".
Notably, AI agressiveness isnt reduced because we agreed elves shouldnt be made less agressive.

Please test if the meditation decision works properly!

**Comment by savagesach** [comment]
the meditation decision works as intended, and mallorn forests do unlock regular forests
![image](https://user-images.githubusercontent.com/86676697/227012037-8ffe88b6-c3dd-402c-9749-8adfa0c9c661.png)
![image](https://user-images.githubusercontent.com/86676697/227012741-097cf1d2-6522-49ba-89de-9c32308196dd.png)
![image](https://user-images.githubusercontent.com/86676697/227012848-530bb8aa-24d5-4ee0-9d3f-8f452a3abde4.png)
![image](https://user-images.githubusercontent.com/86676697/227014879-fd995b44-6c78-4603-bb2e-14053734d70d.png)
