### ISSUE TITLE
Restore Izindubeth Decision

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#774]
We need a decision to restore the Felayan Izindubeth/ Regift him his duchy.
We can do this by repurposing the vanilla "Restore the Papacy" and "Give Rome to the Pope" decisions.

I will probably do this myself eventually, but its not a priority. Feel free to tackle it if you want to. This is mostly to remind myself

**Comment by savagesach** [comment]
https://github.com/jj248/RealmsInExile/issues/1004
closing as this is a duplicate issue
