### ISSUE TITLE
Missing Localisation

### ISSUE THREAD

**Issue by BriceLeduc** [jj248/RealmsInExile#783]
Various locs are missing in the game

**Comment by BriceLeduc** [comment]
![image](https://user-images.githubusercontent.com/98077354/225883551-1343cceb-d17f-4680-9375-7f07d8a7982d.png)

**Comment by BriceLeduc** [comment]
![image](https://user-images.githubusercontent.com/98077354/225883626-775b6d8e-ecf6-4a45-a87d-8b2db211f4b8.png)

**Comment by BriceLeduc** [comment]
![image](https://user-images.githubusercontent.com/98077354/225883826-b8e7687d-d434-4f74-b515-253c9559c838.png)

**Comment by jj248** [comment]
Fixed these missing points.

**Comment by Remerod** [comment]
So in this Issue it's not specified which specif localizations that was missing and which have been fixed.

Are we testing these 3? 
Troop Storehouses (elven Barracks)
 tooltip_oligarchy_merchant_dynast_fame_3
 Unorginazed Fletchers

**Comment by Remerod** [comment]
Troop Storehouses (elven Barracks) is working
Unorginazed Fletchers fixed

need to catch a buss and forgot on the top of my head where i can find tooltip_oligarchy_merchant_dynast_fame_3 atm, will check later

**Comment by BriceLeduc** [comment]
https://discord.com/channels/751097183448727552/1102567353780281436
