### ISSUE TITLE
Galadriel: Deal with the Leofrings event

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#784]
Galadriel's starting event gives her an option to offer the parth celebrant leofrings vassalization. They are weighted to accept this.
In exchange, the Guthmundings' ancient claim on Drownholt is renewed for galadriel to press against dol guldur/drownholt. This should let her expand her realm while still keeping the human leofrings in the duchies between Amon Lanc and Lothlorien

## To Do:
- [x] Get starting event to trigger
- [x] Answer Event for Parth
- [x] Followup event for Galadriel informing her of their choice
- [x] Get Galadriel to actually use the claim war

**Comment by JukeJukestar** [comment]
Moving to testing.
Please also check if the Lasgalen starting event fires.

**Comment by savagesach** [comment]
since you asked to check if the lasgalen event fires, I tested it. It fires, but there are some minor typos.
![image](https://user-images.githubusercontent.com/86676697/226799752-20c6de8d-4d79-4809-a3b8-95b31b7d8812.png)

**Comment by savagesach** [comment]
about the leofring events though, I've tried it on both ends and watched observer games and it mostly works as intended. the main issue is that ai galadriel does not take drownholt. Granted, I only ran the games for 100 years, but I don't think that will change if the games run longer.

**Comment by JukeJukestar** [comment]
I was expecting this, but at least its a nudge into the right direction. 
The intention isnt for her to immediately go pressing her vassals claims, its rather to nudge her toward fighting dol guldur once they inevitably take drownholt
