### ISSUE TITLE
Embrace Piracy Decision, Corsair Tenet

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#787]
Note: Likely wont get around to this for a while, feel free to tackle it if you want!

Decision for coastal rulers of to reject the King's Men faith and return to piracy if there is no powerful ruler enforcing the King's Men doctrine on them. May be avaiable to vassals too if their liege is considered weak (as Burodapan did).

The idea is to create a dynamic relationship between King's Men and Corsairs instead of having the former completely convert the latter.

## Freebooters Tenet
Part of the Corsair faith, increases raiding loot and allows raiding at any level. To give an incentive to using the Corsair faith over King's Men.

**Comment by Jaco-Daan** [comment]
What would be considered 'weak'? I'm personally thinking of things along this line: 

- In debt
- Recently lost a war (if its possible check if it was a war for duchy tier or higher, i.e., high impact war)
- fervor of the corsair faith vs King's Men faith
- (Maybe, not sure on this one) whether Gondor is still controlled by someone who isn't part of King's Men faith

**Comment by JukeJukestar** [comment]
Decision is finished and committed, Seen the AI use it every once in a while though rarely.

**Comment by savagesach** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/86676697/fc2046e4-b081-4460-aca3-f1bcdb918dc7)
![image](https://github.com/jj248/RealmsInExile/assets/86676697/bee83583-07cc-4265-a5ae-af08fb2f7f58)
The decision works, but the requirements are only based on having specific traits rather than having a weak liege. If that is intended, the issue can be closed

**Comment by savagesach** [comment]
After talking to Juke and testing, the ai is able to embrace piracy. I am curious what exactly the ai weighting is based off, I'd like to know for further testing

**Comment by savagesach** [comment]
After talking to Juke and testing, the ai is able to embrace piracy. I am curious what exactly the ai weighting is based off, I'd like to know for further testing

**Comment by savagesach** [comment]
After talking to Juke and testing, the ai is able to embrace piracy. I am curious what exactly the ai weighting is based off, I'd like to know for further testing

**Comment by savagesach** [comment]
After talking to Juke and testing, the ai is able to embrace piracy. I am curious what exactly the ai weighting is based off, I'd like to know for further testing

**Comment by savagesach** [comment]
after further testing, the decision works as intended and rulers can convert to piracy
