### ISSUE TITLE
Make Castamiri Claim repeatable, shatter realm on failure

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#788]
Feel free to tackle if you want to, I'll try to get to it eventually.

### The Idea
Make the Castamiri claim repeatable (though only one chance per character), but shatter the Realm on failure by destroying the Empire and any Kingdom titles you hold, possibly kill the claimant.
Accompanying news event would be sweet.

### The Justification
Lorewise:
The Cassimiri's claim is already basically legally nonexistent, many have tried to attack Gondor in the past. Another defeat wouldn't permanently remove their desire to invade Gondor. The last time Umbar tried it and Aragorn kicked them out, the realm was also shattered and Kathuphazgan had to pick up the pieces.

Gameplaywise:
Theres a decent change that players will miscalculate and their glorious invasion will fail. Having the realm shatter goves them a chance to try again in the future, though at a very heavy disadvantage.
This also creates a fun power vacuum in Anadune, which can be seized by Gondor, Bellakar or many of the other surrounding nations.

**Comment by JukeJukestar** [comment]
Other ideas I had/ optional stuff
- Give aragorn a proper claim on castamiri gondor
- Modifiers/ events for unrest among the gondorian princes to incite revolt against the Castamiri
- If the invader dies, the invasion fails
- Big debuffs for the failed invader, maybe even kill/ imprison him on war end

**Comment by Jaco-Daan** [comment]
Think (if I remember correctly) that @JukeJukestar said I could work on this a bit, so I'm just start doing some of the more basic changes, leaving the more complex things for @JukeJukestar to implement.

**Comment by Jaco-Daan** [comment]
Was thinking that maybe instead of having Kingdom tier title immediately being destroyed, anyone of non-KM faith rebels for independance and any vassals of KM faith is more incentivized to create a claimant faction (install stornger ruler on throne) and if none exists, install the strongest vassal on the throne

**Comment by Jaco-Daan** [comment]
Should we move this issue to Project 3.1? Seeing as its mostly done and should be done by the time compatching is finished. Similar questions concerning issues: #566 and #705

**Comment by Jaco-Daan** [comment]
Completed the issue, things from that were NOT implemented in this version includes:
- opinion swing of Anadune vassals
- Balance of power swing to your co-ruler
- Modifiers/Events to make the gondorian princes incentivise the Gondorian King into declaring war on Umbar after the 'Castamiri Claim War' has failed
- If the invader dies, the claim is invalidated (will be added)

The way to test it would be to use the decision 'Press the Castamiri Claim' and surrender/lose the war. The result should be:

- You lose ANY empire tiered titles (all empire titles get destroyed)
- An event fires (hidden) where a dissolution rebellion is launched against you (former ruler of Anadune) for any kingdom tiered title.

Event id to launch the above mentioned rebellion is umbar.1500
The castamiri claim, if pressed, can't be pressed by the same ruler at all. The castamiri claim also has a cooldown timer of 50 years.

In terms of testing, just make sure the dissolution war targets the roots' kingdom tier titles, and the event should only trigger if the root (person receiving the event) has at least a kingdom tiered title (i.e., if his highest tier title is duchy, then the event shouldn't fire)

**Comment by Jauffr** [comment]
The modifier is applied correctly, you lose any and all empire titles you hold and as long as you have any kingdom titles you will have the dissolusion war fire. The only thing that is wonky is the war however. Your allies will still join the war against you. See here Beruthiel joining against me even though she is my wife, lol! Also it only makes vassals join the war within dejure Umbar. I assume that is intended though
![Screenshot 2023-06-20 144330](https://github.com/jj248/RealmsInExile/assets/108106660/014ff2a0-bfa9-4613-b75a-726629742f62)
![Screenshot 2023-06-20 144640](https://github.com/jj248/RealmsInExile/assets/108106660/a180c19b-a52a-43d7-a999-d2d622896a1c)
![Screenshot 2023-06-20 144539](https://github.com/jj248/RealmsInExile/assets/108106660/395c8fc2-d734-4f2d-8150-8524e3ecbe16)
![Screenshot 2023-06-20 144443](https://github.com/jj248/RealmsInExile/assets/108106660/e126e618-2547-47cd-b8ee-f9b6fbcc4cca)

**Comment by Jaco-Daan** [comment]
Might revisit this to add more stuff, but for now it has been sufficiently tested + is in a finished state, closing.
