### ISSUE TITLE
Summoned Ulairi Physician has no culture/ethnicity

### ISSUE THREAD

**Issue by blackbird5598** [jj248/RealmsInExile#790]
![image](https://user-images.githubusercontent.com/125709421/226114419-90d3af91-b275-4a2d-b382-fd7d7bd62835.png)

Event where my courtier got ill & I asked for a physician came to my court, theres the choice of this hunchback and another physician. They appear to have no culture. I was playing Abrakhan the Golden King, not sure if thats relevant.

**Comment by jj248** [comment]
Should be fixed.

**Comment by savagesach** [comment]
![image](https://user-images.githubusercontent.com/86676697/234947753-8f418e4b-ce4a-47f8-9668-8809ca69690b.png)
![image](https://user-images.githubusercontent.com/86676697/234947915-490e47f4-2ea2-4f71-bbb3-80b1405b56a0.png)
Physicians with culture and ethnicity appear now
