### ISSUE TITLE
Court Grandeur Expectations Bugged

### ISSUE THREAD

**Issue by Commander-Sol** [jj248/RealmsInExile#791]
Playing as Saebert of the Hills, I formed the Kingdom of the Brownlands and have an Expected Court Grandeur Level at the maximum. This cannot be right (especially as I am still tribal), so I'm guessing something funky happened with Brice's Grandeur changes yesterday.

![image](https://user-images.githubusercontent.com/123737916/226122115-94e53248-e065-4e95-9434-6d730897b1c6.png)

**Comment by BriceLeduc** [comment]
Pushed a fix, moving to testing
