### ISSUE TITLE
Court event freezes game

### ISSUE THREAD

**Issue by blackbird5598** [jj248/RealmsInExile#793]
For some reason a court event triggers while playing the game & it acts like you've clicked on it & it freezes the game. You think your game is frozen but if you go to your court its waiting for you to choose a response, it takes several clicks to make the event go away.

**Comment by JukeJukestar** [comment]
Can you elaborate? Do you know what court event triggered? Who were you playing?

**Comment by savagesach** [comment]
![image](https://user-images.githubusercontent.com/86676697/226150883-2ab262e9-80c2-4314-bdce-06b8342a2f55.png)

**Comment by savagesach** [comment]
![image](https://user-images.githubusercontent.com/86676697/226150899-5e494fbd-db10-4279-b9ab-598db5cf5e00.png)

**Comment by savagesach** [comment]
![image](https://user-images.githubusercontent.com/86676697/226150918-fcd621b3-5e0a-4307-8cbc-dca7c91963fc.png)

**Comment by wFredsch** [comment]
Mb, I didn't comment that one. :)

**Comment by wFredsch** [comment]
So, I think I made the fix. Can you test it again?

**Comment by BriceLeduc** [comment]
Issue fixed
