### ISSUE TITLE
Mannish vassal's obligation endlessly invalidated (every day)

### ISSUE THREAD

**Issue by BriceLeduc** [jj248/RealmsInExile#795]
Since the vassal contract of Mannish vassals of Elven lords has been tweaked, they are being invalidated every single day : this is detrimental to performance (and the player's sanity) : 
![image](https://user-images.githubusercontent.com/98077354/226205775-3ee4bff9-34e0-4f77-b4a2-4dd305169abb.png)

**Comment by BriceLeduc** [comment]
The vassal in question 
![image](https://user-images.githubusercontent.com/98077354/226428708-b2e7278f-bdea-4e9e-81b7-1a4dcbbba233.png)

**Comment by jj248** [comment]
I should have captured all of the ways that this could happen.  Please let me know if you see this occurring again and how the vassal was gained.  Ready to test.

**Comment by savagesach** [comment]
I tested this issue and I've gotten no obligation invalidated messages. this works as intended
![image](https://user-images.githubusercontent.com/86676697/229389266-46d6b679-5e41-414e-bf7d-636ceb9744ee.png)

**Comment by BriceLeduc** [comment]
https://discord.com/channels/751097183448727552/1102008132139503626 this issue is still coming up

**Comment by savagesach** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/86676697/92cfb16c-245d-4eb2-8478-1ab23eb7b290)
the obligation are no longer invalidating
