### ISSUE TITLE
Humble Mordor is Bugged

### ISSUE THREAD

**Issue by blackbird5598** [jj248/RealmsInExile#796]
![image](https://user-images.githubusercontent.com/125709421/226221160-61f57a2a-d5e0-45d6-aac8-5204b5abe459.png)
![image](https://user-images.githubusercontent.com/125709421/226221212-b510884d-90b3-4368-99be-3206222a9f2d.png)

So I'm pretty sure these aren't intended to be like this when Saruman defeats Sauron. Sauron keeps any titles outside de jure Mordor, Witch King becomes independent due to holding the Kingdom of Minas Morgul (a non de jure title) Witch King does convert to Cult of the White Hand and Khamul & the Golden King do not. Sauron goes to the deepest pits of Sarumans dungeon but he retains his head of faith title which isn't de jure mordor.

**Comment by JukeJukestar** [comment]
I'm not sure how its INTENDED to play out so I'm not gonna tackle fixing this for now.
Should Sauron stay landed at all or should be be unlanded?

**Comment by jj248** [comment]
This should now be fixed, but @JukeJukestar needs to fix his faith conversion effect that was added as it is now CTDing / hanging when ran.  Will discuss with him separately.

**Comment by jj248** [comment]
I've pushed a fix for the CTDing scripted effect.  Passing to @JukeJukestar to test. <3

**Comment by savagesach** [comment]
![image](https://user-images.githubusercontent.com/86676697/234970633-af1ffc3c-f229-420a-aea2-8549df4a882e.png)
![image](https://user-images.githubusercontent.com/86676697/234970739-b27ed9f8-4d57-480a-a3bd-f5bd3e91a44a.png)
![image](https://user-images.githubusercontent.com/86676697/234970938-1398ec83-3c07-4791-86fb-e826c2e9952c.png)
![image](https://user-images.githubusercontent.com/86676697/234971280-9a03817a-0aca-4078-81e2-28a9ce65961b.png)
Humble Mordor mostly works, with the exception of khamul and the golden king. It makes zero sense that khamul stays lidless eye when the whole point is that the nazgul become saruman's servants as saruman is replacing sauron. both khamul and the golden king should be converted to white hand.

**Comment by savagesach** [comment]
![Uploading image.png…]()
I also forgot to mention humbling mordor should give you minas morgul, otherwise there's no way to move your capital there and picking minas morgul for the two towers decision is pointless

**Comment by Remerod** [comment]
had a chat in issues, issue is not done and apperently needs more white colouring on the nazguls

**Comment by JukeJukestar** [comment]
I think by "white coloring" remerod means that they should all convert to white hand (they currently do not)

**Comment by JukeJukestar** [comment]
Gonna try to tackle this later best as possible.
As i understand

- [ ] all nazgul should convert to white hand
- [ ] cult of zigur should flip to white hand down south

That correct?

**Comment by JukeJukestar** [comment]
So these are the changes I made:
- The Nazgul now all convert to white hand
- If unemployed, Nazgul move to Sarumans court
- If Golden King is recalled, Abrakhan will flip to Kanra instead of White Hand
- General minor improvements to faith conversion
