### ISSUE TITLE
Thrydan fights Saruman for Dunland counties

### ISSUE THREAD

**Issue by savagesach** [jj248/RealmsInExile#798]
Jamie added some code a while back that would force saruman's ai dunland vassal, usually thrydan, to rapidly expand and cause dunland to consolidate fast enough for saruman to be a legitimate threat. However, if saruman conquers any land in dunland himself, which sometimes happens, thrydan will delare war on him too, effectively causing a civil war. This is pretty dumb for obvious reasons.
![image](https://user-images.githubusercontent.com/86676697/226802476-b05fb6ce-8b59-43f2-a1ee-e92262fd4a5b.png)

**Comment by jj248** [comment]
Vector should have fixed the auto-wardec of the Dunlending candidate from declaring war on liege.  Ready to test again.

**Comment by savagesach** [comment]
I've run several observer games and thrydan no longer declares war on saruman

**Comment by jj248** [comment]
Excellent - closing.
