### ISSUE TITLE
Remove "Heir Unmarried / Ruler Unmarried" Alerts for elves

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#804]
![image](https://user-images.githubusercontent.com/76008882/227022182-08a403e7-0f63-4604-8094-5b184e3aa24d.png)

There is a large alert icon at the top of the screen if you or your heir are unmarried, even if you are an elf and cant marry using the interaction.
Since succession for elves is a non-issue, I think this can be safely removed. Even if a player doesnt marry off their heir for a century, it shouldnt matter.

**Comment by BriceLeduc** [comment]
Pushed a fix : icon will only show up if self or heir is unmarried and has a soulmate

**Comment by Remerod** [comment]
Seems to be working for me, checked all of the elven main rulers at start and in an 100 observer game i runned (by switching to them of course) 
So i'll close this issue
