### ISSUE TITLE
Huz-Margoz quest chain

### ISSUE THREAD

**Issue by Jauffr** [jj248/RealmsInExile#805]
Huz-Margoz's quest chain of events and decisions is in a playable state and ready for testing
![Screenshot 2023-03-22 141153](https://user-images.githubusercontent.com/108106660/227027053-325dd767-a5ee-4120-99b7-005ed9e6fa03.png)

**Comment by Jauffr** [comment]
These are all the events/decisions related to the chain at the moment. To begin. Start as Huz-Margoz of Riav. Then work towards each decision. It is not an easy game however. Also. I intend to replace Zhamik with Margoz as the bookmark character for Rhun. Relegating Zhamik to a side character in any rhun focussed bookmarks later. Or even side stepping him entirely for his more capable son Kirun

![Screenshot 2023-03-22 141439](https://user-images.githubusercontent.com/108106660/227028219-a208dd1a-d72f-4afc-b8a0-602b16be5ead.png)
![Screenshot 2023-03-22 141500](https://user-images.githubusercontent.com/108106660/227028223-10926149-13b9-41e7-97ae-960e212b2a4a.png)
![Screenshot 2023-03-22 141521](https://user-images.githubusercontent.com/108106660/227028230-127ddfaa-e3f1-4ad0-a0f9-cedb7bf4e0f9.png)
![Screenshot 2023-03-22 141538](https://user-images.githubusercontent.com/108106660/227028232-9d3957ce-73ba-4e8a-85cb-b5041f809179.png)
![Screenshot 2023-03-22 141556](https://user-images.githubusercontent.com/108106660/227028234-e6f2e6f2-8234-4b11-8744-f912ff1a0283.png)
![Screenshot 2023-03-22 141609](https://user-images.githubusercontent.com/108106660/227028236-17ecee81-4bff-41d9-b294-e7aa96defe2d.png)
![Screenshot 2023-03-22 141631](https://user-images.githubusercontent.com/108106660/227028239-4618b0e5-e51e-42e9-88a1-94661b354ce9.png)
![Screenshot 2023-03-22 141743](https://user-images.githubusercontent.com/108106660/227028241-117c4d1d-a74c-4a78-a32e-3a58f4735fed.png)
![Screenshot 2023-03-22 141802](https://user-images.githubusercontent.com/108106660/227028243-e9954d5f-85a6-48bd-b077-8c50ca05d333.png)
![Screenshot 2023-03-22 141827](https://user-images.githubusercontent.com/108106660/227028246-3dcdad54-c558-43e5-9189-2251143b7879.png)

**Comment by JukeJukestar** [comment]
Small loc error: we localize nicknames with a lowercase "the" unlike vanilla.

**Comment by savagesach** [comment]
I've tested the quest chain and every event and decision works as intended. The main area of concern for me is the ai since I know the ai has very different requirements compared to the player. I think once the ai is tested by running enough observer games, this issue can be closed

**Comment by Remerod** [comment]
Szrel-kain Executions need to be balanced and approved by a dev

**Comment by savagesach** [comment]
The title for huz-margoz should be tyrant huz-margoz of the tyranny of szreldor, and szreldor's de jure capital should be szrel kain instead of mistrand
![image](https://user-images.githubusercontent.com/86676697/230681630-1cd2967a-a762-473b-a545-3ba9d681754c.png)
![image](https://user-images.githubusercontent.com/86676697/230681652-6f931537-4277-4850-b040-aea1df9ba9d4.png)
