### ISSUE TITLE
Istari and Elf invite restrictions

### ISSUE THREAD

**Issue by blackbird5598** [jj248/RealmsInExile#810]
![image](https://user-images.githubusercontent.com/125709421/229266316-e4d4aa0d-0246-4a7e-88cf-10ab4cdc79d5.png)

As Saruman I am able to invite Gandalf to my court, this is a problem thats been dealt with in the past but it has returned.

**Comment by JukeJukestar** [comment]
Note: Likely also possible with Radagast if he becomes unlanded, consider this when fixing

**Comment by BriceLeduc** [comment]
This should be disabled for any evil character inviting Istari, and any non-Elf inviting an Elf

**Comment by savagesach** [comment]
yeah but the problem is saruman is a good istari at game start, so you invite gandalf before turning evil

**Comment by BriceLeduc** [comment]
This is litteraly the plot of the books

**Comment by jj248** [comment]
Working as intended.  Not an issue - closing.
