### ISSUE TITLE
Suladan's missing Mumak Maa

### ISSUE THREAD

**Issue by savagesach** [jj248/RealmsInExile#812]
As some might know, Suladan used to start with siege mumaks. They are currently maa in the released version and earlier in the dev version, they became special non reinforcing maa.
![image](https://user-images.githubusercontent.com/86676697/229945858-1a2481ac-211f-4d69-a7f7-5df4446835b3.png)
However, due to the mumak rework, see here (https://github.com/jj248/RealmsInExile/issues/475), Suladan's mumaks have now vanished as siege mumaks were removed entirely as a maa. As a result, I propose we either give suladan 10 non reinforcing war mumaks or give him a level 1 war mumak maa. I prefer the non reinforcing option but either works.

**Comment by JukeJukestar** [comment]
I cant find where this special unit stack would be spawned. Do you know what the host was called or wether it was added via the starting event?
Further research required as I cannot find any references in the code to this.

**Comment by jj248** [comment]
This is on game start and is randomly created by the AI, we have no control over it, that's why there's no code to spawn it.  Not an issue, so closing.
