### ISSUE TITLE
Broken trigger loc on constructing holdings

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#813]
![image](https://user-images.githubusercontent.com/76008882/230098697-741d0210-39e3-4a43-9677-1cb4dea6063b.png)

These triggers (likely related to being elvish?) are not localized properly

**Comment by jj248** [comment]
Ready to test.

**Comment by savagesach** [comment]
![image](https://user-images.githubusercontent.com/86676697/233799890-d3a88049-7df3-4740-a385-23aa52ae02fd.png)
the trigger is now localized

**Comment by jj248** [comment]
Perfect, thanks.  Closing.
