### ISSUE TITLE
Kingdom of Rhovanion and Rhovanorim Testing

### ISSUE THREAD

**Issue by VectorMaximus** [jj248/RealmsInExile#815]
Good day Testers!

I have finished the general scope of my work on the Rhovanorim and their accompanying decisions. General intent is that you test via doing a campaign as one of the Rhovanorim counts, aiming to take the decisions.

Decisions to test:

- [ ] Reclaim the Kingdom of Rhovanion. Feedback on difficulty, how good the rewards are, etc, is appreciated.
![image](https://user-images.githubusercontent.com/79318177/230503304-84f0cf39-66c4-4552-aeaa-b63345d07508.png)

- [ ] Reclaim the Plains of Rhovanion. Again, feedback on difficulty, balance, rewards, etc.
![image](https://user-images.githubusercontent.com/79318177/230503386-c632c4e4-603d-450d-b701-97d5dcac3d34.png)

Additionally, the MAA need to be tested. There are four added Men-at-Arms
- Free Men of Rhovanion, skirmishers unlocked from the start
- Rhovanion Cavalrymen, light cavalry unlocked by taking the 'Reclaim the Kingdom of Rhovanion' decision.
- Royal Guard of Rhovanion, Spearmen unlocked by holding _either_ the Kingdom or Empire of Rhovanion as your primary title, and constructing the Royal Hall of Vidugavia
- Aivathuida Cavalry, heavy cavalry unlocked by taking the 'Reclaim the Plains of Rhovanion' decision.

Feedback on the whole feel and enjoyment of the campaign is the desired intent, as well as any balance recommendations.

**Comment by savagesach** [comment]
![image](https://user-images.githubusercontent.com/86676697/230520915-3b251313-0847-4d02-8a87-7ed07afd5da2.png)
uhh that's weird

**Comment by VectorMaximus** [comment]
> ![image](https://user-images.githubusercontent.com/86676697/230520915-3b251313-0847-4d02-8a87-7ed07afd5da2.png) uhh that's weird

Well how the heck did that get there?

Fixed

**Comment by savagesach** [comment]
after restoring the kingdom, I recommend the modifiers be changed from character modifiers to dynasty modifiers

**Comment by Jaco-Daan** [comment]
This has been tested thoroughly, closing
