### ISSUE TITLE
Vanquish Darkness does not give a truce with the former ruler

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#816]
This allows them to reconquer their territory instantly

**Comment by savagesach** [comment]
![image](https://user-images.githubusercontent.com/86676697/232365325-5eabb39e-28ec-4365-aaec-0576a3e73ec0.png)
vanquish darkness does not give a truce if you capture orc leaders as they get auto executed, removing the truce

**Comment by BriceLeduc** [comment]
If you capture which Orc leader ? The vanquish darkness cannot spawn an Orc afaik.

**Comment by jj248** [comment]
Agreed.  Truce is still acquired in this situation.  Closing. 
![image](https://user-images.githubusercontent.com/26043074/233601685-5b577975-22ef-45d8-9137-d2a4f647a22c.png)
