### ISSUE TITLE
Rhunnic Pantheon has Ecclesiarchy

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#817]
Rhunnic has the Ecclesiarchy tenet, despite having lay clergy. This is a bug.

**Comment by jj248** [comment]
Presumably we mean Pluralistic here: 
![image](https://user-images.githubusercontent.com/26043074/231719260-a50e7497-1957-4603-a550-80a8564429b7.png)

**Comment by jj248** [comment]
I could switch away from Pluralist but then that would make their adaptive tenet invalid... One for @VectorMaximus to make a call on!
