### ISSUE TITLE
Tributaries cannot join suzerain wars unless called

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#818]
If the suzerain does not initially call the tributary into the war, they are unable to join.
They should have the option to though - situations such as a player Haruzan wanting to support saurons wars could arise

**Comment by jj248** [comment]
I've added the functionality for non-permanent human tributaries to offer to join their suzerain's defensive wars using the offer to join war interaction, ready to test: 
![image](https://user-images.githubusercontent.com/26043074/231717873-7d380a4e-e894-4196-a48a-6d78576659a4.png)

**Comment by savagesach** [comment]
![image](https://user-images.githubusercontent.com/86676697/233716729-f75bd8e8-769b-4055-b480-6a112e47f0c8.png)
this has the same problem as https://github.com/jj248/RealmsInExile/issues/745 where there's no alert to notify players that it's possible to join the war

**Comment by savagesach** [comment]
![image](https://user-images.githubusercontent.com/86676697/234093285-997c9339-6ee8-4a3e-9ad6-96e62ed977c1.png)
the alert does not show up in my game

**Comment by jj248** [comment]
Again, I suspect you may not have pulled latest version, but let me know. :)

**Comment by savagesach** [comment]
![image](https://user-images.githubusercontent.com/86676697/234124421-884861d9-19fb-4e16-9aff-6f8c2a9543c0.png)
yeah you're right I didn't pull latest version. this works now

**Comment by jj248** [comment]
Great - thanks.  Closing.
