### ISSUE TITLE
Sauron can become your friend through event

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#820]
This friends and foes random event allows you to become friends with immortals.

![image](https://user-images.githubusercontent.com/76008882/230759110-be25b23c-b417-4066-8387-7994837c5ea5.png)

Should be pretty easy to patch, just dont fire for cannot_be_killed chars

**Comment by BriceLeduc** [comment]
Pushed a fix, ready for testing

**Comment by blackbird5598** [comment]
You cannot become friends as I've tested with Saruman but you can become best friends apparently

**Comment by Jaco-Daan** [comment]
Lonewolf ssaid he hasn't recieved this event for a while, closing
