### ISSUE TITLE
Suzerains raid their tributaries

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#824]
Suzerains are able to raid their tributaries. Should be prevented or the AI should be discouraged from doing it.

**Comment by jj248** [comment]
There's no real way to prevent this, we just don't have the code for it.  In vanilla too, I imagine there's nothing to stop you raiding your ally.

In code, we can only control who can and can't raid and some ai for raiding that affects all raiders in defines.  I tweaked this already to make the ai favour raiding people they consider to be of evil faith and not at all for righteous:

`# Hostility levels start at 0 (same faith or equivalent to same faith)
	RAID_SCORE_FAITH_HOSTILITY_MULT = {	# Raid score mult based on hostility
		0 #LotR - raiding targets massively favour evil faiths
		1 #LotR
		5 #LotR
		10 #LotR
	}`

I don't think there's more I can do for that, so closing this issue, but @JukeJukestar, feel free to chat with me about it.
