### ISSUE TITLE
Denethor will immediately colonize the wetlands north of Ithilien

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#825]
![image](https://user-images.githubusercontent.com/76008882/231467550-4f07f2fd-d071-47dd-b52c-14b9890abe85.png)

Denethor will immediately start to colonize the abandoned wetlands north of ithilien, although its costly and doesnt help them at all.
I think it also goes against the spirit of Gondor being heavily on the defensive and in a slow decline.

Perhaps prevent AI Gondor from colonizing until Aragorn arrives (either binding it to Denethor, Faramir and Boromir, or having them start colonizing after a certain year)

**Comment by jj248** [comment]
Added a block to stop AI Denethor from colonising.

**Comment by savagesach** [comment]
![image](https://user-images.githubusercontent.com/86676697/232333868-ceffc617-a134-4db6-a4ac-de87bfda46ba.png)
denethor no longer colonizes provinces in north ithilien as you can see here
