### ISSUE TITLE
Dune Sea Mirage Event

### ISSUE THREAD

**Issue by Jaco-Daan** [jj248/RealmsInExile#830]
mirage event in dune sea where character either decides on investigating a spot in the desert or continouing on his/her journey. event is about 4-5 event windows long if you take the 'investigate' option. 

Chance for the event to randomly fire yearly with any character that is located in the Dune Sea region.
To test the event just open console and type 'event harad.0018 - harad.0025'.

Currently a bug where the game crashes when the event window which causes a duel appears.

**Comment by jj248** [comment]
This is ready for testing.  Note that the duel CTD is covered under #622 , so no need to comment on that here.

**Comment by Remerod** [comment]
@Jaco-Daan you done it again, the event code is wrong! plz correct it... (have you heard of copy and paste? just something to check for the future :P )

**Comment by Remerod** [comment]
ok, so after getting the "correct" event code i've tested these ( 'event harad.0018 - harad.0025') and the localization is working! 

i did test them by typing the code and not in a random observer, but i test once by playing and it did fire after 5 years
I did not check the rewards super much but i did not see anything outrageous, so i think it's working fine.

Altough i would like to ask on this comment
> Chance for the event to randomly fire yearly with any character that is located in the Dune Sea region.

 how big is the chance? becouse i do think this is not something that should happen to often to you if there is not to many events, as it could be repetitious if it happens for all rulers all the time in the dune sea/or just each dekade for them

**Comment by Jaco-Daan** [comment]
The event has the same chance of happening as the 'Mumakil rampage' event, but once the event happens a flag is applied to the character.

AKA, after you've received the event, you won't be able to get it for the next 10 years at all.

**Comment by Remerod** [comment]
ok, talked some with Juke some and we agreed it's not common enough so i think this issue is done and ready for close, good job on your first event!
