### ISSUE TITLE
Dynamic COAs are broken

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#832]
I was testing dynamic coat of arms and they dont seem to work.

None of the ones in Ithilien or Gondor are functional.
When I tried to test if the same is the case for Bellakar.

**Comment by JukeJukestar** [comment]
Edit: I was unable to reproduce bellakar getting mardruak crashing the game

**Comment by BriceLeduc** [comment]
Yes, that was a temporary issue, it's been fixed
