### ISSUE TITLE
Elven barons should be able to get married and have children

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#833]
Potentially trigger off of five_year_everyone_pulse in yearly on actions.

**Comment by jj248** [comment]
I've added an on action that will seek to marry off elven barons and give them the chance to have children - ready to test.

**Comment by Remerod** [comment]
**Tested**
So, it is clearly working, almost to well. So I created 10 baronies as thranduil and gave them to elves from the range of age 30 to several millennia old! and within 5 years all but 2 had taken spouses, and most people who where several millennia old married others who where millennia old (one 30 year old ruler married a 501 year old lass)

So it is definitely working, i would personally see it being toned down a little bit, and if something can be done to the elves that 30 year old and similar to wait for marriage to later in life i think would be a good thing!

**Some Pictures!!!**
I included the memories of character so you can see when they decided to marry (and on some pictures i included the age of the spouses) 
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/234739299-a8dbc93d-d920-4f2d-bef6-d3d18aff98ab.png)

![image](https://user-images.githubusercontent.com/79544635/234739341-c403a1b2-1848-4f27-8a38-6051d8660453.png)

![image](https://user-images.githubusercontent.com/79544635/234739595-2cd71249-42f7-44b9-a254-4dd7c3aa9520.png)

![image](https://user-images.githubusercontent.com/79544635/234739406-43eb6abf-9d2a-44ba-9f2f-00187703e334.png)

![image](https://user-images.githubusercontent.com/79544635/234739441-84af7fe9-7505-4b3c-b328-fc1bbc10a8a7.png)

![image](https://user-images.githubusercontent.com/79544635/234739481-92a0166d-956b-4e18-95eb-0597e2ec4651.png)

</details>

**Comment by BriceLeduc** [comment]
Agreed, we should disable romance and marriage for Elves under 50, as they are considered children

**Comment by Remerod** [comment]
ok, i'll move this back to in progress then for now

**Comment by jj248** [comment]
We'll look at this later.

**Comment by Jaco-Daan** [comment]
According to Jauffre, elven barons can get marry + get kids, its merely rare, so it's not often seen. Closing
