### ISSUE TITLE
Elven refuges created in every conquered barony

### ISSUE THREAD

**Issue by RedArkady** [jj248/RealmsInExile#834]
https://discord.com/channels/751097183448727552/752159439703900190/1099375547542413403

**Comment by savagesach** [comment]
![image](https://user-images.githubusercontent.com/86676697/233874629-bddc3559-ca9f-4a05-83c0-ad64da9a9c36.png)
![image](https://user-images.githubusercontent.com/86676697/233874660-239dfc44-3edf-42ee-834b-7bf675299e17.png)
Elven refuges are no longer being made in empty baronies when elves conquer orcs, but the issue still happens in reverse

**Comment by jj248** [comment]
Now fixed and prioritising castle -> city -> church when full. :)  Closing.
![Uploading image.png…]()
