### ISSUE TITLE
Isengard Placeholder Text

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#839]
Evil Isengard events still have placeholder text. Will update if i find more.

## Isengard Events

- [x] - isengard.0004
- [x] - isengard.0006
- [x] - isengard.0007
- [x] - isengard.0015
- [x] - isengard.0016
- [x] - isengard.0018
- [x] - isengard.0019
- [x] - isengard.0260
- [x] - isengard.0261
- [x] - isengard.0262
- [x] - isengard.0289

## Gaze Into the Palantir Decision
![image](https://user-images.githubusercontent.com/76008882/234354033-e54f885b-1472-4651-866e-522845f19ea3.png)
missing trigger loc.

**Comment by jj248** [comment]
Palantir fixed - Vector is working on the missing loc.

**Comment by RedArkady** [comment]
OK loc done. Would be good if the event chains could be tested in playthrough rather than via console to make sure they all read right in context.

**Comment by savagesach** [comment]
just to be clear, should I only test evil isengard loc, or evil and good isengard loc?

**Comment by savagesach** [comment]
so I tested for good saruman the initial two palantir events, the white council events, and the university events.

**Comment by savagesach** [comment]
![image](https://user-images.githubusercontent.com/86676697/234967578-c7f89b44-fa84-4644-bb5f-ddff1a1759a7.png)
I'm not sure how much loc this event is supposed to have, but it seems suspiciously sparse

**Comment by savagesach** [comment]
![image](https://user-images.githubusercontent.com/86676697/234971594-0cbf8d83-ed78-4855-80aa-df806ff165ab.png)
this event definitely needs loc

**Comment by Remerod** [comment]
moving this back to non-critical then, and hopefully it get's tackled, might be good idea to ask writers to take a look at this on #issues-discussion

**Comment by Remerod** [comment]
the two events Nemcraft brought up should have a good amount of text now

**Comment by Remerod** [comment]
i doubled checked with Nemcraft and those 2 events where the only ones missing proper text, that's fixed so closing with this comment
