### ISSUE TITLE
"Recruit from the Ranks" bugged

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#847]
![image](https://user-images.githubusercontent.com/76008882/234552830-4f297979-2383-4ddb-82cf-980bc918ca06.png)

The decision requires the "Workshops of Isengard". However, once they are upgraded to "Furnaces of Isengard", the decision becomes unuseable.

**Comment by jj248** [comment]
Should be fixed @JukeJukestar , you can test.

**Comment by savagesach** [comment]
![image](https://user-images.githubusercontent.com/86676697/234938026-917f3d80-cc15-4910-a4fd-f7dcf6c4de35.png)
![image](https://user-images.githubusercontent.com/86676697/234938102-6fffc3b2-c2a3-42bc-8559-139dbc8a4a04.png)
the workshops of isengard modifier has vanished, meaning that the recruit from the ranks decision never appears

**Comment by Remerod** [comment]
ok, closing this then
