### ISSUE TITLE
Elven lands retain very high development after elves flee

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#851]
This is a relatively minor issue, just something to keep in mind. Dobt adress before 3.0, maybe pick up for 3.1

When elven counties are conquered and converted,  they retain their usually very high development. This feels rather odd if the area was resettled by orcs, easterlings etc.

## Possible solutions
- have the effect include a rough check of development level, and then reduce it appropriately
- Add a monthly development loss to the elven holdouts modifier

## Potential problems
- elves reconquering counties would find them with very low development
- this will be difficult to balance

**Comment by BriceLeduc** [comment]
Elven lands are not very high dev to start with : Caras Galadhon starts at 30, everything else is in the low 10s

**Comment by Natsuki-best-girl** [comment]
a small balancing effect is added that halves their development similar to mongol devastation from vanilla.

**Comment by BriceLeduc** [comment]
Changed this so that only counties above 40 development (will be very rare) are affected. Otherwise it would be too unbalanced
