### ISSUE TITLE
2d: some Faith Icons needs some tweaking (post 3.0)

### ISSUE THREAD

**Issue by Remerod** [jj248/RealmsInExile#853]
So these where over looked bu the lead devs and they wanted some tweaking to these faith icons

**Easterling faith Icons**
these two icons effect was to much and looks a bit weird it was decided by the lead devs and needs to be fixed (in the future)  I'll mention it here, but i'll do an issue for it

![image](https://user-images.githubusercontent.com/79544635/235264876-2050c068-1ddd-4bed-933f-0f1d13fc381d.png)

their names are `easterling_rhun_symbol_morgoths_fire.dds` & easterling_kerkassk_morghul_fanatics.dds

**Generic Faith Icons**
Also these 4 where not accepted by Jamie because there where to blurry for his taste and need to be scaled up in quality

![image](https://user-images.githubusercontent.com/79544635/235265071-96ceb75e-c1ed-4668-a91f-f86c68e440a0.png)

their code names are;
mumakil_faith_icon.dds
spider_abstract_faith_icon.dds
spider_faith_icon.dds
wave_faith_icon.dds

**Comment by Chief305** [comment]
fixed

**Comment by Chief305** [comment]
fixed
