### ISSUE TITLE
Universities Bugged in 3.0 Release

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#855]
Will keep this updated once i get more info.

![image](https://user-images.githubusercontent.com/76008882/235305703-d104e4c7-2eb2-4f34-8f52-58ec443f52cc.png)
A player reported being able to use the decision as Gundabad.

**Comment by VectorMaximus** [comment]
Already did a fix for this

**Comment by JukeJukestar** [comment]
How so? is it disabled now?

**Comment by VectorMaximus** [comment]
It's not the actual decision to establish a university that's showing up there, but an event that's meant to fire when you take it. For some reason it hadn't been commented out. I've commented it out now.
