### ISSUE TITLE
Isengard Unleashed tyranny wars

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#859]
![image](https://user-images.githubusercontent.com/76008882/235313642-e02672f3-35b8-4696-9f63-007e0b7b0f3a.png)

Public bug report - Isengard lost a tyranny revolt by Thrydain and he inherited the empire because he is the strongest vassal.

Possible solution: have a check on succession for isengard unleashed, if its not saruman - destroy the title

**Comment by Jaco-Daan** [comment]
Fixed this, closing.
