### ISSUE TITLE
Elven courtship not firing

### ISSUE THREAD

**Issue by Jaco-Daan** [jj248/RealmsInExile#860]
When testing the MP with a few of the testers, I couldn't romance a character when playing as one of the elves

**Comment by BriceLeduc** [comment]
Pushed a fix, ready for testing

**Comment by savagesach** [comment]
![image](https://user-images.githubusercontent.com/86676697/236942294-f0107df7-0074-45dd-9f3d-79ba493946e3.png)
![image](https://user-images.githubusercontent.com/86676697/236942633-e5368795-5f7a-45ef-a7ed-9e01d95cf3e1.png)
as thranduil I arranged a courtship with legolas, then let the game run a few months before switching to legolas. I also tried arranging a courtship myself by playing Ilmarien. In both cases, courtship worked as intended.

**Comment by Remerod** [comment]
ok, then i'll close this
