### ISSUE TITLE
Endlessly invalidating contracts for Elves with human tribal vassals

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#863]
When elves have TRIBAL! human vassals, sometimes their feudal contract will invalidate endlessly and constantly (Claiming "normal levy obligation invalidated")
When the title is revoked, it stops happening.

![image](https://user-images.githubusercontent.com/76008882/235348763-8eb13b0f-4231-47a1-bafe-b9372aef715d.png)

My theory: Likely related to the fact that the game tries to reset the invalid feudal contract, exept it tries to reset it to default obligations, endlessly causing the same issue again and again.

**Comment by BriceLeduc** [comment]
This is a resurgence of issue #795
