### ISSUE TITLE
Colony Domain Overhaul

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#865]
We talked about it on the discord a bit, and agreed that this would be a good alternative to the current way its set up:
Currently, players will sometimes inherit/ conquer a bunch of colonies at once, effectively reducing their domain limit so much they have to grant out most of their real holdings. Domain management is a nightmare.

## The proposed change:
Have every colony give +1 domain limit, but restrict the player from creating any more colonies while he holds one or more colonies.
This should also reduce colony spam where some characters will continuously fund more and more colonies without finishing their old ones.

**Comment by blackbird5598** [comment]
If the player doesn't want to hand out their "real holdings" I don't see why they would realistically go on a colonizing spree, otherwise I don't see how its a issue.

**Comment by savagesach** [comment]
also a much better way to make colonizing harder would be to actually fix this issue and make colonizing cost money
https://github.com/jj248/RealmsInExile/issues/850

**Comment by Remerod** [comment]
Personally i agree with Juke on this

**Comment by savagesach** [comment]
only being allowed to hold one colony at a time is going to make restoring the greenwood twice as slow compared to the already currently slow pace

**Comment by savagesach** [comment]
other thing is no one's forcing players to give up their good holdings to colonize faster, if they want to do that it's their choice. they could just colonize slower and not have the issue.

**Comment by RedArkady** [comment]
I can see the argument for allowing, say, a limit of 2 colonies at a time to be created rather than one. But the problem that has been identified here isn't people deciding to _create_ so many colonies that it forces them to give up core domain, it's when they _conquer_ territory that incudes colonies that they cannot then give away. Either we adjust for that using a domain limit modifier, or have an option for the conquered colony revert to wilderness.

**Comment by blackbird5598** [comment]
A decision to revert a colony back to wilderness is ideal imo, and possibly add a setting for die hard "it needs to be slower" guys for the colonizing speed, regular, fast, slow.

**Comment by Jaco-Daan** [comment]
Addresed in the general wilderness rework, moving to testing. (Will provide details later)

**Comment by savagesach** [comment]
the wilderness rework has made this issue redundant by addressing the issue in a more efficient and convenient way
