### ISSUE TITLE
Missing cultural beverage for Galadhrim

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#871]
![image](https://user-images.githubusercontent.com/76008882/235362722-f8aa87a4-0190-445f-aedc-80750820d80c.png)

Bug reported on the discord - they are missing a beverage to drink!

**Comment by BriceLeduc** [comment]
Strange. They do have cultural beverages in the code

**Comment by jj248** [comment]
@BriceLeduc - will leave you to update on this.  Event in question is trait_specific.9001 if you're wanting to look at this case in particular.

**Comment by BriceLeduc** [comment]
The Galadhrim do have cultutral beverages in the code, and this bug hasn't been reported again for a year. I say we close the issue

**Comment by jj248** [comment]
Agreed, I've also fired this a bunch a time with no missing loc.  Going to assume this is fixed and close.
