### ISSUE TITLE
Aragorn doesn't get his bling upon royalist victory or the Kingstrife

### ISSUE THREAD

**Issue by BriceLeduc** [jj248/RealmsInExile#873]
https://discord.com/channels/751097183448727552/1102584422328434828

**Comment by savagesach** [comment]
I can't test this issue if I don't know specifically what's wrong

**Comment by BriceLeduc** [comment]
Aragorn didn't get the artifacts once the Kingstrife was won

**Comment by savagesach** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/86676697/057d9774-baec-4ca1-b1b0-ae7c8b5cd44a)
![image](https://github.com/jj248/RealmsInExile/assets/86676697/420c0e81-eef7-4648-8b7f-836d8467fcf2)
aragorn now gets all his artifacts after winning the kinstrife
