### ISSUE TITLE
Aragorn doesnt get his artifacts if he wins the kin-strife

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#874]
If Aragorn becomes King through winning the second kin-strife, he does not get his artifacts.

![image](https://user-images.githubusercontent.com/76008882/235469482-cb0b1486-d2a3-4dc9-823b-d612d64817ef.png)

Probably worth taking a look.

**Comment by BriceLeduc** [comment]
This is a double of issue #873. Closing
