### ISSUE TITLE
Aragorn gets Arwen as his lover even if he chooses a different wife

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#879]
![image](https://user-images.githubusercontent.com/76008882/235590864-a5206f22-09be-4318-9139-e973d9fa3489.png)

The bug is back according to a report from Blackbird.

Needs replication, can someone confirm this is the case?

**Comment by savagesach** [comment]
![image](https://user-images.githubusercontent.com/86676697/236948216-d71ba891-3a55-40b5-8a58-035b692d4d4c.png)
I fired the return of the king event early and aragorn did not get arwen as a lover or arwen's children
![image](https://user-images.githubusercontent.com/86676697/236958652-e2068f58-8b0e-4419-a6b4-d21aeaf7b2fd.png)
I also let the event fire naturally in another game and it still works as intended
