### ISSUE TITLE
Beardless trait for Dwarves

### ISSUE THREAD

**Issue by BriceLeduc** [jj248/RealmsInExile#881]
Idea : possibility to shave another Dwarf's beard (via event, court event or imprisonment), would give them the Beardless trait for 5-10 years, rendering them unable to inherit (basically a temporary castrated trait) and losing 5 diplomacy. After a period of time, the beard would grow back and the trait disappear. 

An additional idea would be to also create a congenital version of the trait, with a very small chance to appear during teenage years.

**Comment by Remerod** [comment]
yeah, that seems kind of cool

**Comment by JukeJukestar** [comment]
Sounds cool. Could be a char modifier instead too if you like, we have similar ones in vanilla such as the one where your clothes are stolen

**Comment by BriceLeduc** [comment]
I think a trait would work better, especially if we want to make it inheritable

**Comment by savagesach** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/86676697/40f17147-3741-4e55-9665-ccf700823b82)
![image](https://github.com/jj248/RealmsInExile/assets/86676697/27cfd6d2-c61c-48a7-b752-42ea6204508b)
The beardless interaction works as intended, though I do think non dwarves should be able to shave dwarves as well

**Comment by BriceLeduc** [comment]
Missing locs and icons corrected.

This interaction is exclusive to Dwarves as a stranger would not be aware of the gravity of the offense to a Dwarf. They would prefer classic torture or blinding/castration if they're eligible.

**Comment by savagesach** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/86676697/4d77439b-9043-4a66-b335-eb4239a072f2)
![image](https://github.com/jj248/RealmsInExile/assets/86676697/44b08052-d338-44b0-acbc-e2ed6e252a64)
The beardless interaction works as intended, and all the icons and locs are there.
