### ISSUE TITLE
Localization: Missing Special Building Map mode loc

### ISSUE THREAD

**Issue by Remerod** [jj248/RealmsInExile#883]
There is a missing Special Building Map mode localization for Abrakhan Bazaar Complex, as reported by community member Marob, i have doubled check to see if this is the case, and it is.

![image](https://user-images.githubusercontent.com/79544635/235928912-02a13eb1-d16d-4cb1-a69d-2d0151ede888.png)

**Comment by RedArkady** [comment]
Fixed - closing.
