### ISSUE TITLE
Saruman befriend scheme is not working

### ISSUE THREAD

**Issue by blackbird5598** [jj248/RealmsInExile#885]
![image](https://user-images.githubusercontent.com/125709421/235946865-b16b1e4a-ae2c-4c3f-b53c-310cae6684ec.png)

I've tried this same scheme on Galadriel and Wulfgar as Saruman, says success but doesn't add them as a friend to relationship tab, early game started the scheme against wulfgar before turning lidless eye but finished after turning lidless eye. Seems to be working fine for other characters.

**Comment by Jaco-Daan** [comment]
Seemed there was a trigger put in the wrong spot. It would make it so that anyone Saruman befriends as an evil istari can't be his friend, moved the trigger to the is_shown block. Closing
