### ISSUE TITLE
Nazgul join factions against Sauron

### ISSUE THREAD

**Issue by blackbird5598** [jj248/RealmsInExile#891]
![image](https://user-images.githubusercontent.com/125709421/236135263-c4d61650-6073-4395-a073-e9e8a089bd73.png)

As the title describes Witch King is declaring liberty wars on Sauron, this is the first one I caught not sure if he declared any other wars before this, unclear how Sauron lost his loyalty hook on him my hypothesis is maybe a unknown event from his spymaster or a court event. more testing required to determine it.

**Comment by JukeJukestar** [comment]
should be fixed, nazgul arent valid characters for joining factions if their liege is sauron
