### ISSUE TITLE
Saruman can get Theoden's Rohan events

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#892]
![image](https://user-images.githubusercontent.com/76008882/236448665-329aa951-d9f0-422f-beb4-c8cd1d0bc8ff.png)
![image](https://user-images.githubusercontent.com/76008882/236448685-25ff6fff-e00a-4f95-9697-08f2b610e5a5.png)

We got reports of Saruman getting theodens events if he takes rohan before they trigger.

**Comment by Natsuki-best-girl** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/88321182/a4f539e3-32f0-4915-9a73-b0f8550631d2)
There it is, anyone that holds the kingdom title get the event

**Comment by Natsuki-best-girl** [comment]
Footnote: I am not sure what triggers event, (see relevant commit) so uh it is really a quick fix that only solves this, eg. if saruman already has rohan it should skip directly to his victory event
