### ISSUE TITLE
Uruk-Hai have no MAA

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#893]
Only Saruman unlocks them. Seems like an oversight.

**Comment by BriceLeduc** [comment]
We should probably tie the MaA to a tech rather than a character flag

**Comment by JukeJukestar** [comment]
> 

The problem there is that there are 8 different combinations of units that are possible. Reckon we can enable certain oned based on global vars?

**Comment by Remerod** [comment]
Jupp this needs to be 100% however we do it

![image](https://github.com/jj248/RealmsInExile/assets/79544635/88c46ece-02d0-4c78-937a-cdb22c125e16)

**Comment by JukeJukestar** [comment]
Its a difficult question - we cant give them game start MAA since the ones they are supposed to have are decided by saruman later in the game. 

Maybe we can keep using sarumans character flags for his own uruk MAA, but his decisions also set the global variables for what uruk-hai MAA are avaiable.
If a player starts as uruk-hai via ruler designer, they could get a gamestart event where they can set those uruk-MAA for saruman?

**Comment by Remerod** [comment]
> Maybe we can have his decisions also set global variables for what uruk-hai MAA are avaiable to uruk-hai culture.
If a player starts as uruk-hai via ruler designer, they could get a gamestart event where they can set those uruk-MAA for themselves?

I can see this work.. but it also feels a bit... complex and easy to become bugged. But sure that's an idea

**Comment by Chief305** [comment]
or we could just set a trigger and we wouldnt need to make a global event

**Comment by JukeJukestar** [comment]
@Chief305 how did you solve it?

**Comment by Chief305** [comment]
@JukeJukestar i created a maa trigger check my last commit
