### ISSUE TITLE
Abrakhân Rework Testing

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#898]
I just pushed my rework to the Abrakhân code. It should hopefully make the decisions and events functional again without changing it too much. Please test Abrakhân extensively so we can track down any remaining issues! (Both with Golden King and Black Vizier!)

- Reworked most of the placeholder localization
- Tweaked decision requirements - Dune Sea should be a bit easier, while Felaya has been moved from 'Subjugate Bellakar' to 'Subjugate Mardruak' (Now called 'Subjugate the Bay of Felaya')
- Tweaked decision rewards, most notably the reward modifiers are now much weaker, but permanent - even after succession
- Merged empires of Nafarât and Abrakhân - it always lead to weird interactions. It should now be handled via cultural name and COA.

**Comment by savagesach** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/86676697/7bddc4fb-0ab0-4461-9b7e-6725492a1ea0)
the golden king recalled event needs localization

**Comment by savagesach** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/86676697/4b99cb79-cd70-49c5-b38e-8542d0d48be8)
![image](https://github.com/jj248/RealmsInExile/assets/86676697/0c69c366-3188-41e1-bc29-1364fc549ae4)
also I do not think the black vizier should be auto converted to pustic, part of what makes him interesting is his anbalukhori culture

**Comment by savagesach** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/86676697/805950f1-f74f-4e39-8080-e7ae621737fa)
![image](https://github.com/jj248/RealmsInExile/assets/86676697/1faa5af4-8c49-4bf7-acc0-e0c0a4307baa)
subjagating umbar and bay of felaya both require mardruak to complete. This seems like a really big oversight

**Comment by savagesach** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/86676697/db860fee-b3e8-4482-bfbd-6f69fc3c8770)
This modifier has unlocalized text

**Comment by savagesach** [comment]
Apart from all that though, the only real complaint I had is that ai sauron never actually recalls a player golden king. This means that if you want the golden king to get recalled in singleplayer, you are forced to switch nations and make the ai recall him. This should be fixed

**Comment by JukeJukestar** [comment]
Thanks for the feedback! Will take a look.
Felaya and Umbar both requiring Madruak is intended, thats also how it was before - basically you just arent supposed to loose it before unlocking the other decision

**Comment by JukeJukestar** [comment]
>  also I do not think the black vizier should be auto converted to pustic, part of what makes him interesting is his anbalukhori culture

I tend to agree, the AI should probably convert on their own. This was added before I touched abrakhan though, not sure why.

**Comment by BouenMarsh** [comment]
The game-start event offers a choice of the two: go after Dune Sea or Nafarati. Whatever you chose though, both decisions become visible simultaneously. Is that intended, or should they be step-by-step?

**Comment by jj248** [comment]
@JukeJukestar - what's the status on this?

**Comment by JukeJukestar** [comment]
Received a bug report or two i gotta take a look at

**Comment by savagesach** [comment]
is this ready for testing or do you still need to look at the bug report?

**Comment by savagesach** [comment]
this has been seen several times in discord and in mp games; when the golden king gets recalled there is a chance of the golden king still having land in abrakhan with the abrakhan kingdom head of faith title which leads to two abrakhans on the map

**Comment by JukeJukestar** [comment]
Shit, Ill take a look

**Comment by Jaco-Daan** [comment]
I've reworked it and tested it, closing
