### ISSUE TITLE
Nazgûl being captured in sieges/raids/"raid for captive" wars

### ISSUE THREAD

**Issue by BriceLeduc** [jj248/RealmsInExile#899]
Triggers were missing to prevent Nazgûl being captured in raids, sieges and "raid for captives" wars. I've pushed a fix. Ready for testing.

**Comment by savagesach** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/86676697/302ac81c-cf92-49ad-b77b-c1dd79dde335)
![image](https://github.com/jj248/RealmsInExile/assets/86676697/474cbe4c-634f-4f7f-9421-579a43dd74c2)
nazgul can still be captured using the slave raid cb

**Comment by Jaco-Daan** [comment]
Seems issue is fixed, closing
