### ISSUE TITLE
Aragorn gets Steward Artifacts

### ISSUE THREAD

**Issue by savagesach** [jj248/RealmsInExile#900]
When Denethor accepts the return of the king, he loses both the chair of the stewards and the rod of the stewards. This makes no sense as aragorn would want to keep denethor as a steward, and denethor still has the steward title. This is why I think aragorn should not get those artifacts transferred to him.

**Comment by BriceLeduc** [comment]
I don't think Denethor loses his scepter, we haven't coded it that way

**Comment by BriceLeduc** [comment]
same as issue #910, closing
