### ISSUE TITLE
Adapt travel terrain backgrounds

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#905]
In addition to the three event background pools `terrain`, `terrain_scope` and `terrain_activity`, Tours and Tournaments added a third one: `terrain_travel`.
This one differenciates itself from the others by being more specific (a bridge when next to a river, differences between settled and unsettled terrain, etc etc.) These are used for travel backgrounds and have to be adapted for our additional travel terrains (such as deep forest, volcanic plains etc)

**Comment by BriceLeduc** [comment]
Ready for testing

**Comment by jj248** [comment]
I'm minded to close and deal with anything arising as a bug.
