### ISSUE TITLE
Review Accolade Strength for long lived races

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#906]
Max level accolades can have some insanely powerful buffs, we need to make sure this isnt too overpowered for long lived races such as elves, numenoreans and even orcs.
The system is designed to give you progressively stronger buffs until the knight dies, in vanilla this is balanced around regular human lifespans. XP gain is apparently quite rapid, though I have not had time to run in-depth tests for myself.

Some options include:
- Strong debuff to XP gain
- Overall nerf to accolade bonuses for elves etc

## Examples
Here are some examples of max level accolade attributes so you can get a rough idea of how powerful they are:
![image](https://github.com/jj248/RealmsInExile/assets/76008882/862d99c6-ae1b-486f-80d4-49a90e298a4d)
![image](https://github.com/jj248/RealmsInExile/assets/76008882/9597225b-37f9-4085-b74a-9655a0725b4e)
![image](https://github.com/jj248/RealmsInExile/assets/76008882/d9d6df98-6d95-4d92-9fa9-6e303ce8462b)
![image](https://github.com/jj248/RealmsInExile/assets/76008882/b66293b7-510b-4449-b308-81649299019f)
![image](https://github.com/jj248/RealmsInExile/assets/76008882/b96600dd-054c-4c06-8b46-24b54c6e7760)

**Comment by BriceLeduc** [comment]
In my vanilla games I regularly have my accolades between levels 3 and 5. I don't think we should touch the bonuses as that would also affect normal humans. I think slowing down xp acquisition for longer-lived races should be enough, if possible

**Comment by JukeJukestar** [comment]
I tend to agree with you since reducing the boni would be complex. Perhaps they could just get an XP reduction somewhere between 50 and 80%

**Comment by BriceLeduc** [comment]
Or an XP continual reduction equivalent to vanilla loss on death/20, if that's possible. To keep things on a level with normal humans

**Comment by BriceLeduc** [comment]
I've checked the code and there is no continual glory loss mechanism. Also, you can increase the amount of glory generated but not decrease it (theres an accolade_glory_gain_mult parameter, but it's additive rather than multiplicative).

**Comment by JukeJukestar** [comment]
> I've checked the code and there is no continual glory loss mechanism. Also, you can increase the amount of glory generated but not decrease it (theres an accolade_glory_gain_mult parameter, but it's additive rather than multiplicative).

yeah there isnt glory loss, its reset entirely on death. Do you think we can make a new parameter to reduce glory gain?

**Comment by Jauffr** [comment]
What if we reduced the number of acolades elves can have? Let them have consistently very strong ones, yet they can only have a small number. Potentially giving a smaller penalty to dwarves and orcs as well after testing I suppose, though numenoreans would also have a similar situation with being long lived enough to keep their acolades fairly high tier, so any non elf nerfs sounds overblown

**Comment by JukeJukestar** [comment]
Brice tested them a bunch and apparently its not actually too bad - we can probably keep it the same as humans for now

**Comment by Jauffr** [comment]
Wonderful news. Thats one less thing to worry about. Should we close this issue for now then as its been open for weeks without comment?

**Comment by BriceLeduc** [comment]
After a 71 years game as Galadriel, fighting multiple wars against Sauron and DG, as well as doing a few tourneys, I had one accolade at lvl 5, 2 at lvl 3 and 1 at lvl 2. I conclude the accolade glory doesn't need adjusting.
