### ISSUE TITLE
Adapt Character Backgrounds

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#907]
None of our characters have our special character backgrounds (galadriel, sauron, nazgul etc...)

We need to adapt 'em!

**Comment by Jauffr** [comment]
Just to clarify. None of these count as the special backgrounds you are reffering to?

![Screenshot 2023-06-28 235929](https://github.com/jj248/RealmsInExile/assets/108106660/77ea9b51-b13b-4028-a56f-a90b64f4d6c7)
![Screenshot 2023-06-28 235906](https://github.com/jj248/RealmsInExile/assets/108106660/09f7926a-b51f-4a4b-b74b-f515886dcaf1)
![Screenshot 2023-06-28 235901](https://github.com/jj248/RealmsInExile/assets/108106660/328246a5-9f81-4ddf-87b1-ce9f80d854e9)
![Screenshot 2023-06-28 235856](https://github.com/jj248/RealmsInExile/assets/108106660/f7cc8938-ed02-4d34-a318-9723065a18db)
