### ISSUE TITLE
Stewards apparently lose all their artifacts on the return of the King

### ISSUE THREAD

**Issue by BriceLeduc** [jj248/RealmsInExile#910]
He should only lose his chair and Palantír

**Comment by BriceLeduc** [comment]
Can some tester confirm this happens consistently ?

**Comment by blackbird5598** [comment]
He takes everything but the chair & his banners it would appear.
![image](https://github.com/jj248/RealmsInExile/assets/125709421/78cfd24d-6b95-4c00-9396-af4902bd0e3b)
These are all the artifacts kept from Aragorn when he takes over

**Comment by savagesach** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/86676697/6e065407-5f16-4fe1-94b5-62db0a4e3fe8)
![image](https://github.com/jj248/RealmsInExile/assets/86676697/40547a10-7105-41f5-ac56-d5051b5a39ed)
Denethor keeps his banners and chair, but he still loses his rod

**Comment by RedArkady** [comment]
Can we check whether the Rod is now being given to whoever has the steward role on the Council, and just for their time in post? Brice said it should be working.

**Comment by BriceLeduc** [comment]
Oh wait, I meant the Steward title. I don't think it's possible for a court position

**Comment by Jaco-Daan** [comment]
just tested, Aragorn does not receive the Rod of Stewards, the stewards do. closing
