### ISSUE TITLE
TaT Melee Tournaments locked for everyone

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#912]
![image](https://github.com/jj248/RealmsInExile/assets/76008882/ddf90860-92e8-4bc7-b578-2d8a7f917626)

Everyone is considered an elf as far as this trigger is concerned (image taken as a human)

**Comment by BriceLeduc** [comment]
Your screenshot is of a culture that does not have access to mêlées, have you checked for cultures in the West region ?

**Comment by JukeJukestar** [comment]
See #915, the scripted trigger is broken
