### ISSUE TITLE
UI wrongly notifies everyone they are Elves, when the trigger "is_elf = no" is used

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#915]
For certain triggers, every ruler seems to be considered an elf.

![image](https://github.com/jj248/RealmsInExile/assets/76008882/fc02d077-4401-45f3-92c5-5c3dec503c13)

![image](https://github.com/jj248/RealmsInExile/assets/76008882/936fa2d6-0a4a-4fc7-b5a2-4dd9be4029bf)

**Comment by BriceLeduc** [comment]
Those are all instances where the culture does not fill the requirements. Does it also happen when they do ?

**Comment by JukeJukestar** [comment]
I still think this is pretty damn important if its not fixed - we need to localize it properly or players will report it en masse

**Comment by Jaco-Daan** [comment]
This was solved by Tobbzn, closing
