### ISSUE TITLE
Grand Marriages broken for Numenoreans

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#917]
The new grand marriages need to be properly reworked for Numenoreans
1. If you arrange a grand marriage with a numenorean, both characters are over 16 but the Numenorean is under his marriage age, the game will give you three years to do it (as vanilla) before its considered broken. However, you also can't actually fulfill your promise because the numenorean is still considered underage.
2. The alert at the top of you screen tells you you can host a grand wedding, but if one of the two is an underage numenorean you obviously can't
3. if you betrothe one or two children, one of which is numenorean, and promise a grand betrothal, the game still expects you to do it when the numenorean turns 16, even though you cant.

Please review and see if you can spot any further issues with this.

**Comment by savagesach** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/86676697/699620d9-558e-4417-a925-1f7a5dd91ce7)
![image](https://github.com/jj248/RealmsInExile/assets/86676697/a316c7a2-16c6-464b-91d4-4eaa3f1322c6)
 Grand Weddings now are set to give enough time for 3 years after the characters are of age. Also, Grand weddings no longer allow you to host them when characters are underage.
