### ISSUE TITLE
Review Old Age Incapable events for Numenoreans

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#918]
The new incapable events from Tours and Tournaments start to appear more and more frequently with age, after becoming around 60 years old. However, Numenoreans also experience this, so you can have situations where aragorn becomes incapable in his 80s and continues to rule with a regent for the next 200 years.

Review how to fix this, change age to be appropriate. Also make sure elves cant get them, dwarves get them at an appropriate age and review them for orcish lifespans (I am fairly certain an incapable orc would just get an axe in their head to cure their disease)

**Comment by BriceLeduc** [comment]
Sould be solved by my latest commit https://github.com/jj248/RealmsInExile/commit/902bb32589d15801596e05b27b3ae945cd94c000 . Ready for testing

**Comment by Jauffr** [comment]
Well i've gone 42 years into a observer game and literally no one has the incapable trait, so either its just working properly now, or its worked a little too well

**Comment by Jauffr** [comment]
except for this guy who I just managed to catch. He died before I could take the screenshot for obvious reasons. I guess its probably working just fine now then
![Screenshot 2023-06-28 235111](https://github.com/jj248/RealmsInExile/assets/108106660/35729463-ae12-4175-bcf7-67cec9bfe5fc)
