### ISSUE TITLE
Random characters with orc armor

### ISSUE THREAD

**Issue by blackbird5598** [jj248/RealmsInExile#921]
![image](https://github.com/jj248/RealmsInExile/assets/125709421/8610b927-6dfd-416e-98f2-ba71c47219ac)

It seems to be only a problem for tribal characters in Enedwaith that I've found so far, I've tried looking at other characters outside of Enedwaith but haven't found any other Humans wearing orc armor.
 
Also on a probably related note I found a Rohirrim wearing tribal clothes
![image](https://github.com/jj248/RealmsInExile/assets/125709421/86ee5818-fd90-48d0-a0e0-3dd97aaf3177)

I think the problem might be characters wearing clothes they aren't meant to.

**Comment by Rewinged** [comment]
@blackbird5598 I don't suppose you have a save file with some of the clothing errors present in it? Would make things easier to troubleshoot

**Comment by Rewinged** [comment]
Fixed the uruk armour bug, the tribal clothing in rohan and other areas is a placeholder for northern 'loremaster' characters, so thats something thats wip
