### ISSUE TITLE
Arrange marriage/find spouse not showing up

### ISSUE THREAD

**Issue by blackbird5598** [jj248/RealmsInExile#922]
![image](https://github.com/jj248/RealmsInExile/assets/125709421/a44daa97-f1da-4462-b74c-f2bb9d16beda)
If you aren't married and don't have the widower/widowed trait the find spouse in the character menu isn't showing up and for some reason am unable to make a betrothals even when I try to manually arrange it by clicking on a foreign ruler.

![image](https://github.com/jj248/RealmsInExile/assets/125709421/491490aa-f88f-4d1a-9ccb-54f1213d2e13)

Also unable to arrange marriages unless your family member is your courtiers & you manually arrange the marriage with the foreign ruler yourself. Betrothals won't work at all from my testing.

**Comment by BriceLeduc** [comment]
Solved
