### ISSUE TITLE
Tributaries showing tribute in the economy tab

### ISSUE THREAD

**Issue by Remerod** [jj248/RealmsInExile#925]
So before it wasn't possible to showcase this but now we might be able to do this (according to Jamie).
So if possible it would be good for us to try to code this in, as this is one of the small issues we've had with the tributaries, because people want to have an idea of what their economy looks like

So to do:
script it so the tributaries you send to your overlord is shown on your economy tab (remember this applies to permant tributaries, unpermanent tributaries and protectorates ) 

(and the reverse where you see your income from your tributaries as the suzerain/overlord)

**Comment by Jaco-Daan** [comment]
This has been done, closing
