### ISSUE TITLE
Thrydan declares war on Saruman constantly

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#927]
Players in public version have reported thrydan declaribg scripted county conquest wars against saruman, who is supposed to be his liege.

**Comment by Jauffr** [comment]
I don't know who coded the isenguard events and such, but I'd imagine this has to do with the fact that Saruman's Dunland puppet is aparently coded to attack anyone in Dunland that is independant and should be solvable I hope by just telling it to exclude the Isengard titles

**Comment by Jaco-Daan** [comment]
This has been fixed, closing
