### ISSUE TITLE
Intent Compatching

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#928]
We need to compatch the new activity intents. Every activity has certain intents your character can use. Some are inappropriate for elves and such - Seduction or murder perhaps

One big question would be matchmaking intent - we would have to make sure its appropriate to elves if we want to keep it for them.

**Comment by Jauffr** [comment]
Elves probably shouldn't be able to take the "letchery" intent for tours

**Comment by JukeJukestar** [comment]
Im having some issues, the gsme doesnt seem to recognize I am trying to block seduction intents

**Comment by Natsuki-best-girl** [comment]
Other than matchmaking I think all the contents should have been blocked for now, any opinions?

**Comment by JukeJukestar** [comment]
seems to be fine and dandy.
