### ISSUE TITLE
Adjusting Building MaA bonus modifiers

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#929]
Modifiers were updated in this commit: https://github.com/jj248/RealmsInExile/commit/56211697e7c253bf65a72c00f909b0bf11be0847

However, the old values were retained.  These were much lower before as they applied to all MaA that the character held, while now they are restricted to the MaA stationed in that province and so can afford to be much higher.

For example, the vanilla barracks went from providing 18% damage and 10% toughness at level 8, to 160% damage and 120% toughness.  As such, maybe a rough rule of thumb is that we should be multiplying these by 10?  I'm hoping @JukeJukestar can feed in with his wider gameplay and balance knowledge where mine lacks, or delegate to someone else who can feed in.

**Comment by JukeJukestar** [comment]
Im hoping to take a look sometime next week

**Comment by JukeJukestar** [comment]
ok after looking at this for about 30 minutes im gonna be honest - i dont wanna touch these with a 10 foot pole, they are so confusing.

The modifiers seem to be generally fine, though its odd we used numbers instead of the scripted vanilla values

**Comment by Jauffr** [comment]
I assume this conversation is specifically relating to our custom buildings for orcs/undead/elves and in the future dwarves. I could take a look and try my hand at it. I do like working with MAA after all. The concept of multiplying the modifiers by 10 sounds absolutely ridiculous, but hey. Trial and error has to start somewhere eh? and besides. I've wanted an excuse to actually put in a bonus for monsters/horse cav for elven buildings somewhere for a long time, cause Nelornieth's strongest MAA desperately need a way to get bonuses since Tours an Tournaments

**Comment by Jauffr** [comment]
I've made some adjustments to elven buildings to allow them to boost archer cavalry and monsters for the rare cases they apply like Nelornieth. Let me know if anyone would like something adjusted. I am pretty interested in MAA and am more than happy to work on their balancing in the mod. Orcs for example. Should they have a building that buffs monsters? Warg pits for example

**Comment by jj248** [comment]
Probably need some tester feedback on this in general, it's been a long time sitting here. @savagesach and @Hendrix1337x

**Comment by Hendrix1337x** [comment]
Orc buildings still have pre tours and tournaments modifiers
Siege Works gives toughness to siege MAA, Siege MAA don't have toughness to begin with
![12](https://github.com/jj248/RealmsInExile/assets/154389264/0a3b9941-a65d-41eb-b076-fd059bbe605d)
The Hunting outposts give a pre tours and tournaments modifier of +1 from levels 2 to 8(also only orcs from gundabad get light cav making the light cav modifier essentially useless for all other orcs)
![13](https://github.com/jj248/RealmsInExile/assets/154389264/91499848-3503-40af-845c-e5fd035bfe33)
![14](https://github.com/jj248/RealmsInExile/assets/154389264/1c272a98-2ad5-4c4d-ae8d-cd1b4547fcc7)

**Comment by savagesach** [comment]
I have pushed a fix for building maa bonus modifiers, this needs to be tested

**Comment by Cairo-Fischer** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/110961821/af8f1d81-3c5f-4e58-a899-420645e841d5)
![image](https://github.com/jj248/RealmsInExile/assets/110961821/79a9f3df-9d5f-4f77-8285-59caf07fb6d2)
![image](https://github.com/jj248/RealmsInExile/assets/110961821/fc05ea32-c87d-4f3a-b80d-abc4c120d084)
It works so far for me
