### ISSUE TITLE
Review Elven activity/travel/guest balancing

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#931]
Elves should be able to attend eachothers activities (mainly thranduil and galadriel atm).
They need either a buff to travel time or an increase of their preparation time.

They also need to get an option to actually invite one another (As they arent neighbouring rulers, they usually wont). Elves already have relatively few guests due to their small realms and isolation from humans. Players can manually invite other elven rulers, but the AI doesnt seem to do so, so maybe an additional guest selection option would be appropriate.

**Comment by BriceLeduc** [comment]
Implemented : new Elven Rulers guest rule for Grand Weddings, elven travel speed increased by 150% and waiting time increased before the beginning of activities

**Comment by savagesach** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/86676697/4f639c42-4a3f-49ea-8a9c-4ec35aca18ee)
After I hosted a tournament as thranduil, ai galadriel joined the tournament and was able to make it there without any issues.
