### ISSUE TITLE
Orcs/Elves can use standard buildings

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#935]
Because vanilla shuffled around the files where buildings are defined, our version of it with the added triggers is no longer up to date - - which is why they are currently all commented out. Thus, vanilla buildings are avaiable to orcs and elves.

**Comment by Natsuki-best-girl** [comment]
I added two files from vanilla to overwrite plus modifying some existing files to prevent elves and orcs from ever using/upgrading vanilla buildings with a trigger, including guild halls in cities. Idk if elves should be locked from trade ports but hey they have their own holding types
