### ISSUE TITLE
Orcish secondary buildings don't convert to refuge

### ISSUE THREAD

**Issue by BriceLeduc** [jj248/RealmsInExile#936]
As an Elf, if you take an Orcish or Nazgûl holding, the main holding changes to refuge type but the secondary buildings stay castle/city/temple

**Comment by Natsuki-best-girl** [comment]
Modified the line slightly to allow all holdings change. Does not apply to evil humans, or orcs/nazguls holding non-orcish holdings, probably not necessary but just a side note in case something needs to be changed.
