### ISSUE TITLE
Unable to create uruk-hai of isengard

### ISSUE THREAD

**Issue by blackbird5598** [jj248/RealmsInExile#938]
![image](https://github.com/jj248/RealmsInExile/assets/125709421/c05865e0-fe1c-47c9-833e-2905eefed2af)

Upon taking the decision "Crown King of Dunland" the modifier "workshops of Isengard" disappears and makes the creating uruk-hai decision impossible.

**Comment by jj248** [comment]
@Jaco-Daan - was this fixed?

**Comment by Jaco-Daan** [comment]
needs to be tested

**Comment by Jauffr** [comment]
Seems to be resolved. I crowned a king of dunland and the workshop modifier stayed
![Screenshot 2023-07-04 160941](https://github.com/jj248/RealmsInExile/assets/108106660/82af62bb-2857-476f-896e-f150c511dbb5)
