### ISSUE TITLE
Ruler designer elves holding bug

### ISSUE THREAD

**Issue by Pepper-san** [jj248/RealmsInExile#939]
Ruler-designer created Elves in non-elven land will have local vassals, whose holdings will the amount of holding slots refuges would have, despite not being refuges. Example:
<img width="503" alt="image" src="https://github.com/jj248/RealmsInExile/assets/115768993/a08027b7-a28a-4fac-9e86-1ab7684eda50">

**Comment by Jaco-Daan** [comment]
Tested this, can't recreate, will wait for someone else to check if they can recreate, otherwise might have been fixed.

**Comment by Jaco-Daan** [comment]
Had Jauffre test this as-well, and the amount of building slots stayed the same. Since issue seems to be resolved, closing
