### ISSUE TITLE
Dune Sea Rework

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#942]
Needs to be tested.
- History rework of the Dune Sea, Lurmsakûn, Darsalan.
- New Gurzil Tenet
- New Sanbaiz witch tenet
- general faith rework

**Comment by savagesach** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/86676697/6f80677f-52e4-47a3-b710-1da38bfc2fab)
The localization for this nickname is broken

**Comment by savagesach** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/86676697/54ef78c0-46c5-40a7-8420-d3d524e575f9)
the localization for this nickname is also broken

**Comment by savagesach** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/86676697/dc60aeaf-62be-4bcf-8df7-90e931d8bea2)
this still needs to be localized

**Comment by savagesach** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/86676697/dac660f0-5647-4e80-8f93-2aafa2ce4697)
the koanoz house is broken somehow

**Comment by savagesach** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/86676697/77b4f87f-1cfd-4f8b-987f-4de9b166593f)
everyone except for the original king has it

**Comment by savagesach** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/86676697/912b2274-cb98-4e6b-ad04-16da85be4170)
this dynasty also has the issue

**Comment by JukeJukestar** [comment]
Prefix fixed.

**Comment by Jaco-Daan** [comment]
This seems to have been done? Closing
