### ISSUE TITLE
Aragorn's grand wedding

### ISSUE THREAD

**Issue by BriceLeduc** [jj248/RealmsInExile#946]
We should set up a grand wedding for Aragorn, with custom (excluding ost vanilla ones).
We already have one (the one where Galadriel gives the Elessar). We'd need custom ones for Elrond and sons, the King of Rohan, the vassals, etc.
I would take care of the main setting up of the wedding but people can make events to slot in.

**Comment by Commander-Sol** [comment]
Sounds like some simple event coding, I'd like to learn that so what better place than here?

**Comment by BriceLeduc** [comment]
Exactly : that or https://github.com/jj248/RealmsInExile/issues/944 are rather simple events. A good way to learn

**Comment by jj248** [comment]
@BriceLeduc - feels like this is done?

**Comment by BriceLeduc** [comment]
We could always use flavour events for it (we currently have just one : Galadriel giving the Elessar), but it is functionally sound

**Comment by Hendrix1337x** [comment]
Post King Strife can't host the wedding, it says both characters are involved in an activity when they aren't
![image](https://github.com/jj248/RealmsInExile/assets/154389264/661fbf99-1842-40d7-a33f-1c8ddd656281)

**Comment by Jaco-Daan** [comment]
Sounds like this has been finished, closing
