### ISSUE TITLE
Orc Cannibalism (v4-development branch)

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#951]
We still have a ton of events that specifically turn orcs into cannibals, also many random orcs spawn with cannibal traits. However, since we made the consumption of humans not count as cannibalism, it should be much rarer than it is right now.

The char gen file ```00_pool_repopulation_character_templates.txt``` gives all generated orcs a 20% chance of being a cannibal, which is just ridiculous

**Comment by Jaco-Daan** [comment]
Pushed a fix, will need testing to confirm orcs spawn with cannibal trait far less

**Comment by JukeJukestar** [comment]
Checked the character creation files real quick and theres still a 15% chance per spawned Orc char.
It shouldnt be much more common than vanilla, 15% is still a lot :p

**Comment by jj248** [comment]
@kellenpure - Jaco thinks you were doing some work on cannibalism recently? Or was that berserkers?

Regardless, @Jaco-Daan or @jj248 should just cover off this last point and close.

**Comment by Jaco-Daan** [comment]
This has been adjusted, closing
