### ISSUE TITLE
"Claim of Convenience" Spouse event (v4-development branch)

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#954]
![image](https://github.com/jj248/RealmsInExile/assets/76008882/e5af77bf-359a-44eb-9ac4-bb8f563beea0)

**Comment by Jaco-Daan** [comment]
Fixed, moving to testing.

**Comment by savagesach** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/86676697/b1e7ea6e-c82b-4eae-b850-571a7814e92c)
claim of convenience event caused andrast to declare war on the druedain forest even though it's gondor's protectorate

**Comment by Jaco-Daan** [comment]
Added the restriction, will have to check in v4 whether it can be closed

**Comment by jj248** [comment]
@savagesach - believe this just needs testing now.

**Comment by Jaco-Daan** [comment]
We've had no more reports of this since we've pushed the fix, closing
