### ISSUE TITLE
Dwarven faiths

### ISSUE THREAD

**Issue by Jauffr** [jj248/RealmsInExile#957]
I intend to create faiths for each of the seven dwarven houses. Here we can discuss potential concepts when people feel inspired, and discuss implementations. As of now we have two faiths implemented. The Broadbeam and standard/Longbeard varieties

1. Longbeards: Khazad. The archatypical dwarven faith. Passed down from Durin the deathless as he learned it from Mahal the maker. All other dwarven faiths stem from this in one way or another
2. Broadbeams: Kemel-Mesen. Influences by the long years of peace and friendship with the elves of lindon and hobbits of the shire. The Broadbeams have just as much reverence for the beauty of nature as that of stone
3. Firebeards: (Name pending) Ideology of those isolationist firebeards who yet hold grudges against the elves of lindon and even their norther kin.
4. Ironfists: (Name Pending) Faith representing the mercenary and merchantil nature of the ironfists. They trade with everyone, regardless of creed or master
5. Stiffbeards: (Name pending) Belief in the halls Aule has set asside for the dwarves upon their deaths are in fact the mountains of their birthplaces
6. Stonefoots
7. Blacklocks

**Comment by jj248** [comment]
@VectorMaximus and @Jauffr - do we have anything left on this?

**Comment by jj248** [comment]
@jj248 to add some hostility tenet to make *all* faiths without that tenet to be hostile, but all others with as astray.

**Comment by Jaco-Daan** [comment]
Seems all the concepts have been added? Issue can be re-opened as we expand into more areas, but current array for v4 has been done. Closing
