### ISSUE TITLE
Dwarven prospecting

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#958]
The idea here would be to produce a mechanic that allows dwarves to invest in uncovering seams of these ores and gems in underground and mountain provinces, represented by province modifiers.

Each of these modifiers would unlock a specific mine building chain that allows the holder to gain the benefits from mining these riches.  Some might be direct boosts to income (e.g. gold), while others might improve MaA (e.g. iron).

This should add some additional variety to big bunches of otherwise similar underground provinces. We can also add logic that dictates what pool of resources are discoverable in different areas, along with associated chances. And we can add pre existing seams on game start.

If we add a crafting mechanic in the future, this could link nicely in to form prerequisite material components.

I see two potential interactions players could have with the mechanic. First would be in owned provinces to actively search for these - effectively a currency sink, maybe with some associated events. Second would be in Wilderness. This would cost less and give some indication of what might be there to direct the player towards potentially lucrative or strategically important expansion areas.

Furthermore, we could add an additional unlock to the mechanic via cultural tradition unlock.

**Comment by Jaco-Daan** [comment]
Closing as the _mechanic_ has been fully added to the mod
