### ISSUE TITLE
Dwarven buildings

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#959]
A new building set needs to be created for dwarves.  These should come in two distinct flavours:

- A set for underground terrain that is the core of dwarven development.
- A set for overground terrain that is far far weaker and with more limited choices, especially as you move from mountains -> hills -> everything else.

There should be some early experimentation to see how the building upgrade gui copes with large numbers of upgrades (i.e. >8 that vanilla uses).

**Comment by Jauffr** [comment]
I intend to try my hand at making said Dwarf building set. And yes, it will definately be necessary to see how much if any GUI adjustments will need to be made to allow for the likely massive eventual selection of available dwarven buildings. I also expect that this is an excellent issue that I/we can introduce new contributors to, to help them get their bearings with more simple CK3 moding.

**Comment by Jaco-Daan** [comment]
This has been done, closing

**Comment by Jaco-Daan** [comment]
Closing this again, since we've implemented all of this
