### ISSUE TITLE
Limitations of colonisation by subterranean terrain type (wastelands_rework branch)

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#960]
We need to add limitations to prevent non-dwarf, non-orc characters from colonising in subterranean terrain.

**Comment by Jaco-Daan** [comment]
Will take a look at this, as I'm currently fixing any kinks that come up with the new wilderness mechanics.

**Comment by Jaco-Daan** [comment]
Ready for testing.

What needs to be tested:

- Make sure only subterranean races, dwarves and orc, can colonise underground.
- Surterranean races (elves/humans/hobbits_ should **not** be able to colonise underground.

**Comment by Jaco-Daan** [comment]
This has been done/tested, closing
