### ISSUE TITLE
New CB targetting subterranean lands (subterranean_CBs branch)

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#963]
Surterranean races should get a new CB that targets subterranean lands (up to a max of Duchy tier) that will reduce development and downgrade buildings (by an amount to be determined).  Should any of the following occur, the province should revert to Wilderness:

- development drops to zero
- holding building reduces below first tier

**Comment by Jaco-Daan** [comment]
Think I'll take a look at this, I've wanted to look at CBs properly for a while now. Also ties in with #962

**Comment by Jaco-Daan** [comment]
So this only needs testing - @savagesach @Hendrix1337x

**Comment by Jaco-Daan** [comment]
This has been done and no issues reported, closing
