### ISSUE TITLE
Restrict AI's desire to vassalise subterranean realms (subterranean_CBs branch)

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#964]
Both sub and sur terranean races should be able to hold each other as vassals.  However, we'll set the AI up so it doesn't seek to do this (except for Nazgul/Fallen Maiar/Fallen Istari towards orcs (who are effectively their surrogate race)).

This should be considered via AI for request and offer vassalisation interactions, as well as through things like the forced vassalisation CB.

**Comment by jj248** [comment]
We might want to also discourage good AI dwarves from war decking good neighbours too based on recent feedback.

Will leave this with you @Jaco-Daan as you've done a bid of CBs in this area.

**Comment by Jaco-Daan** [comment]
Has been done, and heard no complains, closing
