### ISSUE TITLE
on_action to strip AI overground owners of subterranean titles (subterranean_CBs branch)

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#965]
With #962 and #963  in place, it should be theoretically impossible for surterranean players to gain subterranean titles.  So we should be safer to implement a check on the title_gain on actions to ensure that if a surterranean race should somehow gain control of a subterranean title, we can strip them of it, knowing they'll be non-player.

**Comment by savagesach** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/86676697/e31524f9-3235-4dd7-9a0a-d8dc78a331ab)
![image](https://github.com/jj248/RealmsInExile/assets/86676697/c9aa4dda-4439-4918-8826-28e9d27b61f9)
the title gain on action check did not work

**Comment by savagesach** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/86676697/bc72b054-9ffb-4ca7-9e07-b0777028998c)
![image](https://github.com/jj248/RealmsInExile/assets/86676697/f2d6e633-bbfe-4d3a-9469-b01b8efa8e0e)
Also I wanted to mention that even after I won a war against gundabad, none of the subterranean counties flipped to wilderness

**Comment by Jaco-Daan** [comment]
Should be ready for testing ** !!! ON subterranean_CBs BRANCH !!! ** Main things that need to be tested, are:

- You shouldn't be able to declare normal CB on an underground county as a surface dweller ( Surface dwellers is anyone who doesn't belong in underground areas. The **only** races that belong underground are dwarves/goblins/orcs)
- The only CBs that should be available, is a new custom one (still WIP, just pointing it out) and reclaim artifacts.

With above things ^^^ things pointed out, you shouldn't be able to declare war on underground counties, **but** if you do somehow manage it, when you gain the underground title, it should automatically turn to wastelands.

**Comment by Jaco-Daan** [comment]
This has been done, closing
