### ISSUE TITLE
Colonisation mechanic to cope with overseas lands (v4-development branch)

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#966]
Currently the mechanic only targets neighbouring lands, but we'll need to at the very least check neighbours across water to allow Tol Fuin to be colonised.

**Comment by Jaco-Daan** [comment]
Should be relatively easy, will take a look at this since I'm going/went over the wilderness mechanics

**Comment by Jaco-Daan** [comment]
Ready for testing, things that need to be tested:

- [ ] Can you colonize Tol Fuin if you have the closest county titles on the main land (These titles being Dor Maedhros, Lothlann, and Himring)
- [ ] Are there extra costs when **starting** a colony on the island. 
- [ ] The cost should go away when you have at least one county **upgraded into a normal holding**

<details>
<summary>Click to expand</summary>

![20230819145305_1](https://github.com/jj248/RealmsInExile/assets/62937916/3050f136-f43a-44f5-b4f1-14a9d0c1d2f5)
![20230819145317_1](https://github.com/jj248/RealmsInExile/assets/62937916/801b4853-5113-4dab-96ad-9a20ea816a4f)

</details>

**Comment by savagesach** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/86676697/af932f11-8b6c-4def-9547-c0efd7b3b2d7)
![image](https://github.com/jj248/RealmsInExile/assets/86676697/057d84d8-37f6-49f6-8a34-a28afeca56a6)
![image](https://github.com/jj248/RealmsInExile/assets/86676697/7bca7194-9faa-41db-b27c-9341c5a7e2f9)
Colonization for tol fuin works as intended for cirdan, but maglor does not have to pay any extra gold to colonize tol fuin

**Comment by savagesach** [comment]
overseas colonization works as intended
