### ISSUE TITLE
Add childbirth memories to elven birth event (v4-development branch)

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#972]
As description says, these won't be applied automatically as they're handled via event.

**Comment by jj248** [comment]
I'll take this one too.

**Comment by jj248** [comment]
Ready to test @savagesach and @Hendrix1337x . Should be a quickie.

**Comment by Hendrix1337x** [comment]
seems to be working
![image](https://github.com/jj248/RealmsInExile/assets/154389264/b3b110b9-afdf-480a-9a57-7fb0fa9f0cb2)

**Comment by jj248** [comment]
Bravo - thank you. Closing.
