### ISSUE TITLE
Fix Orc beauty traits

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#974]
![Image](https://github.com/jj248/RealmsInExile/assets/76008882/974b3756-fe55-48dc-bb9b-2d05bf93325a)

![Image](https://github.com/jj248/RealmsInExile/assets/76008882/d3dc9910-b782-4d76-9efa-96e139d89be5)

Tours and Tournaments seems to have changed the effect of beauty traits, resulting in orcs with human skin.

**Comment by jj248** [comment]
This looks to be fixed. Closing.
