### ISSUE TITLE
Auto-generate colony blockers (wastelands_rework branch)

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#976]
Colony blockers should be auto-generated.
They should generate based on terrain (mainly "underground vs above ground")

We dont want bears in moria or the dune sea, but we do want spiders in both for example

**Comment by Jaco-Daan** [comment]
So me and Jamie talked a small bit about this and came to the conclusion that having the buildings in the history files, while more tedious to add, would ultimately be better. The amount of work that needs to be done for Auto-generated colonies to function is to much to work for too little pay-off.

Another thing to realise is that such an effect might end up causing serious lag-spikes/increase in loading times, especially as we increase the map size and potentially add more wastelands. 

The plus side for **NOT** having such an effect is that once we have all the buildings in for the wasteland counties, we never need to bother with it again.
