### ISSUE TITLE
Goblin Lifespan, Fertility, etc

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#977]
Currently identical to normal orcs.
Review what we want them to play like and modify appropriately - Im a bit afraid that just making them very fertile and short-lived would lead to a lot of child rulers

**Comment by jj248** [comment]
We have the cultures now - so I think we just need to make a call on things like lifespan, fertility differences etc. 

@VectorMaximus and @JukeJukestar  - please can you facilitate a dev discussion to make a final decision on the Discord?

**Comment by Jaco-Daan** [comment]
Seems like we're fairly good on how we're handling goblin culture, closing
