### ISSUE TITLE
Make hunts less deadly for Elves

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#980]
I've noticed that most of the time when elves die, it seems to be from hunts. We should probably make them less likely to die from hunts compared to humans

**Comment by BriceLeduc** [comment]
Are you taking about the dev build ?

**Comment by BriceLeduc** [comment]
Because if this is about the public release, this feature has already been implemented

**Comment by BriceLeduc** [comment]
@JukeJukestar ? Imo this issue has no justification unless this is something you have tested in either 3.2 or 4.0. Otherwise you're talking about an issue that has amready been fixed.

**Comment by JukeJukestar** [comment]
> Because if this is about the public release, this feature has already been implemented

It has? Great, then close
