### ISSUE TITLE
Eriador vassalization to Aragorn when King as Gondor

### ISSUE THREAD

**Issue by Jaco-Daan** [jj248/RealmsInExile#981]
When Aragorn ascends the throne of Gondor (creating the RK) the people in Eriador that are not already vassalized to Aragorn should get an event to vassalize themselves to him.

- At game start the Dunedain rangers should get an event to vassalize themselves to Aragorn
- When Aragorn becomes King of Gondor, the other people present in Eriador (probs excluding dwarves/elves) should also get an event to vassalize themselves to Aragorn. This would include the Evendim (as an example)

**Comment by Jaco-Daan** [comment]
Will take a look at this after the CB/Wilderness stuff, if no-one else has gotten to it by then.

**Comment by savagesach** [comment]
I tested this and I did not get any event to vassalize to aragorn when aragorn became king of gondor, the dunedain rangers event works as intended though
![image](https://github.com/jj248/RealmsInExile/assets/86676697/a4d756d0-6a57-459e-a019-b7c49e2cddfa)

**Comment by Jaco-Daan** [comment]
This has been done + tested. Closing
