### ISSUE TITLE
General Wilderness Rework

### ISSUE THREAD

**Issue by Jaco-Daan** [jj248/RealmsInExile#984]
Creating a more appropriate issue, as I told Nemcraft to close the old one that was referencing this.

**Changes planned for new system**:

- The cost to colonize a county is now based off of title tier. Currently it uses a linear cost increase with 25 gold per ruler, for example, a count pays 75 gold, a duke 100 gold, etc.
- New modifiers meant to show a colony upkeep. The colony upkeep also changes depending on title tier. For example, a count can have 1 colony before going over it's colony 'limit', a duke can have 2 colonies before going over its 'limit', etc. **To be clear, the modifiers apply a negative gold income per month**.
- After going over the limit, a new modifier is applied **per colony over limit**, which scales up to a tier 7 negative modifier.
- Each modifier increases the cost of maintaining the cost of the colonies by an increasing factorial of 3. For example, the first colony over a limit will be ==>( 1 + 3 ) negative GpM (gold per month), the second colony will be ( 1 + 3 + 9 ) negative GpM, etc., until it reaches a limit of -364 GpM.
- You can now abandon a settlement holding (button should be alongside the settle castle/city/church/elven holding buttons).
- Extra cost for islands, seperate issue #966 .
- Certain areas off limit to certain races, seperate issue #960 

**Changes implemented so far**

- [x] Different cost for settling a county based off of title tier.
- [x] Modifiers that apply a different colony upkeep based on whether a person is over her/his colony limit.
- [x] Extra costs, referenced in #966
- [x] Certain areas off limits races, referenced in #960 
- [x] Abandon settlement interaction implemented.

**Comment by jj248** [comment]
@Hendrix1337x and @savagesach - we need to get to a point where we're happy that this is 'good enough' for release. What's your input?

**Comment by savagesach** [comment]
I'm pretty happy with colonization as it is currently

**Comment by Jaco-Daan** [comment]
Selfnote here: Make is so that AI counts only colonize when they are above a certain amount of gold income per month.

Also add a yearly event that can fire so that AI will abandon wilderness holdings if they are in negative monthly income

**Comment by Jaco-Daan** [comment]
This has been added and heard no major complains with the mechanic itself
