### ISSUE TITLE
Adaptation of WW Yearly Events

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#986]
We need to adapt the new yearly random events added by Wards and Wardens

- [x] bp2_yearly_0_5.txt
- [x] bp2_yearly_1_events.txt
- [x] bp2_yearly_2.txt
- [x] bp2_yearly_3.txt
- [x] bp2_yearly_4.txt
- [x] bp2_yearly_5.txt
- [x] bp2_yearly_7.txt
- [x] bp2_yearly_events_6.txt
- [x] bp2_yearly_extra.txt
- [x] bp2_yearly.txt

**Comment by JukeJukestar** [comment]
Welp, went through all of them and removed some possible murders and such things that could hit immortals.
Also made it so you cant crush on a different race (sorry aragorn!)

**Comment by Jaco-Daan** [comment]
Since nothing has popped up, seems to be everything was adapted, closing
