### ISSUE TITLE
Adapting Wet Nurses

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#989]
We need to think about how race should play into this - can a human have an elven wet nurse? An orc? Naturally the answer should be no, but what if I have an orcish hostage? What if I and my wet nurse are orcs, but we captured a human hostage?
Need to think about the possibilities.
I set the requirement to be same race for now.

We also need to consider how Numenorean blood or being elvish should affect the age requirement:

![Image](https://github.com/jj248/RealmsInExile/assets/76008882/e34b846e-642f-40b9-b8ee-95f22fd28b2b)

**Comment by BriceLeduc** [comment]
Fixed and commited
