### ISSUE TITLE
Daen Rework

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#991]
Rework Daen into three branches:

Daen Lintis (Gwathuirim)
Daen Coentis (White Mountain Men)
Danan Lin (Donan/Coastal/Calenardhon Daen)

- [x] Setup new cultures
- [x] Add appropriate Traditions
- [x] Make sure they are properly used in triggers
- [x] Rework Namelists (Remove germanic elements from most)
- [x] (Optional) Add to province history
- [x] Add/ Rework cultural descriptions
- [x] Add faith localization for Coenmor

**Comment by savagesach** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/86676697/b089300b-4f02-4bde-874a-ded326fd8176)
![image](https://github.com/jj248/RealmsInExile/assets/86676697/d8b22045-f811-4762-bd2b-4826dde4e86a)
![image](https://github.com/jj248/RealmsInExile/assets/86676697/a6a862bc-6bd1-4a43-b235-83b182fbd7a8)
![image](https://github.com/jj248/RealmsInExile/assets/86676697/4af0eec7-965e-4486-a2b2-2b1606305d54)
none of these cultures have any cultural descriptions

**Comment by jj248** [comment]
@JukeJukestar and @VectorMaximus is this done? If not, looks like just a couple of loc bits to get it over the line. :)

**Comment by Jaco-Daan** [comment]
@JukeJukestar @VectorMaximus confirmation on the loc? Would be nice to close this issue.

**Comment by JukeJukestar** [comment]
Done and done
