### ISSUE TITLE
Orcs inheriting Elven MAA and vice versa

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#992]
discord report:
https://discord.com/channels/751097183448727552/1148345707263172762

When inheriting titles, you usually get their MAA. However, this sometimes leads to evil factions getting Elven Men at Arms (and possibly vice versa).

**Comment by Jaco-Daan** [comment]
Unfortunately this isn't something we can fix. There's no way to destroy MaA of a ruler. Closing this issue until we can deal with it
