### ISSUE TITLE
Certain Cultures have weird Bodyshapes

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#993]
Depending on culture, some characters get a really weird bodyshape that is totally fucked up. Changing culture fixes this. Please investigate. Shown here on Herumor, comparing Black Numenorean and Gondorian culture:

![image](https://github.com/jj248/RealmsInExile/assets/76008882/b97aba39-36fd-4aac-a096-521fe8870e10)

# Tested Cultures
## Cultures with regular body:

- Black Numenorean
- Umbarean
- Bellakaze
- Haruze
- Magriag
- Dunlending
- Eredrim
- Woodmen
- Valemen

## Cultures with weird body:

- Numenorean
- Gondorian
- Dunedain
- Arnorian
- Rohirrim
- Eotheod
- Leofring
- Dalemen
- Dorwinionrim

**Comment by jj248** [comment]
Is this really Very High priority @JukeJukestar ? :D
