### ISSUE TITLE
Special Building Localization/Implementation (Dwarves) v4

### ISSUE THREAD

**Issue by Jaco-Daan** [jj248/RealmsInExile#995]
Due to us expanding the scope for v4 (combining initial v4 with v5) thought it would be a good idea to make a list of special buildings for dwarves that still need loc done/still need to be implemented.

**Check the checkbox if it has both been implemented _and_ been localized**

### Implemented, requires localization:

- [x] Belegost [has 3 tiers] **Blue Mountains**
- [x] Nogrod [has 3 tiers] **Blue Mountains**
- [x] Mt Dolmed [Birthplace of broadbeam/firebeard fathers] **Blue Mountains**
- [x] Kheledul [Only known river boat-based trading post for dwarves] **Blue Mountains**
- [x] Thorins Hall **Blue Mountains**
- [x] Sunset Caverns  **Blue Mountains**
- [x] Endless Stairs **Misty Mountains**
- [x] Mirrormere **Misty Mountains**
- [x] Doors of Durin **Misty Mountains**
- [x] Caverns of Farewell **Northern Mountains**

### Still needs to be implemented

- [ ] Throne of Durin [tiered]
- [ ] Glittering caves [pending map update]
- [ ] Special building for underground terrain in Rhun??? Maybe???

**Comment by jj248** [comment]
Just the "still needs to be implemented" left.  Can I leave this with you two @VectorMaximus and @Jauffr ? :)

**Comment by Cairo-Fischer** [comment]
I can do the waterfall hold in Rhun if Jauf and/or vector don't feel strongly about it

**Comment by Jaco-Daan** [comment]
This has been done, closing
