### ISSUE TITLE
Broken Mercenary Bands

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#997]
Orc/Goblin Mercenary bands seem to be broken. Also note that anyone can hire them!

![Image](https://github.com/jj248/RealmsInExile/assets/76008882/71911f33-ce0e-4051-b0cf-b07b9117c635)

**Comment by jj248** [comment]
@JukeJukestar - is this still an issue?

**Comment by savagesach** [comment]
oh yeah I forgot to mention me and jauffre fixed this issue a few weeks ago

**Comment by jj248** [comment]
Bravo - closing.
