### ISSUE TITLE
Thorin's Tomb mechanics

### ISSUE THREAD

**Issue by BriceLeduc** [jj248/RealmsInExile#999]
- Thorin's tomb is located in the Throne of Erebor county, materialised by a modifier present on game start
- Anyone holding it while the tomb is intact or partially restored can take the decision to plunder the tomb, and acquire Orcrist and/or Arkenstone. The county will lose its initial modifier and aquire one or two new ones, materialising what is missing from the tomb, and giving mali. Anyone storming the barony, with the same conditions, will also get the event fired by the decision.
- If they decide to do so, they will receive the "Plundered Thorin's Tomb" modifier, granting a massive malus to opinion to all Dwarven religion characters
- Any character aquiring either or both of the artifacts by other means will receive an event informing them that the Dwarves want them back (if the character is not either an Orc, evil, or the ruler of Erebor, and has a Dwarven ruler within diplo range). They can choose to keep them and get a modifier giving opinion malus from Dwarves, or return them and gain gold and a positive Dwarven opinion modifier. The character can change their mind and return the artifacts later by decision.
- The ruler of Erebor will, upon aquiring either or both of those artifacts, get an event to restore the tomb to its former glory, gaining quite a bit of piety, a permanent bonus modifier and returning the initial modifier to the county.

A fully/partially restored tomb can be plundered again, etc

**Comment by savagesach** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/86676697/bdc5737a-3c9a-4ba4-9d04-dadf81fd2775)
![image](https://github.com/jj248/RealmsInExile/assets/86676697/9b6f4a71-2aaa-4b41-af60-6201ab386546)
Plundering Thorin's tomb does not give you the Arkenstone even though it should.

**Comment by JukeJukestar** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/76008882/f8963be0-a63c-47c5-b3a8-a19f20027ff8)

Currently shows up for everyone

**Comment by jj248** [comment]
@BriceLeduc - please can you update with the status of this? :)

**Comment by savagesach** [comment]
I tested this issue and found no errors, both artifacts are given. Someone else should also test this issue before closing.

**Comment by Cairo-Fischer** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/110961821/53604558-a0fd-4c90-9e05-573d10c1fccd)
![image](https://github.com/jj248/RealmsInExile/assets/110961821/1c7d55c8-fd21-4a79-b503-6af353fcb38c)
![image](https://github.com/jj248/RealmsInExile/assets/110961821/f6486dce-9a36-404c-b11f-f7a7b5368926)
![image](https://github.com/jj248/RealmsInExile/assets/110961821/c9a0d258-8ed0-45a2-9529-41e60686b5af)
The plunder decision appears to work but the "restore Thorin's Tomb" decision doesn't work, when I click it nothing happens, the items remain in my inventory as well as the county modifiers

**Comment by Cairo-Fischer** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/110961821/fa99584e-bc29-488b-af8d-d83b27c07c85)

Nvm, Nemcraft just fixed it, artifacts and modified are removed properly
